export const VERSION='2.0.1', CLASS_RUN='tap-events-2026-10', MAX_SCORES=[2,3,3,2];
export const CHOICES=['cup','open','showcase'], ADJUSTMENTS=['orientation','extra_host','rotations'], PRIORITIES=['newcomers','club','operator'];
export const TEST_IDENTITY={firstName:'Synthetic',lastName:'Fixture',email:'tap-v2@example.invalid',individualWork:true};
export class InputError extends Error {constructor(code,message,status=400){super(message);this.code=code;this.status=status;}}
export const fail=(code,message,status=400)=>{throw new InputError(code,message,status)};
export function objectOnly(value,keys){if(!value||Array.isArray(value)||typeof value!=='object'||Object.keys(value).some(k=>!keys.includes(k)))fail('INVALID_INPUT','Unexpected or missing request fields.');}
export function uuid(value){if(typeof value!=='string'||!/^[0-9a-f]{8}-[0-9a-f]{4}-4[0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$/i.test(value))fail('INVALID_INPUT','Use a UUID v4 identifier.');return value.toLowerCase();}
export function mode(value){if(!['live','test'].includes(value))fail('INVALID_INPUT','Choose live or isolated test mode.');return value;}
export const canonical=value=>Array.isArray(value)?'['+value.map(canonical).join(',')+']':value&&typeof value==='object'?'{'+Object.keys(value).sort().map(k=>JSON.stringify(k)+':'+canonical(value[k])).join(',')+'}':JSON.stringify(value);
export async function sha256(value){return [...new Uint8Array(await crypto.subtle.digest('SHA-256',new TextEncoder().encode(value)))].map(n=>n.toString(16).padStart(2,'0')).join('');}
export function safeCompare(a,b){if(typeof a!=='string'||typeof b!=='string'||a.length!==b.length)return false;let n=0;for(let i=0;i<a.length;i++)n|=a.charCodeAt(i)^b.charCodeAt(i);return n===0;}
function clean(value,max=1800,min=0){if(typeof value!=='string'||value.trim().length<min||value.length>max||/[\u0000-\u0008\u000b\u000c\u000e-\u001f]/.test(value))fail('INVALID_INPUT',`Text must contain ${min}–${max} characters.`);return value.trim();}
export function identity(value,m){objectOnly(value,['firstName','lastName','email','individualWork']);if(value.individualWork!==true)fail('INVALID_INPUT','Confirm that this is your individual work.');const v={firstName:clean(value.firstName,80,1),lastName:clean(value.lastName,80,1),email:clean(value.email,180,5).toLowerCase(),individualWork:true};if(m==='test'){if(canonical(v)!==canonical(TEST_IDENTITY))fail('INVALID_INPUT','Test mode accepts only the fixed Synthetic Fixture identity at tap-v2@example.invalid.');}else if(!/^[a-z0-9.!#$%&'*+/=?^_`{|}~-]+@lasalle\.edu$/i.test(v.email))fail('INVALID_INPUT','Use your La Salle email address ending @lasalle.edu.');return v;}
export const EMPTY_ANSWERS={initialChoice:'',initialPosition:'',finalChoice:'',adjustment:'',priority:'',finalReason:'',runnerUp:'',tradeoff:'',guestConsent:false};
export function answers(value){objectOnly(value,Object.keys(EMPTY_ANSWERS));const v={...EMPTY_ANSWERS,...value};for(const [field,options] of [['initialChoice',CHOICES],['finalChoice',CHOICES],['runnerUp',CHOICES],['adjustment',ADJUSTMENTS],['priority',PRIORITIES]])if(v[field]!==''&&!options.includes(v[field]))fail('INVALID_INPUT','Choose a listed option.');for(const field of ['initialPosition','finalReason','tradeoff'])v[field]=clean(v[field]);if(typeof v.guestConsent!=='boolean')fail('INVALID_INPUT','Guest consent must be true or false.');return v;}
export function validateInitial(v){if(!CHOICES.includes(v.initialChoice))fail('INVALID_INPUT','Choose an initial proposal.');clean(v.initialPosition,1800,40);}
export function validateFinal(v){validateInitial(v);if(!CHOICES.includes(v.finalChoice)||!CHOICES.includes(v.runnerUp)||v.finalChoice===v.runnerUp||!ADJUSTMENTS.includes(v.adjustment)||!PRIORITIES.includes(v.priority))fail('INVALID_INPUT','Complete the final choices and select a different runner-up.');for(const field of ['finalReason','tradeoff'])clean(v[field],1800,40);if(({cup:280,open:180,showcase:240}[v.finalChoice]+(v.adjustment==='extra_host'?75:0))>300)fail('BUDGET_EXCEEDED','This combination exceeds the $300 incremental cap. Choose another adjustment or proposal.');}
export function summary(state){const names={cup:'Rivalry Mini-Cup',open:'Play & Connect',showcase:'Campus Showcase'}, adjustments={orientation:'a 10-minute orientation',extra_host:'one extra host',rotations:'scheduled station rotations'}, priorities={newcomers:'newcomer access',club:'the esports club’s competitive finish',operator:'operational feasibility'};const a=state.answers;if(state.status!=='submitted')return '';return `${names[a.initialChoice]} → ${names[a.finalChoice]}. The final proposal adds ${adjustments[a.adjustment]}, prioritizes ${priorities[a.priority]}, and names ${names[a.runnerUp]} as runner-up. This structured summary does not quote or paraphrase the student’s written responses.`;}
export function projection(state){return {attemptId:state.attemptId,mode:state.mode,classRun:CLASS_RUN,synthetic:state.mode==='test',firstName:state.firstName,lastName:state.lastName,email:state.email,identityVerified:false,individualWork:state.individualWork,answers:state.answers,initialPlan:state.initialPlan,status:state.status,version:state.version,receipt:state.receipt,createdAt:state.createdAt,submittedAt:state.submittedAt,review:state.review,finalGrade:state.review?.total??null,guest:{consent:state.answers.guestConsent,published:state.guestPublished,template:'decision',summary:summary(state)}};}
// Separate boundary allowlist applies even to older durable operation responses.
// Never reuse the full instructor projection in a student response.
export function studentResponse(response){
 const s=response.submission;
 const allowed=['attemptId','mode','classRun','synthetic','firstName','lastName','email','identityVerified','individualWork','status','version','receipt','createdAt','submittedAt'];
 const submission=Object.fromEntries(allowed.filter(k=>Object.hasOwn(s,k)).map(k=>[k,s[k]]));
 submission.answers=Object.fromEntries(Object.keys(EMPTY_ANSWERS).map(k=>[k,s.answers[k]]));
 submission.initialPlan=s.initialPlan?{initialChoice:s.initialPlan.initialChoice,initialPosition:s.initialPlan.initialPosition,lockedAt:s.initialPlan.lockedAt}:null;
 submission.reviewStatus=s.review?'reviewed':'pending';
 submission.guest={consent:s.guest.consent,published:s.guest.published,template:s.guest.template,summary:s.guest.summary};
 return {ok:true,mode:response.mode,submission};
}
export function safePublication(state){return {mode:state.mode,stage:state.status,initial_choice:state.initialPlan?.initialChoice||null,final_choice:state.status==='submitted'?state.answers.finalChoice:null,adjustment:state.status==='submitted'?state.answers.adjustment:null,priority:state.status==='submitted'?state.answers.priority:null,runner_up:state.status==='submitted'?state.answers.runnerUp:null,published:state.guestPublished===true&&state.answers.guestConsent===true&&state.status==='submitted'};}
export function transition(current,cmd,{now=new Date().toISOString(),receiptId=crypto.randomUUID()}={}){let state=current?structuredClone(current):null;
 if(cmd.action==='start'){if(state)fail('STATE_CONFLICT','This attempt already exists. Resume it.',409);state={attemptId:cmd.attemptId,mode:cmd.mode,classRun:CLASS_RUN,...identity(cmd.identity,cmd.mode),answers:{...EMPTY_ANSWERS},initialPlan:null,status:'draft',version:0,receipt:null,createdAt:now,submittedAt:null,review:null,guestPublished:false};}
 else {if(!state)fail('NOT_FOUND','This attempt was not found.',404);if(state.mode!==cmd.mode)fail('UNAUTHORIZED','Attempt access denied.',401);
  if(cmd.action==='save'){if(state.status==='submitted')fail('STATE_CONFLICT','Final submissions are locked.',409);const next=answers(cmd.answers);if(state.initialPlan&&(next.initialChoice!==state.initialPlan.initialChoice||next.initialPosition!==state.initialPlan.initialPosition))fail('STATE_CONFLICT','The initial position is already locked.',409);if(!state.initialPlan&&[next.finalChoice,next.adjustment,next.priority,next.finalReason,next.runnerUp,next.tradeoff].some(Boolean))fail('STATE_CONFLICT','Lock your initial position before the audience update.',409);state.answers=next;}
  else if(cmd.action==='lockPlan'){if(state.status!=='draft')fail('STATE_CONFLICT','The initial position is already locked.',409);validateInitial(state.answers);state.initialPlan={initialChoice:state.answers.initialChoice,initialPosition:state.answers.initialPosition,lockedAt:now};state.status='plan_locked';}
  else if(cmd.action==='submit'){if(state.status==='submitted')fail('STATE_CONFLICT','This attempt is already submitted. Resume to see the receipt.',409);if(!state.initialPlan)fail('STATE_CONFLICT','Lock your initial position first.',409);validateFinal(state.answers);state.status='submitted';state.submittedAt=now;state.receipt=`${state.mode==='test'?'TAP2-TEST':'TAP2'}-${receiptId}`;}
  else if(cmd.action==='instructorReview'){if(state.status!=='submitted')fail('STATE_CONFLICT','Only submitted work can be graded.',409);if(!Array.isArray(cmd.scores)||cmd.scores.length!==4||cmd.scores.some((n,i)=>!Number.isInteger(n)||n<0||n>MAX_SCORES[i]))fail('INVALID_INPUT','Enter four whole-number rubric scores bounded by 2, 3, 3, 2.');state.review={scores:cmd.scores,total:cmd.scores.reduce((a,b)=>a+b,0),notes:clean(cmd.notes??'',4000),reviewedAt:now};}
  else if(cmd.action==='instructorPublish'){if(typeof cmd.published!=='boolean'||cmd.template!=='decision')fail('INVALID_INPUT','Select the structured decision summary and release choice.');if(cmd.published&&(!state.answers.guestConsent||state.status!=='submitted'))fail('STATE_CONFLICT','Publication requires a submitted attempt and student opt-in.',409);state.guestPublished=cmd.published;}
  else fail('INVALID_INPUT','Unknown action.');
 }
 state.version++;return state;
}
