const ROLES={
 publisher:{name:'Publisher',sig:'P',tag:'IP owner / ecosystem architect',desc:'Controls the game and can monetize digital goods, media, events, and partnerships—but still depends on player attention and market demand.',bias:{digital:1.18,media:1.05,sponsor:1.0,merch:.9,events:.9,prize:.55,creator:.82}},
 team:{name:'Pro Team',sig:'T',tag:'High fixed costs / mixed revenue',desc:'Combines sponsorship, publisher-linked support, content, merchandise, events, and competitive performance. Sustainability requires repeatable operating revenue.',bias:{digital:1.04,media:.85,sponsor:1.08,merch:1.0,events:.82,prize:.65,creator:1.06}},
 organizer:{name:'Tournament Organizer',sig:'O',tag:'Value without game ownership',desc:'Builds events through sponsors, media, ticketing, and reputation while remaining structurally dependent on publisher permissions and audience demand.',bias:{digital:.55,media:1.08,sponsor:1.1,merch:.72,events:1.12,prize:.35,creator:.78}},
 creator:{name:'Player / Creator',sig:'C',tag:'Audience-led / talent-centric',desc:'Monetizes attention through platforms, sponsors, creator income, merchandise, appearances, and competitive winnings—with high dependence on personal brand and access.',bias:{digital:.45,media:1.08,sponsor:1.05,merch:.95,events:.7,prize:.78,creator:1.2}}
};
const STREAMS=[
 {id:'sponsor',name:'Sponsorships',sub:'brand partnerships / category rights',color:'#f1b93a',base:.72},
 {id:'media',name:'Media & Streaming',sub:'distribution / ad share / rights',color:'#4ee7ff',base:.62},
 {id:'digital',name:'Digital / Publisher-Linked',sub:'digital goods / rev share / stipends',color:'#9c84ff',base:.76},
 {id:'merch',name:'Merchandise',sub:'consumer products / direct sales',color:'#ff8b68',base:.68},
 {id:'events',name:'Live Events & Ticketing',sub:'attendance / venue economics',color:'#65d6a0',base:.6},
 {id:'prize',name:'Prize Money',sub:'visible, performance-dependent',color:'#ff6576',base:.38},
 {id:'creator',name:'Creator / Content Revenue',sub:'platform monetization / talent reach',color:'#61a9ff',base:.58}
];
const SHOCKS=[
 {id:1,title:'Sponsor Exit',desc:'Your largest sponsor does not renew. Commercial revenue disappears immediately.',mult:{sponsor:.3},fixed:0,fitDeps:['Sponsor concentration','Consumer demand'],fitContracts:['Sponsorship agreement / category rights']},
 {id:2,title:'Revenue-Share Cut',desc:'Publisher-linked ecosystem economics deteriorate by 40%. The relationship supporting digital or shared revenue becomes less valuable.',mult:{digital:.6},fixed:0,fitDeps:['Publisher strategy'],fitContracts:['Participation / revenue-sharing agreement','Publisher tournament license / policy']},
 {id:3,title:'Viewership Drop',desc:'Audience falls 30%. Media value weakens and sponsors discount the reach they are buying.',mult:{media:.55,sponsor:.8,events:.85,creator:.85},fixed:0,fitDeps:['Audience demand','Consumer demand'],fitContracts:['Media-rights agreement','Sponsorship agreement / category rights']},
 {id:4,title:'Fail to Qualify',desc:'Competitive access or marquee participation disappears. Prize money goes to zero and visibility-linked revenue softens.',mult:{prize:0,media:.82,sponsor:.86,events:.9},fixed:0,fitDeps:['Competitive qualification'],fitContracts:['Participation / revenue-sharing agreement','Player / talent agreement','Sponsorship agreement / category rights']},
 {id:5,title:'Platform Change',desc:'A major platform changes monetization and distribution terms. Content economics shift overnight.',mult:{media:.64,creator:.62,sponsor:.9},fixed:0,fitDeps:['Platform access'],fitContracts:['Platform / content licensing terms','Media-rights agreement']},
 {id:6,title:'New Compliance Cost',desc:'A new rule creates an unplanned 12-point operating burden. Revenue is intact, but the margin is not.',mult:{events:.9},fixed:12,fitDeps:['Regulatory / governance compliance','Venue / event operations'],fitContracts:['Insurance / compliance allocation','Venue / event contract','Publisher tournament license / policy']}
];
const dependencies=['Sponsor concentration','Publisher strategy','Platform access','Audience demand','Competitive qualification','Talent / creator availability','Venue / event operations','Consumer demand','Regulatory / governance compliance'];
const contracts=['Sponsorship agreement / category rights','Participation / revenue-sharing agreement','Platform / content licensing terms','Media-rights agreement','Player / talent agreement','Venue / event contract','Publisher tournament license / policy','Insurance / compliance allocation'];
let state={screen:'intro',role:null,alloc:Object.fromEntries(STREAMS.map(s=>[s.id,0])),shock:null,pivot:Object.fromEntries(STREAMS.map(s=>[s.id,0]))};

function q(id){return document.getElementById(id)}
function show(id,phase){document.querySelectorAll('.screen').forEach(s=>s.classList.remove('active'));q(id).classList.add('active');state.screen=id;document.querySelectorAll('.phase-dot').forEach((d,i)=>d.classList.toggle('on',i<=phase));window.scrollTo({top:0,behavior:'smooth'})}
function renderRoles(){q('roleGrid').innerHTML=Object.entries(ROLES).map(([id,r])=>`<button class="role ${state.role===id?'active':''}" data-role="${id}"><div class="sig">${r.sig}</div><h3>${r.name}</h3><p>${r.desc}</p><div class="tag">${r.tag}</div></button>`).join('');document.querySelectorAll('.role').forEach(b=>b.onclick=()=>selectRole(b.dataset.role))}
function selectRole(id){state.role=id;renderRoles();q('roleStatus').textContent=`Selected: ${ROLES[id].name}`;q('lockRole').disabled=false}
function totalAlloc(){return Object.values(state.alloc).reduce((a,b)=>a+b,0)}
function concentration(alloc=state.alloc){const vals=Object.values(alloc);return Math.max(...vals)}
function diversityScore(alloc=state.alloc){const active=Object.values(alloc).filter(v=>v>=8).length;return Math.min(100,active*14 + (100-concentration(alloc))*.45)}
function renderStreams(){q('streamList').innerHTML=STREAMS.map(s=>`<div class="stream"><div class="stream-name"><b style="color:${s.color}">${s.name}</b><small>${s.sub}</small></div><input class="slider" type="range" min="0" max="60" step="5" value="${state.alloc[s.id]}" data-stream="${s.id}" aria-label="${s.name}"><div class="val"><output id="out-${s.id}">${state.alloc[s.id]}</output><span>pts</span></div></div>`).join('');document.querySelectorAll('.slider').forEach(x=>x.oninput=()=>{state.alloc[x.dataset.stream]=+x.value;q('out-'+x.dataset.stream).value=x.value;updateBuild()});updateBuild()}
function updateBuild(){const t=totalAlloc();q('total').textContent=`${t} / 100`;q('total').className='total '+(t===100?'ok':'bad');q('remainingHint').textContent=t<=100?`${100-t} points remaining. Concentration creates efficiency—but also fragility.`:`${t-100} points over budget. Reduce the stack before locking.`;q('lockBuild').disabled=t!==100;renderTower();const top=STREAMS.slice().sort((a,b)=>state.alloc[b.id]-state.alloc[a.id])[0];q('topExposure').textContent=top&&state.alloc[top.id]?`${state.alloc[top.id]}%`:'—';const ds=Math.round(diversityScore());q('diversity').textContent=ds>=75?'High':ds>=50?'Medium':'Low';q('depCount').textContent=Object.values(state.alloc).filter(v=>v>=10).length;let f=ds>=75?'Resilient':ds>=50?'Mixed':'Concentrated';q('forecast').textContent=f}
function renderTower(damaged=false){let entries=STREAMS.filter(s=>state.alloc[s.id]>0).slice().sort((a,b)=>state.alloc[a.id]-state.alloc[b.id]);q('tower').innerHTML=entries.map(s=>`<div class="block ${damaged&&shockAffects(s.id)?'hit':''}" style="color:${s.color};height:${Math.max(40,34+state.alloc[s.id]*.65)}px"><b>${s.name}</b><span>${state.alloc[s.id]}</span></div>`).join('')||'<div style="color:#6f838f;padding:30px;text-align:center">Allocate revenue to construct the tower.</div>'}
function renderDeck(){q('shockDeck').innerHTML=SHOCKS.map(s=>`<button class="crate" data-shock="${s.id}"><span>${String(s.id).padStart(2,'0')}</span><small>Sealed case</small></button>`).join('');document.querySelectorAll('.crate').forEach(b=>b.onclick=()=>revealShock(+b.dataset.shock))}
function shockAffects(id){return state.shock && (state.shock.mult[id]!==undefined && state.shock.mult[id]<1)}
function postShockAlloc(){let out={};STREAMS.forEach(s=>out[s.id]=state.alloc[s.id]*(state.shock.mult[s.id]??1));return out}
function revealShock(id){state.shock=SHOCKS.find(s=>s.id===id);state.pivot=Object.fromEntries(STREAMS.map(s=>[s.id,0]));renderShock();show('rebuild',3);setTimeout(()=>renderDamagedMini(),160)}
function renderShock(){let s=state.shock, impacts=[];let post=postShockAlloc();let postTotal=Math.max(0,Object.values(post).reduce((a,b)=>a+b,0)-s.fixed);let lost=Math.round(100-postTotal);STREAMS.forEach(st=>{let m=s.mult[st.id];if(m!==undefined&&m<1) impacts.push(`<div class="impact-row"><span>${st.name}</span><strong>-${Math.round((1-m)*100)}%</strong></div>`)});if(s.fixed) impacts.push(`<div class="impact-row"><span>Unplanned operating burden</span><strong>-${s.fixed} pts</strong></div>`);q('shockCard').innerHTML=`<div class="num">SHOCK ${String(s.id).padStart(2,'0')} // ${ROLES[state.role].name.toUpperCase()}</div><h3>${s.title}</h3><p style="color:#c4d1d7;line-height:1.5">${s.desc}</p><div style="margin:18px 0;padding:10px 12px;border:1px solid rgba(255,101,95,.35);background:rgba(255,101,95,.06)"><b style="color:var(--red)">Immediate damage: ${lost} points</b><br><small style="color:#9eb0ba">Your original 100-point stack now carries ${Math.round(postTotal)} effective points before the pivot.</small></div><div class="impact">${impacts.join('')}</div>`;q('moveList').innerHTML=STREAMS.map(st=>`<div class="move-row"><span><b style="color:${st.color}">${st.name}</b> <small style="color:#708591">(post-shock ${Math.round(post[st.id])})</small></span><div class="move-controls"><button data-id="${st.id}" data-dir="-">−</button><output id="pivot-${st.id}">0</output><button data-id="${st.id}" data-dir="+">+</button></div></div>`).join('');document.querySelectorAll('.move-controls button').forEach(b=>b.onclick=()=>pivot(b.dataset.id,b.dataset.dir));q('dependency').innerHTML='<option value="">Choose...</option>'+dependencies.map(x=>`<option>${x}</option>`).join('');q('contract').innerHTML='<option value="">Choose...</option>'+contracts.map(x=>`<option>${x}</option>`).join('');q('pivotUsed').textContent='0 / 20';q('resolve').disabled=true;q('dependency').onchange=checkResolve;q('contract').onchange=checkResolve}
function renderDamagedMini(){/* damage conveyed in shock panel; reserved for future visual cue */}
function pivot(id,dir){let used=Object.values(state.pivot).reduce((a,b)=>a+b,0);if(dir==='+'&&used<20)state.pivot[id]+=5;if(dir==='-'&&state.pivot[id]>0)state.pivot[id]-=5;STREAMS.forEach(s=>q('pivot-'+s.id).value=state.pivot[s.id]);used=Object.values(state.pivot).reduce((a,b)=>a+b,0);q('pivotUsed').textContent=`${used} / 20`}
function checkResolve(){q('resolve').disabled=!(q('dependency').value&&q('contract').value)}
function calcResult(){let post=postShockAlloc();let remaining=Object.values(post).reduce((a,b)=>a+b,0)-state.shock.fixed;remaining=Math.max(0,remaining);let pivot=Object.values(state.pivot).reduce((a,b)=>a+b,0);let final={};STREAMS.forEach(s=>final[s.id]=(post[s.id]||0)+(state.pivot[s.id]||0));let role=ROLES[state.role];let quality=0,total=0;STREAMS.forEach(s=>{let v=final[s.id], w=s.base*(role.bias[s.id]||1);quality+=v*w;total+=v});quality=total?quality/total:0;let conc=concentration(final);let div=diversityScore(final);let pivotVar=Object.values(state.pivot).filter(v=>v>0).length;let depFit=state.shock.fitDeps.includes(q('dependency').value);let contractFit=state.shock.fitContracts.includes(q('contract').value);let pivotQuality=Math.min(100,(pivot?42:18)+pivotVar*9+(depFit?18:8)+(contractFit?18:8));let score=Math.round(Math.max(0,Math.min(100,remaining*.48 + quality*30 + div*.16 + pivotQuality*.12 - Math.max(0,conc-45)*.28)));return {score,remaining:Math.round(remaining),conc:Math.round(conc),pivotQuality:Math.round(pivotQuality),final}}
function renderResult(){let r=calcResult(), s=state.shock; q('score').textContent=r.score;let verdict,cls,copy;if(r.score>=76){verdict='SURVIVES — WITH OPTIONS';cls='good';copy='Your model absorbed the shock without becoming dangerously dependent on a single replacement stream. The organization still has strategic room to maneuver.'}else if(r.score>=56){verdict='SURVIVES — BUT FRAGILE';cls='mid';copy='The organization makes it through the year, but the repair created meaningful dependency. One more shock could expose the model.'}else{verdict='CRITICAL — MODEL UNDER STRESS';cls='bad';copy='The shock exposed a structural weakness in the revenue mix. The problem is not simply lost money—it is concentration and limited alternatives.'}q('verdict').textContent=verdict;q('verdict').className='verdict '+cls;q('resultTitle').textContent=`${ROLES[state.role].name} // ${s.title}`;q('resultCopy').textContent=copy;q('mRemain').textContent=r.remaining+' pts';q('mConc').textContent=r.conc+'%';q('mPivot').textContent=r.pivotQuality+' / 100';let dep=q('dependency').value||'an unresolved dependency';let ct=q('contract').value||'an unidentified legal instrument';let depFit=state.shock.fitDeps.includes(dep),contractFit=state.shock.fitContracts.includes(ct);let fitNote=(depFit&&contractFit)?'Your diagnosis closely matches the shock’s central dependency and legal architecture.': 'Your choices may still be defensible, but be ready to explain why they address this particular shock.';q('lesson').innerHTML=`<b>Debrief:</b> Your pivot now relies on <strong>${dep}</strong>. The legal architecture that deserves more attention is <strong>${ct}</strong>. ${fitNote} Revenue diversification is not the absence of dependence—it is a decision about <em>which</em> dependencies you can manage.`;state.lastResult=r;show('result',4)}
function fullReset(){state={screen:'intro',role:null,alloc:Object.fromEntries(STREAMS.map(s=>[s.id,0])),shock:null,pivot:Object.fromEntries(STREAMS.map(s=>[s.id,0]))};renderRoles();q('roleStatus').textContent='No role selected.';q('lockRole').disabled=true;q('teacherSheet').classList.remove('open');show('intro',0)}
q('begin').onclick=()=>show('roles',0);q('randomRole').onclick=()=>selectRole(Object.keys(ROLES)[Math.floor(Math.random()*4)]);q('lockRole').onclick=()=>{q('roleChip').textContent=ROLES[state.role].name;q('buildPrompt').textContent=`${ROLES[state.role].desc} Allocate exactly 100 points; the stack will be locked after this phase.`;renderStreams();show('build',1)};q('lockBuild').onclick=()=>{renderDeck();show('draw',2)};q('resolve').onclick=renderResult;q('newShock').onclick=()=>{renderDeck();show('draw',2)};q('copyReport').onclick=async()=>{let r=state.lastResult||calcResult();let top=STREAMS.slice().sort((a,b)=>state.alloc[b.id]-state.alloc[a.id])[0];let text=`Revenue Jenga Pod Report\nRole: ${ROLES[state.role].name}\nTop original revenue exposure: ${top.name} (${state.alloc[top.id]} pts)\nShock: ${state.shock.title}\nPost-shock revenue: ${r.remaining} pts\nResilience score: ${r.score}/100\nNew dependency: ${q('dependency').value}\nContract/legal instrument: ${q('contract').value}`;try{await navigator.clipboard.writeText(text);q('copyReport').textContent='Copied';setTimeout(()=>q('copyReport').textContent='Copy Pod Report',1400)}catch(e){alert(text)}};q('startOver').onclick=fullReset;q('resetTop').onclick=fullReset;q('teacherBtn').onclick=()=>q('teacherSheet').classList.toggle('open');
renderRoles();
