'use strict';
(()=>{
const ENDPOINT='https://havsvkhddvdbzbsmhqbr.supabase.co/functions/v1/spm370-llc2/instructor';
const STORE='spm370_llc2_teacher_v2';
const $=id=>document.getElementById(id);let key='',rows=[],isOpen=true,loading=false,unlocked=false;
function say(s){$('notice').textContent=s;$('notice').hidden=!s;}
function esc(s){return String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));}
async function api(body){const controller=new AbortController(),timer=setTimeout(()=>controller.abort(),18000);try{const r=await fetch(ENDPOINT,{method:body?'POST':'GET',cache:'no-store',headers:{'x-instructor-key':key,...(body?{'Content-Type':'application/json'}:{})},...(body?{body:JSON.stringify(body)}:{}),signal:controller.signal});const d=await r.json();if(!r.ok)throw new Error(d.error||'Request failed.');return d;}finally{clearTimeout(timer);}}
function matches(r){return `${r.first_name} ${r.last_name} ${r.email}`.toLowerCase().includes($('search').value.trim().toLowerCase());}
function render(){const done=rows.filter(r=>r.submitted_at);$('completed').textContent=done.length;$('inProgress').textContent=rows.length-done.length;$('average').textContent=done.length?(done.reduce((s,r)=>s+Number(r.score),0)/done.length).toFixed(2):'—';$('availability').textContent=isOpen?'OPEN · students may begin':'CLOSED · no new starts';$('toggle').textContent=isOpen?'Close new attempts':'Open new attempts';
const list=rows.filter(r=>matches(r)&&($('filter').value==='all'||($('filter').value==='complete'?!!r.submitted_at:!r.submitted_at)));
$('rows').innerHTML=list.length?list.map(r=>{const complete=!!r.submitted_at;const answers=(r.responses||[]).map(x=>`${x.question}:${x.answerLetter} ${x.correct?'✓':'×'}`).join(' · ');const date=complete?new Date(r.submitted_at).toLocaleString('en-US',{timeZone:'America/New_York',month:'short',day:'numeric',hour:'numeric',minute:'2-digit'}):'—';return `<tr><td><strong>${esc(r.last_name)}, ${esc(r.first_name)}</strong><span class="email">${esc(r.email)}</span></td><td><span class="badge">${complete?'Complete':'In progress'}</span></td><td>${complete?`<strong>${r.score} / 8</strong><br>${Number(r.score)*12.5}%`:`${r.score} points so far`}</td><td>${r.responses.length} / 8</td><td class="answers">${esc(answers)||'—'}</td><td>${esc(date)}</td><td><button class="secondary recover" data-id="${esc(r.id)}">Recovery link</button></td></tr>`;}).join(''):'<tr><td colspan="7">No attempts to display.</td></tr>';
}
async function load(){if(loading)return;loading=true;try{const d=await api();rows=d.attempts||[];isOpen=!!d.isOpen;render();say('');$('updated').textContent='Last loaded '+new Date().toLocaleTimeString()+'. Auto-refresh: 20 seconds.';}finally{loading=false;}}
async function login(){key=$('key').value.trim();if(!key)return;$('open').disabled=true;try{await load();unlocked=true;try{sessionStorage.setItem(STORE,key);}catch{}$('key').value='';$('login').hidden=true;$('dashboard').hidden=false;}catch(e){say(e.message||'Could not open gradebook.');}finally{$('open').disabled=false;}}
$('loginForm').onsubmit=e=>{e.preventDefault();login();};$('refresh').onclick=()=>load().catch(e=>say('Refresh failed. Previously loaded rows may be stale. '+e.message));
$('logout').onclick=()=>{unlocked=false;key='';rows=[];try{sessionStorage.removeItem(STORE);}catch{}$('rows').replaceChildren();$('privateLink').value='';$('recovery').hidden=true;$('dashboard').hidden=true;$('login').hidden=false;say('');};
$('search').oninput=render;$('filter').onchange=render;
$('toggle').onclick=async()=>{if(!confirm(isOpen?'Close the check to new attempts? Students already working can still finish.':'Open the check to new attempts?'))return;const desired=!isOpen;$('toggle').disabled=true;try{await api({action:'set_open',isOpen:desired});await load();}catch(e){say(e.message);}finally{$('toggle').disabled=false;}};
$('rows').onclick=async e=>{const button=e.target.closest('.recover');if(!button)return;const r=rows.find(x=>x.id===button.dataset.id);if(!r||!confirm(`Generate a private recovery link for ${r.first_name} ${r.last_name}? The old browser token will stop working. Locked answers will stay unchanged.`))return;button.disabled=true;try{const d=await api({action:'recover',id:r.id});$('privateLink').value=new URL('../',location.href).href+'#resume='+d.resumeToken;$('recovery').hidden=false;$('privateLink').focus();$('privateLink').select();}catch(error){say(error.message);}finally{button.disabled=false;}};
$('hideRecovery').onclick=()=>{$('privateLink').value='';$('recovery').hidden=true;};
function cell(v){let s=String(v??'');if(/^[\s]*[=+@-]/.test(s))s="'"+s;return '"'+s.replace(/"/g,'""')+'"';}
$('export').onclick=()=>{const list=rows.filter(r=>r.submitted_at&&matches(r));if(!list.length){say('There are no completed scores matching this search to export.');return;}const header=['Last name','First name','Email','Score','Points possible','Percent','Submitted at UTC','Receipt','Version',...Array.from({length:8},(_,i)=>`Q${i+1} response`),...Array.from({length:8},(_,i)=>`Q${i+1} correct`)];const lines=[header,...list.map(r=>[r.last_name,r.first_name,r.email,r.score,8,Number(r.score)*12.5,r.submitted_at,r.receipt,r.version,...r.responses.map(x=>x.answerLetter),...r.responses.map(x=>x.correct?1:0)])];const blob=new Blob(['\ufeff'+lines.map(row=>row.map(cell).join(',')).join('\r\n')],{type:'text/csv;charset=utf-8'});const url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download='SPM370_Copyright_Trail_Grades_'+new Date().toISOString().slice(0,10)+'.csv';a.click();setTimeout(()=>URL.revokeObjectURL(url),3000);};
setInterval(()=>{if(unlocked&&!document.hidden)load().catch(e=>say('Auto-refresh failed. Previously loaded rows may be stale. '+e.message));},20000);
try{const old=sessionStorage.getItem(STORE);if(old){$('key').value=old;login();}}catch{}
})();
