'use strict';
(()=>{
const $=s=>document.querySelector(s),esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const KEY='spm370-bys-quiz-draft-v2';let state=null,answers=[],at=0,busy=false;
const countWords=s=>(String(s||'').trim().match(/\S+/g)||[]).length;
const complete=i=>i<12?Number.isInteger(answers[i]):countWords(answers[i])>=15;
function saveLocal(){try{localStorage.setItem(KEY,JSON.stringify({token:BYS.token(),revision:state.revision,answers,at}));}catch{const s=$('#draftStatus');if(s)s.textContent='Browser saving is blocked. Use Save and continue, and save your resume code.';}}
function focus(){window.scrollTo({top:0,behavior:'instant'});$('#quiz').focus({preventScroll:true});}
function notice(s){const n=$('#notice');if(n)n.textContent=s;}
function render(){
 if(state.quizSubmittedAt){finish();return;}
 const a=state.assessment,q=a.items[at];
 $('#quiz').innerHTML=`<section class="paper"><p class="eyebrow">Legal Literacy Check 3 · NIL and Contracts</p><h1>${at<14?'Apply what you learned.':'Review and submit.'}</h1><p><strong>${esc(state.name)}</strong> · ${esc(state.email)}</p><details><summary>Instructions and allowed materials</summary><p>${esc(a.instructions)}</p><p>One final submission. You may revise responses before submitting. Correct answers and grades are held for instructor review.</p></details><nav class="question-grid" aria-label="Quiz questions">${a.items.map((_,i)=>`<button type="button" data-q="${i}" class="secondary ${complete(i)?'answered':''}" ${at===i?'aria-current="step"':''} aria-label="Question ${i+1}, ${complete(i)?'answered':'not yet complete'}">${i+1}</button>`).join('')}<button id="review" class="secondary" ${at===14?'aria-current="step"':''}>Review</button></nav><p class="small">${answers.filter((_,i)=>complete(i)).length} of 14 responses complete · 20 points total</p><div id="questionArea">${at<14?`<p class="eyebrow">Question ${at+1} of 14 · ${q.points} ${q.points===1?'point':'points'}</p><fieldset><legend>${esc(q.q)}</legend>${q.type==='mc'?`<div class="options">${q.options.map((o,i)=>`<label class="option"><input type="radio" name="answer" value="${i}" ${answers[at]===i?'checked':''}><span>${esc(o)}</span></label>`).join('')}</div>`:`<label for="essay" class="small">Your response · aim for 40–70 words</label><textarea id="essay" maxlength="6000">${esc(answers[at])}</textarea><p id="wordCount" class="small">${countWords(answers[at])} words · at least 15 words to submit</p>`}</fieldset><div class="actions"><button id="next">Save and ${at===13?'review':'continue'}</button>${at>0?'<button id="previous" class="secondary">Previous question</button>':''}</div>`:`<h2>Ready for your final submission?</h2><p>${answers.every((_,i)=>complete(i))?'All 14 questions have a response. Review any question above, then affirm your individual work and submit.':'Some responses need attention. Select an incomplete question above; short responses need at least 15 words.'}</p><label class="checkline"><input id="attestQuiz" type="checkbox"><span>I completed this check individually using only permitted course materials, without generative AI or help from another person.</span></label><p>Your answers will be locked when the server confirms submission. The two short responses are graded by the instructor.</p><div class="actions"><button id="submitQuiz" ${!answers.every((_,i)=>complete(i))?'disabled':''}>Submit Legal Literacy Check 3</button></div>`}</div><div id="notice" class="error" role="alert"></div><p id="draftStatus" class="small muted">Draft kept on this browser. Save and continue also saves it privately with your instructor.</p><button id="saveCode" class="text-button">Download my private resume code</button></section>`;
 document.querySelectorAll('[data-q]').forEach(b=>b.onclick=()=>move(Number(b.dataset.q)));$('#review').onclick=()=>move(14);
 document.querySelectorAll('input[name=answer]').forEach(n=>n.onchange=()=>{answers[at]=Number(n.value);saveLocal();});
 if($('#essay'))$('#essay').oninput=e=>{answers[at]=e.target.value;$('#wordCount').textContent=countWords(e.target.value)+' words · at least 15 words to submit';saveLocal();};
 if($('#next'))$('#next').onclick=()=>move(at+1);if($('#previous'))$('#previous').onclick=()=>move(at-1);
 if($('#submitQuiz'))$('#submitQuiz').onclick=submit;
 $('#saveCode').onclick=()=>download('SPM 370 private resume code\n'+BYS.token()+'\nKeep this code private. Enter it in Course reference on the activity page.\n','SPM370_Private_Resume_Code.txt');
}
async function move(n){if(busy)return;busy=true;document.querySelectorAll('button,fieldset').forEach(b=>b.disabled=true);notice('Saving your responses…');try{state=await BYS.call('saveQuiz',{revision:state.revision,answers});if(state.quizSubmittedAt){render();return;}at=n;saveLocal();render();focus();}catch(e){notice(e.message);document.querySelectorAll('button,fieldset').forEach(b=>b.disabled=false);}finally{busy=false;}}
async function submit(){if(busy)return;if(!$('#attestQuiz').checked){notice('Confirm the individual-work statement before submitting.');return;}busy=true;$('#submitQuiz').disabled=true;notice('Submitting your check. Wait for a receipt…');saveLocal();try{state=await BYS.call('submitQuiz',{revision:state.revision,answers,attest:true});if(!state.quizReceipt)throw Error('No receipt was returned. Resume before assuming submission.');try{localStorage.removeItem(KEY);}catch{}render();focus();}catch(e){notice(e.message);$('#submitQuiz').disabled=false;}finally{busy=false;}}
function download(text,name){const url=URL.createObjectURL(new Blob([text],{type:'text/plain'})),a=document.createElement('a');a.href=url;a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(url),2000);}
function finish(){
 $('#quiz').innerHTML=`<section class="paper"><p class="eyebrow">Both parts recorded</p><h1>Your work is submitted.</h1><p><strong>${esc(state.name)}</strong><br>${esc(state.email)}</p><div class="receipt"><h2>Activity receipt</h2><p class="receipt-code">${esc(state.activityReceipt)}</p><p>${esc(new Date(state.activitySubmittedAt).toLocaleString())}</p><h2>Legal Literacy Check 3 receipt</h2><p class="receipt-code">${esc(state.quizReceipt)}</p><p>${esc(new Date(state.quizSubmittedAt).toLocaleString())}</p></div><p>Your instructor can see both submissions under your name and email. The activity and two short responses require instructor review. No upload or additional submission is needed.</p><div class="actions"><button id="receiptDownload">Download both receipts</button><button id="forget" class="secondary">Clear this device’s saved access</button></div><p class="small">Keep your resume code before clearing access. Server submissions are retained.</p><div id="notice" role="status"></div></section>`;
 $('#receiptDownload').onclick=()=>download(`SPM 370 · October 8, 2026\nName: ${state.name}\nEmail: ${state.email}\nActivity: ${state.activityReceipt}\nSubmitted: ${state.activitySubmittedAt}\nLegal Literacy Check 3: ${state.quizReceipt}\nSubmitted: ${state.quizSubmittedAt}\nBoth submissions are recorded for instructor review.\n`,'SPM370_Submission_Receipts.txt');
 $('#forget').onclick=()=>{if(confirm('Clear saved access on this device? Your server submissions will remain. Keep your private resume code if you need to reopen them.')){BYS.forget();try{localStorage.removeItem(KEY);localStorage.removeItem('spm370-before-you-sign-v1');}catch{}location.href='../';}};
}
async function boot(){try{if(!BYS.hasSession())throw Error('Start the activity first, or enter your private resume code in Course reference on the activity page.');state=await BYS.resume();if(!state.activitySubmittedAt)throw Error('Submit your Before You Sign activity first. The check opens after its receipt.');answers=state.quizAnswers.length===14?state.quizAnswers:Array.from({length:14},(_,i)=>i<12?null:'');let draft;try{draft=JSON.parse(localStorage.getItem(KEY)||'null');}catch{}if(!state.quizSubmittedAt&&draft?.token===BYS.token()&&draft.revision===state.revision&&Array.isArray(draft.answers)&&draft.answers.length===14){answers=draft.answers;at=Number.isInteger(draft.at)&&draft.at>=0&&draft.at<=14?draft.at:0;}render();}catch(e){$('#quiz').innerHTML=`<section class="paper"><h1>Resume your assignment.</h1><p role="alert">${esc(e.message)}</p><a href="../">Return to Before You Sign</a><div class="actions"><button id="retry">Retry connection</button></div></section>`;$('#retry').onclick=boot;}}
boot();
})();
