import {BRANDS,PHASES,ROLES,METRICS,AUDIENCES,OBJECTIVES,OPTIONS,LABELS,JOURNEY,TONES,SHOCK,RUBRIC,brand,choice,budget,campaignCost,validateCampaign,totalGrade,clone} from './model.mjs';
const API='https://havsvkhddvdbzbsmhqbr.supabase.co/functions/v1/spm343-marketing-arena';
const $=s=>document.querySelector(s), esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const params=new URLSearchParams(location.search);let mode=params.get('view')||'student',code=(params.get('room')||'').toUpperCase();
let adminKey=sessionStorage.getItem('arena-admin')||'', token=code?localStorage.getItem('arena-key-'+code)||'':'', S=null, draft={},step=0,tab='control',selected=null,rooms=[],pending=Promise.resolve(),saving=0,dirty=false,polling=false,lastGood=0,autoTimer=null,personalTimer=null;
const root=$('#main');let previousBoard={};if(mode==='projector')document.body.classList.add('projector-mode');
function key(){return Array.from(crypto.getRandomValues(new Uint8Array(32))).map(x=>x.toString(16).padStart(2,'0')).join('');}
function toast(msg){$('#toast').textContent=msg;$('#toast').style.display='block';clearTimeout(toast.t);toast.t=setTimeout(()=>$('#toast').style.display='none',6500);}
function status(msg,bad=false){$('#connection').textContent=msg;$('#connection').className=bad?'bad':'';}
function saveStatus(msg){const el=$('#save-state');if(el)el.textContent=msg;}
async function api(action,body={},credentials=true){
 const controller=new AbortController(),timeout=setTimeout(()=>controller.abort(),20000);
 try{const response=await fetch(API,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({action,code,...(credentials&&mode==='instructor'?{adminKey}:credentials&&mode==='student'?{token}:{}),...body}),signal:controller.signal});const data=await response.json();if(!response.ok||data.error)throw Error(data.error||'Request failed.');lastGood=Date.now();status('Live · synced '+new Date().toLocaleTimeString([],{hour:'2-digit',minute:'2-digit'}));return data;}catch(e){status('Not synced · retrying',true);throw Error(e.name==='AbortError'?'Connection timed out. Your draft is retained; retry.':e.message);}finally{clearTimeout(timeout);}
}
function accept(data){if(!S||data.code!==S.code||data.version===undefined||data.version>=S.version)S=data;}
function enqueue(fn){const next=pending.catch(()=>{}).then(fn);pending=next;return next;}
async function act(action,body={}){return enqueue(async()=>{saving++;try{const data=await api(action,body);accept(data);return data;}finally{saving--;}});}
async function confirmLock(title='Lock this decision?',message='Your instructor will receive this submission. You cannot edit it after locking.'){const d=$('#confirm');$('#confirm-title').textContent=title;$('#confirm-message').textContent=message;d.showModal();return new Promise(resolve=>d.addEventListener('close',()=>resolve(d.returnValue==='yes'),{once:true}));}
const btn=(label,action,cls='secondary',extra='')=>`<button type="button" class="${cls}" data-action="${action}" ${extra}>${label}</button>`;
const input=(name,label,value='',hint='',type='text')=>`<label for="${name}">${label}${hint?`<small>${hint}</small>`:''}</label><input id="${name}" name="${name}" type="${type}" value="${esc(value)}" ${type==='email'?'autocomplete="email"':''} maxlength="${type==='password'?150:200}">`;
const area=(name,label,value='',hint='')=>`<label for="${name}">${label}${hint?`<small>${hint}</small>`:''}</label><textarea id="${name}" name="${name}" maxlength="2500">${esc(value)}</textarea>`;
const select=(name,label,options,value='')=>`<label for="${name}">${label}</label><select id="${name}" name="${name}"><option value="">Choose…</option>${Object.entries(options).map(([id,label])=>`<option value="${id}" ${id===value?'selected':''}>${esc(label)}</option>`).join('')}</select>`;
const labelValues=o=>Object.fromEntries(o.map(x=>[x.id,x.name||x.label]));
const timeString=ms=>{let s=Math.max(0,Math.ceil(ms/1000));return `${Math.floor(s/60)}:${String(s%60).padStart(2,'0')}`;};
function timer(){if(!S?.timer)return '';return timeString(S.timer.end?S.timer.end-(Date.now()+(S._offset||0)):S.timer.remaining);}
function shell(content){return `<div class="session-head"><div><div class="eyebrow">${esc(S.lab)}${S.makeup?' · INDIVIDUAL ALTERNATIVE':''}</div><h2>${esc(S.label)}</h2></div><div><span class="join-code">${esc(S.code)}</span><div class="clock" id="clock">${timer()}</div></div></div><nav class="phasebar" aria-label="Activity progress">${PHASES.map((p,i)=>`<span class="${i===S.phase?'active':i<S.phase?'done':''}" ${i===S.phase?'aria-current="step"':''}>${i+1}. ${p}</span>`).join('')}</nav>${S.paused?'<div class="notice warning">Activity paused by the instructor. Keep your current page open; your draft is retained.</div>':''}${content}`;}
function rubric(){return `<details><summary>How this Decision Lab is graded · 100 points</summary><div><p>The simulated Market Power score determines the leaderboard. Your instructor grades the quality of your reasoning separately: 25 individual points + 75 group points.</p><div class="rubric-list">${RUBRIC.map(r=>`<span>${r.label} <small class="muted">(${r.level})</small></span><b>${r.max}</b>`).join('')}</div><p class="small muted">For an approved individual alternative, you complete all components yourself. Generative AI is not permitted unless Prof. Levine expressly authorizes it.</p></div></details>`;}
function entry(){
 root.innerHTML=`<div class="split entry"><section class="entry-title"><div class="eyebrow">A LIVE ESPORTS MARKETING DECISION LAB</div><h1>Win the audience.<br><em>Earn the right<br>to stay.</em></h1><p class="lead">You have a brand, 100 credits and a market full of rivals. Build a campaign people value. Then defend it when the market turns.</p><div class="factline"><div><b>6</b>competing brands</div><div><b>100</b>campaign credits</div><div><b>1</b>shared market</div></div><p class="small muted">Your choices affect everyone’s market. Your reasoning determines your grade.</p></section><section class="panel"><div class="eyebrow">${mode==='instructor'?'INSTRUCTOR CONSOLE':mode==='projector'?'CLASSROOM LIVE FEED':'TAKE YOUR SEAT'}</div><h2>${mode==='instructor'?'Run the room.':mode==='projector'?'Open the market board.':'Join your class.'}</h2>${mode==='instructor'?`<form id="login">${input('adminKey','Instructor access key','','Use the private key in your instructor guide.','password')}<div class="actions"><button>Open instructor console →</button></div></form>`:mode==='projector'?`<form id="open-projector">${input('room','Room code',code)}<div class="actions"><button>Open live leaderboard →</button></div></form>`:`<form id="join">${input('room','Room code',code,'Your instructor will display this.')}<div class="grid2"><div>${input('name','Full name')}</div><div>${input('email','School email','','Use your official school address.','email')}</div></div>${select('team','Assigned brand',labelValues(BRANDS))}<div class="actions"><button>Join the arena →</button></div><p class="small muted">Names, emails and assessment responses are visible to your instructor. The public board shows brands only.</p></form><details><summary>Already joined? Recover your seat</summary><div><form id="recover"><p class="small">Use the same room code above and your saved personal recovery key.</p>${input('recoveryKey','Personal recovery key','','','password')}<div class="actions"><button class="secondary">Recover my seat</button></div></form></div></details>`}<div class="actions"><a href="?view=student">Student entry</a><span class="muted">/</span><a href="?view=projector">Projector</a><span class="muted">/</span><a href="?view=instructor">Instructor</a></div></section></div><div class="brand-strip">${BRANDS.map(b=>`<div class="brand-mini" style="--brand:${b.color}"><b>${b.name}</b>${b.category}</div>`).join('')}</div>${rubric()}`;
}
function account(){const b=brand(S.me.team);const cost=campaignCost(draft,S.phase>=5?S.team?.initial:null,draft.response);return `<aside class="panel account" style="--brand:${b.color}"><div class="eyebrow">YOUR ACCOUNT</div><h2>${b.name}</h2><p class="category">${b.category}</p><p class="small">${b.description}</p><dl><dt>BOARD MANDATE</dt><dd>${b.mandate}</dd><dt>ADVANTAGE</dt><dd>${b.strength}</dd><dt>VULNERABILITY</dt><dd>${b.risk}</dd><dt>GROWTH OPPORTUNITY</dt><dd>${b.opportunity}</dd></dl>${S.phase>=3?`<div class="budget"><span class="small muted">CAMPAIGN COMMITMENT</span><div><strong id="budget-number" class="${cost.total>100?'bad':''}">${cost.total}</strong> <span class="muted">/ 100 credits</span></div><progress id="budget-meter" max="100" value="${Math.min(100,cost.total)}"></progress><span id="budget-note" class="small muted">${100-cost.total} available${S.phase===5?' · includes response costs':''}</span></div>`:''}<details><summary class="small">What counts as success?</summary><div class="small">${b.weights.map((v,i)=>`${METRICS[i]} ${Math.round(v*100)}%`).join('<br>')}<p class="muted">Weights follow your board mandate. These fictional indices are teaching tools, not sales forecasts. Written reasoning is graded by your instructor.</p></div></details></aside>`;}
function student(){
 if(!S.me){entry();return;}
 if(!Object.keys(draft).length&&S.team)loadDraft();
 const me=S.me,b=brand(me.team);let content='';
 if(me.excused)content='<div class="notice warning">Your instructor marked this record excused. Ask about an individual alternative or reactivation.</div>';
 else if(S.phase===0)content=`<div class="panel"><div class="eyebrow">YOU ARE IN</div><h2>${esc(me.name)}, meet ${b.name}.</h2><p>Read the board mandate. Wait to discuss strategy until everyone has submitted an independent recommendation.</p><div class="notice">Your instructor will open the individual-position round.</div><h3>How the next 50 minutes work</h3><p>Make your own call → share role information → build one team campaign → respond to the market shock → defend your own judgment.</p><p class="small muted">Each student needs a device for the two individual responses. One team recorder enters shared decisions; that responsibility rotates after the shock.</p>${rubric()}</div>`;
 else if(!me.initial&&S.phase<=3)content=`<div class="panel"><div class="eyebrow">INDEPENDENT · 10 POINTS</div><h2>Your initial call.</h2><p>Before talking with your team, decide what this brand should prioritize and why. Aim for 50–100 words.</p><form id="initial">${select('audience','Primary audience',AUDIENCES)}${select('objective','Primary objective',OBJECTIVES)}${area('position','What should your brand prioritize in esports marketing, and why?',localStorage.getItem('arena-personal-'+code)||me.personalDraft||'','Connect the audience’s motivation, your board mandate and an initial strategic direction.')}<div class="bottom-save"><span class="save-state" id="save-state">Your individual response stays private until you lock it.</span><button>Lock my position →</button></div></form></div>`;
 else if(S.phase===1)content=`<div class="panel"><p class="locked">✓ Individual position locked</p><h2>Hold your recommendation.</h2><p>Wait for the instructor to open team briefing. Your teammates’ responses are still sealed.</p><p class="response">${esc(me.initial.text)}</p></div>`;
 else if(S.phase===2)content=`<div class="panel"><div class="eyebrow">ROLE BRIEFING</div><h2>Your team needs what you know.</h2><p>Read your private brief, then share its implications verbally. Teams with fewer than five people combine responsibilities.</p>${intel()}${peerPositions()}<div class="notice">Agree on an audience and strategic purpose before selecting tactics. Your recorder will enter the shared campaign in the next round.</div>${rubric()}</div>`;
 else if(S.phase===3||S.phase===5){const locked=S.phase===3?S.team.initial:S.team.final;
  if(locked)content=`<div class="panel"><p class="locked">✓ ${S.phase===5?'Response':'Campaign'} locked</p><h2>${S.phase===5?'Your response is in the market.':'Your campaign is in the market.'}</h2><p>The board below refreshes as other teams lock. Changes are provisional until all active teams have committed.</p>${report()}${leaderboard(false)}${S.phase===5?'':peerPositions()}</div>`;
  else if(S.editor!==me.id)content=`<div class="panel">${S.phase===5?shock():''}<div class="eyebrow">TEAM DELIBERATION</div><h2>Contribute your judgment.</h2><p><b>${esc(S.peers?.find(p=>p.id===S.editor)?.name||'Your teammate')}</b> is the team recorder for this round. Discuss choices together; only the recorder edits the shared campaign.</p>${intel()}<h3>Shared draft · updates live</h3>${campaignSummary(S.team.draft)}${peerPositions()}</div>`;
  else content=builder();
 }
 else if(S.phase===4||S.phase===6)content=`<div class="panel"><div class="eyebrow">${S.phase===4?'INITIAL MARKET':'FINAL MARKET'}</div>${report()}<p class="muted">What worked, what did you give up, and how did other teams change the conditions?</p>${leaderboard(false)}</div>`;
 else if(S.phase===7)content=me.defense?`<div class="panel"><p class="locked">✓ Individual defense submitted</p><h2>Your evidence is recorded.</h2><p>Join the class debrief. The instructor will review your reasoning using the rubric.</p>${report()}</div>`:`<div class="panel"><div class="eyebrow">INDEPENDENT · 15 POINTS</div><h2>If this were your decision alone…</h2><p>Identify one campaign decision you would keep and one you would change. Explain why using marketing concepts and the market results. Aim for 100–150 words.</p>${report()}<form id="defense-form">${area('defense','Your final executive defense',localStorage.getItem('arena-defense-'+code)||me.defenseDraft||'','Distinguish what the simulated score suggests from what you can actually conclude.')}<div class="bottom-save"><span class="save-state" id="save-state">Your response is assessed individually.</span><button>Submit my defense →</button></div></form></div>`;
 else content=`<div class="panel"><div class="eyebrow">DECISION LAB COMPLETE</div><h2>You have a result. Now explain it.</h2>${report()}${campaignSummary(S.team?.final)}<div class="actions">${btn('Download my decision record','download-student')}${btn('Print report','print')}</div><p class="small muted">Market Power is separate from your academic grade. Official feedback and grades come from your instructor.</p>${rubric()}</div>`;
 root.innerHTML=shell(`<div class="workspace">${account()}<section>${content}</section></div><details class="recovery"><summary>My recovery key & session controls</summary><div><p>Keep this key private. It restores access to your record if you change devices.</p><code>${esc(token)}</code><div class="actions">${btn('Copy recovery key','copy-key')}${btn('Leave this device','logout','quiet')}</div></div></details>`);
}
function intel(){return (S.intel||[]).map(x=>`<div class="intel" style="--brand:${brand(S.me.team).color}"><h3>${esc(x.role)}</h3><p>${esc(x.note)}</p></div>`).join('');}
function peerPositions(){return `<details><summary>Team’s initial recommendations</summary><div>${(S.peers||[]).map(p=>`<h3>${esc(p.name)} · ${esc(p.role)}</h3><p class="response">${esc(p.initial?.text||'Position not yet locked.')}</p>`).join('')}</div></details>`;}
function shock(){return `<div class="notice shock"><div class="eyebrow">MARKET SHOCK / 48 HOURS TO LAUNCH</div><p>${SHOCK.replace('48 HOURS TO LAUNCH: ','')}</p></div>`;}
function loadDraft(){let local;try{local=JSON.parse(localStorage.getItem(`arena-draft-${code}-${S.phase}`)||'null');}catch{}draft=clone(local?.serverVersion===S.team?.draftVersion?local.campaign:S.team?.draft||S.team?.initial||{});}
function setDraft(){localStorage.setItem(`arena-draft-${code}-${S.phase}`,JSON.stringify({campaign:draft,serverVersion:S.team?.draftVersion}));dirty=true;saveStatus('Draft retained on this device · syncing…');clearTimeout(autoTimer);autoTimer=setTimeout(()=>saveDraft().catch(e=>{saveStatus('Not synced · use Save draft to retry');toast(e.message);}),1100);}
async function saveDraft(){if(!dirty||!S?.team||S.editor!==S.me.id)return;return enqueue(async()=>{saving++;const sent=JSON.stringify(draft);try{const data=await api('draft',{campaign:JSON.parse(sent),draftVersion:S.team.draftVersion});accept(data);if(JSON.stringify(draft)===sent){dirty=false;localStorage.removeItem(`arena-draft-${code}-${S.phase}`);saveStatus('Draft saved to instructor records');}}finally{saving--;}});}
function builder(){
 const adapt=S.phase===5;const tabs=['01 Strategy','02 Five Ps','03 Channel & journey','04 Decision memo'];let body='';
 if(step===0)body=`<div class="step-title"><span class="step-num">01</span><h2>Choose the strategic purpose.</h2></div><p class="muted">A tactic is an action. Your strategy explains how a specific audience will help you meet the board’s objective.</p>${select('audience','Primary audience',AUDIENCES,draft.audience)}${select('objective','Primary objective',OBJECTIVES,draft.objective)}${area('strategy','We will use esports to…',draft.strategy,'Complete: achieve [objective] for [audience] by [distinctive value or approach].')}${area('behavior','What should the consumer actually do?',draft.behavior,'Name an observable action, such as register for a trial, purchase, return or participate.')}${area('audienceReason','Why this audience?',draft.audienceReason,'Use a motivation from the module: socialization, competition, learning, novelty, belonging or another defensible motive.')}<div class="actions">${btn('Continue to the Five Ps →','next','')}</div>`;
 if(step===1)body=`<div class="step-title"><span class="step-num">02</span><h2>Make the mix work together.</h2></div><p class="muted">Select one option in each category. “Place” is where the customer obtains the offering. Your communication channel comes next.</p>${['product','price','place','promotion','pr'].map(k=>cards(k)).join('')}<div class="actions">${btn('← Strategy','back')}${btn('Continue to activation →','next','')}</div>`;
 if(step===2)body=`<div class="step-title"><span class="step-num">03</span><h2>Reach people. Give them a reason to return.</h2></div>${cards('channel')}${cards('creator')}${select('tone','Campaign voice',TONES,draft.tone)}<hr class="divider"><h3>Before, during and after</h3><p class="muted">These actions use the campaign resources already selected. Choose a coherent sequence.</p><div class="grid3">${Object.keys(JOURNEY).map(k=>'<div>'+select(k,k[0].toUpperCase()+k.slice(1)+' the event',JOURNEY[k],draft[k])+'</div>').join('')}</div>${area('activationReason','Why this creator, channel and sequence?',draft.activationReason,'Explain fit and how you will build a relationship beyond launch.')}<div class="actions">${btn('← Five Ps','back')}${btn('Continue to decision memo →','next','')}</div>`;
 if(step===3)body=`<div class="step-title"><span class="step-num">04</span><h2>Make the decision defensible.</h2></div><p class="muted">Keep each answer focused: two or three specific sentences. The instructor assesses your reasoning, not how many words you write.</p>${area('mixReason','How do your Five Ps reinforce each other?',draft.mixReason,'Connect the product, price and distribution with your promotion and public relations choices.')}${area('authReason','Why would this audience see the campaign as credible?',draft.authReason,'Name a useful contribution, a fit with the brand, and how you avoid stereotypes.')}${area('riskReason','What do you give up, and who might object?',draft.riskReason,'Name a tradeoff, a stakeholder tension, a meaningful risk and a mitigation.')}${area('marketingType','Marketing of esports, through esports, or both?',draft.marketingType,'Explain which applies to your consumer brand and what esports itself gains or risks.')}<h3 style="margin-top:24px">Your campaign at a glance</h3>${campaignSummary(draft)}${adapt?area('adaptationReason','Defend your shock response',draft.adaptationReason,'What changed? What did you preserve or change? Identify the tradeoff, protected metric and why your response still meets the board mandate.'):''}<div class="actions">${btn('← Activation','back')}${btn(adapt?'Lock shock response →':'Lock campaign →','lock-campaign','')}</div>`;
 return `<section class="panel">${adapt?shock():''}<div class="row"><div class="eyebrow">TEAM RECORDER · ${esc(S.me.name)}</div><span class="pill">${adapt?'Roles rotated':'Build round'}</span></div>${adapt?`<h3>Your response</h3>${select('response','Stay, pivot or double down?',{stay:'Stay the course · no change cost',pivot:'Pivot · change 1–2 paid categories, 5 credits each',double:'Double down · same paid choices + 10-credit investment'},draft.response)}${draft.response==='double'?select('protect','Where does the extra investment go?',Object.fromEntries(METRICS.slice(0,4).map(m=>[m,m])),draft.protect):''}<p class="small muted">All costs, including revisions, must fit within 100 credits. Non-paid choices and explanations may be refined. Do not change paid choices unless you choose Pivot.</p>`:''}<nav class="tabs" aria-label="Campaign sections">${tabs.map((t,i)=>btn(t,'step',i===step?'active':'secondary',`data-step="${i}"`)).join('')}</nav><form id="campaign-form">${body}</form><div class="bottom-save"><span class="save-state" id="save-state">${dirty?'Unsynced changes on this device':'Draft saves as you work'}</span>${btn('Save draft','save-draft')}</div><details><summary>Your role information</summary><div>${intel()}</div></details>${peerPositions()}</section>`;
}
function cards(k){return `<fieldset><legend>${LABELS[k]}</legend><div class="tactics">${OPTIONS[k].map(o=>`<label class="tactic ${draft[k]===o.id?'selected':''}"><input type="radio" name="${k}" value="${o.id}" ${draft[k]===o.id?'checked':''}><b>${o.label}</b><span class="cost">${o.cost} credits</span><p>${o.desc}</p><span class="caution">Tradeoff: ${o.caution}</span>${o.audiences?.includes(draft.audience)?'<span class="fit">Potential audience fit · justify the connection</span>':''}</label>`).join('')}</div></fieldset>`;}
function campaignSummary(c){if(!c)return '<p class="muted">No shared draft yet.</p>';return `<p class="response">${esc(c.strategy||'Strategy not yet recorded.')}</p><div class="selection-summary">${Object.keys(OPTIONS).map(k=>`<span><b>${LABELS[k].split(' ·')[0]}:</b> ${esc(choice(k,c[k])?.label||'Not selected')}</span>`).join('')}</div><p class="small muted">${esc(AUDIENCES[c.audience]||'Audience undecided')} · ${esc(OBJECTIVES[c.objective]||'Objective undecided')} · ${budget(c)} base credits</p>`;}
function report(){const r=S.ownResult;if(!r)return '<p class="muted">Market results appear after the campaign locks.</p>';const initial=S.initialResults?.find(x=>x.team===r.team),delta=initial?r.power-initial.power:null;const sorted=Object.entries(r.metrics).sort((a,b)=>b[1]-a[1]);return `<div class="score-hero reveal-in"><div class="power">${r.power}</div><div><div class="eyebrow">MARKET POWER / 100</div><h2>Rank ${r.rank}${delta!==null?` · ${delta>=0?'+':''}${delta} since initial reveal`:''}</h2><p class="small muted">Strongest: ${sorted[0][0]} · Lowest: ${sorted.at(-1)[0]}</p></div></div><div class="metrics">${METRICS.map(m=>`<div class="metric"><span>${m}</span><strong>${r.metrics[m]}</strong><progress max="100" value="${r.metrics[m]}" aria-label="${m}"></progress></div>`).join('')}</div><details><summary>Why did the model produce this result?</summary><div><p class="small muted">Directional effects beyond the base tactic values. These support discussion; they do not grade written reasoning.</p>${r.reasons.map(x=>`<p class="small"><b class="${x.delta<0?'bad':'good'}">${x.delta>=0?'+':''}${x.delta} ${x.metric}</b> · ${esc(x.reason)}</p>`).join('')}</div></details>`;}
function leaderboard(projector=true){const rows=S.results||[];const changed=new Set(rows.filter(r=>previousBoard[r.team]&&(previousBoard[r.team].power!==r.power||previousBoard[r.team].rank!==r.rank)).map(r=>r.team));previousBoard=Object.fromEntries(rows.map(r=>[r.team,{power:r.power,rank:r.rank}]));return `<div class="table-wrap"><table class="leader-table"><thead><tr><th>Rank</th><th>Brand</th><th class="num">Power</th>${METRICS.map(m=>`<th class="num">${m}</th>`).join('')}<th class="num">Δ Power</th></tr></thead><tbody>${rows.map(r=>`<tr class="${changed.has(r.team)?'market-move':''}" style="--brand:${brand(r.brand).color}"><td class="rank">${r.rank}</td><td class="brand-cell">${brand(r.brand).name}</td><td class="num power">${r.power}</td>${METRICS.map(m=>`<td class="num">${r.metrics[m]}</td>`).join('')}<td class="num ${r.delta>0?'good':r.delta<0?'bad':''}">${r.delta===null?'—':(r.delta>0?'+':'')+r.delta}</td></tr>`).join('')||`<tr><td colspan="9" class="empty">The market opens when campaigns lock.</td></tr>`}</tbody></table></div><div class="signal-grid">${(S.signals||[]).map(s=>`<div class="signal"><b>${s.type}</b><p>${esc(s.text)}</p></div>`).join('')}</div>${projector?`<p class="footer-note">${S.phase<4?'Provisional market · updates as teams commit':S.phase===5?'Shock-adjusted market · responses arriving':S.phase>=6?'Final market · all active responses locked':'Initial market · shared conditions frozen for comparison'}. Power is weighted by each brand’s mandate. It is not an academic grade.</p>`:''}`;}
function projector(){root.innerHTML=shell(`<section class="projector"><div class="row"><h1>${S.phase>=6?'The final market.':S.phase===5?'The market has changed.':'The attention market.'}</h1>${btn('Fullscreen','fullscreen','quiet')}</div>${S.phase===5?shock():''}${leaderboard()}<div class="brand-strip">${S.teams.map(t=>`<div class="brand-mini" style="--brand:${brand(t.brand).color}"><b>${brand(t.brand).name}</b>${t.count} joined · ${t.adapted?'response locked':t.locked?'campaign locked':'building'}</div>`).join('')}</div>${S.phase>=6?debrief():''}</section>`);}
function debrief(){const r=S.results;if(!r.length)return '';const winner=m=>[...r].sort((a,b)=>b.metrics[m]-a.metrics[m])[0];const gain=[...r].sort((a,b)=>(b.delta||0)-(a.delta||0))[0];return `<hr class="divider"><h2>What should we learn from this market?</h2><div class="grid3"><div class="panel"><div class="eyebrow">HIGHEST AUTHENTICITY</div><h3>${brand(winner('Authenticity').brand).name} · ${winner('Authenticity').metrics.Authenticity}</h3><p class="small">What specific value made the campaign credible?</p></div><div class="panel"><div class="eyebrow">HIGHEST CONVERSION</div><h3>${brand(winner('Conversion').brand).name} · ${winner('Conversion').metrics.Conversion}</h3><p class="small">What did the brand sacrifice to produce action?</p></div><div class="panel"><div class="eyebrow">LARGEST POWER CHANGE</div><h3>${brand(gain.brand).name} · ${(gain.delta||0)>=0?'+':''}${gain.delta||0}</h3><p class="small">Was the response defensible before knowing the result?</p></div></div>${S.choices?S.choices.map(c=>`<details><summary>${brand(c.brand).name} · reveal campaign choices</summary><div>${campaignSummary(c)}<p class="small">Voice: ${TONES[c.tone]}<br>Journey: ${JOURNEY.before[c.before]} → ${JOURNEY.during[c.during]} → ${JOURNEY.after[c.after]}</p></div></details>`).join(''):''}<p class="lead" style="margin-top:25px">Would the best-performing campaign also deserve the strongest academic grade? What evidence would you need?</p>`;}
function adminHome(){root.innerHTML=`<div class="row"><div><div class="eyebrow">INSTRUCTOR</div><h1 style="font-size:3rem">Run a Decision Lab.</h1></div>${btn('Sign out','logout','quiet')}</div><div class="admin-grid"><section class="panel"><h2>Create a class session</h2><form id="create">${input('label','Session name','SPM 343 · Marketing Decision Lab')}${select('format','Format',{class:'Live class · six teams',makeup:'Approved individual alternative · one brand'},'class')}<div class="actions"><button>Create session →</button></div></form><p class="small muted">The individual alternative preserves the same written assessment and shock. Advance its rounds when the student is ready. Market rank is not comparable with the live class.</p></section><section class="panel"><h2>Resume a session</h2>${rooms.length?rooms.map(r=>`<div class="row" style="padding:15px 0;border-bottom:1px solid var(--line)"><div><b>${esc(r.label)}</b><div class="small muted">${r.code} · ${PHASES[r.phase]} · ${r.students} students</div></div>${btn('Open','open-room','secondary',`data-code="${r.code}"`)}</div>`).join(''):'<p class="muted">No sessions yet.</p>'}</section></div>${rubric()}`;}
function admin(){
 const nav=`<div class="actions"><a class="button secondary" href="?view=projector&room=${S.code}" target="_blank" rel="noopener">Open separate projector feed ↗</a>${btn('Copy student link','copy-join','quiet')}${btn('All sessions','sessions','quiet')}</div><nav class="tabs" style="margin-top:24px">${[['control','Pacing & participation'],['evidence','Evidence & grading'],['market','Market & debrief']].map(([id,label])=>btn(label,'tab',tab===id?'active':'secondary',`data-tab="${id}"`)).join('')}</nav>`;
 let body='';
 if(tab==='control'){const ready=S.students.filter(s=>s.initial).length,def=S.students.filter(s=>s.defense).length;body=`<div class="admin-grid"><div class="panel"><div class="eyebrow">CURRENT ROUND</div><h2>${PHASES[S.phase]}</h2><p>${phaseGuidance(S.phase)}</p><div class="actions">${S.phase<8?btn(S.phase===4?'Release market shock →':'Advance to '+PHASES[S.phase+1]+' →','advance',''):''}${btn(S.paused?'Resume activity':'Pause activity','pause')}</div><p class="small muted">Advancing waits for required submissions. Mark truly absent students excused to remove them from readiness checks.</p></div><div class="panel"><h3>Synchronized timer</h3><p class="small muted">The timer guides pacing. Reaching zero never submits student work.</p><form id="timer"><div class="admin-controls"><label for="minutes">Minutes</label><input id="minutes" name="minutes" type="number" min="0" max="60" value="5"><button class="secondary">Start / reset timer</button>${btn('Hide','hide-timer','quiet')}</div></form><p class="clock" id="clock-admin">${timer()}</p><div class="row"><span>${ready}/${S.students.length} initial positions</span><span>${def}/${S.students.length} defenses</span></div></div></div><div class="panel" style="margin-top:24px"><h2>Participation & team assignments</h2><p class="small muted">Names are private here. Initial and final submissions are timestamped. The team recorder rotates at the shock; you can reassign if needed.</p><div class="table-wrap"><table class="roster"><thead><tr><th>Student</th><th>Brand</th><th>Initial</th><th>Defense</th><th>Actions</th></tr></thead><tbody>${S.students.map(s=>`<tr><td><b>${esc(s.name)}</b><br><span class="muted">${esc(s.email)}</span></td><td>${brand(s.team).name}${S.privateTeams.find(t=>t.id===s.team).editor===s.id?' · recorder':''}</td><td>${s.initial?'✓ Locked':'Missing'}</td><td>${s.defense?'✓ Locked':'Missing'}</td><td><div class="actions" style="margin:0">${btn(s.excused?'Reactivate':'Excuse','excuse','quiet',`data-id="${s.id}"`)}${btn('Recorder','editor','quiet',`data-id="${s.id}"`)}${btn('Reset access','reset-key','quiet',`data-id="${s.id}"`)}${!s.initial&&S.phase<3?btn('Move team','move','quiet',`data-id="${s.id}"`):''}</div></td></tr>`).join('')||'<tr><td colspan="5">Share the student link and room code. Students will appear here as they join.</td></tr>'}</tbody></table></div></div>`;}
 if(tab==='market')body=`${S.phase>=5?shock():''}${leaderboard()}${S.phase>=6?`<div class="actions">${btn(S.choices?'Hide campaign choices on projector':'Reveal campaign choices on projector','reveal')}</div>${debrief()}`:''}`;
 if(tab==='evidence'){body=`<div class="row"><div><h2>Grade the decisions.</h2><p class="muted">75 shared points + 25 individual points. Blank means ungraded, never zero.</p></div><div class="actions">${btn('Export grade CSV','export-csv')}${btn('Export full evidence JSON','export-json','quiet')}</div></div><div class="grid2"><div>${select('grade-team','Review a team',Object.fromEntries(S.privateTeams.map(t=>[t.id,brand(t.brand).name])),selected?.level==='group'?selected.id:'')}</div><div>${select('grade-student','Review a student',Object.fromEntries(S.students.map(s=>[s.id,s.name+' · '+brand(s.team).name])),selected?.level==='individual'?selected.id:'')}</div></div>${selected?gradingPanel():`<div class="empty" style="margin-top:20px">Select a team or student to see the relevant evidence and enter rubric scores.</div>`}<div class="table-wrap" style="margin-top:25px"><table><thead><tr><th>Student</th><th>Brand</th><th>Total / 100</th><th>Status</th></tr></thead><tbody>${S.students.map(s=>{const total=gradeTotal(s);return `<tr><td>${esc(s.name)}</td><td>${brand(s.team).name}</td><td class="grade-total">${total??'—'}</td><td>${s.excused?'Excused':total===null?'Awaiting rubric scores':'Scored'}</td></tr>`;}).join('')}</tbody></table></div>${rubric()}`;}
 root.innerHTML=shell(nav+body);
}
function phaseGuidance(p){return ['Allow 3 minutes. Assign brands, check names, and explain that market rank is not the grade.','Allow 5 minutes. Students make an independent call before seeing teammates’ recommendations.','Allow 4 minutes. Ask everyone to share their private role information.','Allow 12–15 minutes. Each team recorder builds the campaign; other students deliberate and challenge it.','Allow 3 minutes. Ask teams to diagnose strengths, weaknesses and market crowding before releasing the shock.','Allow 8 minutes. Recorders and roles rotate. Teams stay, pivot or double down under the original budget.','Allow 3 minutes. Compare changes and ask which tradeoffs explain them.','Allow 5 minutes. Each student independently defends one decision to keep and one to change.','Debrief, review evidence, enter rubric scores and export your gradebook.'][p];}
function gradeTotal(s){return totalGrade({teams:S.privateTeams},s);}
function evidence(c,title){if(!c)return `<p class="muted">${title}: not submitted.</p>`;return `<details open><summary>${title}${c.at?' · '+new Date(c.at).toLocaleString():''}</summary><div>${campaignSummary(c)}${[['behavior','Desired consumer behavior'],['audienceReason','Audience reasoning'],['mixReason','Five Ps integration'],['activationReason','Digital / creator / journey'],['authReason','Authenticity'],['riskReason','Tradeoff / stakeholder / risk'],['marketingType','Marketing of / through esports'],['adaptationReason','Adaptation rationale']].map(([k,label])=>c[k]?`<h3>${label}</h3><p class="response">${esc(c[k])}</p>`:'').join('')}</div></details>`;}
function gradingPanel(){const group=selected.level==='group',target=(group?S.privateTeams:S.students).find(x=>x.id===selected.id);if(!target)return '';const t=group?target:S.privateTeams.find(t=>t.id===target.team);return `<section class="panel grade-card"><h2>${esc(group?brand(target.brand).name:target.name)}</h2><div class="grid2"><div class="scroll-text">${group?evidence(t.initial,'Initial campaign')+evidence(t.final,'Shock response'):`<h3>Initial individual position</h3><p class="small muted">${target.initial?.at?new Date(target.initial.at).toLocaleString():'Missing'}</p><p class="response">${esc(target.initial?.text||'No submission.')}</p><h3>Final individual defense</h3><p class="small muted">${target.defense?.at?new Date(target.defense.at).toLocaleString():'Missing'}</p><p class="response">${esc(target.defense?.text||'No submission.')}</p>${evidence(t.initial,'Team’s original campaign')}${evidence(t.final,'Team’s shock response')}`}</div><form id="grade"><p class="small muted">Full credit: specific, coherent application supported by the case. Partial credit: relevant reasoning with gaps. Low credit: unsupported assertions, misconceptions or missing evidence.</p>${RUBRIC.filter(r=>r.level===selected.level).map(r=>`<div class="grade-row"><label for="score-${r.id}">${r.label} / ${r.max}<small>${r.evidence}</small></label><input aria-label="${r.label} score" id="score-${r.id}" name="${r.id}" type="number" min="0" max="${r.max}" step="0.5" value="${target.grades?.[r.id]??''}"></div>`).join('')}${area('comment','Instructor feedback',target.comment||'')}<div class="actions"><button>Save ${group?'group':'individual'} scores</button></div><p class="small muted">${group?'Shared scores apply to every student on this team.':'Individual scores apply only to this student.'}</p></form></div></section>`;}
function download(name,content,type='text/plain'){const url=URL.createObjectURL(new Blob([content],{type}));const a=document.createElement('a');a.href=url;a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);}
function csvCell(v){let s=String(v??'');if(/^[=+\-@\t\r]/.test(s))s="'"+s;return '"'+s.replace(/"/g,'""')+'"';}
function exportCSV(){const header=['Student Name','Email','Session','Team','Brand','Role at Build','Role at Adaptation',...RUBRIC.map(r=>r.label),'Total Decision Lab Score','Initial Market Power','Final Market Power','Final Rank','Initial Submitted','Defense Submitted','Status','Group Feedback','Individual Feedback'];const rows=S.students.map(s=>{const t=S.privateTeams.find(t=>t.id===s.team),peers=S.students.filter(x=>x.team===s.team),idx=peers.findIndex(x=>x.id===s.id);const a=S.initialResults?.find(r=>r.team===s.team),f=S.phase>=6?S.results.find(r=>r.team===s.team):null;return [s.name,s.email,S.label,s.team,brand(s.team).name,ROLES[idx%5],ROLES[(idx+1)%5],...RUBRIC.map(r=>(r.level==='group'?t.grades:s.grades)?.[r.id]),gradeTotal(s),a?.power,f?.power,f?.rank,s.initial?.at,s.defense?.at,s.excused?'Excused':gradeTotal(s)===null?'Ungraded':'Scored',t.comment,s.comment];});download(`Marketing_Arena_${code}_Grades.csv`,'\uFEFF'+[header,...rows].map(r=>r.map(csvCell).join(',')).join('\r\n'),'text/csv;charset=utf-8');}
function render(){if(mode==='instructor'){if(!adminKey)entry();else if(S?.admin)admin();else adminHome();}else if(mode==='projector'){if(S)projector();else entry();}else studentOrEntry();}
function studentOrEntry(){if(S?.me)student();else entry();}
function changeRoom(c){code=c;const url=new URL(location.href);url.searchParams.set('room',code);url.searchParams.set('view',mode);history.replaceState({},'',url);}
async function openRoom(c){changeRoom(c);S=null;draft={};if(mode==='student')token=localStorage.getItem('arena-key-'+code)||'';accept(await api('state'));render();}
async function listRooms(){rooms=(await api('list')).rooms;S=null;code='';history.replaceState({},'','?view=instructor');adminHome();}
function readCampaignInputs(){for(const el of root.querySelectorAll('#campaign-form input,#campaign-form textarea,#campaign-form select,#response,#protect')){if(el.type==='radio'&&!el.checked)continue;draft[el.name]=el.value;}}
function updateBudget(){const c=campaignCost(draft,S.phase===5?S.team?.initial:null,draft.response);if($('#budget-number')){$('#budget-number').textContent=c.total;$('#budget-number').className=c.total>100?'bad':'';$('#budget-meter').value=Math.min(c.total,100);$('#budget-note').textContent=(100-c.total)+' available'+(S.phase===5?' · includes response costs':'');}}
root.addEventListener('input',e=>{
 if(e.target.closest('#campaign-form')||['response','protect'].includes(e.target.id)){readCampaignInputs();setDraft();updateBudget();}
 if(e.target.id==='position'||e.target.id==='defense'){const k=e.target.id==='position'?'arena-personal-':'arena-defense-';localStorage.setItem(k+code,e.target.value);saveStatus('Draft retained on this device');clearTimeout(personalTimer);const value=e.target.value;personalTimer=setTimeout(()=>act('personalDraft',{text:value}).then(()=>saveStatus('Individual draft saved')).catch(()=>saveStatus('Draft retained locally · connection needed to submit')),1500);}
});
root.addEventListener('change',e=>{
 if(e.target.type==='radio'){root.querySelectorAll(`input[name="${e.target.name}"]`).forEach(i=>i.closest('.tactic').classList.toggle('selected',i.checked));}
 if(e.target.id==='response'){readCampaignInputs();setDraft();student();}
 if(e.target.id==='grade-team'||e.target.id==='grade-student'){selected=e.target.value?{level:e.target.id==='grade-team'?'group':'individual',id:e.target.value}:null;admin();}
});
root.addEventListener('submit',async e=>{e.preventDefault();const f=e.target,data=Object.fromEntries(new FormData(f));const submit=f.querySelector('button[type=submit],button:not([type])');if(submit)submit.disabled=true;
 try{
  if(f.id==='login'){adminKey=data.adminKey.trim();await listRooms();sessionStorage.setItem('arena-admin',adminKey);}
  if(f.id==='open-projector')await openRoom(data.room.trim().toUpperCase());
  if(f.id==='join'){changeRoom(data.room.trim().toUpperCase());token=localStorage.getItem('arena-key-'+code)||key();localStorage.setItem('arena-key-'+code,token);S=await api('join',{name:data.name,email:data.email,team:data.team});render();}
  if(f.id==='recover'){code=$('#room').value.trim().toUpperCase();token=data.recoveryKey.trim();const result=await api('state');if(!result.me)throw Error('Key not recognized.');localStorage.setItem('arena-key-'+code,token);changeRoom(code);S=result;render();}
  if(f.id==='create'){S=await api('create',{label:data.label,makeup:data.format==='makeup'});changeRoom(S.code);render();}
  if(f.id==='initial'){if(!data.audience||!data.objective||data.position.trim().length<120)throw Error('Choose an audience and objective and explain your call (at least 120 characters).');if(await confirmLock()){clearTimeout(personalTimer);await act('initial',{position:{audience:data.audience,objective:data.objective,text:data.position}});localStorage.removeItem('arena-personal-'+code);render();}}
  if(f.id==='defense-form'){if(data.defense.trim().length<200)throw Error('Develop your defense before submitting (at least 200 characters).');if(await confirmLock('Submit your individual defense?')){clearTimeout(personalTimer);await act('defense',{text:data.defense});localStorage.removeItem('arena-defense-'+code);render();}}
  if(f.id==='timer'){await act('timer',{seconds:Number(data.minutes)*60});render();}
  if(f.id==='grade'){let scores={};for(const r of RUBRIC.filter(r=>r.level===selected.level))scores[r.id]=data[r.id]===''?null:Number(data[r.id]);await act('grade',{level:selected.level,target:selected.id,scores,comment:data.comment});toast('Rubric scores saved.');admin();}
 }catch(err){toast(err.message);if(f.id==='login'){adminKey='';entry();}}finally{if(submit)submit.disabled=false;}
});
root.addEventListener('click',async e=>{const el=e.target.closest('[data-action]');if(!el)return;const a=el.dataset.action;
 try{
  if(['next','back','step'].includes(a)){readCampaignInputs();if((a==='next'||Number(el.dataset.step)>0)&&step===0&&(!draft.audience||!draft.objective||(draft.strategy||'').trim().length<40))throw Error('Set your audience, objective and strategic purpose before choosing tactics.');step=a==='next'?Math.min(3,step+1):a==='back'?Math.max(0,step-1):Number(el.dataset.step);student();window.scrollTo({top:100,behavior:'smooth'});}
  if(a==='save-draft'){readCampaignInputs();dirty=true;await saveDraft();toast('Shared draft saved.');}
  if(a==='lock-campaign'){readCampaignInputs();validateCampaign(draft,S.phase===5?S.team.initial:null);if(await confirmLock(S.phase===5?'Lock your shock response?':'Commit this campaign to the market?','Confirm that everyone has contributed and the campaign matches your strategy. This locks the shared submission.')){clearTimeout(autoTimer);await saveDraft();await enqueue(async()=>{const data=await api('campaign',{campaign:draft,draftVersion:S.team.draftVersion});accept(data);});dirty=false;localStorage.removeItem(`arena-draft-${code}-${S.phase}`);render();}}
  if(a==='tab'){tab=el.dataset.tab;admin();}
  if(a==='open-room')await openRoom(el.dataset.code);
  if(a==='sessions')await listRooms();
  if(a==='advance'){if(await confirmLock('Advance the class?',`Open ${PHASES[S.phase+1]}. Current submissions stay locked and the timer resets.`)){await act('advance');render();}}
  if(['pause','reveal'].includes(a)){await act(a);render();}
  if(a==='hide-timer'){await act('timer',{seconds:0});render();}
  if(a==='excuse'||a==='editor'){await act(a,{student:el.dataset.id});render();}
  if(a==='move'){const dest=prompt('Enter the target brand: pulse, clearwave, northline, pacepay, metrobite or vela.');if(dest){await act('move',{student:el.dataset.id,team:dest.trim().toLowerCase()});render();}}
  if(a==='reset-key'){if(await confirmLock('Reset this student’s access?','The old key will stop working. Give the new key only to this student after verifying their identity.')){const token=key();const hash=Array.from(new Uint8Array(await crypto.subtle.digest('SHA-256',new TextEncoder().encode(token)))).map(x=>x.toString(16).padStart(2,'0')).join('');await act('recover',{student:el.dataset.id,newHash:hash});prompt('Give this private recovery key to the student. Copy it now:',token);}}
  if(a==='copy-join'){await navigator.clipboard.writeText(location.origin+location.pathname+'?room='+code);toast('Student link copied.');}
  if(a==='copy-key'){await navigator.clipboard.writeText(token);toast('Personal recovery key copied. Keep it private.');}
  if(a==='fullscreen'){if(!document.fullscreenElement)await document.documentElement.requestFullscreen();else await document.exitFullscreen();}
  if(a==='export-csv')exportCSV();
  if(a==='export-json')download(`Marketing_Arena_${code}_Evidence.json`,JSON.stringify({exportedAt:new Date().toISOString(),...S},null,2),'application/json');
  if(a==='download-student')download(`Marketing_Arena_${code}_My_Record.json`,JSON.stringify({session:S.label,student:S.me,team:S.team,initialMarket:S.initialResults?.find(x=>x.team===S.me.team),finalMarket:S.ownResult},null,2),'application/json');
  if(a==='print')window.print();
  if(a==='logout'){if(mode==='instructor'){sessionStorage.removeItem('arena-admin');adminKey='';}else{localStorage.removeItem('arena-key-'+code);localStorage.removeItem('arena-personal-'+code);localStorage.removeItem('arena-defense-'+code);token='';}S=null;draft={};entry();}
 }catch(err){toast(err.message);}
});
async function poll(){if(polling||!code||!S||saving)return;polling=true;try{const oldPhase=S.phase,oldVersion=S.version,oldEditor=S.editor,oldMe=!!S.me?.initial;const data=await api('state');data._offset=data.serverNow-Date.now();accept(data);if(S.phase!==oldPhase||S.editor!==oldEditor||!!S.me?.initial!==oldMe){draft={};step=0;render();if(S.phase!==oldPhase)toast('New round: '+PHASES[S.phase]);}
 else if(mode==='projector')projector();
 else if(mode==='instructor'){if(tab==='control'&&!root.querySelector('input:focus,textarea:focus,select:focus'))admin();if(tab==='market')admin();}
 else if(!root.querySelector('#campaign-form,#initial,#defense')&&S.version!==oldVersion)student();
 }catch(e){status('Connection interrupted · last synced '+(lastGood?new Date(lastGood).toLocaleTimeString():'never'),true);}finally{polling=false;}}
setInterval(poll,3000);setInterval(()=>{for(const id of ['clock','clock-admin'])if($('#'+id))$('#'+id).textContent=timer();},1000);
window.addEventListener('beforeunload',e=>{if(dirty){e.preventDefault();e.returnValue='';}});
window.addEventListener('online',()=>{poll();if(dirty)saveDraft().catch(()=>{});});
async function init(){status('Ready');entry();try{if(mode==='instructor'&&adminKey){if(code)await openRoom(code);else await listRooms();}else if(code&&(mode==='projector'||token))await openRoom(code);}catch(e){toast(e.message);S=null;entry();}}
init();
