const API='https://havsvkhddvdbzbsmhqbr.supabase.co/functions/v1/spm343-launch-day';
const ROOT=new URL('.',location.href); ROOT.search='';ROOT.hash='';
const params=new URLSearchParams(location.search), admin=params.get('view')==='instructor';
const $=s=>document.querySelector(s), esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const rounds=[{title:'Know Your Stakeholders',short:'Stakeholders',context:'The event needs permission, partners, and an audience.',ids:[1,2,3]},{title:'Reach Your Audience',short:'Marketing',context:'Identify the audience and make marketing choices that fit its needs.',ids:[4,5,6,7,8]},{title:'Deliver Sponsor Value',short:'Sponsorship',context:'Connect a sponsor’s goals with an appropriate fan experience.',ids:[9,10,11,12]}];
const roundOf=i=>i<=3?0:i<=8?1:2;
const STORE='spm343-launch-day-v1';
let s={code:'',token:'',answers:{},index:0,version:0,dirty:false}, questions=[],session=null,attempt=null,review=false,savePromise=null,saving=false,saveTimer=null,clock=null,offset=0;
let adminKey='',sessions=[],activeCode='',rows=[],activeSession=null,adminTimer=null;
function readStore(){try{return JSON.parse(localStorage.getItem(STORE)||'null')}catch{return null}}
function persist(){try{localStorage.setItem(STORE,JSON.stringify(s))}catch{toast('Device storage is unavailable. Keep this page open until you submit.')}}
function token(){return Array.from(crypto.getRandomValues(new Uint8Array(32))).map(x=>x.toString(16).padStart(2,'0')).join('')}
function toast(msg){$('#toast').textContent=msg;$('#toast').classList.add('show');setTimeout(()=>$('#toast').classList.remove('show'),4500)}
function header(){return `<header class="topbar"><a class="brand" href="${ROOT}"><span class="brandmark" aria-hidden="true">LD</span><div><b>LA SALLE UNIVERSITY</b><span class="small">ESPORTS & DIGITAL GAMING MANAGEMENT</span></div></a><div class="topmeta">SPM 343 &nbsp; / &nbsp; KNOWLEDGE CHECK 02</div></header>`}
function footer(){return `<footer class="pagefooter"><span>SPM 343 · Prof. Levine</span><a href="?view=instructor">Instructor access</a></footer>`}
function screen(html){$('#app').innerHTML=header()+html+footer()}
async function api(body){const controller=new AbortController(),tid=setTimeout(()=>controller.abort(),20000);try{const r=await fetch(API,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(body),signal:controller.signal});const data=await r.json();if(!r.ok){const e=new Error(data.error||'Unable to complete the request.');e.status=r.status;throw e}return data}catch(e){if(!e.status)throw new Error('Connection interrupted. Your work is retained on this device. Please retry.');throw e}finally{clearTimeout(tid)}}
const studentApi=(action,extra={})=>api({action,code:s.code,token:s.token,...extra});
function apply(data,keepDirty=false){attempt=data.attempt;questions=data.questions;session=data.session;offset=data.serverNow-Date.now();s.version=attempt.version;if(!keepDirty){s.answers=attempt.answers;s.dirty=false}s.name=attempt.name;s.email=attempt.email;s.startedAt=attempt.startedAt;persist()}
function landing(message=''){
 clearInterval(clock);
 screen(`<main id="main" class="intro"><section class="brief"><div class="eyebrow">Knowledge Check 02</div><h1>Launch<br><em>Day.</em></h1><p class="lead">An esports tournament is about to go live. You have three rounds to get the fundamentals right.</p><div class="stats"><div><strong>12</strong><span>questions</span></div><div><strong>3</strong><span>rounds</span></div><div><strong>12 min</strong><span>suggested time</span></div></div><ol class="mission">${rounds.map((r,i)=>`<li><span class="num">0${i+1}</span><div><b>${r.title}</b><small>${r.ids.length} questions · ${r.short==='Marketing'?'Segmentation & the Five Ps':r.short==='Sponsorship'?'Activation & measurement':'Roles & dependencies'}</small></div></li>`).join('')}</ol></section><section class="entry"><div class="eyebrow">Individual assessment</div><h2>Ready for launch?</h2><p class="muted">Enter the session code from your instructor. Your name and results go directly to Prof. Levine.</p><form id="join"><div class="field"><label class="label" for="name">Full name</label><input id="name" name="name" type="text" autocomplete="name" maxlength="100" minlength="2" required value="${esc(s.name||'')}" placeholder="First and last name"></div><div class="field"><label class="label" for="email">La Salle email</label><input id="email" name="email" type="email" autocomplete="email" maxlength="160" required placeholder="you@lasalle.edu" value="${esc(s.email||'')}"></div><div class="field"><label class="label" for="code">Session code</label><input id="code" name="code" type="text" autocomplete="off" autocapitalize="characters" spellcheck="false" required minlength="8" maxlength="8" value="${esc(params.get('room')||s.code||'')}" placeholder="8-character code"></div><label class="check"><input type="checkbox" required><span>I will complete this independently, without notes, outside assistance, or generative AI.</span></label><div class="error" id="join-error" role="alert">${esc(message)}</div><button class="btn full" type="submit">Begin assessment <span aria-hidden="true">→</span></button><span class="help">1 point per question. No speed bonus. Approved accommodations apply.</span></form><details><summary>Returning on another device?</summary><p>Ask your instructor for a private recovery link. If you already started here, use the same browser to restore your attempt.</p></details></section></main>`);
 $('#join').onsubmit=async e=>{e.preventDefault();const b=e.submitter;b.disabled=true;$('#join-error').textContent='';const code=$('#code').value.trim().toUpperCase(),email=$('#email').value.trim().toLowerCase(),name=$('#name').value.trim();
 if(s.code!==code||s.email!==email||!s.token)s={code,token:token(),email,name,answers:{},index:0,version:0,dirty:false};else Object.assign(s,{name,email,code});persist();
 try{apply(await studentApi('join',{name,email}));renderStudent()}catch(err){$('#join-error').textContent=err.message;b.disabled=false}};
}
function savedLabel(text,warning=false){const el=$('#save-state');if(el){el.textContent=text;el.classList.toggle('pending',warning)}}
async function flush(){
 clearTimeout(saveTimer);if(savePromise){await savePromise;if(s.dirty)return flush();return}
 if(!s.dirty||attempt?.submittedAt)return;
 const snapshot=JSON.stringify(s.answers),version=s.version;s.inFlightAnswers=JSON.parse(snapshot);persist();saving=true;savedLabel('Saving answers…',true);
 savePromise=(async()=>{try{const data=await studentApi('save',{answers:JSON.parse(snapshot),version});s.version=data.attempt.version;s.inFlightAnswers=null;attempt=data.attempt;session=data.session;if(JSON.stringify(s.answers)===snapshot)s.dirty=false;persist();savedLabel(s.dirty?'Changes pending':'Answers saved',s.dirty)}catch(e){savedLabel('Saved on this device · retry',true);const el=$('#save-warning');if(el)el.textContent=e.message;throw e}finally{saving=false;savePromise=null}})();
 return savePromise;
}
function schedule(){persist();savedLabel('Saving answers…',true);clearTimeout(saveTimer);saveTimer=setTimeout(()=>flush().catch(()=>{}),500)}
function sidebar(){return `<aside class="sidebar"><div class="eyebrow">Launch Day / 02</div><h2>Your mission</h2><p class="identity">${esc(s.name)}<br><span class="muted">Session ${esc(s.code)}</span></p><nav class="roundnav" aria-label="Assessment rounds">${rounds.map((r,i)=>{const n=r.ids.filter(id=>s.answers[id]).length;return `<button class="roundbtn ${!review&&roundOf(s.index+1)===i?'active':''}" data-round="${i}"><span class="step">${n===r.ids.length?'✓':i+1}</span><span><strong>${r.short}</strong><small>${n} of ${r.ids.length} answered</small></span></button>`}).join('')}</nav><div class="timerbox"><span class="eyebrow">Time elapsed</span><b id="elapsed">00:00</b><small>Suggested time: 12 minutes.<br>Your instructor controls the session.</small></div></aside>`}
function answered(){return Object.keys(s.answers).length}
function renderStudent(){
 clearInterval(clock);if(attempt?.submittedAt)return receipt();
 const q=questions[s.index];if(!q)return landing('Assessment unavailable. Please retry.');
 const r=rounds[roundOf(q.id)];
 const contents=review?`<div class="eyebrow">Final checkpoint</div><h2 class="qheading">Review your launch</h2><p class="round-context">Check your answers before submitting. Your submission is final.</p><div class="review-list">${questions.map(x=>`<button class="review-item" data-question="${x.id-1}"><span class="letter">${x.id}</span><span>${esc(x.text)}</span><small>${s.answers[x.id]?'Answer '+s.answers[x.id]:'Unanswered'}</small></button>`).join('')}</div><div id="submit-error" class="error" role="alert"></div><div class="question-nav"><button class="btn secondary" id="back-review">Back to questions</button><button class="btn" id="submit" ${answered()<12?'disabled':''}>Submit ${answered()}/12 answers</button></div>${answered()<12?'<p class="help">Answer the remaining questions to submit.</p>':''}`:`<div class="eyebrow">Round 0${roundOf(q.id)+1}</div><h2 class="qheading">${r.title}</h2><p class="round-context">${r.context}</p><section class="question-card" aria-labelledby="question-text"><div class="qnum">QUESTION ${q.id} OF 12 &nbsp; / &nbsp; 1 POINT</div><h3 class="question" id="question-text" tabindex="-1">${esc(q.text)}</h3><fieldset class="options" style="border:0;margin:0;padding:0"><legend class="screenreader">Choose one answer</legend>${q.options.map(o=>`<label class="option"><input type="radio" name="answer" value="${o.id}" ${s.answers[q.id]===o.id?'checked':''}><span class="letter" aria-hidden="true">${o.id}</span><span>${esc(o.text)}</span></label>`).join('')}</fieldset></section><div class="question-nav"><button class="btn secondary" id="prev" ${s.index===0?'disabled':''}>Previous</button><button class="btn" id="next">${s.index===11?'Review answers':roundOf(q.id+1)!==roundOf(q.id)?'Next round':'Next question'} <span aria-hidden="true">→</span></button></div><nav class="qgrid" aria-label="Question navigation">${questions.map(x=>`<button class="qdot ${s.answers[x.id]?'done':''} ${x.id===q.id?'current':''}" data-question="${x.id-1}" aria-label="Question ${x.id}, ${s.answers[x.id]?'answered':'unanswered'}" ${x.id===q.id?'aria-current="step"':''}>${x.id}</button>`).join('')}</nav><div class="worktop"><span class="navhint">You can revisit any question before submitting.</span><button id="review" class="linkbtn">Review all</button></div>`;
 screen(`<div class="layout">${sidebar()}<main id="main" class="workspace"><div class="worktop"><span>${answered()} of 12 answered</span><span id="save-state" class="saveState ${s.dirty?'pending':''}" role="status">${s.dirty?'Changes saved on this device':'Answers saved'}</span></div><div class="progress" role="progressbar" aria-label="Questions answered" aria-valuemin="0" aria-valuemax="12" aria-valuenow="${answered()}"><div style="width:${answered()/12*100}%"></div></div>${contents}<div class="error" id="save-warning" role="alert"></div></main></div>`);
 document.querySelectorAll('[data-round]').forEach(b=>b.onclick=()=>navigate(rounds[Number(b.dataset.round)].ids[0]-1));
 document.querySelectorAll('[data-question]').forEach(b=>b.onclick=()=>navigate(Number(b.dataset.question)));
 if(review){$('#back-review').onclick=()=>navigate(s.index);$('#submit').onclick=submit}
 else{document.querySelectorAll('input[name=answer]').forEach(el=>el.onchange=()=>{s.answers[q.id]=el.value;s.dirty=true;schedule();const focused=el.value;renderStudent();document.querySelector(`input[value="${focused}"]`).focus()});$('#prev').onclick=()=>navigate(s.index-1);$('#next').onclick=()=>s.index===11?showReview():navigate(s.index+1);$('#review').onclick=showReview}
 const tick=()=>{const el=$('#elapsed');if(el){const seconds=Math.max(0,Math.floor((Date.now()+offset-new Date(s.startedAt).getTime())/1000));el.textContent=String(Math.floor(seconds/60)).padStart(2,'0')+':'+String(seconds%60).padStart(2,'0')}};tick();clock=setInterval(tick,1000);
}
function navigate(i){s.index=Math.max(0,Math.min(11,i));review=false;persist();renderStudent();$('#question-text')?.focus({preventScroll:true});window.scrollTo({top:0,behavior:'instant'})}
function showReview(){review=true;renderStudent();window.scrollTo({top:0,behavior:'instant'})}
async function submit(){const btn=$('#submit');btn.disabled=true;btn.textContent='Confirming submission…';$('#submit-error').textContent='';try{await flush();const data=await studentApi('submit',{answers:s.answers,version:s.version});apply(data);renderStudent()}catch(e){$('#submit-error').textContent=e.message;btn.disabled=false;btn.textContent='Retry submission'}}
function download(content,name,type='text/plain'){const u=URL.createObjectURL(new Blob([content],{type}));const a=document.createElement('a');a.href=u;a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(u),1000)}
function receipt(){
 screen(`<main id="main" class="receipt"><div class="receipt-icon" aria-hidden="true">✓</div><div class="eyebrow">All three rounds submitted</div><h1>Launch complete.</h1><p class="muted">${esc(attempt.name)}, your assessment is recorded. Prof. Levine can now see your submission.</p><section class="receipt-panel">${attempt.score!==null?`<div class="eyebrow">Your Launch Score</div><div class="score">${attempt.score}<small> / 12</small></div><p class="muted">${Math.round(attempt.score/12*1000)/10}% · 1 point per correct answer</p><div class="breakdown">${rounds.map((r,i)=>`<div><b>${attempt.roundScores[i]} / ${r.ids.length}</b><span>${r.short}</span></div>`).join('')}</div>`:'<h3>Submission confirmed</h3><p class="muted">Your score will appear here when your instructor releases results.</p>'}<div style="margin-top:26px"><span class="eyebrow">Your receipt</span><p class="receipt-id">${esc(attempt.receipt)}</p><span class="help">${esc(attempt.email)} · ${new Date(attempt.submittedAt).toLocaleString()}</span></div></section><div class="toolbar"><button class="btn" id="refresh-score">Check for released score</button><button class="btn secondary" id="download-receipt">Download receipt</button></div><p class="help" style="margin-top:18px">You may close this page. Your submitted answers cannot be changed.</p></main>`);
 $('#refresh-score').onclick=async e=>{e.target.disabled=true;try{apply(await studentApi('resume'));receipt()}catch(err){toast(err.message);e.target.disabled=false}};
 $('#download-receipt').onclick=()=>download(`SPM 343 Knowledge Check 2 — Launch Day\nName: ${attempt.name}\nEmail: ${attempt.email}\nSession: ${s.code}\nSubmitted: ${attempt.submittedAt}\nReceipt: ${attempt.receipt}\nScore: ${attempt.score===null?'Awaiting instructor release':attempt.score+'/12'}\n`,'Launch-Day-Receipt.txt');
}
function adminApi(action,data={}){return api({action,adminKey,...data})}
function adminLogin(message=''){
 clearInterval(adminTimer);screen(`<main id="main" class="admin-login"><div class="eyebrow">Instructor access</div><h1>Launch control</h1><p class="muted">Manage your class session and review individual results.</p><form id="admin-login"><div class="field"><label class="label" for="key">Private instructor key</label><input id="key" type="password" autocomplete="off" required><span class="help">Use your Esports Marketing Arena instructor key.</span></div><div class="error" id="admin-error" role="alert">${esc(message)}</div><button class="btn full" type="submit">Open dashboard</button></form></main>`);
 $('#admin-login').onsubmit=async e=>{e.preventDefault();e.submitter.disabled=true;adminKey=$('#key').value.trim();try{await loadSessions();try{sessionStorage.setItem('launch-day-admin',adminKey)}catch{}adminHome()}catch(err){$('#admin-error').textContent=err.message;e.submitter.disabled=false;adminKey=''}};
}
async function loadSessions(){sessions=(await adminApi('list')).sessions}
function logout(){adminKey='';rows=[];sessions=[];activeCode='';try{sessionStorage.removeItem('launch-day-admin')}catch{}adminLogin()}
function adminHome(){
 activeCode='';clearInterval(adminTimer);
 screen(`<main id="main" class="admin"><div class="admin-header"><div><div class="eyebrow">SPM 343 / Knowledge Check 02</div><h1>Launch control</h1><p class="muted">Open a session, share its code, and collect individual results.</p></div><button class="btn secondary" id="logout">Lock dashboard</button></div><form id="create" class="create-form"><div class="field"><label class="label" for="session-label">New session name</label><input type="text" id="session-label" required minlength="2" maxlength="100" placeholder="e.g. SPM 343 · Thursday"></div><button type="submit" class="btn">Create session</button></form><div class="error" id="admin-error" role="alert"></div><div class="admin-cards">${sessions.map(x=>`<article class="session-card"><span class="badge ${x.is_open?'ok':''}">${x.is_open?'Open for students':'Closed'}</span><h3 style="margin-top:18px">${esc(x.label)}</h3><div class="session-code">${x.code}</div><button class="btn secondary" data-session="${x.code}">Open session</button></article>`).join('')||'<p class="muted">Create your first session to begin.</p>'}</div><p class="help">Sessions start closed. Scores are private until you release them. Student names and grades are visible only in this protected dashboard.</p></main>`);
 $('#logout').onclick=logout;document.querySelectorAll('[data-session]').forEach(b=>b.onclick=()=>openSession(b.dataset.session).catch(e=>toast(e.message)));
 $('#create').onsubmit=async e=>{e.preventDefault();e.submitter.disabled=true;try{const d=await adminApi('create',{label:$('#session-label').value});await loadSessions();await openSession(d.session.code)}catch(err){$('#admin-error').textContent=err.message;e.submitter.disabled=false}};
}
async function openSession(code){activeCode=code;await refreshAdmin();clearInterval(adminTimer);adminTimer=setInterval(()=>refreshAdmin().catch(e=>{$('#admin-error')&&($('#admin-error').textContent=e.message)}),15000)}
async function refreshAdmin(){if(!activeCode)return;const code=activeCode;const d=await adminApi('results',{code});if(activeCode!==code)return;rows=d.attempts;activeSession=d.session;adminSession()}
function studentLink(){const u=new URL(ROOT);u.searchParams.set('room',activeCode);return u.href}
function adminSession(){
 const x=activeSession,done=rows.filter(r=>r.submitted_at),mean=done.length?(done.reduce((a,r)=>a+r.score,0)/done.length).toFixed(1):'—';
 screen(`<main id="main" class="admin"><div class="admin-header"><div><button class="linkbtn" id="all-sessions">← All sessions</button><div class="eyebrow">Knowledge Check 02 / Instructor</div><h1>${esc(x.label)}</h1><div class="toolbar"><span class="session-code" style="margin:0">${x.code}</span><span class="badge ${x.is_open?'ok':''}">${x.is_open?'Open for students':'Session closed'}</span></div></div><button class="btn secondary" id="logout">Lock dashboard</button></div><div class="toolbar"><button class="btn" id="toggle">${x.is_open?'Close session':'Open for students'}</button><button class="btn secondary" id="copy-link">Copy student link</button><button class="btn secondary" id="release">${x.results_released?'Hide student scores':'Release student scores'}</button><button class="btn secondary" id="csv" ${done.length?'':'disabled'}>Export CSV</button><button class="btn secondary" id="refresh-admin">Refresh</button></div><p class="help">${x.is_open?'Students can join, save, and submit.':'Students cannot join or submit while the session is closed.'} ${x.results_released?'Submitted students can view their own score.':'Scores are visible only to you.'}</p><div class="error" id="admin-error" role="alert"></div><div class="adminstats"><div><b>${rows.length}</b><span>Joined</span></div><div><b>${done.length}</b><span>Submitted</span></div><div><b>${mean}<span> / 12</span></b><span>Class average</span></div></div><div class="table-wrap"><table><thead><tr><th>Student</th><th>Progress</th><th>Score</th><th>Round totals</th><th>Submitted</th><th>Access</th></tr></thead><tbody>${rows.map(r=>`<tr><td><strong>${esc(r.student_name)}</strong><small>${esc(r.email)}</small></td><td><span class="badge ${r.submitted_at?'ok':''}">${r.submitted_at?'Submitted':Object.keys(r.answers||{}).length+'/12 saved'}</span></td><td>${r.submitted_at?`<strong>${r.score} / 12</strong><small>${Math.round(r.score/12*1000)/10}%</small>`:'—'}</td><td>${r.round_scores?r.round_scores.map((v,i)=>`${v}/${rounds[i].ids.length}`).join(' · '):'—'}</td><td>${r.submitted_at?new Date(r.submitted_at).toLocaleTimeString([],{hour:'2-digit',minute:'2-digit'}):'In progress'}</td><td><button class="linkbtn" data-recover="${r.id}">Recovery link</button></td></tr>`).join('')||'<tr><td colspan="6" class="empty">No students have joined yet. Share the student link and open the session.</td></tr>'}</tbody></table></div><p class="help">Updates every 15 seconds. Round totals: stakeholders /3 · marketing /5 · sponsorship /4.</p><div id="recovery-result"></div></main>`);
 $('#logout').onclick=logout;$('#all-sessions').onclick=async()=>{activeCode='';await loadSessions();adminHome()};
 const run=async fn=>{try{await fn()}catch(e){$('#admin-error').textContent=e.message}};
 $('#toggle').onclick=()=>run(async()=>{if(x.is_open&&!confirm('Close this session? Students will keep their drafts, but cannot submit until you reopen it.'))return;await adminApi('configure',{code:activeCode,isOpen:!x.is_open});await refreshAdmin()});
 $('#release').onclick=()=>run(async()=>{await adminApi('configure',{code:activeCode,release:!x.results_released});await refreshAdmin()});
 $('#copy-link').onclick=()=>copy(studentLink());$('#refresh-admin').onclick=()=>run(()=>openSession(activeCode));$('#csv').onclick=exportCSV;
 document.querySelectorAll('[data-recover]').forEach(b=>b.onclick=()=>run(async()=>{const row=rows.find(r=>r.id===b.dataset.recover);if(!confirm(`Replace access for ${row.student_name}? Their previous browser will lose access. Send the new link privately to this student.`))return;const t=token();await adminApi('recover',{code:activeCode,id:row.id,token:t});const u=new URL(studentLink());u.hash='access='+t;clearInterval(adminTimer);$('#recovery-result').innerHTML=`<div class="notice"><label class="label" for="recovery-url">Private recovery link for ${esc(row.student_name)}</label><input type="text" id="recovery-url" readonly value="${esc(u.href)}"><p class="help">Share only with this student. Refresh this dashboard to resume live updates.</p></div>`;await copy(u.href)}));
}
async function copy(text){try{await navigator.clipboard.writeText(text);toast('Link copied')}catch{prompt('Copy this link:',text)}}
function exportCSV(){
 const cols=['Name','Email','Session','Status','Score /12','Percent','Stakeholders /3','Marketing /5','Sponsorship /4','Started at','Submitted at','Receipt',...questions.map(q=>'Q'+q.id)];
 // Question columns stay fixed even if the instructor has not entered a student flow.
 const headers=cols.slice(0,12).concat(Array.from({length:12},(_,i)=>'Q'+(i+1)));
 const cell=v=>{let x=String(v??'');if(/^[=+\-@\t\r]/.test(x))x="'"+x;return '"'+x.replaceAll('"','""')+'"'};
 const data=rows.map(r=>[r.student_name,r.email,activeCode,r.submitted_at?'Submitted':'In progress',r.score,r.submitted_at?Math.round(r.score/12*1000)/10:'',...(r.round_scores||['','','']),r.started_at,r.submitted_at,r.submitted_at?r.id:'',...Array.from({length:12},(_,i)=>r.answers?.[i+1]||'')]);
 download('\uFEFF'+[headers,...data].map(r=>r.map(cell).join(',')).join('\r\n'),'SPM343-KC2-'+activeCode+'.csv','text/csv;charset=utf-8');
}
async function boot(){
 if(admin){try{adminKey=sessionStorage.getItem('launch-day-admin')||''}catch{}if(adminKey){try{await loadSessions();adminHome();return}catch{adminKey=''}}adminLogin();return}
 const cached=readStore();if(cached&&cached.token)s=cached;
 const recovery=new URLSearchParams(location.hash.slice(1)).get('access');if(recovery){s={code:params.get('room')||'',token:recovery,answers:{},index:0,version:0,dirty:false};persist();history.replaceState(null,'',location.pathname+location.search)}
 if(s.token&&s.code&&(!params.get('room')||params.get('room')===s.code)){
 screen('<main id="main" class="receipt"><div class="eyebrow">Launch Day</div><h2>Restoring your attempt…</h2><p class="muted">Checking your saved answers and submission status.</p></main>');
 try{const data=await studentApi('resume');const keep=s.dirty&&!data.attempt.submittedAt&&(s.version===data.attempt.version||(data.attempt.version===s.version+1&&JSON.stringify(data.attempt.answers)===JSON.stringify(s.inFlightAnswers)));apply(data,keep);renderStudent();if(s.dirty)flush().catch(()=>{});return}catch(e){landing(e.message);return}
 }
 landing();
}
window.addEventListener('beforeunload',e=>{if(s.dirty&&!attempt?.submittedAt){e.preventDefault();e.returnValue=''}});
window.addEventListener('online',()=>{if(s.dirty)flush().catch(()=>{})});
boot();
