import test from 'node:test';
import assert from 'node:assert/strict';
import {cleanIdentity, identityError, validAnswers, recoverState, buildPayload, escapeHTML} from '../model.js';
const sample = () => ({assessmentVersion:'unit-test-only',preview:false,attemptId:'11111111-1111-4111-8111-111111111111',identity:{firstName:'Test',lastName:'Only',email:'test@lasalle.edu'},answers:Array(10).fill(null),clientStartedAt:'2026-10-05T12:00:00Z',status:'answering',result:null});
test('identity normalization and strict institutional domain',()=>{assert.deepEqual(cleanIdentity(' Test ',' Only ',' TEST@LASALLE.EDU '),sample().identity);assert.equal(identityError(sample().identity),'');for(const email of ['test@example.com','test@lasalle.edu.evil.test','x@y@lasalle.edu'])assert.notEqual(identityError({...sample().identity,email}),'');});
test('exactly ten bounded choices; partial answers allowed only in draft',()=>{assert.equal(validAnswers(Array(10).fill(null)),true);assert.equal(validAnswers(Array(10).fill(null),true),false);for(const answers of [[],Array(9).fill(0),Array(10).fill(4),Array(10).fill('0')])assert.equal(validAnswers(answers),false);});
test('restore valid draft and fail closed on corruption/version/mode changes',()=>{const s=sample();assert.deepEqual(recoverState(JSON.stringify(s),'unit-test-only',false),s);for(const raw of ['broken','null','{}',JSON.stringify({...s,attemptId:'bad'}),JSON.stringify({...s,answers:[]})])assert.equal(recoverState(raw,'unit-test-only',false),null);assert.equal(recoverState(JSON.stringify(s),'different',false),null);assert.equal(recoverState(JSON.stringify(s),'unit-test-only',true),null);});
test('interrupted submission restores locked for same-attempt retry',()=>{const s={...sample(),answers:Array(10).fill(0),status:'pending'};assert.equal(recoverState(JSON.stringify(s),'unit-test-only',false).status,'error');});
test('payload contains only designated submission fields; no client score',()=>{const s={...sample(),score:10,unwanted:'test'};assert.deepEqual(Object.keys(buildPayload(s)).sort(),['answers','assessmentVersion','attemptId','clientStartedAt','email','firstName','lastName']);assert.notEqual(buildPayload(s).answers,s.answers);});
test('display values are escaped',()=>assert.equal(escapeHTML('<script>"&\''),'&lt;script&gt;&quot;&amp;&#39;'));

test('recovery rejects preview and live status crossovers',()=>{const s={...sample(),answers:Array(10).fill(0)};assert.equal(recoverState(JSON.stringify({...s,status:'preview-complete'}),'unit-test-only',false),null);assert.equal(recoverState(JSON.stringify({...s,preview:true,identity:null,status:'saved'}),'unit-test-only',true),null);});
