/* OFF SCRIPT — a fictional NIL management story. Course adaptation, not legal advice.
   Pure, deterministic branching model. No random outcomes or legal-probability scores. */
(function(root,factory){const api=factory();if(typeof module==='object'&&module.exports)module.exports=api;else root.OffScript=api;})(typeof globalThis!=='undefined'?globalThis:this,function(){
'use strict';
const VERSION='1.0.0', TOTAL=6;
const money=n=>(n<0?'−':'')+'$'+Math.abs(n).toLocaleString('en-US');
const clone=s=>JSON.parse(JSON.stringify(s));
const cast={
 mara:{name:'Mara Chen',role:'Producer · Signal House',initials:'MC',color:'amber'},
 blaze:{name:'Blaze',role:'Pro player · personal Rook deal',initials:'BZ',color:'blue'},
 nova:{name:'Nova',role:'Creator · fiercely protective of her voice',initials:'NV',color:'pink'},
 dev:{name:'Dev Malik',role:'Seatline · headline sponsor',initials:'DM',color:'green'},
 izzy:{name:'Izzy',role:'Counsel · asks what the document actually says',initials:'IZ',color:'violet'},
 moth:{name:'Moth',role:'Fan artist · not your unpaid creative department',initials:'MO',color:'blue'},
 echo:{name:'ECHO Studio',role:'Synthetic-voice vendor',initials:'EC',color:'violet'}
};
const curriculum=[
 {title:'The first promise',concept:'Defined uses, reserved categories, and the team’s authority to license identity.',source:'Chapter 5, Practical Mechanics and Sample NIL Clause; slides 15–17, 21, 32.'},
 {title:'The chair problem',concept:'Personal sponsorships versus team exclusivity; read both grants rather than assume ownership.',source:'Chapter 5, The Conflicting Sponsors; slides 16–17.'},
 {title:'The thirty-second trailer',concept:'Identity permission is separate from copyright in footage, photos, games, and music. Endorsement disclosure is another obligation.',source:'Chapter 5, Definition and Core Concepts and Practical Mechanics; slides 4, 15, 18, 21.'},
 {title:'The fan-made problem',concept:'Recognizable identity, possible false endorsement, and expressive defenses; sales alone do not resolve the issue.',source:'Chapter 5, Defenses and The Fan Art Gone Commercial; slides 12–14, 29–30.'},
 {title:'The voice that never spoke',concept:'Separate, specific permission for model training and synthetic output; identifiability and AI labels do not settle consent.',source:'Chapter 5, AI Voices, Consent, and Digital Replicas and Sample NIL Clause; slides 23–26, 32.'},
 {title:'One last little reuse',concept:'Duration, new uses, approval, retirement, and the consequences of granting more than you possess.',source:'Chapter 5, No Doubt spotlight, Sample NIL Clause, and Conclusion; slides 14–16, 25, 28, 32.'}
];
function initial(){return {version:VERSION,step:0,funds:0,trust:65,community:60,deal:'',scope:'',pending:0,sponsorOK:true,carveout:false,media:'none',disclosure:true,fan:'none',voice:'none',open:[],history:[],ledger:[],launch:'',delayed:false,repair:false,expanded:false,critical:false};}
function add(s,id){if(!s.open.includes(id))s.open.push(id);}
function remove(s,id){s.open=s.open.filter(x=>x!==id);}
function transact(s,amount,note){s.funds+=amount;s.ledger.push({decision:s.step+1,amount,note});}
const issueLabels={sponsor:'Blaze / chair-category conflict',media:'Trailer footage and music clearances',disclosure:'Paid-endorsement disclosure',voice:'Nova’s synthetic-voice permission',extension:'New uses after the license ends'};
function issues(s){return s.open.map(x=>({id:x,label:issueLabels[x]||x}));}
function relation(s){return s.trust>=76?'In your corner':s.trust>=55?'Working with you':s.trust>=35?'Asking hard questions':'Trust is damaged';}
function dealName(s){return {event:'Event-first agreement',broad:'All-channel proposal',creator:'Creator-led collaboration'}[s.deal]||'No agreement yet';}
function documents(s){
 let sponsor='No contract selected yet.';
 if(s.scope==='event')sponsor='Seatline: campaign and official event channels only. Blaze’s existing Rook sponsorship remains reserved on personal, non-event streams. No Rook clip may be repackaged into Seatline advertising without fresh clearance.';
 if(s.scope==='broad')sponsor=s.sponsorOK?'All-channel chair exclusivity is now backed by Blaze’s written assent and Rook’s signed waiver. The specified Rook make-good is due after this campaign.':'All-channel chair exclusivity was proposed, but Rook has not waived its earlier personal-stream rights. The extra $10,000 remains conditional; the team cannot erase the earlier deal.';
 if(s.scope==='creator')sponsor='Seatline receives two agreed event appearances. Personal channels and other categories remain reserved. New uses require each creator’s written approval.';
 return [
 {title:'Sponsor scope',text:sponsor},
 {title:'Identity permission',text:'All signed opening options cover specified, approved event promotion using Blaze and Nova’s identities. None transfers ownership of the people, their streaming accounts, or all copyrights. The original permission ends on day 30.'},
 {title:'Media rights',text:s.media==='owned'?'Original footage and music were commissioned under signed campaign licenses; required identity approvals and game-free edits are on file.':s.media==='licensed'?'The producer secured the specified camera, game-footage, and music rights, plus the required campaign identity approvals.':s.media==='uncleared'?'The original trailer contains editorial-only footage, game IP, and music without sponsor-ad clearance. Owning the channel did not resolve those rights.':'No trailer has been approved yet.'},
 {title:'Fan art',text:s.fan==='ally'?'Moth and Nova each signed an event-only collaboration license. Moth retains copyright; the art cannot automatically become a year-long sponsor ad.':s.fan==='space'?'Moth’s independent parody remains separate from the official campaign. The team has no permission to reuse Moth’s art.':s.fan==='threat'?'The blanket removal demand did not obtain any license. Moth has declined collaboration; no court ordered removal.':'No official fan-art license.'},
 {title:'Voice / AI',text:s.voice==='limited'?'Separate agreement: licensed source audio; limited model training; ten approved greetings for this event only; stated payment; human approval; no product testimonials or open-ended voice chat. Model access and campaign outputs must be retired at the agreed end.':s.voice==='unauthorized'?'A recognizable synthetic Nova preview was released without her separate consent. “AI-generated” labeling does not supply that consent.':s.voice==='human'?'No synthetic Nova voice is authorized or needed. A human host uses their own voice; any Nova recording is used only as specifically approved.':'The opening agreement excludes AI training and digital replicas. A separate written agreement is required under this fictional contract.'},
 {title:'Ending / retirement',text:s.expanded?'A new, signed 90-day agreement permits specified static assets and identified paid ads. It does not authorize an interactive Nova, new synthetic dialogue, or unrelated game uses.':s.launch==='scoped'||s.launch==='reset'?'Official uses are limited to the approved event package. The workflow stops new promotion and retires controlled assets by the agreed deadline; third-party reposts are not guaranteed to disappear.':'The original event permissions end on day 30. Buying a file is not permission for every future use.'}
 ];
}
function option(id,title,body,trade,apply){return {id,title,body,trade,apply};}
function scene(s){
 if(!s||s.step<0||s.step>=TOTAL)throw Error('No active scene.');
 let v={index:s.step,phase:['10 days to launch','8 days to launch','5 days to launch','3 days to launch','Tomorrow','Launch morning'][s.step],title:'',deck:'',messages:[],evidence:[],callback:'',callbackFrom:[],options:[]};
 if(s.step===0){
 v.id='opening';v.title='The offer comes with a footprint.';
 v.deck='You manage brand partnerships at Signal House. Seatline wants Blaze and Nova to front CROSSPLAY, your creator weekend. All three offers are negotiable and the creators are at the table. Which deal do you put into writing?';
 v.messages=[['dev','We can fund a bigger show. We just need clarity on where the chairs—and the creators—appear.'],['blaze','I already have a personal Rook chair deal. Please do not sell that space twice.'],['nova','My face in an event trailer? Let’s discuss it. A bot talking as me forever? Different conversation.']];
 v.evidence=[['Existing agreement','Blaze’s Rook contract covers personal streams. Rook has not waived it. Official event promotion can be separated from those streams.'],['Common terms in all three offers','30-day event permissions; creator assent to specified uses; separate media clearances; no AI training or replicas; new uses need written approval. All people are adults.']];
 v.options=[
 option('event','Keep it event-first.','Accept $20,000 for official event promotion. Reserve Blaze’s Rook deal and personal channels in a signed schedule.','Less reach for Seatline; clearer separation.',n=>{n.deal='event';n.scope='event';n.carveout=true;n.trust+=7;transact(n,20000,'Seatline event-first production funding');return ['The agreement has edges.','Seatline, the team, and the creators sign the event-only schedule. The personal-stream carve-out is now something you can point to, not something you hope exists.','Your event-only permission will matter when personal footage enters the campaign.'];}),
 option('broad','Chase the all-channel deal.','Accept $20,000 now and pursue $10,000 more for all-channel chair exclusivity. The extra scope and payment wait for a written Rook waiver.','More potential funding; a live consent dependency.',n=>{n.deal='broad';n.scope='broad';n.sponsorOK=false;n.pending=10000;add(n,'sponsor');n.trust-=3;transact(n,20000,'Seatline base payment; extra $10,000 remains conditional');return ['You bought yourself a negotiation.','The base payment arrives. The extra $10,000 does not. Blaze agrees to explore the broader package, but neither the team nor Seatline can cancel Rook’s prior rights by declaring exclusivity.','Rook’s signature is now a condition of your bigger plan.'];}),
 option('creator','Build a smaller creator-led deal.','Accept $16,000 for two agreed appearances. Keep personal categories reserved and require written approval for each new campaign use.','Less production money; more creator control.',n=>{n.deal='creator';n.scope='creator';n.carveout=true;n.trust+=12;transact(n,16000,'Seatline creator-led production funding');return ['The creators lean in.','Nova approves the two appearances. Blaze’s existing sponsor stays outside the event. You have less money to spend and no blanket shortcut around later approvals.','Specific approval can create cooperation without becoming unlimited permission.'];})
 ];
 }else if(s.step===1){
 v.callbackFrom=[1];
 if(s.scope==='broad'){
 v.id='waiver';v.title='Two chair brands. One promised channel.';v.callback='Your all-channel proposal left $10,000 conditional on a Rook waiver.';
 v.deck='Seatline wants tomorrow’s personal stream. Rook points to its existing agreement. A written waiver is available: pay a $3,000 make-good and give Rook an agreed appearance after CROSSPLAY. Blaze will sign that limited change—not an unlimited transfer.';
 v.messages=[['dev','The wider buy is still on the table. “We will sort it later” is not clearance.'],['blaze','I’ll consider a defined trade. I won’t pretend my other contract vanished.']];
 v.evidence=[['Rook’s proposed waiver','Signed consent would release this campaign window only. The $3,000 make-good includes the specified creator payment and the later Rook appearance.'],['Fallback','Seatline will accept the original $20,000 event-only deal instead. The conditional $10,000 would lapse without a breach penalty.']];
 v.options=[
 option('waiver','Negotiate the signed waiver.','Complete the limited Rook waiver and Blaze’s amendment before any personal-channel promotion.','Spend $3,000; release the conditional $10,000.',n=>{transact(n,-3000,'Rook waiver make-good and creator compensation');transact(n,n.pending,'Conditional all-channel payment released after signed waiver');n.pending=0;n.sponsorOK=true;n.carveout=false;n.trust+=4;remove(n,'sponsor');return ['The second signature changes the story.','Rook and Blaze sign the specified amendment. Seatline releases the additional payment. You now have broader campaign rights—but still no AI permission and no indefinite license.','An agreed waiver, not the bigger sponsor’s demand, expanded your authority.'];}),
 option('narrow','Take the event-only fallback.','Keep Seatline off personal streams. Record the reserved Rook category and let the extra payment lapse.','Give up $10,000 of potential funding; preserve the earlier deal.',n=>{n.pending=0;n.scope='event';n.sponsorOK=true;n.carveout=true;n.trust+=8;remove(n,'sponsor');return ['You shrink the promise, not the person.','Seatline accepts the event-only fallback in writing. The budget never contained the conditional $10,000, so no imaginary cash disappears. Rook’s personal-stream rights remain intact.','Your new event-only boundary now follows every clip you use.'];}),
 option('override','Tell Blaze to stream the Seatline promotion.','Proceed under the team’s general promotional clause while you contest Rook’s restriction.','Meet tomorrow’s slot; the conflicting contract remains unresolved.',n=>{n.sponsorOK=false;n.trust-=18;add(n,'sponsor');return ['The slot is filled. The permission is not.','Rook objects and asks for the agreement you relied on. Seatline keeps the extra payment on hold. Blaze notices that the team’s promise was treated as more important than his earlier contract. No court has decided the dispute.','A filled schedule can carry an unresolved rights problem into the next scene.'];})
 ];
 }else{
 const flexible=s.scope==='creator';
 v.id=flexible?'creator-boundary':'personal-carveout';v.title=flexible?'“Two appearances” becomes “everywhere.”':'A personal stream enters the sponsor brief.';
 v.callback=flexible?'You sold two agreed appearances, not control over the creators’ entire channels.':'You reserved Blaze’s Rook deal on personal, non-event streams.';
 v.deck=flexible?'Seatline sends an updated brief asking Blaze to replace Rook on his personal channel for the whole campaign. The brand calls this “normal activation.” Your agreement did not include it.':'Blaze plans a clearly paid Rook segment on his personal stream. Seatline wants to cut that footage into a CROSSPLAY sponsor trailer. Your written schedule permits the personal stream, but does not permit that crossover.';
 v.messages=[['blaze','My personal channel is not automatically an extension of the team’s sponsor inventory.'],['dev',flexible?'Could you approve the wider activation? We have a little extra money.':'That personal clip looks great. Can we just crop out the other chair logo?']];
 v.evidence=[['The signed schedule',flexible?'Two specified appearances; personal channels reserved. New uses need written creator approval.':'Rook is reserved for personal streams. Event jerseys, event footage, and Seatline ad reuse are outside that carve-out.'],['Written opt-in offer','Rook and Blaze will approve a specific separated Seatline shoot for an additional package. Seatline adds $6,000; the required permissions and compensation cost $2,000.']];
 v.options=[
 option('boundary','Hold the existing boundary.','Keep the Rook personal stream separate. Deliver only the agreed Seatline appearances and use a different event shoot.','No new payment; no new personal-channel commitment.',n=>{n.sponsorOK=true;n.carveout=true;n.trust+=6;return ['The carve-out earns its keep.','Both brands receive the signed schedule. Blaze’s Rook stream remains personal and separate; the event uses different footage. Saying no to one reuse keeps the original campaign moving.','The rival-sponsored personal clip is still not cleared for your event trailer.'];}),
 option('optin','Buy a specific opt-in.','Get Blaze’s assent, Rook’s written permission, and a defined Seatline shoot license. Keep unrelated personal content reserved.','Receive $6,000; pay $2,000 for the defined expansion.',n=>{transact(n,6000,'Seatline separate-shoot expansion');transact(n,-2000,'Specific permissions and creator compensation');n.sponsorOK=true;n.carveout=true;n.trust+=2;return ['A new use gets a new agreement.','Blaze and Rook approve the limited shoot in writing. This creates usable sponsor material; it does not erase the personal sponsorship or license every future clip.','You have a defined additional shoot, not unlimited rights.'];}),
 option('assume','Approve the crossover edit now.','Use the personal stream in Seatline’s campaign and rely on the team’s general promotion language.','Save coordination time; the reserved-category boundary is still in the contract.',n=>{n.sponsorOK=false;n.trust-=17;add(n,'sponsor');return ['The edit creates the conflict you had avoided.','Blaze and Rook object to the sponsor reuse. Seatline pauses this asset pending clarification. A personal-stream carve-out did not automatically authorize a competing brand’s ad.','The unresolved sponsorship objection will follow your trailer approval.'];})
 ];
 }
 }else if(s.step===2){
 v.id=s.sponsorOK?'trailer-clearance':'trailer-exclusion';v.title='Thirty seconds. At least three different rights.';
 v.callbackFrom=[1,2];v.callback=s.sponsorOK?'Your sponsor scope is now documented. That does not clear the footage or the music.':'The chair objection is unresolved. A new sponsor trailer cannot quietly cure that earlier promise.';
 v.deck='The editor delivers a gorgeous highlight: Nova’s face, Blaze’s gameplay, and a trending track. The team owns the channel, but the camera license says editorial use only. The publisher and music permissions do not cover this sponsor ad. The draft disclosure sits in the profile bio.';
 v.messages=[['mara','We own the upload. That is not the same as owning everything inside it.'],['nova','Use the shot I approved—not my face next to a claim I never made.'],['izzy','There are separate questions: identity, the creative works, the sponsor scope, and the paid relationship viewers actually see.']];
 v.evidence=[['Asset sheet','Camera operator: editorial license only. Game footage: no sponsor-ad clearance shown. Music: no commercial synchronization permission shown. Creator approval covers the specified event concept, not unlimited endorsements.'],['Production alternatives',s.sponsorOK?'A clean reshoot costs $1,800; a complete existing-asset clearance costs $2,400. Both include contextual paid disclosures and only truthful approved statements.':'A clean reshoot excluding the disputed chair crossover costs $1,800; a cleared recut with the same exclusion costs $2,400. These fix this trailer, not the outstanding sponsor conflict.']];
 v.options=[
 option('original','Make a clean, original trailer.','Commission campaign-licensed footage and music, omit game footage and any disputed crossover, and secure the creators’ specific approvals. Put paid disclosures in the content.','Spend $1,800; save a reusable, approved Nova greeting for the event.',n=>{transact(n,-1800,'Original campaign footage, music, creator approvals, disclosure edit');n.media='owned';n.disclosure=true;n.trust+=5;return ['You now have footage you can actually use.','The new trailer has separate media and identity permissions on file, with paid disclosures in the content. Nova also approves one recorded event greeting. It is a recording—not permission to train a voice model.'+(n.sponsorOK?'':' The earlier chair dispute remains open.'),'That approved greeting could become a fallback if Nova cannot appear live.'];}),
 option('license','Clear the existing footage properly.','Obtain the camera, game-footage, and music licenses plus specific identity approvals. Recut disputed sponsorship material and add in-content disclosure.','Spend $2,400; keep the high-production highlight.',n=>{transact(n,-2400,'Specified footage, publisher and music licenses, identity approvals, disclosure edit');n.media='licensed';n.disclosure=true;n.trust+=3;return ['The highlight stays. The shortcuts do not.','The rights holders provide the defined licenses and the creators approve the cut. The editor places the paid relationship in the ad, not only in the profile. No standalone Nova greeting or AI permission is included.'+(n.sponsorOK?'':' The prior chair objection is still unresolved.'),'You licensed this particular highlight, not every new use of its component parts.'];}),
 option('ship','Post the existing cut.','Rely on the team’s channel ownership and leave the paid relationship in the profile bio.','No new production cost; the missing permissions and disclosure remain.',n=>{n.media='uncleared';n.disclosure=false;n.trust-=12;add(n,'media');add(n,'disclosure');return ['The trailer goes out before the file is ready.','The camera operator requests the commercial license. Fans ask whether Nova personally endorsed the sponsor’s claims. The profile notice does not tell every viewer what they need to know. These are unresolved issues—not automatic damages or a court verdict.','You have a public asset to repair, not just an internal approval to obtain.'];})
 ];
 }else if(s.step===3){
 const friction=!s.sponsorOK||!s.disclosure;
 v.id=friction?'fan-backlash':'fan-opportunity';v.title=friction?'The fan art is about your campaign now.':'The unofficial design gets the better reviews.';
 v.callbackFrom=friction?[2,3]:[1,3];v.callback=friction?'Your earlier sponsor or disclosure problem gave the community something to parody.':'The campaign’s visibility brought a fan creator to your attention.';
 v.deck='Moth sells an original cartoon of Nova’s neon hoodie and goggles, surrounded by absurdly oversized sponsor chairs. The caption reads “Authenticity, sponsored.” It is labeled unofficial satire. Some reposts omit that context and fans ask whether it is official merchandise. Seatline wants it taken down—or in its ads.';
 v.messages=[['moth','I drew a joke about sponsorship. I did not volunteer to become the sponsor’s art department.'],['nova',friction?'Honestly? I can see why they drew it. But do not use me in more ads without asking.':'It is funny. That does not mean either of us has licensed it to Seatline.'],['izzy','Selling a parody does not automatically destroy expressive protection. Reposting its art as a sponsor ad is a different proposed use.']];
 v.evidence=[['What is actually known','Original art; recognizable combined features; explicit criticism of sponsorship; unofficial label on the original listing; confusing reposts. No court has evaluated the depiction, governing law, or defenses.'],['Possible collaboration','Moth is willing to draw a new, expressly official event variant for $900 and credit. Nova is willing to approve that variant. Both permissions would be limited to this event; the original satire stays independent.']];
 v.options=[
 option('collab','Invite a paid, opt-in collaboration.','License a new official variant from Moth and obtain Nova’s specific approval. Preserve the independent satire and identify what is official.','Spend $900; gain a collaborator, not ownership of all fan work.',n=>{transact(n,-900,'Moth official variant: limited license and artist payment');n.fan='ally';n.community+=15;n.trust+=5;return ['The person you almost treated as a problem joins the project.','Moth and Nova each sign the event-only agreement. Moth keeps copyright; Nova controls the specified identity use. The official variant is labeled as a paid collaboration. The original parody remains independent.','Moth has agreed to help with an event graphic fallback—but not a year-long ad campaign.'];}),
 option('space','Leave the satire independent.','Clarify that it is unofficial, document confusing reposts, and distinguish possible misleading uses from the original parody. Do not reuse the artwork.','No collaboration fee; Seatline loses this creative asset.',n=>{n.fan='space';n.community+=8;n.trust+=3;return ['Not every recognizable face becomes your enforcement target.','The team issues a factual clarification and reviews specific confusing uses. Moth keeps the independent parody. You have not conceded every possible claim—and you still have no license to put the art in Seatline’s ads.','Respecting a fan’s expression does not create a license to reuse their work.'];}),
 option('demand','Demand removal of every version.','Send a blanket identity-rights demand to the artist and resellers, including the original satire.','Spend $600 on the demand and follow-up; expect resistance.',n=>{transact(n,-600,'Blanket demand preparation and follow-up');n.fan='threat';n.community-=23;n.trust-=9;return ['The demand becomes the next piece of content.','Moth posts the letter and declines collaboration. Counsel still needs to analyze identification, context, defenses, and jurisdiction. The demand is not a court order; no takedown or damages is automatic.','Moth will not supply an official fallback later, and the community remembers the approach.'];})
 ];
 }else if(s.step===4){
 const prepared=s.media==='owned', ally=s.fan==='ally';
 v.id=prepared?'voice-with-recording':ally?'voice-with-artist':'voice-without-backup';v.title='Nova cannot go live. Someone offers another Nova.';
 v.callbackFrom=[3,4];v.callback=prepared?'Your clean reshoot saved an approved, ordinary event greeting. You have a non-AI fallback.':ally?'Your agreement with Moth includes an approved event graphic. That gives you a simpler live-show alternative.':'You have no standalone Nova greeting or collaborating artist ready for a fallback.';
 v.deck='Nova cannot attend live. ECHO offers a host that sounds unmistakably like her, built from public streams. The vendor says the outputs are new audio and will be labeled AI. Nova has not authorized this model. She will consider ten approved event greetings under a separate agreement, but refuses open-ended chat and product testimonials.';
 v.messages=[['echo','We can ship a voice preview by dinner. Nobody has to record anything new.'],['nova','A label is not my signature. Ten approved greetings is a conversation. An infinite version of me is not.'],['mara',prepared?'We also have the greeting you cleared earlier. It is less spectacular. It exists.':ally?'Moth can adapt the licensed event graphic for a human host. We do have options.':'A real host is available. We would need to pay for a rush booking.']];
 v.evidence=[['Scope of the proposed AI agreement','Nova signs for licensed source audio, limited training, ten approved greetings, stated payment, human output approval, event-only use, and retirement of model access and outputs. No open chat, new testimonials, or other games. Source-recording rights are separately cleared.'],['Separate obligations','A recognizable simulation may raise identity issues without copying the original recording. The story does not assume union coverage; any applicable performer or labor agreement needs its own review. Positive trust is not consent.']];
 const fallbackCost=prepared?500:ally?900:2200;
 v.options=[
 option('specific','Negotiate a limited, paid voice license.','Discard the unapproved vendor model. Build from separately cleared source audio under Nova’s specific written terms; use only the ten approved greetings.','Spend $2,800; no open-ended chat or sponsor testimonials.',n=>{transact(n,-2800,'Specific synthetic-voice agreement, source clearance, build and review');n.voice='limited';n.trust+=4;return ['Nova says yes to something specific.','The parties sign the supplied scope. The vendor retires its unapproved model and uses authorized source audio for the controlled build. Each greeting is reviewed. This is new consent—not consent inferred from her contract, public streams, or relationship with you.','The limited model will not be licensed for Seatline’s next idea.'];}),
 option('human',prepared?'Use the greeting you already cleared.':ally?'Let the artist and a real host carry the show.':'Book a real host.',prepared?'Play Nova’s approved recording once and let a human host use their own voice. Do not clone her.':ally?'Use Moth’s approved event graphic with a human host speaking in their own voice. No imitation of Nova.':'Book a human host using their own identity and approved script. Remove promises of a live Nova appearance; do not imitate her.',`Spend ${money(fallbackCost)}; a less novel production with no synthetic Nova.`,n=>{transact(n,-fallbackCost,'Non-AI host and approved event fallback');n.voice='human';n.trust+=6;return [prepared?'Yesterday’s clearance pays off.':ally?'The fan relationship becomes production capacity.':'The show has a human voice.',prepared?'The ordinary greeting plays within its approved event scope. The host is introduced accurately and no Nova model is created.':ally?'Moth approves the event graphic adaptation under the existing scope. A clearly identified human host runs the show without impersonating Nova.':'The audience is told Nova cannot attend live. The named host presents the approved material in their own voice. You forgo the synthetic spectacle rather than pretending a substitute is Nova.','No synthetic voice exists to authorize in a later interactive ad.'];}),
 option('preview','Release ECHO’s AI-labeled voice preview.','Use the recognizable model built from public streams. Treat the new recording and AI label as enough to proceed.','Spend $700; Nova has not agreed to this use.',n=>{transact(n,-700,'Unapproved synthetic-voice preview production');n.voice='unauthorized';n.trust-=27;add(n,'voice');return ['The voice says yes. Nova says no.','Nova objects: she never recorded or approved the performance. Fans infer a partnership despite the AI label. She now expressly refuses any new voice license today. No liability has been adjudicated; the unauthorized preview still requires a response.','The limited-license offer is no longer available at tomorrow’s deadline.'];})
 ];
 }else if(s.step===5){
 const wounded=s.voice==='unauthorized', open=s.open.length>0;
 v.id=wounded?'finale-no-consent':open?'finale-repair':'finale-expansion';
 v.title=wounded?'Launch morning. Nova withdraws the offer.':open?'The launch inherits your open tabs.':'The successful test creates the next demand.';
 v.callbackFrom=[1,2,3,4,5];
 v.callback=wounded?'Your AI preview changed what Nova is willing to authorize. A new voice deal is unavailable today.':open?'The unresolved permissions came from earlier choices. The calendar did not close them for you.':'The permissions you collected made this launch possible. Each still has a defined purpose and end date.';
 v.deck=wounded?'Seatline wants a year-long interactive ad host using Nova’s voice and the campaign art. Nova refuses a new voice license today. Your original contract ends on day 30. She will allow accurate event listings and an approved non-AI repair, but will not approve an expansion at this deadline.':open?'Seatline offers an additional $12,000 for a year of ads and an interactive host. Your team still has unresolved clearances. The original event permission ends on day 30, and none of the signed packages authorizes this new interactive use.':'Seatline loves the test and offers an additional $12,000 for a year of ads and an interactive Nova. Your signed event rights expire on day 30. A limited voice license, an artist collaboration, or ownership of a file does not include this new use.';
 v.messages=[['dev','Could we keep the assets running for another year? It is mostly the same campaign.'],['nova',wounded?'No new voice license today. Stop the preview. You can propose a real repair—not another launch with my face on it.':'An interactive version of me is not “mostly the same.” I can discuss a narrower static campaign.'],['izzy',open?'The missing permissions and the new request are separate tasks. Repairing one does not silently authorize the other.':'Scope and expiration are real constraints even when the first project succeeds.']];
 const repairCost=1200+(s.open.includes('sponsor')?2200:0)+(s.open.includes('media')?1600:0)+(s.open.includes('disclosure')?300:0)+(wounded?1800:0);
 const hasPastProblem=s.history.some(h=>h.openAfter.length>0 && h.index>0);
 v.evidence=[['Current deadline','Original identity and campaign-art grants end on day 30. A limited model, if authorized, is restricted to the approved greetings. Independent parody is never licensed by default. Third-party reposts may persist after official withdrawal.'],[wounded?'Nova’s recorded boundary':'Negotiated alternative',wounded?'No new replica or extended identity license today. A $'+repairCost.toLocaleString('en-US')+' scoped-repair package is available with express approval of the replacement event assets. A longer rights reset requires postponement; no future license is guaranteed.':'Seatline and the creators offer a narrower signed 90-day STATIC campaign: no interactive voice, no new generated dialogue. Extra funding is $8,000 rather than $12,000; rights/compensation and replacement production cost '+money(3600+repairCost-1200)+'. Launch moves by 24 hours.']];
 v.options=[
 option('scoped',open?'Repair and launch a smaller show.':'Launch only what you actually licensed.',open?'Replace or withdraw uncleared assets, resolve the sponsor scope in writing, use truthful in-content disclosures, and deliver the expressly approved non-AI or limited-scope event package.':'Decline the year-long extension. Deliver the approved event package, then stop promotion and retire controlled assets at the agreed end.',`Spend ${money(repairCost)} on ${open?'repair and scoped delivery':'delivery and retirement'}; no expansion payment.`,n=>{transact(n,-repairCost,'Scoped delivery, required replacements/agreements, and retirement workflow');n.repair=open;n.open=[];n.sponsorOK=true;if(n.scope==='broad'&&n.pending){n.scope='event';n.carveout=true;n.pending=0;}if(n.media==='uncleared')n.media='owned';n.disclosure=true;if(wounded)n.voice='human';n.launch='scoped';n.trust+=open?4:7;return ['A launch is not a license to keep going.','The relevant parties expressly approve the scoped package and any sponsor amendment. Uncleared materials are withdrawn or replaced; no automatic retroactive permission is claimed. Official uses stop at the agreed endpoint. '+(open?'Earlier costs and damage to confidence remain. Third-party copies may still circulate.':'You leave the expansion money on the table and keep the promise you made.'),'The final scope is workable because it was actually agreed, not because the risk meter turned green.'];}),
 wounded?
 option('reset','Postpone and reset the rights conversation.','Withdraw the preview, pause launch, account to the creators, and negotiate a new schedule without assuming Nova will consent again.','Spend $4,500 on refunds/rebooking and cleanup; no launch or new license today.',n=>{transact(n,-4500,'Postponement, rebooking/refunds, withdrawal and rights review');n.launch='reset';n.delayed=true;n.repair=true;n.pending=0;n.open=[];n.trust+=9;return ['You stop selling a yes you do not have.','Seatline accepts a written postponement. The team stops disputed uses and begins a rights reset; no new Nova license is obtained in this ending. No campaign launches today. Earlier uses may still require advice or resolution even after withdrawal.','A reset protects the possibility of repair, not a guaranteed future deal.'];}):
 option('extend','Negotiate the smaller, explicit extension.','Obtain new creator and media licenses for 90 days of identified static ads. Exclude interactive voice and unlicensed fan art; replace unresolved assets before launch.','Add $8,000; pay '+money(3600+repairCost-1200)+'; delay 24 hours.',n=>{transact(n,8000,'Signed 90-day static-campaign expansion funding');transact(n,-(3600+repairCost-1200),'New limited licenses, creator compensation, replacement/retirement work');n.expanded=true;n.repair=open;n.delayed=true;n.open=[];n.sponsorOK=true;if(n.scope==='broad'&&n.pending){n.scope='event';n.carveout=true;n.pending=0;}n.disclosure=true;if(n.media==='uncleared')n.media='licensed';n.launch='extended';n.trust+=5;return ['The deal changes before the use changes.','The parties sign the specified static-ad extension and resolve this package’s component permissions. The new uses exclude synthetic dialogue and the unlicensed parody. '+(n.fan==='ally'?'Moth and Nova separately approve the paid official-art extension. ':'Replacement campaign art is separately licensed. ')+'The event moves by 24 hours. Past disputed uses are not erased.','Growth is available, but it arrives with new scope, payment, and a schedule tradeoff.'];}),
 option('expand-now','Release the year-long interactive package.','Accept Seatline’s plan and provide the assets now, relying on the original event agreement while further approvals catch up.','The $12,000 is only an offer; approval of this new use is missing.',n=>{n.launch='overreach';n.critical=true;add(n,'extension');add(n,'voice');n.trust-=20;n.pending=0;return ['The deliverable outruns the permission.','The extended package is released without the new identity and component licenses. The creators object and Seatline withholds its offered $12,000. The team must respond to disputed uses and continuing distribution. The story does not invent an injunction, statutory fine, or court win.','Success in an earlier scene did not enlarge the original grant.'];})
 ];
 }
 return v;
}
function choose(s,id,read=[]){
 const v=scene(s),o=v.options.find(x=>x.id===id);if(!o)throw Error('That option is not available on this branch.');
 const n=clone(s), before={funds:n.funds,trust:n.trust,open:clone(n.open)};
 const outcome=o.apply(n);n.trust=Math.max(0,Math.min(100,n.trust));n.community=Math.max(0,Math.min(100,n.community));
 n.history.push({index:s.step,sceneId:v.id,sceneTitle:v.title,option:id,title:o.title,body:o.body,trade:o.trade,evidence:read.filter(x=>Number.isInteger(x)&&x>=0&&x<v.evidence.length),callback:v.callback,callbackFrom:v.callbackFrom,outcome,delta:n.funds-before.funds,trustDelta:n.trust-before.trust,openBefore:before.open,openAfter:clone(n.open),concept:curriculum[s.step].concept,source:curriculum[s.step].source});
 n.step++;return n;
}
function rebuild(choices){let s=initial();for(const item of choices){const id=typeof item==='string'?item:item.option;s=choose(s,id,typeof item==='string'?[]:item.evidence||[]);}return s;}
function ending(s){
 if(s.step!==TOTAL)throw Error('Finish the story first.');
 if(s.launch==='overreach')return {id:'borrowed',title:'Borrowed identity. Borrowed time.',tag:'The expansion did not clear',text:'You delivered a bigger campaign than your permissions supported. The sponsor’s offered money never arrived. The next meeting is about stopping disputed uses, not announcing the next collaboration.'};
 if(s.launch==='reset')return {id:'reset',title:'The launch that waits.',tag:'Repair before release',text:'You postponed rather than treat a refusal as a production inconvenience. There is no launch and no new Nova license today. You have a recovery conversation to earn, with the earlier decisions still on the record.'};
 if(s.repair)return {id:'repair',title:'The recovery cut.',tag:s.delayed?'A repaired launch · 24 hours later':'A smaller, repaired launch',text:'The final package has expressly agreed boundaries, but the repair used money and goodwill. You stopped adding to the problem. You did not undo the first publication or guarantee the disappearance of third-party copies.'};
 if(s.expanded)return {id:'expansion',title:'The deal you actually made.',tag:'Defined expansion · 24 hours later',text:'You turned a sweeping request into a specified, paid static-ad agreement. The production is later and the expansion smaller than Seatline initially wanted. It is also grounded in actual permission.'};
 if(s.fan==='ally')return {id:'community',title:'The community gets a credit.',tag:'Scoped launch · creative collaboration',text:'The launch stays within its agreements, and the fan creator becomes a paid collaborator without surrendering the original parody. You finish with an event, a working relationship, and boundaries for the next request.'};
 return {id:'scope',title:'A smaller promise, kept.',tag:'Scoped launch · no expansion',text:'You delivered the event you could authorize and declined to turn a limited permission into a permanent inventory item. You did not take every available dollar. The campaign ends when the agreement says it ends.'};
}
function audit(s){
 const errors=[];
 if(s.step!==s.history.length)errors.push('history mismatch');
 if(s.funds!==s.ledger.reduce((a,t)=>a+t.amount,0))errors.push('funds reconciliation');
 if(s.pending && s.sponsorOK)errors.push('pending sponsor despite clearance');
 if(s.open.length!==new Set(s.open).size)errors.push('duplicate issues');
 if(s.step===TOTAL&&s.launch==='extended'&&s.history[4].option==='preview')errors.push('refused license magically granted');
 return errors;
}
return Object.freeze({VERSION,TOTAL,cast,curriculum,initial,scene,choose,rebuild,ending,issues,documents,relation,dealName,audit,money});
});
