/** Run with: node tests.mjs. No packages or network required. */
import {readFileSync} from 'node:fs';
import vm from 'node:vm';
import assert from 'node:assert/strict';
const html=readFileSync(new URL('./index.html',import.meta.url),'utf8');
const code=html.match(/<script id="game-engine">([\s\S]*?)<\/script>/)?.[1];
assert.ok(code,'Model script must exist');
const sandbox={};vm.createContext(sandbox);vm.runInContext(code,sandbox);const E=sandbox.ArenaTurnaroundEngine;
const A=(loadout=0,floor=0,reset=0)=>({loadout,floor,reset});
const efficient=[A(2,0,1),A(2,0,1),A(0,2,1),A(0,2,1),A(0,2,0)];
function run(plan,mode='standard',signoff=true){let s=E.create(mode);for(const assignment of plan)s=E.work(s,assignment);if(signoff)s=E.inspect(s);return s;}
let checks=0;function check(name,fn){fn();checks++;console.log('PASS '+name);}
check('Strong rehearsal: ready06, one-hour buffer, contribution5000',()=>{const s=run(efficient),o=E.outcome(s);assert.equal(s.hour,6);assert.equal(o.ready,true);assert.equal(o.onTime,true);assert.equal(o.buffer,1);assert.equal(o.contribution,5000);assert.equal(o.overtimeHours,0);assert.equal(E.isValidState(s),true);});
check('Inspection is a required separate full hour',()=>{const s=run(efficient,'standard',false);assert.equal(s.phase,'inspection');assert.equal(s.hour,5);assert.equal(E.outcome(s).ready,false);const out=E.inspect(s);assert.equal(out.hour,6);assert.equal(out.log.at(-1).kind,'inspection');assert.throws(()=>E.inspect(E.create()));assert.throws(()=>E.work(s,A()));});
check('Load-out dependency blocks floor work in the same hour',()=>{let s=E.create();s=E.work(s,A(2,0,1));assert.throws(()=>E.work(s,A(1,1,1)));s=E.work(s,A(2,0,1));assert.equal(s.hour,2);assert.equal(E.available(s,'floor'),2);});
check('Crew count, per-task maximum, integer and remaining-work bounds',()=>{let s=E.create();assert.throws(()=>E.work(s,A(2,0,2)));assert.throws(()=>E.work(s,A(3,0,0)));assert.throws(()=>E.work(s,A(-1,0,0)));assert.throws(()=>E.work(s,A(1.5,0,0)));s=E.work(s,A(1,0,2));s=E.work(s,A(1,0,2));s=E.work(s,A(1,0,0));assert.equal(E.available(s,'loadout'),1);assert.throws(()=>E.work(s,A(2,0,0)));assert.throws(()=>E.work(s,A(0,0,1)));});
check('Exact deadline07 has no overtime;08 costs600 once',()=>{const at7=E.outcome(run([A(),...efficient])),at8=E.outcome(run([A(),A(),...efficient]));assert.equal(at7.readyHour,7);assert.equal(at7.onTime,true);assert.equal(at7.contribution,5000);assert.equal(at7.buffer,0);assert.equal(at8.readyHour,8);assert.equal(at8.onTime,false);assert.equal(at8.overtimeCost,600);assert.equal(at8.contribution,4400);});
check('Poor sequencing: ready10, contribution3200',()=>{const s=run([A(1,0,2),A(1,0,2),A(2,0,0),...Array(6).fill(A(0,1,0))]);const o=E.outcome(s);assert.equal(s.hour,10);assert.equal(o.overtimeHours,3);assert.equal(o.contribution,3200);});
check('Stretch workload: earliest reference plan ready07, contribution5000',()=>{const s=run([...efficient,A(0,2,0)],'stretch');assert.equal(s.hour,7);assert.equal(E.outcome(s).onTime,true);assert.equal(E.outcome(s).contribution,5000);assert.equal(s.done.floor,8);});
check('Noon cap distinguishes unready from a completed noon sign-off',()=>{let stopped=E.create();for(let i=0;i<12;i++)stopped=E.work(stopped,A());const o=E.outcome(stopped);assert.equal(stopped.phase,'stopped');assert.equal(o.ready,false);assert.equal(o.contribution,2000);assert.equal(o.overtimeCost,3000);assert.throws(()=>E.work(stopped,A()));const ready=run([...Array(6).fill(A()),...efficient]);assert.equal(ready.hour,12);assert.equal(E.outcome(ready).ready,true);assert.equal(E.outcome(ready).contribution,2000);assert.equal(E.isValidState(stopped),true);});
check('Saved states are replay-validated; tampered progress does not resume',()=>{const s=run(efficient);const restored=JSON.parse(JSON.stringify(s));assert.equal(E.isValidState(restored),true);restored.done.floor=5;assert.equal(E.isValidState(restored),false);assert.equal(E.isValidState({mode:'standard',phase:'complete',hour:6,done:s.done,log:[],inspectionComplete:true}),false);});
check('Actions do not mutate previous state or allocation',()=>{const s=E.create(),a=A(2,0,1),snapshot=JSON.stringify(s);const n=E.work(s,a);assert.equal(JSON.stringify(s),snapshot);a.loadout=0;assert.equal(n.log[0].allocation.loadout,2);});
/** Exhaustive reachable-state search verifies the optimum and sequencing diversity.
 * Deduplicate by elapsed hour and progress; history has no model effect. */
function search(mode){let frontier=[E.create(mode)],best=Infinity,completionTimes=new Set(),states=0;for(let layer=0;layer<=8;layer++){const next=new Map();for(const s of frontier){states++;if(s.phase==='inspection'){const complete=E.inspect(s);best=Math.min(best,complete.hour);completionTimes.add(complete.hour);continue;}if(s.phase!=='work')continue;for(let l=0;l<=2;l++)for(let f=0;f<=2;f++)for(let r=0;r<=2;r++){const a=A(l,f,r);if(E.validateAllocation(s,a))continue;const n=E.work(s,a);const key=[n.hour,n.done.loadout,n.done.floor,n.done.reset,n.phase].join(',');if(!next.has(key))next.set(key,n);}}frontier=[...next.values()];}return {best,completionTimes,states};}
check('Exhaustive search matches independent critical-chain lower bounds',()=>{const baseline=search('standard'),stretch=search('stretch');const lowerBaseline=Math.max(Math.ceil(14/3),Math.ceil(4/2)+Math.ceil(6/2))+1;const lowerStretch=Math.max(Math.ceil(16/3),Math.ceil(4/2)+Math.ceil(8/2))+1;assert.equal(baseline.best,lowerBaseline);assert.equal(stretch.best,lowerStretch);assert.equal(baseline.best,6);assert.equal(stretch.best,7);assert.ok(baseline.completionTimes.has(7),'An on-time alternative with no buffer must exist');console.log('  searched '+baseline.states+' baseline states and '+stretch.states+' stretch states');});
check('Self-contained HTML: no remote assets, imports, analytics or fetch calls',()=>{assert.equal(/<(?:script|img|link)[^>]+(?:src|href)\s*=\s*["']https?:/i.test(html),false);assert.equal(/\b(?:fetch|XMLHttpRequest|WebSocket)\s*\(/.test(html),false);assert.equal(/@import\s/.test(html),false);for(const match of html.matchAll(/<script[^>]*>([\s\S]*?)<\/script>/g))new vm.Script(match[1]);});
console.log('\n'+checks+' model and packaging checks passed.');
