import test from 'node:test';
import assert from 'node:assert/strict';
import { freshPlan, normalizePlan, totals, readiness, proposalText } from '../model.mjs';

const complete = () => ({...freshPlan(), eventName:'Welcome to Play', audience:'New student gamers', purpose:'Help newcomers meet people.',format:'beginner',experience:'Try short games, then meet the next group in the social area.',venue:'lounge',venueReason:'Twenty PCs reduce waiting; fewer funds remain for extras.',extras:['coach','prizes'],operations:'One organizer welcomes, one manages timing, one supports the social area. If a PC fails, the technician fixes it while the organizer offers another activity.',success:'24 of 30 report meeting two people on an exit card.'});
test('both venues have defensible budgets; overspending is visible',()=>{assert.equal(totals(complete()).total,1000);assert.equal(totals({...complete(),extras:['coach','prizes','refreshments']}).remaining,-100);assert.equal(totals({...complete(),venue:'campus',extras:['coach','prizes','refreshments']}).total,800);assert.equal(totals({...complete(),venue:'campus',extras:[]}).remaining,650);});
test('every optional purchase combination is added once',()=>{for(const venue of ['lounge','campus'])for(let mask=0;mask<8;mask++){const keys=['coach','prizes','refreshments'].filter((_,i)=>mask&(1<<i));const expected=(venue==='lounge'?650:350)+keys.reduce((n,k)=>n+({coach:150,prizes:200,refreshments:100}[k]),0);assert.equal(totals({...freshPlan(),venue,extras:keys}).total,expected);}assert.equal(totals({...complete(),extras:['coach','coach']}).extrasCost,150);});
test('schedule requires positive whole-minute blocks totaling120',()=>{assert.equal(totals(freshPlan()).validSchedule,true);for(const n of [0,-1,1.5,'',Infinity,NaN])assert.equal(totals({...freshPlan(),mainMinutes:n}).validSchedule,false);assert.equal(totals({...freshPlan(),mainMinutes:100}).validSchedule,false);assert.equal(totals({...freshPlan(),openingMinutes:20,mainMinutes:80,closingMinutes:20}).validSchedule,true);});
test('readiness checks fields and arithmetic without assigning a grade',()=>{assert.equal(readiness(freshPlan()).complete,false);assert.equal(readiness(complete()).complete,true);assert.equal(readiness({...complete(),extras:['coach','prizes','refreshments']}).complete,false);assert.equal(readiness({...complete(),success:''}).complete,false);assert.equal(readiness({...complete(),updateResponse:''}).complete,true);});
test('restored plans discard invalid choices and deduplicate costs',()=>{const p=normalizePlan({venue:'__proto__',format:'unknown',extras:['coach','coach','unknown'],podName:12,purpose:'Keep this',mainMinutes:''});assert.equal(p.venue,'');assert.equal(p.format,'');assert.deepEqual(p.extras,['coach']);assert.equal(p.podName,'');assert.equal(p.purpose,'Keep this');assert.equal(p.mainMinutes,'');assert.deepEqual(normalizePlan(null),freshPlan());});
test('export contains the actual plan and distinguishes an incomplete draft',()=>{const p=complete();const t=proposalText(p);assert.match(t,/Total planned spending: \$1000/);assert.match(t,/24 of 30/);assert.match(t,/not sent to an instructor/);assert.doesNotMatch(t,/DRAFT —/);assert.match(proposalText(freshPlan()),/DRAFT —/);assert.match(proposalText({...p,updateResponse:'Combine welcome and timing.'}),/Combine welcome and timing/);});
