'use strict';
(() => {
const ENDPOINT='https://havsvkhddvdbzbsmhqbr.supabase.co/functions/v1/spm370-llc2';
const STORE='spm370_llc2_attempt_v2';
const questions=[
['Copyright basics','The saved poster','A student designer creates an original tournament poster and saves the file to her laptop.','When does copyright protection generally begin?',['Only after the work is registered with the U.S. Copyright Office','When the original work is fixed in the saved file','Only after the poster is sold or publicly displayed','Only after the creator places a copyright notice on it']],
['Ideas and expression','The shared mechanic','Two competitive games both use teams fighting to capture control points.','What would copyright most clearly protect?',['The general idea of teams capturing control points','The concept of assigning players different strategic roles','Specific character artwork, animations, music, and code','The basic rules needed to play the game']],
['Ownership','The team designer','A team employee creates original promotional graphics within her assigned job duties. No agreement changes the usual ownership rule.','Who generally owns that employee-created expression?',['The employer under the work-made-for-hire rule','The employee in every situation because she physically created it','The players promoted by the team','The streaming platform that later hosts the graphics']],
['Exclusive rights','The live match','A tournament streams moving gameplay live to an online audience.','Which exclusive copyright right most directly concerns presenting those moving images?',['Distribution','Public display','Public performance','Digital audio performance of sound recordings']],
['Permission','The walk-on song','A publisher permits the tournament to stream its game. The production team wants to add a popular commercial song to the broadcast.','Which statement should guide the organizer?',['Permission to stream the game automatically includes any commercial music','Game-stream permission does not automatically clear third-party music','Music never raises copyright issues when used during esports','Buying a personal music subscription automatically clears broadcast use']],
['DMCA','The removed video','A platform removes a creator’s archived match video after receiving a copyright notice.','What does the platform’s removal itself establish?',['A court has conclusively found the creator liable for infringement','The creator has automatically lost all fair-use arguments','The copyright owner has automatically won statutory damages','It is a platform action under notice and takedown, not a court judgment']],
['DMCA','The locked gate','A modding tool bypasses an effective technological access control on a game.','Which legal framework specifically addresses that bypass?',['The DMCA anti-circumvention rules','The copyright registration process','The copyright joint-authorship rules','The DMCA notice-and-takedown process']],
['Fair use','The highlight market','An analysis show uses match clips. You are specifically concerned viewers may use the show instead of obtaining the publisher’s official highlights.','Which fair-use factor does that concern most directly address?',['Purpose and character of the use','Nature of the copyrighted work','Effect on the market for the original or a relevant licensing market','Amount and substantiality used']]
];
const $=id=>document.getElementById(id);
let saved=null,state=null,busy=false,selected=null,activeQuestion=0,sound=false,audio;
let calm=matchMedia('(prefers-reduced-motion: reduce)').matches;
function notice(text){$('message').textContent=text;$('message').hidden=!text;}
function write(){try{localStorage.setItem(STORE,JSON.stringify(saved));return true;}catch{notice('This browser is blocking local saving. Use a normal browser window before starting so your attempt can be resumed.');return false;}}
function screens(name){['intro','play','finish'].forEach(id=>$(id).hidden=id!==name);}
function tone(){if(!sound||calm)return;try{audio=audio||new(window.AudioContext||window.webkitAudioContext)();audio.resume();[392,494,587].forEach((f,i)=>{const o=audio.createOscillator(),g=audio.createGain(),t=audio.currentTime+i*.11;o.type='triangle';o.frequency.value=f;g.gain.setValueAtTime(.035,t);g.gain.exponentialRampToValueAtTime(.001,t+.15);o.connect(g);g.connect(audio.destination);o.start(t);o.stop(t+.16);});}catch{}}
function wagon(animate=false){const score=state?.score||0;$('rig').style.transform=`translate(${20+score*85}px,137px)`;$('wagonScore').textContent=`WAGON POINTS ${score} / 8`;
if(animate){$('rig').classList.remove('travel');void $('rig').getBoundingClientRect();$('rig').classList.add('travel');tone();setTimeout(()=>$('rig').classList.remove('travel'),1500);}}
function setMotion(){document.body.classList.toggle('calm',calm);$('motion').textContent=calm?'Motion off':'Motion on';$('motion').setAttribute('aria-pressed',String(calm));}
$('motion').onclick=()=>{calm=!calm;setMotion();};setMotion();
$('sound').onclick=()=>{sound=!sound;$('sound').textContent=sound?'Sound on':'Sound off';$('sound').setAttribute('aria-pressed',String(sound));};
$('plain').onclick=()=>{const off=$('scene').classList.toggle('hidden-scene');$('plain').textContent=off?'Show scenery':'Text view';$('plain').setAttribute('aria-pressed',String(off));};
async function api(body){const controller=new AbortController(),timer=setTimeout(()=>controller.abort(),18000);try{const r=await fetch(ENDPOINT,{method:'POST',cache:'no-store',headers:{'Content-Type':'application/json'},body:JSON.stringify(body),signal:controller.signal});let d;try{d=await r.json();}catch{throw new Error('The server did not return a confirmation. Resume your saved attempt.');}if(!r.ok){const e=new Error(d.error||'Could not confirm this request.');e.code=d.code;e.status=r.status;throw e;}return d;}finally{clearTimeout(timer);}}
function accept(d){if(!d.ok||!Array.isArray(d.responses)||d.answered!==d.responses.length||!Number.isInteger(d.score)||d.score<0||d.score>8)throw new Error('The server response could not be verified. Resume your saved attempt.');state=d;}
function render(){notice('');if(state.complete){finish();return;}screens('play');activeQuestion=state.answered+1;selected=null;const q=questions[state.answered];if(!q){notice('Please resume your saved attempt to confirm completion.');return;}
$('qProgress').textContent=`QUESTION ${activeQuestion} OF 8`;$('points').textContent=`POINTS ${state.score} / 8`;$('progress').replaceChildren(...questions.map((_,i)=>{const n=document.createElement('span');n.className=i<state.answered?'done':'';return n;}));
$('topic').textContent=q[0];$('title').textContent=q[1];$('scenario').textContent=q[2];$('question').textContent=q[3];$('options').replaceChildren();
q[4].forEach((text,i)=>{const label=document.createElement('label');label.className='option';const radio=document.createElement('input');radio.type='radio';radio.name='choice';radio.value=i;radio.onchange=()=>{selected=i;$('lock').disabled=false;};const letter=document.createElement('span');letter.className='letter';letter.textContent=String.fromCharCode(65+i);const span=document.createElement('span');span.textContent=text;label.append(radio,letter,span);$('options').append(label);});
$('choices').disabled=false;$('lock').hidden=false;$('lock').disabled=true;$('lock').textContent='Lock answer';$('feedback').hidden=true;$('retry').hidden=true;$('saveStatus').textContent='You can change your choice until you lock it.';wagon();$('title').focus({preventScroll:true});}
function finish(){screens('finish');wagon();$('finishName').textContent=`${state.firstName} ${state.lastName} · ${state.email}`;$('finalScore').textContent=`${state.score} / 8`;
if(!state.receipt){notice('Your server response did not include a receipt. Please resume to confirm submission.');return;}
$('receipt').textContent=state.receipt;$('submitted').textContent='Server confirmed '+new Date(state.submittedAt).toLocaleString();$('copy').textContent='Copy receipt';saved.pending=null;saved.identity=null;write();}
async function resume(){if(busy||!saved?.token)return;busy=true;$('resume').disabled=true;notice('Checking your saved progress…');try{let d;try{d=await api({action:'resume',attemptToken:saved.token});}catch(e){if(e.code==='INVALID_ATTEMPT'&&saved.identity){d=await api({action:'start',attemptToken:saved.token,...saved.identity});}else throw e;}accept(d);saved.identity=null;
if(saved.pending && saved.pending.questionNumber<=state.answered)saved.pending=null;write();busy=false;render();if(saved.pending && !state.complete)await sendAnswer(saved.pending);
}catch(e){notice(e.name==='AbortError'?'The connection timed out. Your resume token has been kept. Try Resume saved attempt again.':e.message);$('resume').hidden=false;}finally{busy=false;$('resume').disabled=false;}}
$('resume').onclick=resume;
$('identity').onsubmit=async e=>{e.preventDefault();if(busy)return;const identity={firstName:$('first').value.trim(),lastName:$('last').value.trim(),email:$('email').value.trim().toLowerCase()};if(!identity.firstName||!identity.lastName||!$('honor').checked){notice('Enter your first and last name and confirm the individual-work statement.');return;}if(!/^[^\s@]+@lasalle\.edu$/i.test(identity.email)){notice('Please use your La Salle email ending in @lasalle.edu.');return;}
if(saved?.token){notice('A saved attempt is already associated with this browser. Use Resume saved attempt.');$('resume').hidden=false;return;}
saved={token:Array.from(crypto.getRandomValues(new Uint8Array(24)),b=>b.toString(16).padStart(2,'0')).join(''),identity,pending:null};if(!write()){saved=null;return;}busy=true;$('begin').disabled=true;notice('Creating your private attempt…');
try{accept(await api({action:'start',attemptToken:saved.token,...identity}));saved.identity=null;write();render();}catch(error){if(error.status===400||error.code==='EXISTING_ATTEMPT'){localStorage.removeItem(STORE);saved=null;}notice(error.name==='AbortError'?'The connection timed out. Use Resume saved attempt; do not start over.':error.message);$('resume').hidden=false;}finally{busy=false;$('begin').disabled=false;}};
async function sendAnswer(pending){if(busy)return;busy=true;saved.pending=pending;write();$('choices').disabled=true;$('lock').disabled=true;$('lock').textContent='Saving…';$('retry').hidden=true;notice('');
try{const prior=state.score;const d=await api({action:'answer',attemptToken:saved.token,...pending});accept(d);saved.pending=null;write();wagon(state.score>prior);$('points').textContent=`POINTS ${state.score} / 8`;$('lock').hidden=true;$('saveStatus').textContent=`Saved to your instructor · ${state.answered} of 8 answered`;
$('feedback').className='feedback'+(d.correct?'':' miss');$('feedbackTitle').textContent=d.correct?'One point. Wagon rolling!':'Answer saved. Keep going.';$('feedbackText').textContent=d.correct?'Your wagon advanced one trail segment.':'No point this time. There is no extra penalty, and you can still complete every question.';$('next').textContent=state.complete?'View saved score':'Next question';$('feedback').hidden=false;$('next').focus({preventScroll:true});
}catch(e){notice(e.name==='AbortError'?'The connection timed out before confirmation. Your answer may already be saved. Retry below; it cannot count twice.':e.message);$('retry').hidden=false;$('saveStatus').textContent='Waiting for server confirmation. Your selected answer is kept.';}finally{busy=false;}}
$('lock').onclick=()=>{if(selected!==null&&!busy)sendAnswer({questionNumber:activeQuestion,answerIndex:selected});};$('retry').onclick=()=>saved.pending&&sendAnswer(saved.pending);$('next').onclick=()=>{if(!busy)render();};
$('copy').onclick=async()=>{const text=`SPM 370 Legal Literacy Check 2\n${state.firstName} ${state.lastName}\n${state.email}\nScore: ${state.score}/8\nReceipt: ${state.receipt}`;try{await navigator.clipboard.writeText(text);$('copy').textContent='Receipt copied';}catch{notice('Select and copy the receipt displayed above.');}};
$('forget').onclick=()=>{if(confirm('Remove only this browser’s resume token? Your official score stays saved with your instructor.')){localStorage.removeItem(STORE);location.reload();}};
try{saved=JSON.parse(localStorage.getItem(STORE)||'null');}catch{}
const incoming=new URLSearchParams(location.hash.slice(1)).get('resume');if(incoming&&/^[a-f0-9]{48}$/i.test(incoming)){saved={token:incoming,pending:null};write();history.replaceState(null,'',location.pathname+location.search);}
if(saved?.token){$('resume').hidden=false;resume();}
})();
