import test from 'node:test';
import assert from 'node:assert/strict';
import {randomUUID} from 'node:crypto';
import {createHandler,sha256} from './server.mjs';
import {validateSubmission,validateGrade,requestFingerprintInput} from './validation.mjs';
import model from './model.mjs';

const NOW='2026-10-01T19:15:00.000Z';
const KEY='synthetic-review-key-never-used-in-production';
const valid=()=>({action:'submit',attemptId:randomUUID(),firstName:'Synthetic',lastName:'Review',email:'qa-'+randomUUID()+'@example.com',version:'1.2.0',sourceVersion:'1.1.1',choices:['event','boundary','original','collab','human','scoped'],checks:['permissions','new-agreement'],reflections:['Our first choice reserved the personal stream rights.','I would negotiate explicit duration and approved future uses.'],completedAt:NOW});
const fields=(row,columns)=>Object.fromEntries(columns.split(',').map(k=>[k,row[k]]));
function fakeDB(){
 const rows=[];const calls=[];const buckets=new Map();let rateFailure=false,insertFailure=false,selectFailure=false;
 function from(table){calls.push(['from',table]);assert.equal(table,'spm370_offscript_submissions');let operation='select',projection='*',body,filters=[],sort;
  const q={select(c){projection=c;return q;},eq(k,v){filters.push([k,v]);return q;},order(k,opts){sort=[k,opts];return q;},limit(n){return execute('many',n);},insert(v){operation='insert';body=v;return q;},update(v){operation='update';body=v;return q;},maybeSingle(){return execute('maybe');},single(){return execute('single');}};
  async function execute(kind,n){calls.push([operation,{projection,body,filters}]);
   if(operation==='select'&&selectFailure)return{data:null,error:{message:'SQL error including sensitive content'}};
   if(operation==='insert'){
    if(insertFailure)return{data:null,error:{code:'XX000',message:'private db error'}};
    if(rows.some(r=>r.attempt_id===body.attempt_id||r.email===body.email))return {data:null,error:{code:'23505',message:'private index detail'}};
    const row={id:randomUUID(),max_score:10,review_status:'PENDING_REVIEW',grade_override:null,grader_notes:null,...body,score:body.completion_score+body.concept_score};rows.push(row);return{data:fields(row,projection),error:null};
   }
   let match=rows.filter(r=>filters.every(([k,v])=>r[k]===v));
   if(operation==='update')match.forEach(r=>Object.assign(r,body));
   if(sort)match.sort((a,b)=>a[sort[0]]>b[sort[0]]?-1:1);
   const output=match.slice(0,n).map(r=>fields(r,projection));return {data:kind==='many'?output:output[0]??null,error:null};
  }
  return q;
 }
 return {rows,calls,from,buckets,setRateFailure(v){rateFailure=v;},setInsertFailure(v){insertFailure=v;},setSelectFailure(v){selectFailure=v;},async rpc(name,args){calls.push(['rpc',name,args]);assert.equal(name,'spm370_offscript_check_rate');assert.match(args.p_bucket,/^[a-f0-9]{64}$/);if(rateFailure)return{data:null,error:{message:'private failure'}};const n=(buckets.get(args.p_bucket)||0)+1;buckets.set(args.p_bucket,n);return{data:n<=args.p_limit,error:null};}};
}
async function setup(){const db=fakeDB();let factories=0;const handler=createHandler({db:()=>{factories++;return db;},instructorKeyHash:await sha256(KEY),rateSecret:'synthetic-rate-secret',clock:()=>new Date(NOW)});return{db,handler,get factories(){return factories;}};}
function request(body,opts={}){const {method='POST',path='',origin='https://jflevine.github.io',key,contentType='application/json',headers={}}=opts;return new Request('https://example.invalid/functions/v1/spm370-offscript'+path,{method,headers:{...(origin!==null?{origin}:{}),...(contentType!==null?{'content-type':contentType}:{}),...(key?{'x-instructor-key':key}:{}),...headers},...(!['GET','HEAD'].includes(method)?{body:typeof body==='string'?body:JSON.stringify(body)}:{})});}
async function json(handler,body,opts){const res=await handler(request(body,opts));return{res,data:await res.json()};}

test('all 729 valid stories accepted; score independent of management path',()=>{let count=0;function walk(s){if(s.step===6){const v=validateSubmission({...valid(),choices:s.history.map(h=>h.option)});assert.equal(v.completion_score,6);assert.equal(v.concept_score,4);assert.equal(v.ending_id,model.ending(s).id);count++;return;}for(const o of model.scene(s).options)walk(model.choose(s,o.id));}walk(model.initial());assert.equal(count,729);});
test('branch-invalid and incomplete decisions rejected',()=>{for(const choices of [[],['event'],['event','waiver','original','space','human','scoped'],['event','boundary','original','space','preview','extend'],['event','boundary','original','space','human','reset']])assert.throws(()=>validateSubmission({...valid(),choices}));});
test('score comes solely from server answer key and completion',()=>{for(const [checks,score] of [[['permissions','new-agreement'],4],[['identity','new-agreement'],2],[['permissions','money'],2],[['ownership','label'],0]]){const v=validateSubmission({...valid(),checks,score:10,completion_score:10,concept_score:4,grade_override:10,review_status:'REVIEWED'});assert.equal(v.concept_score,score);assert.equal(v.completion_score,6);assert.equal(v.grade_override,undefined);assert.equal(v.review_status,undefined);}});
test('malformed bodies, identifiers, names, email, checks, reflections and versions rejected',()=>{for(const body of [null,[],true,'x',{}, {...valid(),action:'grade'},{...valid(),attemptId:'not-a-uuid'},{...valid(),attemptId:'00000000-0000-0000-0000-000000000000'},{...valid(),firstName:'\n'},{...valid(),lastName:'a\u0000b'},{...valid(),email:'a@b'},{...valid(),email:'a\nb@example.com'},{...valid(),checks:['permissions','bogus']},{...valid(),checks:[true,1]},{...valid(),reflections:['short','Short again']},{...valid(),reflections:['x'.repeat(3001),'long enough legitimate reflection']},{...valid(),version:'1.1.1'},{...valid(),sourceVersion:'2.0.0'},{...valid(),completedAt:'invalid'}])assert.throws(()=>validateSubmission(body));});
test('name/email normalization and timestamp-invariant retry fingerprint',()=>{const b=valid(),v=validateSubmission({...b,attemptId:b.attemptId.toUpperCase(),firstName:' José ',email:b.email.toUpperCase()});assert.equal(v.first_name,'José');assert.equal(v.email,b.email);assert.equal(v.attempt_id,b.attemptId);const first=validateSubmission(b),second=validateSubmission({...b,completedAt:'2026-10-01T19:16:00Z'});assert.equal(requestFingerprintInput(first),requestFingerprintInput(second));});
test('strict grade schema never accepts coercion or out-of-range values',()=>{const id=randomUUID();for(const grade of ['10',null,true,10.1,-1,11,Infinity,NaN])assert.throws(()=>validateGrade({action:'grade',id,grade}));assert.equal(validateGrade({action:'grade',id,grade:0}).grade_override,0);assert.throws(()=>validateGrade({action:'grade',id,grade:1,notes:'x'.repeat(2001)}));});
test('public GET reveals metadata only; no database operation',async()=>{const s=await setup();const {res,data}=await json(s.handler,null,{method:'GET'});assert.equal(res.status,200);assert.equal(data.identity,'self-reported');assert.equal(data.maxScore,10);assert.equal(s.factories,0);for(const key of ['submissions','email','receipt','score'])assert.equal(data[key],undefined);});
test('instructor authentication fails closed before any DB access',async()=>{for(const method of ['GET','POST'])for(const key of [undefined,'incorrect','x'.repeat(201)]){const s=await setup();const {res,data}=await json(s.handler,{action:'grade',id:randomUUID(),grade:10},{method,path:'/instructor',key});assert.equal(res.status,401);assert.equal(s.factories,0);assert.equal(data.code,'UNAUTHORIZED');}});
test('unknown routes, disallowed origins and methods fail before database access',async()=>{for(const [opts,status] of [[{path:'/instructor/foo'},404],[{path:'/evil/instructor'},404],[{path:'/instructor%2f'},404],[{path:'/anything'},404],[{origin:'https://attacker.invalid'},403],[{method:'DELETE'},405],[{method:'PATCH'},405]]){const s=await setup();const {res}=await json(s.handler,valid(),opts);assert.equal(res.status,status);assert.equal(s.factories,0);}});
test('allowed preflight works without auth or DB; attacker preflight denied',async()=>{const s=await setup();const res=await s.handler(request(null,{method:'OPTIONS',path:'/instructor'}));assert.equal(res.status,204);assert.equal(res.headers.get('access-control-allow-origin'),'https://jflevine.github.io');assert.equal(s.factories,0);const denied=await s.handler(request(null,{method:'OPTIONS',origin:'https://attacker.invalid'}));assert.equal(denied.status,403);});
test('successful submit returns narrow private receipt and only generated 10 point score',async()=>{const s=await setup(),b=valid();const {res,data}=await json(s.handler,b);assert.equal(res.status,201);assert.equal(data.score,10);assert.equal(data.maxScore,10);assert.equal(data.submittedAt,NOW);assert.match(data.receipt,/^SPM370-LDL2-/);assert.equal(s.db.rows.length,1);assert.equal(s.db.rows[0].first_name,b.firstName);assert.equal(s.db.rows[0].email,b.email);assert.deepEqual(Object.keys(data).sort(),['ok','receipt','submittedAt','score','maxScore','completionScore','conceptScore','reviewStatus','status','replayed'].sort());assert.equal(res.headers.get('cache-control'),'no-store');assert.equal(res.headers.get('x-content-type-options'),'nosniff');});
test('sequential and simultaneous same-key retries produce one row and receipt',async()=>{const s=await setup(),b=valid();const results=await Promise.all(Array.from({length:6},()=>json(s.handler,b)));assert.equal(s.db.rows.length,1);assert.equal(new Set(results.map(r=>r.data.receipt)).size,1);assert.ok(results.every(r=>[200,201].includes(r.res.status)));const replay=await json(s.handler,{...b,completedAt:'2026-10-01T19:20:00Z'});assert.equal(replay.res.status,200);assert.equal(replay.data.replayed,true);});
test('changed work cannot mutate original attempt or retrieve its data',async()=>{const s=await setup(),b=valid();const first=await json(s.handler,b);const next=await json(s.handler,{...b,checks:['identity','label']});assert.equal(next.res.status,409);assert.equal(next.data.code,'ATTEMPT_CONFLICT');assert.equal(s.db.rows.length,1);assert.equal(s.db.rows[0].score,10);assert.equal(next.data.receipt,undefined);assert.equal(next.data.email,undefined);});
test('different key with same email yields safe conflict without original receipt',async()=>{const s=await setup(),b=valid();await json(s.handler,b);const {res,data}=await json(s.handler,{...b,attemptId:randomUUID()});assert.equal(res.status,409);assert.equal(data.code,'EMAIL_ALREADY_SUBMITTED');assert.equal(data.receipt,undefined);assert.equal(data.score,undefined);assert.equal(s.db.rows.length,1);});
test('JSON content type, malformed JSON, UTF-8 and byte-size limits',async()=>{const s=await setup();for(const [body,opts,status] of [['{',{},400],[valid(),{contentType:'text/plain'},415],[' '.repeat(32001),{},413],['é'.repeat(16001),{},413],[valid(),{headers:{'content-length':'32001'}},413]]){const {res}=await json(s.handler,body,opts);assert.equal(res.status,status);}const req=new Request('https://example.invalid/functions/v1/spm370-offscript',{method:'POST',headers:{'content-type':'application/json'},body:new Uint8Array([0xff,0xfe,0x7b])});assert.equal((await s.handler(req)).status,400);assert.equal(s.db.rows.length,0);});
test('rate failure and database errors fail safely with no sensitive details',async()=>{for(const kind of ['setRateFailure','setInsertFailure','setSelectFailure']){const s=await setup();s.db[kind](true);const {res,data}=await json(s.handler,valid());assert.equal(res.status,500);assert.equal(data.code,'SERVER_ERROR');assert.doesNotMatch(JSON.stringify(data),/SQL|private|password|service_role/);assert.equal(s.db.rows.length,0);}});
test('email retry rate limit returns 429 and no duplicate rows',async()=>{const s=await setup(),b=valid();for(let i=0;i<20;i++)assert.ok([200,201].includes((await json(s.handler,b)).res.status));const {res,data}=await json(s.handler,b);assert.equal(res.status,429);assert.equal(data.code,'RATE_LIMITED');assert.equal(s.db.rows.length,1);});
test('authorized list projects no attempt secrets, authorized grade preserves original score',async()=>{const s=await setup(),b=valid();await json(s.handler,b);const listing=await json(s.handler,null,{method:'GET',path:'/instructor',key:KEY});assert.equal(listing.res.status,200);assert.equal(listing.data.submissions.length,1);const row=listing.data.submissions[0];assert.equal(row.email,b.email);assert.equal(row.request_hash,undefined);assert.equal(row.attempt_id,undefined);const grading=await json(s.handler,{action:'grade',id:row.id,grade:8,notes:'Synthetic review only'},{path:'/instructor',key:KEY});assert.equal(grading.res.status,200);assert.equal(s.db.rows[0].grade_override,8);assert.equal(s.db.rows[0].score,10);assert.equal(s.db.rows[0].review_status,'REVIEWED');});
test('authorized malformed grade is 400; nonexistent submission is 404',async()=>{const s=await setup();const invalid=await json(s.handler,{action:'grade',id:randomUUID(),grade:'10'},{path:'/instructor',key:KEY});assert.equal(invalid.res.status,400);const missing=await json(s.handler,{action:'grade',id:randomUUID(),grade:10},{path:'/instructor',key:KEY});assert.equal(missing.res.status,404);});
