(function () {
  'use strict';
  const M=window.HypeModel;
  const KEY='spm343-build-the-hype-v1';
  const $=s=>document.querySelector(s);
  const esc=value=>String(value).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
  const symbols={
    trophy:'<path d="M7 3h10v6a5 5 0 0 1-10 0V3Zm0 2H3v3a4 4 0 0 0 4 4m10-7h4v3a4 4 0 0 1-4 4M12 14v6m-5 1h10"/>',
    controller:'<path d="M7 7h10l4 11-3 2-4-4h-4l-4 4-3-2 4-11Z"/><path d="M8 9v5m-2.5-2.5h5M16 10h.1M18 13h.1"/>',
    spark:'<path d="m12 2 2.5 7.5L22 12l-7.5 2.5L12 22l-2.5-7.5L2 12l7.5-2.5L12 2Z"/>',
    bracket:'<path d="M3 3h5v5H3m0 8h5v5H3m5-16h7v14H8m7-7h6"/>',
    grid:'<rect x="3" y="3" width="7" height="7" rx="1"/><rect x="14" y="3" width="7" height="7" rx="1"/><rect x="3" y="14" width="7" height="7" rx="1"/><rect x="14" y="14" width="7" height="7" rx="1"/>',
    loop:'<path d="M20 8a8 8 0 0 0-14-3L3 8m0-5v5h5m-4 8a8 8 0 0 0 14 3l3-3m0 5v-5h-5"/>',
    star:'<path d="m12 2 3 6 7 1-5 5 1 7-6-3-6 3 1-7-5-5 7-1Z"/>',
    mic:'<rect x="8" y="2" width="8" height="13" rx="4"/><path d="M5 10v2a7 7 0 0 0 14 0v-2m-7 9v3m-4 0h8"/>',
    flag:'<path d="M5 22V3c5-4 9 4 15 0v10c-6 4-10-4-15 0"/>',
    chat:'<path d="M21 11a9 9 0 0 1-9 9H4l-2 2v-11a9 9 0 0 1 19 0Z"/><path d="M7 9h10M7 13h6"/>',
    clock:'<circle cx="12" cy="12" r="9"/><path d="M12 6v6l4 3"/>',
    crowd:'<circle cx="12" cy="6" r="3"/><path d="M6 21v-5a6 6 0 0 1 12 0v5M4 7a3 3 0 0 0 0 6m-1 3-1 5m18-14a3 3 0 0 1 0 6m1 3 1 5"/>',
    ticket:'<path d="M3 5h18v5a2 2 0 0 0 0 4v5H3v-5a2 2 0 0 0 0-4V5Z"/><path d="M15 5v3m0 3v2m0 3v3"/>',
    arrow:'<path d="M4 12h16m-6-6 6 6-6 6"/>'
  };
  const icon=id=>`<span class="icon" aria-hidden="true"><svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.7" stroke-linecap="round" stroke-linejoin="round">${symbols[id]||symbols.spark}</svg></span>`;
  let state=M.fresh(),storageOK=true,message='';
  try {const saved=localStorage.getItem(KEY); if(saved) state=M.restore(JSON.parse(saved));}
  catch {storageOK=false;}
  function storageNotice(text) {const el=$('#storage-notice');el.hidden=false;el.textContent=text;}
  if(!storageOK) storageNotice('Browser saving is unavailable or the saved plan could not be read. You can still play. Keep this tab open and export your recap before leaving.');
  function save() {
    try {localStorage.setItem(KEY,JSON.stringify(state));storageOK=true;}
    catch {storageOK=false;storageNotice('Your browser could not save this plan. Keep this tab open and download or print your recap before leaving.');}
  }
  function announce(text){$('#announcer').textContent='';setTimeout(()=>{$('#announcer').textContent=text;},20);}
  function go(step,{replace=false,focus=true}={}) {
    if(step===4 && state.mission && state.format) state.featuresConfirmed=true;
    state.step=Math.min(Math.max(0,step),M.maxStep(state));message='';save();
    if(replace) history.replaceState(null,'',`#${state.step}`);else if(location.hash!==`#${state.step}`) history.pushState(null,'',`#${state.step}`);
    render();if(focus){$('#screen').focus();window.scrollTo({top:0,behavior:'instant'});}
  }
  function mutate(patch,focusSelector) {state={...state,...patch,featuresConfirmed:false,adjustment:''};save();render();if(focusSelector)$(focusSelector)?.focus();}
  function chosen(list,id){return M.find(list,id);}
  function title(){return state.name.trim()||chosen(M.MISSIONS,state.mission)?.title||'Your next big night';}
  function controls(nextLabel,nextStep,ready=true) {return `<div class="button-row">${state.step?'<button type="button" class="back" id="back">← Back</button>':''}<button type="button" class="primary" id="next" data-step="${nextStep}" ${ready?'':'disabled'}>${nextLabel}<span aria-hidden="true">→</span></button></div>`;}
  function choice(item,kind,selected,extra='') {return `<button type="button" class="choice" data-${kind}="${item.id}" aria-pressed="${selected}">${icon(item.icon)}<span class="choice-copy"><strong>${esc(item.label)}</strong><span class="short">${esc(item.short||item.audience)}</span>${selected&&item.detail?`<span class="detail">${esc(item.detail)}</span>`:''}${extra}</span>${selected?'<span class="check" aria-hidden="true">✓</span>':''}</button>`;}
  function welcome(){return `<div class="reveal"><p class="eyebrow">YOUR CAMPUS. YOUR CROWD. YOUR CALL.</p><h1 id="screen-title" class="welcome-title">Build an event.<br><em>Make it matter.</em></h1><p class="lede">You’re the campus esports organizer. You’ve got a room, a crew, and one afternoon to turn players and fans into a community.</p><span class="inline-tag">12–15 minutes</span><span class="inline-tag">One device</span><span class="inline-tag">Many ways to make it work</span><div class="brief"><p><strong>Already covered:</strong> the student center, game permissions, equipment, core officials, check-in, safety, and accessibility support. A backup host, activity guides, and a warm-up station are also on standby.</p><p><strong>Your job:</strong> choose a purpose, a format, and a few features people will care about. Then handle opening day.</p></div><span class="field-label">How are you playing?</span><div class="mode-pick" role="group" aria-label="Solo or pair"><button type="button" class="mode-button" data-mode="solo" aria-pressed="${state.mode==='solo'}">Just me</button><button type="button" class="mode-button" data-mode="pair" aria-pressed="${state.mode==='pair'}">With a partner</button></div><p class="input-hint" id="mode-hint">${state.mode==='pair'?'One device, two perspectives. Switch who drives at opening day.':'Make the choices yourself. Be ready to defend one tradeoff.'}</p><label class="field-label" for="event-name">Name your event <span>(optional)</span></label><input type="text" id="event-name" maxlength="50" autocomplete="off" placeholder="Or let us name it for you" value="${esc(state.name)}"><p class="input-hint">Use an event name, not student names. Nothing is submitted.</p>${controls('Let’s build it',1)}</div>`;}
  function missionScreen(){const m=chosen(M.MISSIONS,state.mission);return `<div class="reveal"><p class="eyebrow">01 / PURPOSE & PEOPLE</p><h2 id="screen-title">Who is this for?</h2><p class="lede">Pick the experience you want to create. Your audience and goal should drive the rest.</p><div class="choice-stack">${M.MISSIONS.map(x=>choice(x,'mission',x.id===state.mission,x.id===state.mission?`<span class="detail">${esc(x.purpose)}</span>`:'')).join('')}</div>${m?`<div class="goal-callout"><strong>Your definition of success</strong><p>${esc(m.goal)}</p><small>${esc(m.measure)} This is your target, not a simulated result.</small></div>`:'<p class="input-hint">Choose an audience to reveal a concrete event goal.</p>'}${controls('Choose a format',2,!!m)}</div>`;}
  function formatScreen(){return `<div class="reveal"><p class="eyebrow">02 / THE MAIN EVENT</p><h2 id="screen-title">How will people play?</h2><p class="lede">Same campus space. Three different experiences. Every format comes with a workable schedule and core crew.</p><div class="choice-stack">${M.FORMATS.map(x=>choice(x,'format',x.id===state.format,x.id===state.format?`<span class="detail"><b>The tradeoff:</b> ${esc(x.tradeoff)}</span>`:'')).join('')}</div>${state.format?`<div class="crew-strip"><strong>Your operations plan:</strong> ${esc(chosen(M.FORMATS,state.format).staff)}. Core roles are already covered; your feature choices add their own hosts.</div>`:''}${controls('Add event features',3,!!state.format)}</div>`;}
  function featureScreen(){const spent=M.total(state);return `<div class="reveal"><p class="eyebrow">03 / GIVE THEM A REASON TO STAY</p><h2 id="screen-title">What’s beyond the game?</h2><p class="lede">Event features are the extra things guests can do or enjoy. Choose up to 3 within your 10-credit budget.</p><div class="budget-bar" aria-label="Planning budget"><div><strong>${M.BUDGET-spent} credits left</strong><small>${state.features.length} of 3 features · ${spent} of 10 credits used</small></div><div class="credit-tokens" aria-hidden="true">${Array.from({length:10},(_,i)=>`<span class="${i<spent?'used':''}"></span>`).join('')}</div></div><div class="feature-grid">${M.FEATURES.map(f=>{const on=state.features.includes(f.id);return `<button type="button" class="choice feature" data-feature="${f.id}" aria-pressed="${on}">${icon(f.icon)}<span class="cost">${f.cost} CREDITS</span><strong>${esc(f.label)}</strong><span class="short">${esc(f.short)}</span>${on?`<span class="detail">${esc(f.detail)}</span><span class="selection-label">✓ On your poster · click to remove</span>`:''}</button>`;}).join('')}</div><p class="status-message" id="selection-status" role="status">${esc(message)}</p><p class="input-hint">Credits bundle the feature’s supplies and helpers. These are made-up planning units, not dollars. You don’t have to spend all 10.</p>${state.features.length?`<div class="crew-strip"><strong>Feature crew:</strong> ${state.features.map(id=>esc(chosen(M.FEATURES,id).staff)).join(' · ')}. These roles are separate from required safety and access support.</div>`:''}${controls('Open the doors',4)}</div>`;}
  function surpriseScreen(){return `<div class="reveal"><p class="eyebrow">04 / OPENING DAY</p><h2 id="screen-title">The plan meets real life.</h2><p class="lede">${state.mode==='pair'?'Switch who drives. ':''}Your poster is ready. Your guests are arriving. Then the message comes in.</p><div class="surprise-banner">${icon('clock')}<div><p><strong>${esc(M.SURPRISE.title)}</strong></p><p>${esc(M.SURPRISE.body)}</p></div></div><p class="locked-plan">${esc(M.SURPRISE.boundary)} All three responses cost 0 extra credits.</p><div class="choice-stack">${M.ADJUSTMENTS.map(x=>choice(x,'adjustment',x.id===state.adjustment)).join('')}</div><p class="input-hint">Same surprise on every replay. Pick the tradeoff you can defend for your audience.</p>${controls('See how it plays out',5,!!state.adjustment)}</div>`;}
  function outcome(iconId,label,value,text){return `<div class="outcome">${icon(iconId)}<div><small>${esc(label)}</small><h3>${esc(value)}</h3><p>${esc(text)}</p></div></div>`;}
  function recapScreen(){const r=M.recap(state);if(!r)return featureScreen();return `<div class="reveal"><span class="recap-stamp">EVENT WRAP · ILLUSTRATIVE SIMULATION</span><h2 id="screen-title">${esc(title())}<br>had a point of view.</h2><p class="lede">Here’s how your choices fit together. These are teaching signals, not real attendance or satisfaction results.</p><div class="outcomes">${outcome('crowd','Turnout signal',r.drawLevel,r.drawText)}${outcome('controller','Player & guest experience',r.experienceLevel,r.experienceText)}${outcome('ticket','Planning budget',`${r.remaining} of 10 credits left`,r.remaining?'You kept some flexibility. Unspent credits could support a future improvement; saving them is a valid choice.':'You used the full feature budget. Your opening-day response stayed within it, with no financial cushion left.')}</div><div class="recap-note"><strong>Your tradeoff:</strong> ${esc(r.tradeoff)}<br><br><strong>Your adjustment:</strong> ${esc(r.adjustmentTradeoff)}</div>${r.benefits.length?`<p class="input-hint"><strong>Why the fit:</strong> ${r.benefits.map(esc).join(' + ')} directly support ${esc(r.mission.audience.toLowerCase())}.</p>`:''}<div class="goal-callout"><strong>Did you achieve the goal?</strong><p>${esc(r.mission.goal)}</p><small>${esc(r.goalEvidence)} ${esc(r.mission.measure)}</small></div><label for="reflection" class="field-label" style="margin-top:24px">Your one-sentence defense <span>(optional)</span></label><textarea id="reflection" maxlength="300" placeholder="We chose ___ for ___, and accepted ___ after the surprise.">${esc(state.reflection)}</textarea><div class="counter"><span id="reflection-count">${state.reflection.length}</span>/300</div><div class="export-actions"><button type="button" class="secondary" id="download">Download one-page recap</button><button type="button" class="secondary" id="print">Print / save PDF</button></div><p class="input-hint" id="export-status" role="status">No automatic submission. Save this only if you want it or your instructor asks.</p><div class="button-row"><button type="button" class="primary" id="replay">Remix your event <span aria-hidden="true">↻</span></button><button type="button" class="back" id="back">← Revisit the surprise</button></div><p class="input-hint" style="margin-top:15px">A remix keeps your choices so you can change one. Same conditions, no random score.</p></div>`;}
  function renderPoster(){const m=chosen(M.MISSIONS,state.mission),f=chosen(M.FORMATS,state.format);$('#poster').innerHTML=`<article class="event-poster" style="--poster-accent:${m?.color||'#bdff70'}" aria-label="Your event poster"><div class="poster-top"><div class="poster-kicker"><span>CAMPUS ESPORTS COLLECTIVE</span><span class="date-stamp">ONE AFTERNOON</span></div><h3 class="poster-title">${esc(title())}</h3><p class="poster-tagline">${esc(m?.tagline||'A little competition. A lot of possibility.')}</p></div><div class="poster-art"><img src="assets/arena.svg" alt="Illustrated campus esports stage with players, spectators, and colored lights" width="720" height="430"><span class="poster-ticket">${esc(f?.label||'Build your main event')}</span></div><div class="poster-features">${state.features.length?state.features.map(id=>`<span class="poster-feature">${esc(chosen(M.FEATURES,id).label)}</span>`).join(''):`<span class="poster-placeholder">${state.featuresConfirmed?'All focus on the main event.':'Your event features will appear here.'}</span>`}</div><div class="poster-bottom"><span>STUDENT CENTER · CAMPUS EVENT</span><span>${esc(m?.audience.toUpperCase()||'PLAY · WATCH · BELONG')}</span></div></article>`;}
  function renderProgress(){const labels=['Audience','Format','Features','Opening day','Recap'];$('#progress').innerHTML=labels.map((label,i)=>`<button type="button" data-go="${i+1}" ${i+1>M.maxStep(state)?'disabled':''} ${state.step===i+1?'aria-current="step"':''} class="${state.step>i+1?'is-done':''}"><span aria-hidden="true">${state.step>i+1?'✓':String(i+1).padStart(2,'0')}</span>${label}</button>`).join('');}
  function reportMarkup(){const r=M.recap(state);if(!r)return '';return `<div class="report-head"><p class="report-meta">BUILD THE HYPE · SPM 343 ESPORTS EVENTS · ${state.mode==='pair'?'PAIR':'SOLO'} ACTIVITY</p><h1>${esc(title())}</h1><p>Campus esports event plan & illustrative recap</p></div><h2>1. Purpose, audience & goal</h2><p>${esc(r.mission.purpose)} Audience: ${esc(r.mission.audience)}.</p><p>${esc(r.mission.goal)}</p><h2>2. Event design</h2><p><b>Format:</b> ${esc(r.format.label)}. ${esc(r.tradeoff)}</p><p><b>Features:</b> ${r.features.length?r.features.map(f=>`${esc(f.label)} (${f.cost} credits)`).join('; '):'No extras; focus on the main event' }.</p><p><b>People:</b> ${esc(r.format.staff)}; ${r.features.map(f=>esc(f.staff)).join('; ')}.</p><h2>3. Opening-day adjustment</h2><p>${esc(M.SURPRISE.title)} <b>Decision:</b> ${esc(r.adjustment.label)}.</p><p>${esc(r.adjustmentTradeoff)} No added credits.</p><div class="report-grid"><div><small>ILLUSTRATIVE TURNOUT SIGNAL</small><strong>${esc(r.drawLevel)}</strong></div><div><small>EXPERIENCE FIT</small><strong>${esc(r.experienceLevel)}</strong></div><div><small>BUDGET REMAINING</small><strong>${r.remaining} / 10 credits</strong></div></div><h2>4. Evaluate with evidence</h2><p>${esc(r.goalEvidence)} ${esc(r.mission.measure)}</p><h2>Our / my one-sentence defense</h2><p class="report-reflection">${esc(state.reflection.trim()||'We chose __________________ for __________________, and accepted __________________ after the surprise.')}</p><p class="report-limit">Simulation, not a forecast or grade. Outcomes and planning credits are invented teaching assumptions. Fixed venue, game permissions, equipment, required staffing, safety, and access support are provided. No student identity is collected; this report stays on your device until you choose to share it.</p>`;}
  const reportCSS=`body{font-family:Arial,Helvetica,sans-serif;color:#1d1825;max-width:740px;margin:32px auto;padding:0 24px;line-height:1.4;font-size:13px}h1{font-size:32px;line-height:1.05;margin:0 0 9px;overflow-wrap:anywhere}h2{font-size:15px;margin:15px 0 5px}p{margin:0 0 6px}.report-head{border-bottom:2px solid;padding-bottom:12px;margin-bottom:14px}.report-meta{font-size:10px;letter-spacing:1px}.report-grid{display:grid;grid-template-columns:repeat(3,1fr);gap:12px;margin:16px 0}.report-grid div{border:1px solid #bbb;padding:12px;border-radius:6px}.report-grid strong{display:block;font-size:16px}.report-grid small{font-size:9px}.report-reflection{border:1px solid #bbb;padding:12px;white-space:pre-wrap;overflow-wrap:anywhere}.report-limit{border-top:1px solid #bbb;padding-top:10px;margin-top:18px;font-size:10px}.print-button{font:inherit;padding:10px 16px;background:#241735;color:white;border:0;border-radius:6px;cursor:pointer;margin-bottom:20px}@media(max-width:520px){.report-grid{grid-template-columns:1fr}body{margin:20px auto}}@media print{body{margin:0;padding:0;font-size:10pt;max-width:none}.print-button{display:none}h1{font-size:24pt}h2{font-size:12pt;margin-top:11pt}.report-grid{grid-template-columns:repeat(3,1fr)}.report-grid strong{font-size:12pt}.report-grid div{padding:8pt}.report-limit{font-size:8pt}@page{size:letter portrait;margin:15mm}}`;
  function download(){try{const html=`<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>${esc(title())} · Build the Hype recap</title><style>${reportCSS}</style></head><body><button class="print-button" onclick="window.print()">Print / save PDF</button>${reportMarkup()}</body></html>`;const url=URL.createObjectURL(new Blob([html],{type:'text/html;charset=utf-8'}));const a=document.createElement('a');a.href=url;a.download='build-the-hype-recap.html';document.body.append(a);a.click();a.remove();setTimeout(()=>URL.revokeObjectURL(url),1000);$('#export-status').textContent='Recap download requested. Open the HTML file to view it or print it to PDF. No work was submitted.';}catch{$('#export-status').textContent='Your browser blocked the download. Use Print / save PDF, or copy the visible recap.';}}
  function bind(){
    $('#next')?.addEventListener('click',e=>go(Number(e.currentTarget.dataset.step)));
    $('#back')?.addEventListener('click',()=>go(state.step-1));
    document.querySelectorAll('[data-go]').forEach(b=>b.addEventListener('click',()=>go(Number(b.dataset.go))));
    document.querySelectorAll('[data-mode]').forEach(b=>b.addEventListener('click',()=>{state.mode=b.dataset.mode;save();render();$(`[data-mode="${state.mode}"]`).focus();}));
    $('#event-name')?.addEventListener('input',e=>{state.name=M.cleanText(e.target.value);save();renderPoster();});
    document.querySelectorAll('[data-mission]').forEach(b=>b.addEventListener('click',()=>mutate({mission:b.dataset.mission},`[data-mission="${b.dataset.mission}"]`)));
    document.querySelectorAll('[data-format]').forEach(b=>b.addEventListener('click',()=>mutate({format:b.dataset.format},`[data-format="${b.dataset.format}"]`)));
    document.querySelectorAll('[data-feature]').forEach(b=>b.addEventListener('click',()=>{const result=M.toggleFeature(state,b.dataset.feature);if(result.ok){state=result.state;message=`${chosen(M.FEATURES,b.dataset.feature).label} ${state.features.includes(b.dataset.feature)?'added':'removed'}. ${M.BUDGET-M.total(state)} credits left.`;save();}else message=result.message;render();$(`[data-feature="${b.dataset.feature}"]`).focus();announce(message);}));
    document.querySelectorAll('[data-adjustment]').forEach(b=>b.addEventListener('click',()=>{state.adjustment=b.dataset.adjustment;save();render();$(`[data-adjustment="${state.adjustment}"]`).focus();}));
    $('#reflection')?.addEventListener('input',e=>{state.reflection=M.cleanText(e.target.value,300);$('#reflection-count').textContent=state.reflection.length;save();$('#print-report').innerHTML=reportMarkup();});
    $('#download')?.addEventListener('click',download);
    $('#print')?.addEventListener('click',()=>{try{window.print();}catch{$('#export-status').textContent='Printing is unavailable here. Use Download one-page recap instead.';}});
    $('#replay')?.addEventListener('click',()=>{state.adjustment='';state.reflection='';go(1);announce('Remix started. Your original event choices are ready to edit. The opening-day surprise will be the same.');});
  }
  function render(){renderProgress();$('#screen').innerHTML=[welcome,missionScreen,formatScreen,featureScreen,surpriseScreen,recapScreen][state.step]();renderPoster();$('#print-report').innerHTML=reportMarkup();bind();}
  function hashStep(){const v=Number(location.hash.slice(1));return /^#[0-5]$/.test(location.hash)?v:state.step;}
  window.addEventListener('popstate',()=>go(hashStep(),{replace:true}));
  window.addEventListener('hashchange',()=>{if(hashStep()!==state.step)go(hashStep(),{replace:true});});
  $('#guide-button').addEventListener('click',()=>$('#guide-dialog').showModal());
  $('#reset-button').addEventListener('click',()=>$('#reset-dialog').showModal());
  $('#cancel-reset').addEventListener('click',()=>$('#reset-dialog').close());
  $('#confirm-reset').addEventListener('click',()=>{state=M.fresh();$('#reset-dialog').close();go(0,{replace:true});if(!storageOK) storageNotice('Event cleared for this tab only. The browser prevented replacing saved data; an older plan may reappear after reload.');announce('A fresh event is ready.');});
  go(hashStep(),{replace:true,focus:false});
})();
