'use strict';
(()=>{
const ENDPOINT='https://havsvkhddvdbzbsmhqbr.supabase.co/functions/v1/spm370-llc3-v3/instructor';
const $=s=>document.querySelector(s),esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
let key='',rows=[],assessment=null,isOpen=true,busy=false,generation=0;
const lastName=r=>r.full_name.trim().split(/\s+/).at(-1).toLowerCase();
const reviewStatus=r=>!r.submitted_at?'In progress':r.reviewed?'Reviewed':'Writing review pending';
const say=s=>{$('#notice').textContent=s;};
async function api(body){const controller=new AbortController(),timer=setTimeout(()=>controller.abort(),18000);try{const r=await fetch(ENDPOINT,{method:body?'POST':'GET',cache:'no-store',headers:{'x-instructor-key':key,...(body?{'Content-Type':'application/json'}:{})},...(body?{body:JSON.stringify(body)}:{}),signal:controller.signal});const d=await r.json();if(!r.ok||!d.ok)throw Error(d.error||'Request not confirmed.');return d;}catch(e){throw Error(e.name==='AbortError'?'The connection timed out. Refresh to confirm whether the change saved.':e.message);}finally{clearTimeout(timer);}}
function filtered(){const q=$('#search').value.toLowerCase().trim();return rows.filter(r=>(r.full_name+' '+r.email).toLowerCase().includes(q));}
function render(){
 $('#counts').textContent=`${rows.length} students started · ${rows.filter(r=>r.submitted_at).length} submitted · ${rows.filter(r=>r.reviewed).length} writing reviews complete`;
 $('#toggleOpen').textContent=isOpen?'Close submissions':'Open submissions';
 $('#rubric').innerHTML=`<p>${esc(assessment.rubric.notes)}</p><p>${esc(assessment.rubric.brief)}</p><ol>${assessment.rubric.noteGuidance.map(x=>`<li>${esc(x)}</li>`).join('')}</ol>`;
 $('#rows').innerHTML=filtered().length?filtered().map(r=>`<details data-record="${r.id}"><summary><strong>${esc(r.full_name)}</strong><span class="student-email">${esc(r.email)}</span><span class="summary-status">${reviewStatus(r)} · MC ${r.mc_score}/12${r.reviewed?` · Writing ${r.writingScore}/8 · Final ${r.finalScore}/20`:r.submitted_at?' · Final pending':` · ${r.stage_answers.filter(Boolean).length}/6 decision sets recorded`}</span></summary><p class="small">Started ${esc(new Date(r.created_at).toLocaleString())}${r.submitted_at?` · Submitted ${esc(new Date(r.submitted_at).toLocaleString())}<br>Receipt ${esc(r.receipt)}`:''}</p>${!r.submitted_at?'<p class="notice">This is an unfinished draft. Writing grades can be entered after the student submits.</p>':''}<form data-grade="${r.id}">${assessment.stages.map((s,i)=>`<h2>${i+1}. ${esc(s.short)}</h2><p>${esc(s.note)}</p><p class="student-response">${esc(r.notes[i]||'No saved case note yet.')}</p><p class="small">Review focus: ${esc(assessment.rubric.noteGuidance[i])}</p><label for="note-${r.id}-${i}">Case note ${i+1} /1</label><select id="note-${r.id}-${i}" name="note${i}" ${r.submitted_at?'required':'disabled'}><option value="">Awaiting review</option>${[0,.5,1].map(n=>`<option value="${n}" ${r.note_scores?.[i]===n?'selected':''}>${n}</option>`).join('')}</select><details class="key-detail"><summary>Recorded multiple-choice answers and key</summary>${s.questions.map((q,j)=>{const v=r.stage_answers[i]?.[j];return `<h3>Question ${i*2+j+1}</h3><p>${esc(q.prompt)}</p><p>Student: ${v===undefined?'Not recorded':esc(q.options[v])}</p><p><strong>${v===undefined?'Pending':v===q.answer?'1/1':'0/1'}</strong> · Best answer: ${esc(q.options[q.answer])}</p><p>${esc(q.why)}</p>`;}).join('')}</details>`).join('')}<h2>Final recommendation · 2 points</h2><h3>${esc(r.final_decision||'No recommendation saved')}</h3><p class="student-response">${esc(r.final_brief||'No saved final brief yet.')}</p><p class="small">${esc(assessment.rubric.brief)}</p><label for="brief-${r.id}">Final recommendation /2</label><select id="brief-${r.id}" name="brief" ${r.submitted_at?'required':'disabled'}><option value="">Awaiting review</option>${[0,.5,1,1.5,2].map(n=>`<option value="${n}" ${Number(r.brief_score)===n&&r.brief_score!==null?'selected':''}>${n}</option>`).join('')}</select><label for="notes-${r.id}">Private instructor review notes</label><textarea id="notes-${r.id}" name="notes" maxlength="4000" ${r.submitted_at?'':'disabled'}>${esc(r.grader_notes)}</textarea><div class="actions"><button ${r.submitted_at?'':'disabled'}>Save all writing grades</button><button type="button" class="secondary" data-recover="${r.id}">Create recovery code</button></div></form></details>`).join(''):'<section class="paper"><p>No matching student attempts.</p></section>';
}
async function load(){const ticket=generation,d=await api();if(ticket!==generation)return;rows=d.submissions.sort((a,b)=>lastName(a).localeCompare(lastName(b))||a.full_name.localeCompare(b.full_name));assessment=d.assessment;isOpen=d.isOpen;render();$('#updated').textContent='Updated '+new Date().toLocaleString();}
$('#loginForm').onsubmit=async e=>{e.preventDefault();if(busy)return;busy=true;key=$('#key').value;$('#open').disabled=true;try{await load();$('#key').value='';$('#login').hidden=true;$('#dashboard').hidden=false;say('');}catch(e){key='';say(e.message);}finally{busy=false;$('#open').disabled=false;}};
$('#logout').onclick=()=>{generation++;key='';rows=[];assessment=null;$('#rows').innerHTML='';$('#rubric').innerHTML='';$('#counts').textContent='';$('#dashboard').hidden=true;$('#login').hidden=false;$('#key').value='';say('');};
$('#refresh').onclick=()=>load().then(()=>say('')).catch(e=>say(e.message));$('#search').oninput=render;
$('#toggleOpen').onclick=async()=>{const value=!isOpen;if(!confirm(value?'Open LLC3 submissions?':'Close new attempts and submissions? Students can still retrieve saved work and receipts.'))return;try{await api({action:'setOpen',isOpen:value});await load();say(value?'Submissions opened.':'Submissions closed.');}catch(e){say(e.message);}};
$('#rows').onsubmit=async e=>{const form=e.target;if(!form.matches('[data-grade]'))return;e.preventDefault();const r=rows.find(x=>x.id===form.dataset.grade),f=form.elements,noteScores=Array.from({length:6},(_,i)=>f['note'+i].value===''?null:Number(f['note'+i].value)),briefScore=f.brief.value===''?null:Number(f.brief.value);if(noteScores.includes(null)||briefScore===null){say('Review all six case notes and the final recommendation before saving the writing total.');return;}const b=form.querySelector('button');b.disabled=true;const ticket=generation;try{await api({action:'grade',id:r.id,revision:r.revision,noteScores,briefScore,notes:f.notes.value});if(ticket!==generation)return;await load();say('Writing grades saved. The final /20 total is available in the dashboard, CSV, and student receipt.');}catch(e){if(ticket===generation){say(e.message);b.disabled=false;}}};
$('#rows').onclick=async e=>{const b=e.target.closest('[data-recover]');if(!b)return;const r=rows.find(x=>x.id===b.dataset.recover);if(!confirm('Create a new private resume code for '+r.full_name+'? The old code will stop working. Share the new code privately with that student.'))return;b.disabled=true;const ticket=generation;try{const d=await api({action:'recover',id:r.id,revision:r.revision});if(ticket!==generation)return;download(`SPM 370 LLC3 private recovery code\nStudent: ${r.full_name}\nEmail: ${r.email}\nCode: ${d.recoveryCode}\nEnter in Course reference → Resume saved attempt on the lesson page.\nKeep this code private.\n`,'SPM370_LLC3_Private_Recovery_Code.txt','text/plain');await load();say('Recovery code downloaded. Share it privately with the named student.');}catch(e){if(ticket===generation){say(e.message);b.disabled=false;}}};
function cell(value){let s=String(value??'');if(/^[\s]*[=+@-]/.test(s))s="'"+s;return '"'+s.replace(/"/g,'""')+'"';}
function download(text,name,type){const url=URL.createObjectURL(new Blob([text],{type})),a=document.createElement('a');a.href=url;a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(url),2000);}
$('#export').onclick=()=>{const data=[['Name','Email','Status','Started UTC','Submitted UTC','Receipt','MC /12',...Array.from({length:6},(_,i)=>`Case note ${i+1} /1`),'Final brief /2','Writing /8','Final /20','Final percent',...Array.from({length:6},(_,i)=>`Case note ${i+1} response`),'Recommendation','Final brief response',...Array.from({length:12},(_,i)=>`Q${i+1} response`),'Reviewed UTC','Instructor notes'],...filtered().map(r=>[r.full_name,r.email,reviewStatus(r),r.created_at,r.submitted_at,r.receipt,r.mc_score,...Array.from({length:6},(_,i)=>r.note_scores?.[i]),r.brief_score,r.writingScore,r.finalScore,r.reviewed?r.finalScore*5:null,...r.notes,r.final_decision,r.final_brief,...assessment.stages.flatMap((s,i)=>s.questions.map((q,j)=>q.options[r.stage_answers[i]?.[j]]||'')),r.reviewed_at,r.grader_notes])];download('\ufeff'+data.map(r=>r.map(cell).join(',')).join('\r\n'),'SPM370_LLC3_Scores_and_Responses.csv','text/csv;charset=utf-8');};
})();
