function computeRisks(){
 let r={ip:state.model==='open'?62:42,contract:58,labor:state.level==='pro'?58:state.level==='scholastic'?48:42,antitrust:state.model==='closed'?58:state.model==='hybrid'?47:32,governance:state.model==='open'?63:state.model==='hybrid'?50:40,safeguarding:state.level==='scholastic'?68:state.level==='grassroots'?56:34};
 if(has('license'))r.ip-=26;if(has('participation')){r.contract-=15;r.antitrust-=4}if(has('revenue'))r.contract-=8;if(has('player'))r.labor-=19;if(has('sponsor'))r.contract-=5;if(has('exit'))r.contract-=8;if(has('format'))r.contract-=9;if(has('rulebook')){r.governance-=17;r.safeguarding-=7}if(has('dispute')){r.contract-=8;r.governance-=5}if(publisherDependency()>50)r.ip+=8;return Object.fromEntries(Object.entries(r).map(([k,v])=>[k,clamp(v)]));
}
function recalc(){if(state.level&&state.model&&state.step<5){state.metrics=computeBaseMetrics();state.metricDeltas={}}save();renderMetrics();if(state.step===4)renderRisk()}
function renderMetrics(){const defs=[['financial','💰','Financial Sustainability'],['access','🎮','Competitive Access'],['control','🏛','Publisher Control'],['legal','⚖','Legal Resilience'],['fan','❤️','Fan Legitimacy']];const box=document.getElementById('metrics');box.innerHTML='';defs.forEach(([id,icon,name])=>{const v=state.metrics[id]??55,d=state.metricDeltas[id]||0;box.insertAdjacentHTML('beforeend',`<div class="metric ${d?'flash':''}"><div class="mhead"><span>${icon} ${name}</span><span class="mval">${v}${d?`<span class="delta ${d>0?'pos':'neg'}">${d>0?'+':''}${d}</span>`:''}</span></div><div class="mtrack"><div class="mfill" style="width:${v}%"></div></div></div>`)});document.getElementById('teamTag').innerHTML=`<strong>${escapeHtml(state.team||'NEXUS//ARENA')}</strong><br>${state.model?modelDefs[state.model].name+' · ':''}Publisher / Ecosystem Designer`;document.getElementById('depVal').textContent=publisherDependency()+'%';document.getElementById('depFill').style.width=publisherDependency()+'%';}

function activeStakeholders(){let set=new Set();if(state.step===3){state.contracts.forEach(id=>{const c=contracts.find(x=>x.id===id);(c?.nodes||[]).forEach(n=>set.add(n))})}else if(state.step===5&&state.crises.length){const c=crisisBank.find(x=>x.id===state.crises[state.crisisIndex]);(c?.affects||[]).forEach(n=>set.add(n))}else if(state.step===6){['publisher','league','organizer','team','player','sponsor','platform'].forEach(n=>set.add(n))}else{if(state.model==='closed'){['publisher','league','team'].forEach(n=>set.add(n))}if(state.model==='open'){['publisher','organizer','team','player'].forEach(n=>set.add(n))}if(state.model==='hybrid'){['publisher','league','organizer','team','player'].forEach(n=>set.add(n))}}return set}
function renderNetwork(){const svg=document.getElementById('networkSvg');if(!svg)return;const pos={publisher:[160,28],league:[76,95],organizer:[244,95],team:[84,182],player:[160,205],sponsor:[236,182],platform:[160,112]};const labels={publisher:'PUBLISHER',league:'LEAGUE',organizer:'ORGANIZER',team:'TEAM',player:'PLAYER',sponsor:'SPONSOR',platform:'PLATFORM'};const edges=[['publisher','league'],['publisher','organizer'],['publisher','platform'],['league','team'],['organizer','team'],['team','player'],['team','sponsor'],['platform','player'],['league','sponsor']];const hot=activeStakeholders();let out=`<defs><linearGradient id="edgeGrad" x1="0%" y1="0%" x2="100%" y2="0%"><stop offset="0%" stop-color="#45c8d9"/><stop offset="100%" stop-color="#d9a63b"/></linearGradient></defs>`;edges.forEach(([a,b])=>{const [x1,y1]=pos[a],[x2,y2]=pos[b];out+=`<line class="edge ${hot.has(a)&&hot.has(b)?'hot':''}" x1="${x1}" y1="${y1}" x2="${x2}" y2="${y2}"/>`});Object.keys(pos).forEach(id=>{const [x,y]=pos[id];out+=`<g class="node ${hot.has(id)?'hot':''}">${hot.has(id)?`<circle class="node-ring" cx="${x}" cy="${y}" r="34"/>`:''}<circle cx="${x}" cy="${y}" r="27"/><text x="${x}" y="${y+4}">${labels[id]}</text></g>`});svg.innerHTML=out;const caption=state.step===5?'This crisis is lighting up the stakeholders most directly implicated by the shock.':state.step===3?'Selected contracts light up the relationships your legal architecture currently covers.':'Your structure determines where power and dependency concentrate.';document.getElementById('networkCaption').textContent=caption}
function riskColor(v){return v>=65?'#b34755':v>=45?'#c8782f':'#2f7b62'}
function renderRisk(){const r=computeRisks();const defs=[['ip','IP Gatekeeping','Publisher permissions, tournament policy, software, branding, audiovisual uses.'],['contract','Contract Risk','Cross-references, change, exit, revenue, sponsor, and dispute architecture.'],['labor','Labor Risk','Classification, control, compensation, travel, and player obligations.'],['antitrust','Antitrust Risk','Coordination, exclusionary conduct, market power, and labor-market restraints.'],['governance','Governance / Integrity','Rulebooks, anti-cheat, sanctions, consistency, and enforcement authority.'],['safeguarding','Safeguarding / Privacy','Minors, student data, consent, reporting, and institutional obligations.']];const list=document.getElementById('riskList');list.innerHTML='';defs.forEach(([id,name,note])=>{const v=r[id];list.insertAdjacentHTML('beforeend',`<div class="riskrow"><div class="rhead"><strong>${name}</strong><span>${v}/100</span></div><div class="rtrack"><div class="rfill" style="width:${v}%;background:${riskColor(v)}"></div></div><div class="risknote">${note}</div></div>`)});renderRadar(r,defs);const top=defs.map(d=>[d[0],r[d[0]],d[1]]).sort((a,b)=>b[1]-a[1])[0];document.getElementById('riskLens').innerHTML=`<strong>Highest current exposure: ${top[2]} (${top[1]}/100).</strong><br>${mitigation(top[0])}`}
function renderRadar(r,defs){const cx=175,cy=160,R=110,n=defs.length;let axes='',rings='',labels='',pts=[],dots='';for(let ring=1;ring<=4;ring++){const rr=R*ring/4,arr=[];for(let i=0;i<n;i++){const a=-Math.PI/2+i*2*Math.PI/n;arr.push(`${cx+rr*Math.cos(a)},${cy+rr*Math.sin(a)}`)}rings+=`<polygon points="${arr.join(' ')}" fill="none" stroke="${ring===4?'#d7dfec':'#e8edf5'}" stroke-dasharray="${ring===4?'0':'3 4'}"/>`}defs.forEach((d,i)=>{const a=-Math.PI/2+i*2*Math.PI/n;const x=cx+R*Math.cos(a),y=cy+R*Math.sin(a);axes+=`<line x1="${cx}" y1="${cy}" x2="${x}" y2="${y}" stroke="#d6dce7"/>`;const lr=R+30;labels+=`<text x="${cx+lr*Math.cos(a)}" y="${cy+lr*Math.sin(a)+4}" font-size="11" text-anchor="middle" fill="#536077">${d[1].replace(' / ','/')}</text>`;const rr=R*(r[d[0]]/100);const px=cx+rr*Math.cos(a),py=cy+rr*Math.sin(a);pts.push(`${px},${py}`);dots+=`<circle cx="${px}" cy="${py}" r="4.5" fill="#45c8d9" stroke="#ffffff" stroke-width="2"/>`});document.getElementById('radarBox').innerHTML=`<svg viewBox="0 0 350 330" aria-label="Legal risk radar"><defs><linearGradient id="radFill" x1="0%" y1="0%" x2="100%" y2="100%"><stop offset="0%" stop-color="rgba(69,200,217,.42)"/><stop offset="100%" stop-color="rgba(116,91,216,.20)"/></linearGradient><filter id="glow"><feGaussianBlur stdDeviation="5" result="blur"/><feMerge><feMergeNode in="blur"/><feMergeNode in="SourceGraphic"/></feMerge></filter></defs><circle cx="175" cy="160" r="22" fill="#f4f7ff" stroke="#d9e1ef"/><text x="175" y="157" text-anchor="middle" font-size="10" fill="#6b7588">RISK</text><text x="175" y="171" text-anchor="middle" font-size="12" font-weight="700" fill="#31415f">BOARD</text>${rings}${axes}<polygon points="${pts.join(' ')}" fill="url(#radFill)" stroke="#745bd8" stroke-width="3" filter="url(#glow)"/>${dots}${labels}<text x="175" y="317" text-anchor="middle" font-size="12" fill="#697284">Higher score = greater exposure</text></svg>`}
function mitigation(id){return ({ip:'Map the publisher license, tournament policy, branding, software, and broadcast permissions before launch.',contract:'Audit cross-references and add clear change, exit, revenue, and dispute provisions.',labor:'Review the real working relationship under the governing classification test; escalate classification uncertainty.',antitrust:'Identify whether the conduct is coordinated or unilateral before selecting the antitrust theory.',governance:'Clarify which rulebook governs, how changes bind participants, and who enforces integrity standards.',safeguarding:'Build a data and safeguarding map identifying participants, data flows, consent, reporting, and institutional obligations.'})[id]}

function startCrises(){state.crises=shuffle(crisisBank.map(x=>x.id)).slice(0,3);state.crisisIndex=0;state.crisisChoices={};state.metricDeltas={};save();showLaunchSequence()}
function showBootSequence(next){const ov=document.getElementById('bootOverlay'),title=document.getElementById('bootTitle'),count=document.getElementById('bootCount'),textEl=document.getElementById('bootText');ov.classList.add('show');const seq=[['01','AUTHENTICATING TEAM','Verifying board access and loading your saved classroom environment.'],['02','SYNCING STRATEGY ROOM','Calibrating architecture, revenue, and legal dashboards.'],['03','ACTIVATING SIMULATION','Your premium classroom boardroom is ready.']];let i=0;function tick(){count.textContent=seq[i][0];title.textContent=seq[i][1];textEl.textContent=seq[i][2];i++;if(i<seq.length)setTimeout(tick,560);else setTimeout(()=>{ov.classList.remove('show');next&&next()},620)}tick()}
function showLaunchSequence(){const ov=document.getElementById('launchOverlay'),count=document.getElementById('countdown'),txt=document.getElementById('launchText');ov.classList.add('show');const seq=[['3','LOCKING ARCHITECTURE'],['2','LOADING REVENUE MODEL'],['1','ARMING RISK BOARD'],['LIVE','SEASON LIVE']];let i=0;function tick(){count.textContent=seq[i][0];txt.textContent=seq[i][1];i++;if(i<seq.length)setTimeout(tick,650);else setTimeout(()=>{ov.classList.remove('show');go(5);showNewsOverlay()},750)}tick()}
function renderChaosList(){const box=document.getElementById('chaosGrid');if(!box)return;box.innerHTML=crisisBank.map(c=>`<div class="chaos-card" data-chaos="${c.id}"><div class="mini-tags">${c.tags.map(t=>`<span>${t}</span>`).join('')}</div><h4>${c.title}</h4><p>${c.text}</p></div>`).join('');document.querySelectorAll('[data-chaos]').forEach(el=>el.onclick=()=>injectChaos(el.dataset.chaos))}
function openChaosMode(){renderChaosList();document.getElementById('chaosOverlay').classList.add('show')}
function closeChaosMode(){document.getElementById('chaosOverlay').classList.remove('show')}
function injectChaos(id){const exists=crisisBank.find(c=>c.id===id);if(!exists)return;const current=currentCrisis();if(state.step<5||!state.crises.length){state.crises=[id,...shuffle(crisisBank.map(x=>x.id).filter(x=>x!==id))].slice(0,3);state.crisisIndex=0;state.crisisChoices={};save();closeChaosMode();go(5);showNewsOverlay();return}if(current&&state.crisisChoices[current.id]!==undefined){state.crisisIndex++;state.crises.splice(state.crisisIndex,0,id)}else{state.crises[state.crisisIndex]=id;delete state.crisisChoices[id]}state.crises=[...new Set(state.crises)].slice(0,5);save();closeChaosMode();showNewsOverlay()}
function randomChaos(){const options=crisisBank.map(c=>c.id);injectChaos(options[Math.floor(Math.random()*options.length)])}
function currentCrisis(){return crisisBank.find(x=>x.id===state.crises[state.crisisIndex])}
function showNewsOverlay(){const c=currentCrisis();if(!c)return;document.getElementById('newsTitle').textContent=c.title.toUpperCase();document.getElementById('newsText').textContent=c.text;document.getElementById('newsTags').innerHTML=c.tags.map(t=>`<span>${t}</span>`).join('');document.getElementById('newsOverlay').classList.add('show');renderNetwork()}