const defaults={team:'',step:1,level:null,model:null,revenue:{sponsor:20,media:10,digital:20,support:15,merch:15,live:10,prize:10},contracts:[],crises:[],crisisIndex:0,crisisChoices:{},metrics:{financial:60,access:60,control:60,legal:55,fan:60},metricDeltas:{},reflections:{r1:'',r2:'',r3:''}};
let state=loadState();
function loadState(){try{return {...structuredClone(defaults),...JSON.parse(localStorage.getItem(STORAGE)||'{}')}}catch(e){return structuredClone(defaults)}}
function save(){localStorage.setItem(STORAGE,JSON.stringify(state))}
function clamp(v){return Math.max(0,Math.min(100,Math.round(v)))}
function escapeHtml(s){return String(s).replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]))}
function has(id){return state.contracts.includes(id)}
function publisherDependency(){return (state.revenue.digital||0)+(state.revenue.support||0)}

function renderChoices(){
 const lvl=document.getElementById('levelChoices');lvl.innerHTML='';Object.entries(levelDefs).forEach(([id,d])=>{const el=document.createElement('div');el.className='choice'+(state.level===id?' selected':'');el.innerHTML=`<div class="icon">${d.icon}</div><h3>${d.name}</h3><p>${d.text}</p><div class="effects">${d.effects.map(x=>`<div class="effect"><span>${x[0]}</span><strong class="${x[1]==='↑'?'up':x[1]==='↓'?'down':''}">${x[1]}</strong></div>`).join('')}</div>`;el.onclick=()=>{state.level=id;save();renderChoices();recalc();renderNetwork();};lvl.appendChild(el)});
 const mdl=document.getElementById('modelChoices');mdl.innerHTML='';Object.entries(modelDefs).forEach(([id,d])=>{const el=document.createElement('div');el.className='choice'+(state.model===id?' selected':'');el.innerHTML=`<div class="icon">${d.icon}</div><h3>${d.name}</h3><p>${d.text}</p><div class="effects">${d.effects.map(x=>`<div class="effect"><span>${x[0]}</span><strong class="${x[1]==='↑'?'up':x[1]==='↓'?'down':''}">${x[1]}</strong></div>`).join('')}</div>`;el.onclick=()=>{state.model=id;save();renderChoices();recalc();renderNetwork();};mdl.appendChild(el)});
 document.getElementById('toRevenue').disabled=!(state.level&&state.model);
}
function renderSliders(){const box=document.getElementById('sliders');box.innerHTML='';revenueDefs.forEach(d=>{const row=document.createElement('div');row.className='slider';row.innerHTML=`<div class="sliderhead"><strong><span>${d.icon}</span>${d.name}</strong><span class="pct" id="pct-${d.id}">${state.revenue[d.id]||0}%</span></div><input type="range" min="0" max="60" step="1" value="${state.revenue[d.id]||0}" aria-label="${d.name}" id="range-${d.id}">`;box.appendChild(row);row.querySelector('input').oninput=e=>{state.revenue[d.id]=+e.target.value;document.getElementById('pct-'+d.id).textContent=e.target.value+'%';save();renderRevenue();recalc();renderNetwork();}});renderRevenue()}
function renderRevenue(){
 const total=revenueDefs.reduce((s,d)=>s+(state.revenue[d.id]||0),0);const t=document.getElementById('total');t.textContent=total;t.className='total '+(total===100?'good':'bad');document.getElementById('toContracts').disabled=total!==100;
 let cursor=0;const stops=[];revenueDefs.forEach(d=>{const v=state.revenue[d.id]||0;const end=cursor+v;stops.push(`${d.color} ${cursor}% ${end}%`);cursor=end});document.getElementById('donut').style.background=total?`conic-gradient(${stops.join(',')})`:'#dfe4ee';
 document.getElementById('revLegend').innerHTML=revenueDefs.map(d=>`<span><i style="background:${d.color}"></i>${d.icon} ${d.name.replace('Publisher-mediated ','Digital ').replace('League / publisher ','League ')}</span>`).join('');
 const stability=computeRevenueStability();document.getElementById('stabilityScore').textContent=stability;
 const dep=publisherDependency(),prize=state.revenue.prize||0,max=Math.max(...revenueDefs.map(d=>state.revenue[d.id]||0));let cls='good',msg=`Balanced operating mix. Publisher-linked revenue is ${dep}% of the model.`;if(prize>=25){cls='bad';msg=`Investor alert: ${prize}% of projected revenue depends on prize money, a highly variable operating source.`}else if(dep>=50){cls='warn';msg=`Dependency warning: ${dep}% of your model depends directly on publisher-controlled digital revenue or ecosystem support.`}else if(max>=45){cls='warn';msg=`Concentration warning: one revenue stream represents ${max}% of the model. A single market shock could reshape the budget.`}document.getElementById('revenueAlert').className='alert '+cls;document.getElementById('revenueAlert').textContent=msg;
 document.getElementById('depVal').textContent=dep+'%';document.getElementById('depFill').style.width=dep+'%';
}
function computeRevenueStability(){let weighted=0;revenueDefs.forEach(d=>weighted+=(state.revenue[d.id]||0)*d.weight);const max=Math.max(...revenueDefs.map(d=>state.revenue[d.id]||0));const concentration=Math.max(0,max-35)*.5;return clamp(weighted-concentration+18)}
function renderContracts(){const grid=document.getElementById('contractGrid');grid.innerHTML='';contracts.forEach(c=>{const el=document.createElement('div');const on=state.contracts.includes(c.id);el.className='contract'+(on?' selected':'');el.innerHTML=`<div class="tag">${c.tag}</div><h3>${c.name}</h3><p>${c.text}</p><div class="why">${c.why}</div>`;el.onclick=()=>toggleContract(c.id);grid.appendChild(el)});const slots=document.getElementById('slots');slots.innerHTML='';for(let i=0;i<5;i++){const s=document.createElement('div');s.className='slot'+(i<state.contracts.length?' on':'');slots.appendChild(s)}document.getElementById('slotText').textContent=`${state.contracts.length} / 5 selected`;document.getElementById('toRisk').disabled=state.contracts.length<3;renderNetwork()}
function toggleContract(id){const i=state.contracts.indexOf(id);if(i>=0)state.contracts.splice(i,1);else if(state.contracts.length<5)state.contracts.push(id);save();renderContracts();recalc()}
function computeBaseMetrics(){
 const p=state.model==='closed'?{financial:72,access:38,control:90,legal:58,fan:61}:state.model==='open'?{financial:50,access:88,control:53,legal:45,fan:75}:{financial:66,access:72,control:77,legal:52,fan:79};
 if(state.level==='grassroots'){p.financial-=12;p.access+=7;p.control-=5;p.legal-=8;p.fan+=4}if(state.level==='scholastic'){p.financial-=5;p.access+=2;p.control+=1;p.legal-=1;p.fan+=3}if(state.level==='pro'){p.financial+=5;p.control+=4;p.legal+=2}
 p.financial=(p.financial+computeRevenueStability())/2;const dep=publisherDependency();p.control+=(dep-30)*.18;p.legal+=state.contracts.length*3;if(has('exit'))p.legal+=5;if(has('format'))p.legal+=5;if(has('dispute'))p.legal+=3;if(has('license'))p.legal+=4;if(has('rulebook'))p.legal+=3;return Object.fromEntries(Object.entries(p).map(([k,v])=>[k,clamp(v)]));
}