const STORAGE='spm370_ecosystem_architect_v2';
const revenueDefs=[
{id:'sponsor',icon:'🤝',name:'Sponsorships & brand partnerships',color:'#244f86',weight:.56},
{id:'media',icon:'▶',name:'Media / streaming / advertising',color:'#c23b49',weight:.52},
{id:'digital',icon:'🎮',name:'Publisher-mediated digital revenue',color:'#19a59f',weight:.80},
{id:'support',icon:'🏛',name:'League / publisher support',color:'#7258c7',weight:.83},
{id:'merch',icon:'🛒',name:'Merchandise & consumer products',color:'#e3a020',weight:.62},
{id:'live',icon:'🎟',name:'Live events & ticketing',color:'#2b8fc8',weight:.50},
{id:'prize',icon:'🏆',name:'Prize money',color:'#496376',weight:.25}
];
const levelDefs={
grassroots:{name:'Grassroots / Community',icon:'🕹️',text:'Community-driven competition with low barriers and lighter formal infrastructure.',effects:[['Access','↑'],['Cost','↓'],['IP / safeguarding exposure','↑']]},
scholastic:{name:'Scholastic / Amateur',icon:'🎓',text:'Institutional or developmental competition shaped by eligibility, privacy, safeguarding, and uneven resources.',effects:[['Structure','↑'],['Safeguarding duties','↑'],['Commercial scale','↔']]},
pro:{name:'Professional',icon:'🏟️',text:'High-cost, high-visibility operations with sophisticated contracts, global mobility, sponsors, and publisher dependencies.',effects:[['Revenue potential','↑'],['Cost','↑'],['Legal complexity','↑']]}
};
const modelDefs={
closed:{name:'Closed / Partnered',icon:'🔒',text:'Durable participation rights inside a publisher-defined league or partnership architecture.',effects:[['Planning certainty','↑'],['Publisher control','↑'],['Competitive access','↓']]},
open:{name:'Open Circuit',icon:'🌐',text:'Independent event production and performance-based access inside publisher licensing and tournament rules.',effects:[['Competitive access','↑'],['Organizer freedom','↑'],['Commercial volatility','↑']]},
hybrid:{name:'Hybrid',icon:'🔀',text:'Partner-team economics combined with repeated open pathways into elite competition.',effects:[['Access','↑'],['Flexibility','↑'],['Contract complexity','↑']]}
};
const contracts=[
{id:'participation',name:'Participation / Partnership Agreement',tag:'Access',text:'Defines competitive access, commercial rights, governance obligations, transfer, discipline, and continued eligibility.',why:'Especially valuable in closed or partnered models.',nodes:['publisher','league','team']},
{id:'license',name:'Publisher / Tournament License',tag:'IP',text:'Defines authorized use of game IP, tournament operations, branding, audiovisual content, and related permissions.',why:'Critical where third parties produce competition.',nodes:['publisher','organizer','platform']},
{id:'revenue',name:'Revenue-Sharing Agreement',tag:'Money',text:'Allocates digital-goods, sponsorship, league, media, or other shared commercial revenue.',why:'Protects expectations when publisher-linked revenue is material.',nodes:['publisher','league','team','sponsor']},
{id:'player',name:'Player Agreement',tag:'Labor',text:'Addresses compensation, classification, conduct, appearances, streaming, termination, and roster obligations.',why:'Helps align the real relationship with the chosen labor structure.',nodes:['team','player','league']},
{id:'sponsor',name:'Sponsor Agreement',tag:'Commercial',text:'Covers category exclusivity, activation rights, brand safety, deliverables, conflicts, and termination.',why:'Reduces collision risk across league and team sponsors.',nodes:['team','league','sponsor']},
{id:'exit',name:'Exit / Buy-Back Clause',tag:'Downside',text:'Defines remedies, buy-back rights, wind-down economics, and what happens if the ecosystem fails.',why:'Direct response to first-generation franchise co-dependency risk.',nodes:['publisher','league','team']},
{id:'format',name:'Change-of-Format Clause',tag:'Change',text:'Allocates risk when qualification pathways, seeding, league structure, or competitive format changes.',why:'Especially valuable in hybrid and publisher-controlled ecosystems.',nodes:['publisher','league','team','player']},
{id:'rulebook',name:'Rulebook Incorporation Clause',tag:'Governance',text:'Identifies which rules are incorporated, how changes become binding, and the consequences of violations.',why:'Connects competition rules to enforceable contractual obligations.',nodes:['league','team','player','organizer']},
{id:'dispute',name:'Dispute Resolution Clause',tag:'Enforcement',text:'Defines escalation, venue, arbitration or litigation procedures, and emergency relief mechanisms.',why:'Creates a pathway for inevitable conflict.',nodes:['publisher','league','team','organizer']}
];
const crisisBank=[
{id:'publisherShock',title:'Publisher Shock',tags:['Publisher governance','Change of format'],affects:['publisher','league','team','player'],escalation:'Counsel recommended',text:'The publisher announces a new competitive format beginning next season. Your existing qualification pathway disappears.',options:[
{label:'Accept immediately and redesign around the new pathway.',impact:{financial:2,access:-6,control:5,legal:-4,fan:-3},debrief:'Fast adaptation may preserve the publisher relationship, but it leaves transition costs and existing contractual expectations unresolved.',lesson:'Change-of-format and transition provisions matter because the pathway itself can change.'},
{label:'Renegotiate participation agreements before committing.',impact:{financial:-2,access:1,control:-2,legal:9,fan:2},debrief:'This treats structural change as a risk-allocation problem rather than a purely operational announcement.',lesson:'Qualification rights, transition periods, revenue entitlements, termination, and seeding are plausible negotiation points.'},
{label:'Publicly challenge the redesign and rally teams against it.',impact:{financial:-6,access:4,control:-8,legal:-3,fan:6},debrief:'Public pressure may create leverage or fan legitimacy, but it can worsen the commercial relationship.',lesson:'Public advocacy does not itself resolve the governing agreements.'},
{label:'Exit the ecosystem.',impact:{financial:-12,access:-8,control:-15,legal:4,fan:-4},debrief:'Exit can cap future dependency but may trigger sunk-cost, sponsor, player, and revenue-sharing consequences.',lesson:'The value of an exit clause becomes visible when the business assumptions change.'}]},
{id:'sponsorCollision',title:'Sponsor Collision',tags:['Contracts','Commercial rights'],affects:['league','team','sponsor'],escalation:'Management first; counsel if conflict cannot be cured',text:'The league signs an exclusive automotive sponsor. One of your largest teams already has a competing automotive sponsorship.',options:[
{label:'Force the team to terminate its existing sponsor immediately.',impact:{financial:-8,legal:-5,fan:-4,control:6,access:0},debrief:'Central control may solve the category conflict, but the team may face breach exposure.',lesson:'The participation agreement must clarify how league exclusivity interacts with team sponsor rights.'},
{label:'Negotiate a grandfather period and carve-out.',impact:{financial:1,legal:8,fan:3,control:-2,access:0},debrief:'A negotiated carve-out recognizes the layered contract network and allocates transition cost.',lesson:'Commercial conflicts often require reconciliation across more than one contract.'},
{label:'Let both sponsorships run and hope activation can be separated.',impact:{financial:3,legal:-8,fan:-2,control:-4,access:0},debrief:'Commercially attractive in the short term, but exclusivity language can create cascading breach risk.',lesson:'Revenue opportunity does not erase cross-contract conflict.'}]},
{id:'playerBan',title:'Star Player Banned',tags:['Rulebooks','Contract cascade'],affects:['player','team','league','sponsor','platform'],escalation:'Management triage + legal review',text:'Forty-eight hours before a sponsor showcase, your highest-profile player is suspended under the league rulebook for cheating.',options:[
{label:'Remove the player and immediately audit the linked contracts.',impact:{financial:-5,legal:8,fan:2,control:1,access:0},debrief:'This is the contract-dominoes response: isolate the immediate integrity problem, then trace the linked obligations.',lesson:'Player agreement, rulebook, participation agreement, sponsor obligations, and media commitments may all be implicated.'},
{label:'Ignore the suspension until after the sponsor event.',impact:{financial:4,legal:-14,fan:-8,control:-5,access:0},debrief:'Short-term commercial gain can magnify downstream breach and integrity risk.',lesson:'Rulebook consequences become legally significant when governing agreements incorporate them.'},
{label:'Appeal first and pause all sponsor obligations.',impact:{financial:-3,legal:4,fan:0,control:-1,access:0},debrief:'A dispute pathway may preserve rights, but pausing unrelated obligations may itself create exposure.',lesson:'The underlying contracts determine what can actually be suspended.'}]},
{id:'labor',title:'Labor Challenge',tags:['Classification','Escalation'],affects:['team','player','league'],escalation:'Counsel recommended',text:'A player classified as an independent contractor claims the organization controls training, travel, appearances, streaming obligations, schedule, and exclusivity.',options:[
{label:'Keep the contract label and make no operational changes.',impact:{financial:3,legal:-15,fan:-5,control:4,access:0},debrief:'The label is not the law.',lesson:'Classification turns on applicable law and the realities of the relationship, including control and economic dependence.'},
{label:'Audit the relationship and renegotiate duties and classification.',impact:{financial:-3,legal:11,fan:2,control:-3,access:0},debrief:'This is the legally literate response: inspect the actual relationship before deciding whether the written classification is defensible.',lesson:'Training, scheduling, exclusivity, appearances, and economic structure all matter.'},
{label:'Escalate to employment counsel before changing status.',impact:{financial:-2,legal:9,fan:1,control:0,access:0},debrief:'Escalation is appropriate because classification can trigger wage, tax, benefit, and workplace consequences.',lesson:'Managers should know when an operational problem has become a legal-classification problem.'}]},
{id:'antitrust',title:'Antitrust Alert',tags:['Sherman Act §1','Labor market'],affects:['league','team','player'],escalation:'Counsel required',text:'Twelve independently owned teams agree that none will pay any player more than $150,000.',options:[
{label:'Treat it as a likely Section 1 coordination issue and stop implementation.',impact:{financial:-2,legal:14,fan:2,control:-2,access:0},debrief:'The first diagnostic question is “who agreed with whom?”',lesson:'Coordination among separate economic actors over player compensation can trigger Section 1 scrutiny.'},
{label:'Call it Section 2 because the publisher owns the game.',impact:{financial:0,legal:-9,fan:0,control:0,access:0},debrief:'This collapses distinct antitrust theories.',lesson:'IP ownership is not itself an antitrust violation, and the described conduct is coordination among independently owned teams.'},
{label:'Proceed because competitive balance automatically immunizes the rule.',impact:{financial:5,legal:-15,fan:-4,control:5,access:0},debrief:'A competitive-balance rationale can be relevant, but it does not automatically immunize a coordinated compensation restraint.',lesson:'Purpose matters, but the structure and competitive effect still require analysis.'}]},
{id:'consumer',title:'Consumer Protection Crisis',tags:['COPPA','Consumer protection'],affects:['publisher','player','platform'],escalation:'Counsel recommended',text:'Randomized digital items are heavily marketed to children. Actual dollar prices are obscured by virtual currency and prize probabilities are difficult to find.',options:[
{label:'Review multiple regimes: privacy, consumer protection, advertising, and potentially gambling law.',impact:{financial:-2,legal:13,fan:5,control:0,access:0},debrief:'The issue should not be reduced to “is this gambling?”',lesson:'Multiple legal regimes can independently reshape the monetization model.'},
{label:'Focus only on gambling classification.',impact:{financial:0,legal:-8,fan:-2,control:0,access:0},debrief:'That lens is too narrow.',lesson:'Children’s privacy, deceptive-practice, advertising, pricing, and probability-disclosure issues can matter even without a gambling classification.'},
{label:'Keep the system unchanged because users agreed to platform terms.',impact:{financial:7,legal:-16,fan:-9,control:2,access:0},debrief:'Private assent does not eliminate regulatory risk.',lesson:'Consumer-protection and children’s-privacy obligations may operate independently of platform terms.'}]},
{id:'license',title:'Tournament License Dispute',tags:['IP','Tournament operations'],affects:['publisher','organizer','sponsor','platform'],escalation:'Counsel recommended',text:'A major third-party organizer wants to run a $750,000 event using official branding, game assets, and a modified tournament client outside your published policy.',options:[
{label:'Require a negotiated event license before launch.',impact:{financial:1,legal:10,fan:1,control:6,access:-2},debrief:'Commercial scale, official branding, audiovisual uses, and a modified client make licensing architecture central.',lesson:'Identify the specific rights, software uses, marks, and audiovisual permissions at issue.'},
{label:'Assume publisher ownership automatically makes every element unlawful.',impact:{financial:-2,legal:-4,fan:-6,control:8,access:-7},debrief:'Publisher IP creates substantial leverage, but an absolute-veto shortcut skips the actual legal analysis.',lesson:'Ask which protected uses and license terms are implicated.'},
{label:'Allow the event with no written terms because open circuits need freedom.',impact:{financial:5,legal:-11,fan:4,control:-10,access:8},debrief:'Operational freedom does not remove licensing, branding, broadcast, integrity, or revenue questions.',lesson:'Open competition can still sit inside publisher meta-governance.'}]},
{id:'privacy',title:'Scholastic Data Incident',tags:['FERPA','COPPA','Privacy'],affects:['organizer','player','platform'],escalation:'Counsel / institutional privacy review',text:'A scholastic partner discovers that a third-party platform collected student names, ages, chat logs, and behavioral analytics without a clear institutional data map.',options:[
{label:'Pause data flows and identify what law and institutional rule governs each dataset.',impact:{financial:-3,legal:12,fan:4,control:1,access:-1},debrief:'The key managerial move is source identification.',lesson:'FERPA, COPPA, contracts, and institutional policies do different work. Determine what data exists, who holds it, and what authority governs disclosure.'},
{label:'Treat all student data as “FERPA data” and move on.',impact:{financial:0,legal:-7,fan:-2,control:0,access:0},debrief:'That is overbroad.',lesson:'FERPA concerns covered education records; other privacy rules and platform obligations may separately apply.'},
{label:'Leave the issue to the vendor because the vendor collected the data.',impact:{financial:2,legal:-12,fan:-8,control:-3,access:0},debrief:'Outsourcing collection does not eliminate institutional risk.',lesson:'Vendor contracts, consent, school authority, and applicable privacy regimes still matter.'}]},
{id:'exit',title:'Investor Exit Pressure',tags:['Capital','Governance'],affects:['publisher','team','sponsor'],escalation:'Management + finance/legal governance review',text:'After two loss-making seasons, your lead investor demands a rapid sale. The ecosystem has strong audience growth but weak recurring revenue and no clear buy-back mechanism.',options:[
{label:'Sell immediately to protect the investor relationship.',impact:{financial:4,legal:-5,fan:-5,control:-8,access:0},debrief:'Outside capital can accelerate growth without curing weak unit economics.',lesson:'A rushed sale may expose governance, IP-ownership, and transition gaps.'},
{label:'Use governance rights to negotiate a staged exit and operating-revenue plan.',impact:{financial:2,legal:8,fan:3,control:2,access:0},debrief:'This distinguishes capital from operating revenue and uses governance architecture to manage downside.',lesson:'Investment is not recurring income.'},
{label:'Raise another round without changing the business model.',impact:{financial:7,legal:-2,fan:0,control:-3,access:0},debrief:'Fresh capital may extend runway, but it does not solve weak unit economics.',lesson:'The revenue engine still needs repeatable operating income.'}]},
{id:'integrity',title:'Integrity Breakdown',tags:['Governance','Sponsor confidence'],affects:['organizer','league','team','sponsor','player'],escalation:'Management can lead; counsel if sanctions or contract remedies follow',text:'Two tournament operators apply conflicting anti-cheat standards, and sponsors threaten to suspend activations unless the ecosystem produces a consistent integrity response.',options:[
{label:'Adopt a baseline integrity framework and require transparent enforcement standards.',impact:{financial:1,legal:7,fan:8,control:3,access:-1},debrief:'Governance creates market credibility.',lesson:'Standardization can reduce fragmentation while still leaving room for organizer implementation.'},
{label:'Let every organizer continue independently with no coordination.',impact:{financial:-3,legal:-6,fan:-9,control:-5,access:3},debrief:'Decentralization can encourage experimentation, but inconsistent integrity enforcement can undermine legitimacy.',lesson:'Governance quality is itself part of the business model.'},
{label:'Centralize every tournament decision at the publisher level.',impact:{financial:-2,legal:1,fan:-3,control:12,access:-5},debrief:'Centralization can improve consistency, but it deepens publisher dependence.',lesson:'Solving one governance problem can create a different architecture problem.'}]}
];