const $=(s,r=document)=>r.querySelector(s), $$=(s,r=document)=>[...r.querySelectorAll(s)];
const STORAGE='spm370_ecosystem_architect_season1_v6';
const stakeholderDefs=[
{id:'publisher',name:'Aiko Tanaka',role:'Publisher President',color:'#42d5e7',desc:'Controls the game IP, official competition architecture, licensing, and key commercial permissions.',power:94,legitimacy:78,urgency:72,note:'Publisher power is structural because professional competition generally depends on publisher authorization, licensing, or policy.'},
{id:'team',name:'Marcus Vale',role:'Team Owner',color:'#7c5cff',desc:'Controls talent, brand relationships, fan engagement, and day-to-day competitive operations.',power:62,legitimacy:71,urgency:66,note:'Teams convert talent and audience into commercial value but remain dependent on league access, sponsors, and publisher rules.'},
{id:'player',name:'Nova Reyes',role:'Star Player',color:'#ef4c5d',desc:'Creates competitive performance, audience attention, cultural influence, and sponsor value.',power:58,legitimacy:82,urgency:72,note:'Player leverage rises with scarce talent, fandom, controversy, labor disputes, or moments when performance cannot easily be replaced.'},
{id:'sponsor',name:'Celeste Park',role:'Brand Director',color:'#e3b545',desc:'Provides commercial capital and can trigger rapid consequences through brand-safety and termination rights.',power:72,legitimacy:66,urgency:62,note:'Sponsorship creates financial power. Morality, exclusivity, activation, and termination terms can quickly reshape team economics.'},
{id:'community',name:'Zee Morgan',role:'Community Creator',color:'#4cc38a',desc:'Holds cultural credibility, grassroots reach, fan sentiment, and the ability to mobilize attention.',power:46,legitimacy:92,urgency:52,note:'Community power is often informal. When legitimacy combines with sudden urgency, cultural pressure can become strategically decisive.'},
{id:'investor',name:'Samira Noor',role:'Investor Representative',color:'#ff8c42',desc:'Controls capital, ownership rights, runway, governance influence, and the capacity to scale infrastructure.',power:84,legitimacy:58,urgency:55,note:'IP determines access; capital determines capacity. Investment power can overlap with publisher or organizer ownership without being identical to IP power.'},
{id:'organizer',name:'Idris Cole',role:'Tournament Director',color:'#2b8fc8',desc:'Controls event production, scheduling, broadcast execution, sponsor delivery, and competitive presentation.',power:56,legitimacy:78,urgency:68,note:'Organizers can build strong operational legitimacy while remaining structurally dependent on publisher licensing and tournament rules.'},
{id:'platform',name:'Lena Brooks',role:'Platform Partnerships',color:'#d15bb7',desc:'Controls audience distribution, discoverability, monetization tools, and the viewing environment.',power:69,legitimacy:63,urgency:57,note:'Streaming platforms are not passive pipes. Distribution choices can affect reach, fan loyalty, data, and revenue-sharing.'}
];
const architectureDefs=[
{id:'closed',title:'THE FORTRESS',name:'Closed / Partnered',icon:'⬢',promise:'Planning certainty',risk:'Publisher dependency',desc:'Selected organizations receive durable participation rights through publisher-defined agreements. Modern economics may rely on stipends, digital-goods revenue, and ecosystem support rather than only entry fees.',lesson:'Closed participation can stabilize access and commercial planning, but the value of that stability depends on the economics and on what the governing agreements allow the publisher to change.',metric:{financial:7,access:-14,control:18,resilience:4,legitimacy:-2}},
{id:'open',title:'THE OPEN ARENA',name:'Open Circuit',icon:'◎',promise:'Competitive permeability',risk:'Commercial volatility',desc:'Independent organizers produce events and teams reach competition through rankings, invitations, or qualifiers inside publisher-defined licensing and operating rules.',lesson:'Open does not mean uncontrolled. Counter-Strike illustrates decentralized event production inside centralized meta-governance through licenses, rankings, eligibility rules, and tournament standards.',metric:{financial:-4,access:18,control:-12,resilience:-3,legitimacy:8}},
{id:'hybrid',title:'THE HYBRID PATH',name:'Hybrid',icon:'⇄',promise:'Stability + access',risk:'Contract complexity',desc:'Partner economics coexist with repeated competitive pathways for non-partner teams. The structure can evolve over time as the publisher redesigns qualification and partnership cycles.',lesson:'VCT illustrates why contracts must anticipate structural change: partner status, seeding, qualification, digital revenue, transition rights, and termination can all move.',metric:{financial:3,access:10,control:7,resilience:0,legitimacy:6}}
];
const revenueDefs=[
{id:'sponsor',name:'Sponsorships & brand partnerships',short:'Sponsorship',weight:.58,color:'#244f86',hint:'Commercially important, but exposed to brand priorities and contract renewal.'},
{id:'media',name:'Media / streaming / advertising',short:'Media',weight:.50,color:'#c23b49',hint:'Can expand reach and cash flow, but platform choice and exclusivity affect audience.'},
{id:'digital',name:'Publisher-mediated digital revenue',short:'Digital goods',weight:.82,color:'#19a59f',hint:'Can be repeatable and scalable, while increasing direct publisher dependency.'},
{id:'support',name:'League / publisher support',short:'League support',weight:.85,color:'#7258c7',hint:'Potentially predictable, but controlled by the ecosystem operator.'},
{id:'merch',name:'Merchandise & consumer products',short:'Merchandise',weight:.62,color:'#e3a020',hint:'Diversifies brand value but carries inventory and demand risk.'},
{id:'live',name:'Live events & ticketing',short:'Live events',weight:.52,color:'#2b8fc8',hint:'Builds fan legitimacy and local revenue but carries event costs.'},
{id:'prize',name:'Prize money',short:'Prize money',weight:.24,color:'#496376',hint:'Highly visible but usually too volatile to serve as a recurring operating base.'}
];
const contractDefs=[
{id:'participation',tag:'ACCESS',name:'Participation / Partnership Agreement',text:'Defines competitive access, commercial rights, governance duties, discipline, transfer, and continued eligibility.',omit:'Without it: access rights and publisher obligations can be dangerously unclear.'},
{id:'license',tag:'IP',name:'Publisher / Tournament License',text:'Defines authorized use of game IP, branding, tournament operations, audiovisual content, and software.',omit:'Without it: commercial events can collide with licensing, software, branding, or broadcast restrictions.'},
{id:'revenue',tag:'MONEY',name:'Revenue-Sharing Agreement',text:'Allocates digital-goods, sponsorship, media, league, or other shared commercial revenue.',omit:'Without it: revenue expectations can become assumptions instead of enforceable rights.'},
{id:'player',tag:'LABOR',name:'Player Agreement',text:'Addresses compensation, classification, conduct, streaming, appearances, termination, and roster obligations.',omit:'Without it: control, compensation, conduct, and classification risk can become operational chaos.'},
{id:'sponsor',tag:'COMMERCIAL',name:'Sponsor Agreement',text:'Covers activation, exclusivity, category conflicts, brand safety, deliverables, and termination.',omit:'Without it: one sponsor can collide with league, team, creator, or platform commitments.'},
{id:'exit',tag:'DOWNSIDE',name:'Exit / Buy-Back Clause',text:'Defines wind-down economics, remedies, buy-back rights, and what happens if the ecosystem fails.',omit:'Without it: long-term commitments can outlive the assumptions that justified them.'},
{id:'format',tag:'CHANGE',name:'Change-of-Format Clause',text:'Allocates risk when pathways, seeding, league structure, or competitive format changes.',omit:'Without it: a publisher redesign can destroy the value assumptions behind existing deals.'},
{id:'rulebook',tag:'GOVERNANCE',name:'Rulebook Incorporation Clause',text:'Specifies which competition rules become binding, who may change them, and what violations trigger.',omit:'Without it: rulebook authority and contractual consequences can become uncertain.'},
{id:'dispute',tag:'ENFORCEMENT',name:'Dispute Resolution Clause',text:'Defines escalation, venue, arbitration or litigation, timing, and emergency relief.',omit:'Without it: the process for resolving urgent disputes may be as contested as the merits.'}
];
const concepts={
salience:['Stakeholder Salience','Stakeholder prominence changes as power, legitimacy, and urgency combine. A stakeholder with all three attributes will usually demand the most managerial attention.'],
publisherPower:['Publisher Gatekeeping','Game IP, licenses, tournament policies, software terms, and broadcast controls can give publishers substantial gatekeeping power over organized commercial competition.'],
capitalPower:['Capital vs. IP Power','IP determines access; capital determines capacity. Investment ownership can shape strategy and infrastructure without replacing the publisher’s underlying IP authority.'],
meta:['Publisher Meta-Governance','An ecosystem can have decentralized event production while the publisher still structures competition through licensing, rankings, eligibility rules, and operating requirements.'],
partnered:['Closed / Partnered Architecture','Durable participation can improve planning certainty while deepening dependence on publisher-controlled access, commercial rights, governance, and exit terms.'],
hybrid:['Structural Change Risk','Hybrid ecosystems can change pathways over time. Change-of-format provisions, transition rights, seeding, revenue entitlements, and termination can become central risk-allocation tools.'],
recurring:['Recurring Revenue','Operating sustainability depends on repeatable revenue, not merely investor capital or tournament winnings. Revenue stability and strategic independence are separate questions.'],
dependency:['Publisher Dependency','Revenue can be stable and still create strategic vulnerability when the rights holder controls access to the revenue source or participation system.'],
contractWeb:['Web of Contracts','Player, team, league, sponsor, platform, and venue obligations can cross-reference one another. A single breach can trigger consequences across the network.'],
rulebook:['Rulebook Incorporation','A rulebook can become contractually consequential when an agreement incorporates it by reference. Notice, assent, change authority, governing law, and remedies still matter.'],
classification:['The Label Is Not the Law','Worker classification turns on applicable law and the realities of the relationship, including control over training, scheduling, exclusivity, appearances, and economic dependence.'],
antitrust1:['Section 1 Coordination','When separate economic actors coordinate to restrict competition—such as agreements affecting player pay—the first antitrust question is often “who agreed with whom?”'],
consumer:['Multiple Consumer-Protection Regimes','Loot-box and digital-item risk can implicate consumer protection, children’s privacy, advertising, pricing, and probability disclosures even without a legal gambling classification.'],
morality:['Morality & Brand-Safety Clauses','Sponsor contracts can allocate reputational risk through morality, termination, exclusivity, and brand-safety provisions. The scope of those rights depends on the drafting.'],
integrity:['Governance Legitimacy','Independent integrity bodies can possess legitimacy without statutory power. Their effectiveness often depends on publisher, organizer, or league recognition and enforcement.'],
betting:['Betting & Competitive Integrity','Wagering can create commercial value while increasing match-fixing, data-sharing, underage-gambling, and regulatory risk. Trust in outcomes is part of the product.'],
platform:['Platform Power','Streaming platforms shape distribution, discoverability, monetization, community features, and audience reach. Platform choice can therefore affect both commercial and cultural legitimacy.'],
ownership:['Ownership Networks','Common ownership does not itself establish wrongdoing, but managers should examine control rights, information flows, conflicts of interest, disclosures, and organizational firewalls.']
};
const crisisBank=[
{id:'pathway',title:'THE PATHWAY DISAPPEARS',cut:'The publisher redesigns elite qualification before Year Two.',text:'Partner organizations and challenger teams built sponsor, roster, and revenue plans around the current pathway. The publisher announces a new structure that changes seeding and qualification.',tags:['Publisher governance','Structural change'],concept:'hybrid',salience:{publisher:[8,0,12],team:[0,2,10],player:[0,1,7]},options:[
{label:'Accept immediately and rebuild around the new pathway.',impact:{financial:2,access:-5,control:5,resilience:-3,legitimacy:-2},result:'Fast adaptation preserves the publisher relationship but leaves transition costs and prior expectations unresolved.'},
{label:'Renegotiate transition, seeding, revenue, and exit terms before committing.',impact:{financial:-2,access:1,control:-2,resilience:10,legitimacy:3},result:'This treats structural change as a risk-allocation problem rather than merely an operational announcement.'},
{label:'Mobilize teams and community pressure against the redesign.',impact:{financial:-5,access:5,control:-6,resilience:-2,legitimacy:7},result:'Public legitimacy can create leverage, but it does not replace the governing agreements.'}]},
{id:'sponsor',title:'THE SPONSOR WALKS',cut:'A star player creates a brand crisis during a livestream.',text:'Within 24 hours, your largest automotive sponsor invokes its brand-safety rights and announces termination. The team warns that losing the deal will force roster cuts.',tags:['Sponsor power','Contract risk'],concept:'morality',salience:{sponsor:[10,7,18],player:[4,-4,12],team:[0,0,14]},options:[
{label:'Accept termination and immediately cut costs.',impact:{financial:-12,access:0,control:0,resilience:0,legitimacy:1},result:'This limits cash burn but does not test whether the sponsor actually has the contractual right to terminate.'},
{label:'Review morality, cure, notice, and termination language before responding.',impact:{financial:-4,access:0,control:0,resilience:10,legitimacy:3},result:'The right response depends on the contract’s actual trigger, discretion, notice, and remedy language.'},
{label:'Publicly attack the sponsor for abandoning the team.',impact:{financial:-7,access:0,control:-2,resilience:-5,legitimacy:-4},result:'Public pressure may mobilize fans but can magnify reputational and contractual risk.'}]},
{id:'capital',title:'CAPITAL MEETS IP',cut:'Your lead investor expands across both tournament infrastructure and game ownership.',text:'Rival publishers and sponsors begin asking whether common ownership could influence scheduling, promotion, access to information, or competitive independence.',tags:['Investment ownership','Governance'],concept:'ownership',salience:{investor:[12,-2,10],publisher:[4,0,5],organizer:[2,0,5]},options:[
{label:'Treat ownership overlap as irrelevant because no violation is proven.',impact:{financial:3,access:0,control:4,resilience:-9,legitimacy:-8},result:'No legal violation is established by the facts alone, but ignoring governance and perception risk is strategically weak.'},
{label:'Create disclosure rules, information barriers, and conflict-review procedures.',impact:{financial:-1,access:1,control:-2,resilience:10,legitimacy:8},result:'Governance can address both actual conflicts and stakeholder perceptions without assuming that common ownership is unlawful.'},
{label:'Exclude all entities connected to the investor.',impact:{financial:-10,access:-7,control:5,resilience:1,legitimacy:-2},result:'A categorical exclusion may create new commercial and competition concerns of its own.'}]},
{id:'betting',title:'ODDS MOVE BEFORE THE MATCH',cut:'Betting markets signal something is wrong.',text:'An underdog’s odds collapse minutes before a match. The team then makes obvious mistakes. An integrity body requests betting data, but a major betting partner refuses to share proprietary information.',tags:['Integrity','Betting'],concept:'betting',salience:{organizer:[3,8,15],sponsor:[4,-2,9],community:[0,5,10]},options:[
{label:'Pause competition, preserve evidence, and coordinate an integrity investigation.',impact:{financial:-4,access:-1,control:2,resilience:12,legitimacy:10},result:'Competitive integrity is a market asset. Preserving evidence and defining cooperation duties can matter as much as immediate revenue.'},
{label:'Continue the event unless law enforcement intervenes.',impact:{financial:5,access:0,control:0,resilience:-10,legitimacy:-12},result:'Waiting may protect the schedule while degrading trust in competitive outcomes.'},
{label:'Ban the team instantly based on social-media accusations.',impact:{financial:-3,access:-5,control:8,resilience:-7,legitimacy:-4},result:'Urgency does not eliminate the need for credible investigation and fair process.'}]},
{id:'platform',title:'THE PLATFORM WAR',cut:'A lucrative exclusivity deal changes where fans can watch.',text:'A platform offers guaranteed money for exclusive streaming rights, but your core community uses a rival service and warns that discoverability, chat culture, and fan engagement will suffer.',tags:['Distribution','Audience'],concept:'platform',salience:{platform:[12,2,10],community:[2,8,9],sponsor:[3,0,5]},options:[
{label:'Take the guaranteed exclusive deal.',impact:{financial:10,access:-8,control:-4,resilience:1,legitimacy:-7},result:'Guaranteed revenue can reduce financial uncertainty while shrinking reach and community legitimacy.'},
{label:'Negotiate limited exclusivity plus co-streaming and highlight rights.',impact:{financial:5,access:2,control:-1,resilience:6,legitimacy:5},result:'Rights design can convert a binary platform choice into a portfolio of distribution permissions.'},
{label:'Reject all platform guarantees and remain fully open.',impact:{financial:-5,access:8,control:2,resilience:-2,legitimacy:7},result:'Open reach can strengthen accessibility while giving up predictable media economics.'}]},
{id:'labor',title:'THE CONTRACTOR CHALLENGE',cut:'A player says the contract label does not match reality.',text:'Your organization calls players independent contractors but controls training, travel, appearances, streaming schedules, exclusivity, and competition availability.',tags:['Labor classification','Player rights'],concept:'classification',salience:{player:[8,8,16],team:[2,-4,11]},options:[
{label:'Keep the classification because the written contract says contractor.',impact:{financial:4,access:0,control:5,resilience:-15,legitimacy:-8},result:'The label is not the law. The legal test depends on jurisdiction and the real relationship.'},
{label:'Audit actual control and renegotiate classification or operating practices.',impact:{financial:-4,access:0,control:-3,resilience:13,legitimacy:6},result:'This aligns management practice with the legal question instead of relying on terminology.'},
{label:'Escalate to employment counsel before changing status.',impact:{financial:-2,access:0,control:0,resilience:10,legitimacy:3},result:'Classification can trigger wage, tax, benefit, and workplace consequences, making escalation appropriate.'}]},
{id:'antitrust',title:'THE PAY CEILING PACT',cut:'Twelve independently owned teams agree on a player-pay ceiling.',text:'The teams say the rule protects competitive balance and financial sustainability. Players say the teams have agreed not to compete for their labor above the threshold.',tags:['Sherman Act §1','Labor market'],concept:'antitrust1',salience:{player:[6,6,15],team:[5,-3,12]},options:[
{label:'Pause the agreement and obtain antitrust review.',impact:{financial:-2,access:0,control:-3,resilience:15,legitimacy:4},result:'The key diagnostic is coordination among separate economic actors competing for player services.'},
{label:'Call it automatically lawful because competitive balance is a good goal.',impact:{financial:6,access:0,control:7,resilience:-16,legitimacy:-6},result:'A legitimate objective does not automatically immunize a coordinated restraint on compensation.'},
{label:'Treat it only as a Section 2 monopoly problem because the publisher owns the game.',impact:{financial:0,access:0,control:0,resilience:-9,legitimacy:0},result:'That collapses distinct antitrust theories. The described conduct is coordination among independent teams.'}]},
{id:'consumer',title:'THE DIGITAL GOODS INQUIRY',cut:'Regulators focus on children, virtual currency, and randomized rewards.',text:'Rare digital items are marketed heavily to young users. Actual dollar prices are obscured by virtual currency and probabilities are difficult to locate.',tags:['COPPA','Consumer protection'],concept:'consumer',salience:{publisher:[5,-7,14],community:[0,8,12],platform:[2,0,6]},options:[
{label:'Review privacy, consumer protection, advertising, pricing, and probability disclosure.',impact:{financial:-3,access:0,control:0,resilience:14,legitimacy:9},result:'The legal issue does not depend solely on whether the mechanic is legally classified as gambling.'},
{label:'Analyze only gambling law.',impact:{financial:0,access:0,control:0,resilience:-8,legitimacy:-3},result:'That is too narrow. Children’s privacy and deceptive-practice theories can independently reshape the model.'},
{label:'Rely on user acceptance of platform terms.',impact:{financial:8,access:0,control:3,resilience:-15,legitimacy:-11},result:'Private assent does not eliminate regulatory obligations.'}]},
{id:'license',title:'THE UNLICENSED MAJOR',cut:'A creator announces a $500K invitational using official assets and a modified client.',text:'The event has major sponsors and co-streaming plans but no formal publisher approval. It is scheduled to launch in 72 hours.',tags:['IP','Tournament policy'],concept:'publisherPower',salience:{publisher:[10,0,12],organizer:[0,4,14],community:[0,5,8]},options:[
{label:'Identify the exact protected uses, software terms, marks, and tournament policies before acting.',impact:{financial:-1,access:0,control:4,resilience:12,legitimacy:5},result:'Publisher ownership creates substantial leverage, but legally literate management identifies the specific rights and permissions at issue.'},
{label:'Assume game ownership creates an automatic veto over every element of the event.',impact:{financial:-3,access:-7,control:12,resilience:-3,legitimacy:-8},result:'That shortcut skips the actual licensing, copyright, trademark, software, and commercial analysis.'},
{label:'Ignore the issue because open competition should be free.',impact:{financial:5,access:8,control:-10,resilience:-13,legitimacy:3},result:'Competitive openness does not eliminate publisher IP, software, branding, broadcast, or tournament-policy risk.'}]},
{id:'governance',title:'THE SANCTION NO ONE ENFORCES',cut:'An integrity body issues bans. The publisher refuses to recognize them.',text:'Sponsors and fans support the investigation, but the sanctioned players remain eligible for the publisher’s largest events.',tags:['Governance','Legitimacy'],concept:'integrity',salience:{publisher:[6,-4,10],organizer:[0,3,8],community:[0,8,10]},options:[
{label:'Build a publisher-organizer enforcement protocol before the next incident.',impact:{financial:-1,access:0,control:0,resilience:12,legitimacy:9},result:'Governance legitimacy becomes more durable when institutions agree in advance on recognition and enforcement.'},
{label:'Treat the integrity body’s legitimacy as equivalent to legal enforcement power.',impact:{financial:0,access:0,control:-1,resilience:-8,legitimacy:-5},result:'Legitimacy can influence behavior without creating statutory or contractual authority.'},
{label:'Let each organizer decide independently.',impact:{financial:1,access:2,control:-4,resilience:-7,legitimacy:-8},result:'Fragmentation can preserve local discretion while eroding consistency and sponsor confidence.'}]}
];
let state={team:'NEXUS//ARENA',episode:1,priorities:[],architecture:null,revenue:{sponsor:28,media:12,digital:22,support:15,merch:10,live:8,prize:5},contracts:[],metrics:{financial:55,access:55,control:55,resilience:55,legitimacy:55},salience:Object.fromEntries(stakeholderDefs.map(s=>[s.id,{p:s.power,l:s.legitimacy,u:s.urgency}])),crises:[],crisisIndex:0,crisisAnswers:{},unlocked:['salience','publisherPower','capitalPower'],yearDecision:null};
let soundOn=true,audioCtx=null;
function clamp(n,a=0,b=100){return Math.max(a,Math.min(b,n))}function save(){localStorage.setItem(STORAGE,JSON.stringify(state))}function load(){try{const x=JSON.parse(localStorage.getItem(STORAGE));if(x)state={...state,...x}}catch(e){}}function tone(freq=440,d=.08,type='sine',vol=.035){if(!soundOn)return;audioCtx=audioCtx||new (window.AudioContext||window.webkitAudioContext)();const o=audioCtx.createOscillator(),g=audioCtx.createGain();o.type=type;o.frequency.value=freq;g.gain.setValueAtTime(vol,audioCtx.currentTime);g.gain.exponentialRampToValueAtTime(.0001,audioCtx.currentTime+d);o.connect(g).connect(audioCtx.destination);o.start();o.stop(audioCtx.currentTime+d)}function sting(){[330,494,659].forEach((f,i)=>setTimeout(()=>tone(f,.14,'triangle',.025),i*85))}function alarm(){[160,130,180].forEach((f,i)=>setTimeout(()=>tone(f,.18,'sawtooth',.025),i*120))}
function unlockConcept(id,show=true){if(!state.unlocked.includes(id))state.unlocked.push(id);save();renderIntel();if(show){const [t,x]=concepts[id];$('#unlockTitle').textContent=t;$('#unlockText').textContent=x;$('#unlock').classList.remove('hidden');sting()}}
function startOpening(){let i=0;const shots=$$('.shot');const next=()=>{shots.forEach(s=>s.classList.remove('active'));shots[i].classList.add('active');if(i<5){tone(180+i*55,.11,'triangle',.02);i++;setTimeout(next,i===5?1350:1150)}};next()}
$('#skipOpening').onclick=()=>{$$('.shot').forEach(s=>s.classList.remove('active'));$('.shot[data-shot="5"]').classList.add('active')};$('#enterSim').onclick=()=>{$('#coldOpen').classList.add('hidden');$('#sim').classList.remove('hidden');sting()};$('#soundBtn').onclick=()=>{soundOn=!soundOn;$('#soundBtn').textContent=soundOn?'SFX ON':'SFX OFF';$('#soundBtn').setAttribute('aria-pressed',String(!soundOn));tone(520)};$('#resetBtn').onclick=()=>{if(confirm('Reset Season One and start over?')){localStorage.removeItem(STORAGE);location.reload()}};
function renderStakeholders(){const box=$('#stakeholderGrid');box.innerHTML=stakeholderDefs.map(s=>`<article class="stake-card" style="--role:${s.color}" data-stake="${s.id}"><div class="stake-top"><div class="portrait"><div class="hair"></div><div class="face"><i></i><i></i></div><div class="jacket"></div></div></div><div class="stake-body"><small>${s.role.toUpperCase()}</small><h3>${s.name}</h3><p>${s.desc}</p><div class="plu"><div><b>POWER</b><span>${s.power}</span></div><div><b>LEGIT.</b><span>${s.legitimacy}</span></div><div><b>URGENCY</b><span>${s.urgency}</span></div></div></div><div class="role-note">${s.note}</div></article>`).join('');$$('.stake-card').forEach(c=>c.onclick=()=>c.classList.toggle('open'))}
function renderPriorityChoices(){const box=$('#priorityChoices');box.innerHTML=stakeholderDefs.map(s=>`<button class="priority-choice ${state.priorities.includes(s.id)?'selected':''}" data-priority="${s.id}"><b>${s.role}</b><span>${s.name}</span></button>`).join('');$$('[data-priority]').forEach(b=>b.onclick=()=>{const id=b.dataset.priority;if(state.priorities.includes(id))state.priorities=state.priorities.filter(x=>x!==id);else if(state.priorities.length<3)state.priorities.push(id);renderPriorityChoices();renderPrioritySeats();renderIntel();$('#toArchitecture').disabled=state.priorities.length!==3;save();tone(420+state.priorities.length*55)})}
function renderPrioritySeats(){const seat=$('#prioritySeats');seat.innerHTML=state.priorities.map(id=>{const s=stakeholderDefs.find(x=>x.id===id);return `<div class="seat-token" style="border-color:${s.color}">${s.role.replace(' Representative','')}</div>`}).join('');const names=state.priorities.map(id=>stakeholderDefs.find(x=>x.id===id).role);$('#priorityQuote').textContent=names.length===3?`Your board prioritizes ${names[0]}, ${names[1]}, and ${names[2]}. Every later tradeoff will be judged against that choice.`:'“The stakeholders you prioritize today will shape which problems feel acceptable tomorrow.”'}
function renderVisions(){const box=$('#visionDeck');box.innerHTML=architectureDefs.map(a=>`<article class="vision-card ${state.architecture===a.id?'selected':''}" data-vision="${a.id}"><div class="vision-art ${a.id}"><div class="${a.id==='closed'?'stadium-glyph':a.id==='open'?'circuit-glyph':'path-glyph'}">${a.icon}</div></div><div class="vision-body"><small>${a.title}</small><h3>${a.name}</h3><p>${a.desc}</p><div class="promise-risk"><div><b>PROMISE</b><span>${a.promise}</span></div><div><b>RISK</b><span>${a.risk}</span></div></div></div></article>`).join('');$$('[data-vision]').forEach(c=>c.onclick=()=>selectArchitecture(c.dataset.vision))}
function selectArchitecture(id){const prev=state.architecture;if(prev&&prev!==id){const a=architectureDefs.find(x=>x.id===prev);Object.keys(a.metric).forEach(k=>state.metrics[k]=clamp(state.metrics[k]-a.metric[k]))}state.architecture=id;const a=architectureDefs.find(x=>x.id===id);if(prev!==id)Object.keys(a.metric).forEach(k=>state.metrics[k]=clamp(state.metrics[k]+a.metric[k]));renderVisions();$('#visionDetail').classList.remove('hidden');$('#visionDetail').innerHTML=`<h3>${a.name}: what you are really choosing</h3><p>${a.lesson}</p>`;$('#toRevenue').disabled=false;unlockConcept(id==='closed'?'partnered':id==='open'?'meta':'hybrid',true);renderIntel();save()}
function renderRevenue(){const box=$('#revenueSliders');box.innerHTML=revenueDefs.map(r=>`<div class="rev-row"><label>${r.name}<small>${r.hint}</small></label><input type="range" min="0" max="60" value="${state.revenue[r.id]}" data-rev="${r.id}"><b id="rv-${r.id}">${state.revenue[r.id]}%</b></div>`).join('');$$('[data-rev]').forEach(i=>i.oninput=()=>{state.revenue[i.dataset.rev]=+i.value;renderRevenueIntel();save()});renderRevenueIntel()}
function revenueTotal(){return Object.values(state.revenue).reduce((a,b)=>a+b,0)}function revenueStability(){const total=Math.max(1,revenueTotal());let weighted=0;revenueDefs.forEach(r=>weighted+=(state.revenue[r.id]||0)*r.weight);const concentration=Math.max(...Object.values(state.revenue));return clamp(Math.round(weighted/total*100-(concentration>45?(concentration-45)*.45:0)),0,100)}function publisherDependency(){return (state.revenue.digital||0)+(state.revenue.support||0)}
function renderRevenueIntel(){const total=revenueTotal();$('#revTotal').textContent=total;revenueDefs.forEach(r=>{const el=$(`#rv-${r.id}`);if(el)el.textContent=(state.revenue[r.id]||0)+'%'});let p=0,stops=[];revenueDefs.forEach(r=>{const v=state.revenue[r.id]||0;const a=p/Math.max(1,total)*100;p+=v;const b=p/Math.max(1,total)*100;stops.push(`${r.color} ${a}% ${b}%`)});$('#donut').style.background=`conic-gradient(${stops.join(',')})`;const score=revenueStability(),dep=publisherDependency();$('#revScore').textContent=score+'/100';let msg=`${dep}% of your mix is directly publisher-linked.`;if(state.revenue.prize>20)msg+=` Prize money is ${state.revenue.prize}%, which makes recurring operations harder to forecast.`;else if(dep>50)msg+=` Your model may be stable but strategically dependent on publisher-controlled revenue.`;else if(Math.max(...Object.values(state.revenue))>45)msg+=' One revenue stream dominates the model.';else msg+=' The mix is comparatively diversified.';$('#revMessage').textContent=msg;$('#revDependency').innerHTML=`<b>Publisher-linked dependency: ${dep}%</b><div class="dep-track"><i style="width:${dep}%"></i></div>`;$('#toLegal').disabled=total!==100;if(total===100){state.metrics.financial=clamp(40+Math.round(score*.45));unlockConcept('recurring',false);if(dep>=40)unlockConcept('dependency',false)}renderIntel()}
function renderContracts(){const box=$('#contractDeck');box.innerHTML=contractDefs.map(c=>`<article class="contract-card ${state.contracts.includes(c.id)?'selected':''}" data-contract="${c.id}"><span class="tag">${c.tag}</span><h3>${c.name}</h3><p>${c.text}</p><div class="omit">${c.omit}</div></article>`).join('');$$('[data-contract]').forEach(c=>c.onclick=()=>{const id=c.dataset.contract;if(state.contracts.includes(id))state.contracts=state.contracts.filter(x=>x!==id);else if(state.contracts.length<5)state.contracts.push(id);renderContracts();renderLoadout();$('#launchSeason').disabled=state.contracts.length!==5;save();tone(360+state.contracts.length*50)});renderLoadout()}
function renderLoadout(){$('#loadoutSlots').innerHTML=Array.from({length:5},(_,i)=>`<i class="${i<state.contracts.length?'filled':''}"></i>`).join('');$('#loadoutCount').textContent=`${state.contracts.length} / 5`}
function applyPriorityBias(){state.priorities.forEach(id=>{if(id==='publisher')state.metrics.control=clamp(state.metrics.control+4);if(id==='team')state.metrics.financial=clamp(state.metrics.financial+3);if(id==='player')state.metrics.legitimacy=clamp(state.metrics.legitimacy+4);if(id==='sponsor')state.metrics.financial=clamp(state.metrics.financial+4);if(id==='community')state.metrics.legitimacy=clamp(state.metrics.legitimacy+6);if(id==='investor')state.metrics.financial=clamp(state.metrics.financial+5);if(id==='organizer')state.metrics.resilience=clamp(state.metrics.resilience+3);if(id==='platform')state.metrics.access=clamp(state.metrics.access+4)})}
function startSeason(){applyPriorityBias();state.metrics.resilience=clamp(state.metrics.resilience+state.contracts.length*3);if(state.contracts.includes('exit'))state.metrics.resilience=clamp(state.metrics.resilience+4);if(state.contracts.includes('format'))state.metrics.resilience=clamp(state.metrics.resilience+5);if(state.contracts.includes('rulebook'))unlockConcept('rulebook',false);unlockConcept('contractWeb',false);const categories=[['pathway','capital','platform'],['sponsor','labor','consumer'],['betting','antitrust','license','governance']];state.crises=categories.map(g=>g[Math.floor(Math.random()*g.length)]);state.crisisIndex=0;state.crisisAnswers={};save();showEpisode(6);showCrisisCutin()}
function currentCrisis(){return crisisBank.find(c=>c.id===state.crises[state.crisisIndex])}function showCrisisCutin(){const c=currentCrisis();if(!c)return;alarm();$('#cutEyebrow').textContent=`YEAR ONE // INCIDENT ${state.crisisIndex+1} OF ${state.crises.length}`;$('#cutTitle').textContent=c.title;$('#cutText').textContent=c.cut;$('#cutin').classList.remove('hidden')}
$('#cutContinue').onclick=()=>{$('#cutin').classList.add('hidden');renderCrisis()};
function renderCrisis(){const c=currentCrisis(),answered=state.crisisAnswers[c.id];const box=$('#crisisStage');box.innerHTML=`<article class="crisis-card"><div class="crisis-banner"><small>${c.tags.join(' · ').toUpperCase()}</small><h3>${c.title}</h3><p>${c.text}</p></div><div class="crisis-options">${c.options.map((o,i)=>`<button class="crisis-option" data-answer="${i}" ${answered!==undefined?'disabled':''}>${String.fromCharCode(65+i)}. ${o.label}</button>`).join('')}</div>${answered!==undefined?crisisResult(c,answered):''}</article>`;$$('[data-answer]').forEach(b=>b.onclick=()=>answerCrisis(+b.dataset.answer))}
function crisisResult(c,i){const o=c.options[i];return `<div class="crisis-result"><h4>CONSEQUENCE</h4><p>${o.result}</p><div class="shift-grid"><div><b>FINANCIAL</b><strong>${fmt(o.impact.financial)}</strong></div><div><b>RESILIENCE</b><strong>${fmt(o.impact.resilience)}</strong></div><div><b>LEGITIMACY</b><strong>${fmt(o.impact.legitimacy)}</strong></div></div><button class="nextbtn" id="crisisNext">${state.crisisIndex<state.crises.length-1?'NEXT INCIDENT →':'CALL THE BOARD →'}</button></div>`}
function fmt(n){return n>0?'+'+n:String(n)}function answerCrisis(i){const c=currentCrisis(),o=c.options[i];state.crisisAnswers[c.id]=i;Object.entries(o.impact).forEach(([k,v])=>state.metrics[k]=clamp(state.metrics[k]+v));Object.entries(c.salience||{}).forEach(([id,vals])=>{const s=state.salience[id];s.p=clamp(s.p+vals[0]);s.l=clamp(s.l+vals[1]);s.u=clamp(s.u+vals[2])});save();renderIntel();renderCrisis();unlockConcept(c.concept,true);setTimeout(()=>{const b=$('#crisisNext');if(b)b.onclick=advanceCrisis},50)}
function advanceCrisis(){if(state.crisisIndex<state.crises.length-1){state.crisisIndex++;save();showCrisisCutin()}else{showEpisode(7);renderFinal();sting()}}
function salienceScore(s){return Math.round((s.p+s.l+s.u)/3)}function salienceLeader(){return Object.entries(state.salience).sort((a,b)=>salienceScore(b[1])-salienceScore(a[1]))[0]}
function archetype(){if(state.architecture==='closed'&&state.metrics.control>70)return 'THE CONTROLLED FORTRESS';if(state.architecture==='open'&&state.metrics.access>70)return 'THE OPEN MARKETPLACE';if(state.architecture==='hybrid'&&state.metrics.legitimacy>65)return 'THE ADAPTIVE HYBRID';if(publisherDependency()>50)return 'THE PUBLISHER MACHINE';if(state.metrics.resilience>75)return 'THE RESILIENT NETWORK';return 'THE BALANCED ECOSYSTEM'}
function renderFinal(){const leaderId=salienceLeader()[0],leader=stakeholderDefs.find(s=>s.id===leaderId);const missing=contractDefs.filter(c=>!state.contracts.includes(c.id)).slice(0,3);const topRev=revenueDefs.map(r=>[r.name,state.revenue[r.id]]).sort((a,b)=>b[1]-a[1])[0];$('#finalReport').innerHTML=`<div class="dna-card"><small>YOUR ECOSYSTEM DNA</small><h3>${archetype()}</h3><p>${state.team}</p><div class="dna-grid"><div><b>ARCHITECTURE</b><span>${architectureDefs.find(a=>a.id===state.architecture)?.name||'—'}</span></div><div><b>LEAD REVENUE</b><span>${topRev[0]} · ${topRev[1]}%</span></div><div><b>PUBLISHER DEPENDENCY</b><span>${publisherDependency()}%</span></div><div><b>LEGAL RESILIENCE</b><span>${state.metrics.resilience}/100</span></div><div><b>SALIENCE LEADER</b><span>${leader.role}</span></div><div><b>FAN / STAKEHOLDER LEGITIMACY</b><span>${state.metrics.legitimacy}/100</span></div></div></div><div class="board-card"><h3>Board briefing</h3><p><strong>What worked:</strong> Your model finished Year One with financial sustainability ${state.metrics.financial}/100 and competitive access ${state.metrics.access}/100.</p><p><strong>What matters next:</strong> ${leader.role} currently has the highest combined salience in your ecosystem.</p><p><strong>Missing protections worth discussing:</strong></p><ul>${missing.map(m=>`<li>${m.name}</li>`).join('')}</ul><p>The board should decide whether the current tradeoffs are acceptable—not whether every metric can be maximized.</p></div>`;renderPlaybook()}
function renderPlaybook(){$('#playbookGrid').innerHTML=state.unlocked.map(id=>concepts[id]).filter(Boolean).map(([t,x])=>`<div class="concept-card"><b>${t}</b><p>${x}</p></div>`).join('')}
function renderIntel(){if(!$('#intelTeam'))return;$('#intelTeam').textContent=state.team||'NEXUS//ARENA';$('#intelModel').textContent=state.architecture?architectureDefs.find(a=>a.id===state.architecture).name.toUpperCase():'UNSET';$('#intelPriorities').innerHTML=state.priorities.length?state.priorities.map(id=>`<span>${stakeholderDefs.find(s=>s.id===id).role}</span>`).join(''):'<span>Not selected</span>';const bars=[['Financial',state.metrics.financial],['Access',state.metrics.access],['Control',state.metrics.control],['Resilience',state.metrics.resilience],['Legitimacy',state.metrics.legitimacy]];$('#healthBars').innerHTML=bars.map(([n,v])=>`<div class="health-row"><span>${n}</span><i style="--w:${v}%"></i><b>${v}</b></div>`).join('');const [lid]=salienceLeader(),lead=stakeholderDefs.find(s=>s.id===lid);$('#salienceLeader').textContent=lead.role;const top=Object.entries(state.salience).sort((a,b)=>salienceScore(b[1])-salienceScore(a[1])).slice(0,3);$('#salienceMini').innerHTML=top.map(([id,s])=>{const d=stakeholderDefs.find(x=>x.id===id);return `<div class="sal-mini-row"><span>${d.role.split(' ')[0]}</span><i style="--w:${s.p}%;--c:#42d5e7"></i><i style="--w:${s.l}%;--c:#e3b545"></i><i style="--w:${s.u}%;--c:#ef4c5d"></i></div>`}).join('');$('#conceptCount').textContent=state.unlocked.length}
const episodeNames=['','EPISODE 1 — WHO MATTERS?','EPISODE 2 — BUILD THE BOARD','EPISODE 3 — THREE FUTURES','EPISODE 4 — THE MONEY ENGINE','EPISODE 5 — LEGAL LOADOUT','EPISODE 6 — PRESSURE TEST','FINAL EPISODE — THE BOARD DECIDES'];function showEpisode(n){state.episode=n;$$('.episode').forEach(e=>e.classList.toggle('active',+e.dataset.episode===n));$('#episodeTitle').textContent=episodeNames[n];$('#episodeCount').textContent=`${n} / 7`;$('#episodeFill').style.width=`${n/7*100}%`;window.scrollTo({top:68,behavior:'smooth'});renderIntel();save()}
$('#beginMission').onclick=()=>{state.team=$('#teamName').value.trim()||'Team Nexus';$('#missionBrief').classList.add('hidden');$('#simShell').classList.remove('hidden');renderStakeholders();renderPriorityChoices();renderPrioritySeats();renderVisions();renderRevenue();renderContracts();showEpisode(state.episode||1);unlockConcept('salience',false);sting()};$$('[data-next]').forEach(b=>b.onclick=()=>showEpisode(+b.dataset.next));$$('[data-back]').forEach(b=>b.onclick=()=>showEpisode(+b.dataset.back));$('#toArchitecture').onclick=()=>showEpisode(3);$('#toRevenue').onclick=()=>showEpisode(4);$('#toLegal').onclick=()=>showEpisode(5);$('#launchSeason').onclick=startSeason;$('#unlockClose').onclick=()=>$('#unlock').classList.add('hidden');
$$('[data-year]').forEach(b=>b.onclick=()=>{state.yearDecision=b.dataset.year;$$('[data-year]').forEach(x=>x.classList.toggle('selected',x===b));save();tone(620)});$('#copyBoard').onclick=async()=>{const leader=stakeholderDefs.find(s=>s.id===salienceLeader()[0]);const txt=`ECOSYSTEM ARCHITECT — SEASON ONE\nTeam: ${state.team}\nArchitecture: ${architectureDefs.find(a=>a.id===state.architecture)?.name}\nFinancial Sustainability: ${state.metrics.financial}/100\nCompetitive Access: ${state.metrics.access}/100\nPublisher Control: ${state.metrics.control}/100\nLegal Resilience: ${state.metrics.resilience}/100\nLegitimacy: ${state.metrics.legitimacy}/100\nPublisher-linked revenue: ${publisherDependency()}%\nSalience leader: ${leader.role}\nYear Two decision: ${state.yearDecision||'Not selected'}\nReason: ${$('#yearReason').value||''}`;await navigator.clipboard.writeText(txt);$('#toast').classList.add('show');setTimeout(()=>$('#toast').classList.remove('show'),1600)};
load();startOpening();
if(localStorage.getItem(STORAGE)){setTimeout(()=>{const resume=confirm('Resume your saved Season One simulation?');if(resume){$('#coldOpen').classList.add('hidden');$('#sim').classList.remove('hidden');$('#missionBrief').classList.add('hidden');$('#simShell').classList.remove('hidden');renderStakeholders();renderPriorityChoices();renderPrioritySeats();renderVisions();renderRevenue();renderContracts();if(state.episode===7)renderFinal();if(state.episode===6&&state.crises.length)renderCrisis();showEpisode(state.episode||1)}},350)}