import {getDebtSummary,estimateProposalImpact} from './model.js?v=20260928c';
import {VERSION,ROUNDS,newGame,optionsFor,closeClassroomCycle,financialView,fanReaction,leagueComparison,reportText} from './classroom-model.js?v=20260928c';
import {stadium,icon} from './classroom-visuals.js?v=20260928c';
const app=document.querySelector('#app');
const $=s=>document.querySelector(s);
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const money=v=>`${v<0?'−':''}$${Math.abs(v).toFixed(1)}M`;
const percent=v=>`${(v*100).toFixed(1)}%`;
const KEY='pst-classroom-20260928';
let session={version:VERSION,phase:'welcome',profile:{mode:'solo',names:'',club:'Explorer Sport'},state:null,draft:{id:'',debtPct:0,text:''},reflection:''};
let storageOK=true;
try{const saved=JSON.parse(localStorage.getItem(KEY));if(saved?.version===VERSION&&saved.state&&['decision','result','final'].includes(saved.phase)&&saved.state.history.length<=3)session=saved;}catch{storageOK=false;}
function save(){try{localStorage.setItem(KEY,JSON.stringify(session));}catch{storageOK=false;}}
let noticeTimer;
function notify(text){$('#status').textContent=text;$('#status').classList.add('visible');clearTimeout(noticeTimer);noticeTimer=setTimeout(()=>$('#status').classList.remove('visible'),4500);}
function move(phase){session.phase=phase;save();render();window.scrollTo({top:0,behavior:'instant'});app.querySelector('h1')?.focus();}
const row=(label,value,total=false)=>`<div class="ledger-row ${total?'total':''}"><span>${label}</span><b>${money(value)}</b></div>`;
function progress(cycle,done=false){return `<ol class="progress" aria-label="Three annual decisions">${ROUNDS.map((r,i)=>`<li class="${done||i+1<cycle?'done':i+1===cycle?'current':''}" ${!done&&i+1===cycle?'aria-current="step"':''}><span>${done||i+1<cycle?'✓':i+1}</span>${['Fans & revenue','Venue & funding','Roster & commitments'][i]}</li>`).join('')}</ol>`;}
function metrics(state,r=null){return `<div class="metrics"><div><span>Cash available</span><b>${money(r?r.cash:state.cash)}</b><small>${r?`Started this year at ${money(r.openingCash)}`:'Your resource for the next decision'}</small></div><div><span>${r?'Season win rate':'Latest win rate'}</span><b>${percent(r?r.wins:state.history.at(-1)?.wins??.5)}</b><small>${r?'A whole-team outcome':'Performance, not a guaranteed forecast'}</small></div><div><span>Fan confidence</span><b>${(r?r.fan:state.fanTrust).toFixed(1)}<em>/100</em></b><small>${r?`${r.fan>=r.openingFan?'+':''}${(r.fan-r.openingFan).toFixed(1)} points this cycle`:'Approval is not financial health'}</small></div></div>`;}
function continuing(state){const debt=getDebtSummary(state);return `<details class="continuing"><summary>Your financial position & continuing commitments</summary><p><b>${money(debt.principal)}</b> debt outstanding. Next year’s scheduled principal and interest: <b>${money(debt.service)}</b>, before any new borrowing.</p>${state.activeInvestments.length?`<ul>${state.activeInvestments.map(p=>`<li><b>${esc(p.name)}</b> · ${p.remaining} years left · ${money(p.annualCost)} base annual operating cost</li>`).join('')}</ul>`:'<p>Existing roster and club operations continue even when you make no new investment.</p>'}<p class="fine">This is a financial-position summary, not a formal balance sheet. Cost shocks can change annual operating costs. Project borrowing may continue after a project’s modeled operating term.</p></details>`;}
function welcome(){app.innerHTML=`<section class="welcome"><div class="intro-copy"><p class="eyebrow">YOUR CLUB. THREE CONNECTED DECISIONS.</p><h1 tabindex="-1">Build a team.<br>Keep it in business.</h1><p class="lead">The fans want more. The money has limits. Take charge for three seasons—and explain the choices you make.</p><div class="intro-tags"><span>Solo or with a partner</span><span>15–20 minute target</span><span>No calculator needed</span></div></div><div class="hero-art">${stadium()}<span class="art-label">A fictional franchise. Real management tradeoffs.</span></div></section>
<section class="onboard"><div><p class="eyebrow">A CLEAR STARTING POINT</p><h2>Same club. Your decisions.</h2><p>You inherit a growing-market franchise with <b>$155M in cash</b>, <b>$205M in debt</b> and a 50% baseline win rate.</p><p>Your assignment: support the team and its fans while protecting the club’s ability to pay its obligations.</p><ol class="short-steps"><li>Choose one option each year.</li><li>Explain the benefit and risk in one sentence.</li><li>See the result, then make your next decision.</li></ol></div><form id="startForm"><fieldset><legend>How are you playing?</legend><div class="segmented"><label><input type="radio" name="format" value="solo" checked> On my own</label><label><input type="radio" name="format" value="pair"> With a partner</label></div></fieldset><label>Your name<input id="name1" autocomplete="name" required maxlength="70" placeholder="First and last name"></label><label id="partnerWrap" hidden>Partner’s name<input id="name2" maxlength="70" placeholder="First and last name"></label><label>Franchise name <span class="optional">optional</span><input id="clubName" maxlength="44" placeholder="Explorer Sport"></label><button class="primary full" type="submit">Start Cycle 1 ${'→'}</button><p class="fine">Use one device. Progress stays in this browser when storage is available. Download your report at the end; nothing is sent automatically.</p></form></section>`;
 $('#startForm').onchange=e=>{if(e.target.name==='format'){const pair=e.target.value==='pair';$('#partnerWrap').hidden=!pair;$('#name2').required=pair;}};
 $('#startForm').onsubmit=e=>{e.preventDefault();const mode=new FormData(e.currentTarget).get('format');const names=[$('#name1').value.trim(),...(mode==='pair'?[$('#name2').value.trim()]:[])];if(names.some(n=>!n))return;session.profile={mode,names:names.join(' & '),club:$('#clubName').value.trim()||'Explorer Sport'};session.state=newGame();move('decision');};
}
function choiceCard(o){const p=o.proposal;const selected=session.draft.id===o.id;return `<label class="choice ${selected?'selected':''}"><input type="radio" name="choice" value="${o.id}" ${selected?'checked':''}><span class="choice-top"><span class="option-icon">${icon(o.icon)}</span><span class="pick">${selected?'Selected':'Choose'}</span></span><h3>${o.label}</h3><p>${o.benefit}</p><div class="option-numbers"><div><span>Upfront investment</span><b>${money(p.upfront)}</b></div><div><span>Base annual operating net</span><b>${money(p.annualRevenue-p.annualCost)}</b></div></div><p class="commitment">${money(p.annualCost)} annual cost · ${p.term}-year commitment</p><p class="risk"><b>Risk:</b> ${o.risk}</p></label>`;}
function selectionPanel(){const {state,draft}=session;if(!draft.id)return `<div class="selection-empty">Choose an option above to see your funding plan and explain your decision.</div>`;
 const o=optionsFor(state).find(o=>o.id===draft.id);const p=o?.proposal;const x=p?estimateProposalImpact(state,p,draft.debtPct):null;
 const roi=p?.type==='capital'?`<details class="roi"><summary>How is the project’s ROI calculated?</summary><p><b>Annual project ROI = (additional annual revenue − annual operating costs) ÷ upfront investment × 100.</b></p><p>(${money(p.annualRevenue)} − ${money(p.annualCost)}) ÷ ${money(p.upfront)} × 100 = <b>${x.directROI.toFixed(1)}%</b>.</p><p class="fine">A simplified annual operating return before financing, taxes and depreciation—not a guaranteed return or the total return over the asset’s life. Borrowing changes cash payments, not the project’s underlying operating return.</p></details>`:'';
 return `<section class="decision-plan"><div><p class="eyebrow">YOUR CHOICE</p><h2>${o?o.label:'Preserve cash'}</h2>${p?`<p>You commit to ${p.term} years of operating costs. The forecast is an estimate; your outcome can differ.</p>`:'<p>You make no new investment this year. Existing staff, contracts, operating costs and debt payments continue. You also pass up the benefits of the other choices.</p>'}
 ${p?.debtEligible?`<fieldset><legend>How will you fund it?</legend><div class="segmented funding"><label><input type="radio" name="funding" value="0" ${!draft.debtPct?'checked':''}> Use club cash</label><label><input type="radio" name="funding" value="0.5" ${draft.debtPct?'checked':''}> Borrow half</label></div></fieldset>`:''}
 ${p?`<div class="fund-summary"><p><b>${money(x.cashNeed)}</b> cash invested now${x.debtAmount?` + <b>${money(x.debtAmount)}</b> borrowed`:'. No new borrowing.'}</p>${x.debtAmount?`<p>New loan: 5.8% interest, 10 annual principal payments. First-year payments: <b>${money(x.annualDebtService)}</b>. Interest declines with the balance.</p>`:''}<p>Base direct annual cash contribution after operating costs${x.debtAmount?' and project debt payments':''}: <b>${money(x.afterDebtNet)}</b>.</p><p class="fine">This direct figure excludes wider effects on wins, brand and fan demand.${p.type==='player'?' A negative direct return can accompany a valuable competitive benefit.':''}</p></div>`:''}${roi}</div><div class="explain"><label for="rationale">Why is this worth the tradeoff?</label><p>One sentence: “I/we chose ___ for ___ benefit and accept ___ risk.”</p><textarea id="rationale" rows="3" minlength="12" maxlength="900" required placeholder="Explain your benefit and accepted risk…">${esc(draft.text)}</textarea><p class="fine">Your explanation is saved before you see the outcome. You can still change your choice.</p><p id="decisionError" role="alert" class="error"></p><button class="primary full" id="runBtn" type="submit">Commit & see Cycle ${state.cycle} ${'→'}</button></div></section>`;
}
function decision(){const {state}=session;const round=ROUNDS[state.cycle-1];app.innerHTML=`${progress(state.cycle)}<div class="page-heading"><div><p class="eyebrow">CYCLE ${state.cycle} OF 3 · ${round.theme.toUpperCase()}</p><h1 tabindex="-1">${round.title}</h1><p class="lead">${round.brief}</p></div><span class="club-badge">${esc(session.profile.club)}</span></div>${metrics(state)}${continuing(state)}
<form id="decisionForm"><fieldset class="choice-fieldset"><legend>Choose ONE option</legend><p class="fine">Base annual operating net = direct revenue − recurring operating costs, before borrowing. All amounts are $M.</p><div class="choices">${optionsFor(state).map(choiceCard).join('')}<label class="choice hold ${session.draft.id==='hold'?'selected':''}"><input type="radio" name="choice" value="hold" ${session.draft.id==='hold'?'checked':''}><span class="choice-top"><span class="option-icon">${icon('cash')}</span><span class="pick">${session.draft.id==='hold'?'Selected':'Choose'}</span></span><h3>Preserve cash</h3><p>Keep flexibility for later decisions and existing obligations.</p><div class="option-numbers"><div><span>New investment</span><b>$0.0M</b></div><div><span>New operating benefit</span><b>$0.0M</b></div></div><p class="commitment">No new commitment</p><p class="risk"><b>Risk:</b> You pass up this year’s investment opportunities. Existing costs continue.</p></label></div></fieldset><div id="selectionPanel">${selectionPanel()}</div></form><p class="save-note">${storageOK?'Progress saved in this browser.':'Browser storage is unavailable. Keep this tab open and download your report at the end.'}</p>`;
 $('#decisionForm').onchange=e=>{if(e.target.name==='choice'){session.draft.id=e.target.value;session.draft.debtPct=0;save();decision();}if(e.target.name==='funding'){session.draft.debtPct=Number(e.target.value);save();$('#selectionPanel').innerHTML=selectionPanel();bindRationale();}};
 bindRationale();
 $('#decisionForm').onsubmit=e=>{e.preventDefault();if(session.phase!=='decision')return;try{const result=closeClassroomCycle(session.state,session.draft.id,session.draft.debtPct,session.draft.text);session.state=result.next;move('result');}catch(error){const target=$('#decisionError');if(target)target.textContent=error.message;else notify(error.message);}};
}
function bindRationale(){if($('#rationale'))$('#rationale').oninput=e=>{session.draft.text=e.target.value;save();};}
function statements(r){const f=financialView(r);return `<div class="finance-grid"><section class="ledger"><p class="eyebrow">THE YEAR’S INCOME</p><h2>Did operations make money?</h2>${row('Shared league revenue',f.shared)}${row('Local & investment revenue',f.local)}${row('Total revenue',f.revenue,true)}${row('Less: operating expenses',f.operatingCosts)}${row('Operating result',f.operatingResult,true)}${row('Less: interest expense',f.interest)}${row('Simplified profit after interest',f.profit,true)}<details><summary>What is included?</summary><p>Operating expenses include ${money(r.expenses.roster)} of roster costs and ${money(r.expenses.operations)} of club operations, including active programs. Financing is not revenue. Loan principal is not an operating expense.</p></details></section><section class="ledger cash-ledger"><p class="eyebrow">THE CASH EXPLANATION</p><h2>Why is cash different?</h2>${row('Opening cash',f.openingCash)}${row('+ Simplified profit after interest',f.profit)}${row('− Club cash invested',f.investment)}${row('− Loan principal repaid',f.principal)}${row('= Ending cash',f.endingCash,true)}<p class="lesson">${r.upfrontCash>0?`Your investment used ${money(r.upfrontCash)} of cash without being treated as this year’s operating expense in the model.`:'Preserving cash avoided a new investment outflow, but existing obligations still required payment.'} Principal repayment reduced cash and debt, not profit.</p><p class="fine">Borrowing covers part of a purchase; “club cash invested” is the remaining cash-funded amount. No taxes, depreciation or working-capital timing. Upfront program costs are modeled as investment outflows. Display rounding may differ by $0.1M.</p></section></div>`;}
function outcomeStory(r){const p=r.realized[0];return `<section class="causal-story"><p class="eyebrow">FOLLOW YOUR DECISION</p><h2>${esc(r.classroomChoice.label)}</h2><div class="story-steps"><div><span>01 · YOU COMMITTED</span><p>${money(r.upfrontCash)} club cash${r.newDebt?` + ${money(r.newDebt)} borrowing`:''}.</p></div><div><span>02 · YOU EXPECTED</span><p>${p?`${money(p.annualRevenue-p.annualCost)} direct annual operating net, plus the stated strategic benefits.`:'More flexibility, with no new investment benefit.'}</p></div><div><span>03 · WHAT HAPPENED</span><p>${p?`${money(p.realizedRevenue-p.actualCost)} actual direct operating net; ${money(p.actualNet)} after project debt payments.`:'Existing operations and commitments continued.'}</p></div></div><p class="event-note"><b>${esc(r.event.title)}.</b> ${esc(r.event.desc)}${p?' The project’s own revenue realization and costs determine its direct result.':''}</p><p class="fine">Direct project net is part of the club result, not an additional amount to add to profit. Team performance, fan demand and the external event also affect the whole club.</p></section>`;}
function results(){const r=session.state.history.at(-1),reaction=fanReaction(r);app.innerHTML=`${progress(r.cycle)}<div class="page-heading"><div><p class="eyebrow">CYCLE ${r.cycle} · THE RECORDED RESULT</p><h1 tabindex="-1">See what your choice set in motion.</h1><p class="lead">Read the result before making your next decision. A difficult outcome can follow a defensible choice.</p></div></div>
<div class="reaction-layout"><div class="crowd-scene animate">${stadium(r,reaction.mood)}</div><section class="reaction-copy ${reaction.mood}"><p class="eyebrow">THE FANS RESPOND</p><h2>${reaction.title}</h2><p class="lead">Confidence ${reaction.change>=0?'rose':'fell'} <b>${Math.abs(reaction.change).toFixed(1)} points</b>.</p><p>${reaction.note}</p><details><summary>Why did fans react this way?</summary><p>${reaction.explanation}</p></details><button id="replayCrowd" class="secondary">Replay fan reaction</button><p class="fine">Silent, brief and skippable. No waiting required.</p></section></div>
${metrics(session.state,r)}${outcomeStory(r)}${statements(r)}${continuing(session.state)}<details class="original"><summary>Your explanation before the result</summary><blockquote>${esc(r.rationale.text)}</blockquote></details><div class="next-bar"><p><b>Pause and connect:</b> What changed because of your decision, and what changed because of the environment?</p><button class="primary" id="nextBtn">${r.cycle===3?'Finish & review your franchise':'Continue to Cycle '+(r.cycle+1)} →</button></div>`;
 $('#replayCrowd').onclick=()=>{const scene=$('.crowd-scene');scene.classList.remove('animate');void scene.offsetWidth;scene.classList.add('animate');};
 $('#nextBtn').onclick=()=>{session.draft={id:'',debtPct:0,text:''};move(r.cycle===3?'final':'decision');};
}
function final(){const {state}=session;const r=state.history.at(-1);const cut=leagueComparison(r);app.innerHTML=`${progress(3,true)}<div class="page-heading"><div><p class="eyebrow">THREE YEARS LATER · YOUR BOARD REPORT</p><h1 tabindex="-1">${esc(session.profile.club)}</h1><p class="lead">${esc(session.profile.names)} · ${session.profile.mode==='pair'?'Partner team':'Individual'}<br>Defend the choices behind your results.</p></div></div>${metrics(state,r)}
<section class="decision-trail"><p class="eyebrow">YOUR MANAGEMENT STORY</p><h2>Three choices. Continuing consequences.</h2><div class="trail-grid">${state.history.map(x=>`<article><span class="year">CYCLE ${x.cycle}</span><h3>${esc(x.classroomChoice.label)}</h3><p>${esc(x.rationale.text)}</p><dl><div><dt>Ending cash</dt><dd>${money(x.cash)}</dd></div><div><dt>Simplified profit</dt><dd>${money(x.afterInterest)}</dd></div><div><dt>Fan confidence</dt><dd>${x.fan.toFixed(1)}/100</dd></div></dl></article>`).join('')}</div></section>
${continuing(state)}<section class="reflection-card"><p class="eyebrow">ONE FINAL REFLECTION</p><h2>Which decision would you defend—or change—and why?</h2><label for="reflection">Use one result as evidence. A good answer connects the benefit, cost and risk.</label><textarea id="reflection" rows="3" maxlength="1500" placeholder="I/we would defend or change… because the result showed…">${esc(session.reflection)}</textarea><div class="actions"><button id="downloadReport" class="primary">Download Board Report</button><button id="copyReport" class="secondary">Copy report</button><button id="viewReport" class="secondary">View report</button></div><div id="reportPreview" class="report-preview" hidden></div><p class="fine">Submit through the channel your instructor specifies. There is no automatic submission or grade. Your report includes both partners’ names when applicable.</p><p id="reportError" class="error" role="alert"></p></section>
<details class="league-lens"><summary>Day 2 connection: your rivals are also business partners</summary><p>In Cycle 3, <b>${money(r.revenue.shared)}</b>—${Math.round(r.revenue.shared/r.revTotal*100)}% of your club’s revenue—came from the shared league distribution. Teams jointly produce the competition that supports the league’s commercial value.</p><button id="compareLeague" class="secondary" aria-expanded="false">What if shared revenue fell 20%?</button><div id="leagueResult" hidden><div class="table-wrap"><table><thead><tr><th>Cycle 3 measure</th><th>Recorded</th><th>20% lower distribution</th></tr></thead><tbody>${[['League revenue',r.revenue.shared,cut.shared],['Simplified profit',r.afterInterest,cut.profit],['Ending cash',r.cash,cut.cash]].map(([label,a,b])=>`<tr><th>${label}</th><td>${money(a)}</td><td>${money(b)}</td></tr>`).join('')}</tbody></table></div><p>The loss of ${money(cut.loss)} lowers profit and cash by the same amount. All other inputs stay fixed. This comparison does not change your saved result.</p></div><p class="fine">Sharing supports resources; it does not require a club to invest in talent or ensure equal competitiveness. This is a one-cycle sensitivity, not another game round.</p></details><div class="finish-note"><b>No single winning score.</b> Evaluate cash, performance, fan confidence and your reasoning together.</div>`;
 $('#reflection').oninput=e=>{session.reflection=e.target.value;save();};
 function ready(){if(session.reflection.trim().length<12){$('#reportError').textContent='Write a short final reflection before saving your report.';$('#reflection').focus();return false;}$('#reportError').textContent='';return true;}
 $('#downloadReport').onclick=()=>{if(!ready())return;const blob=new Blob([reportText(session)],{type:'text/plain;charset=utf-8'});const url=URL.createObjectURL(blob);const a=document.createElement('a');a.href=url;a.download='Pro_Sport_Tycoon_Board_Report.txt';document.body.appendChild(a);a.click();a.remove();setTimeout(()=>URL.revokeObjectURL(url),60000);notify('Download requested. If your browser blocks it, use View report to copy the text.');};
 $('#copyReport').onclick=async()=>{if(!ready())return;try{await navigator.clipboard.writeText(reportText(session));notify('Board Report copied.');}catch{notify('Copy is unavailable in this browser. Use Download Board Report.');}};
 $('#viewReport').onclick=()=>{if(!ready())return;$('#reportPreview').hidden=false;$('#reportPreview').innerHTML='<label for="reportText">Your complete report — select and copy if needed</label><textarea id="reportText" readonly rows="14"></textarea>';$('#reportText').value=reportText(session);$('#reportText').focus();};
 $('#compareLeague').onclick=()=>{const x=$('#leagueResult');x.hidden=!x.hidden;$('#compareLeague').setAttribute('aria-expanded',String(!x.hidden));$('#compareLeague').textContent=x.hidden?'What if shared revenue fell 20%?':'Hide comparison';};
}
function render(){({welcome,decision,result:results,final}[session.phase]||welcome)();}
$('#howBtn').onclick=()=>$('#help').showModal();
$('#resetBtn').onclick=()=>$('#resetDialog').showModal();
$('#cancelReset').onclick=()=>$('#resetDialog').close();
$('#confirmReset').onclick=()=>{try{localStorage.removeItem(KEY);}catch{}session={version:VERSION,phase:'welcome',profile:{mode:'solo',names:'',club:'Explorer Sport'},state:null,draft:{id:'',debtPct:0,text:''},reflection:''};$('#resetDialog').close();render();window.scrollTo(0,0);};
render();
