'use strict';
(()=>{
const $=s=>document.querySelector(s),esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const KEY='spm370-llc3-draft-v3',choices=['Revise before signing','Seek more information before deciding','Decline this draft'];
const words=s=>(String(s||'').trim().match(/\S+/g)||[]).length;
const fresh=()=>({owner:null,name:'',email:'',stage:0,phase:0,selections:Array.from({length:6},()=>[null,null]),notes:Array(6).fill(''),brief:'',decision:''});
let draft=fresh(),remote=null,busy=false;
try{const d=JSON.parse(localStorage.getItem(KEY)||'null');if(d&&Array.isArray(d.notes)&&d.notes.length===6&&Array.isArray(d.selections)&&d.selections.length===6)draft={...fresh(),...d};}catch{}
function save(){try{localStorage.setItem(KEY,JSON.stringify(draft));$('#saveWarning').hidden=true;}catch{$('#saveWarning').hidden=false;}}
function status(text,error=false){$('#notice').textContent=text;$('#notice').className=error?'error':'status';}
function adopt(r){remote=r;if(draft.owner!==r.id||r.submittedAt){draft={...fresh(),owner:r.id,name:r.name,email:r.email,notes:[...r.notes],brief:r.brief,decision:r.decision,selections:r.stageAnswers.map(x=>x?[...x]:[null,null])};}else{draft.name=r.name;draft.email=r.email;for(let i=0;i<6;i++){if(r.stageAnswers[i])draft.selections[i]=[...r.stageAnswers[i]];if(!draft.notes[i]&&r.notes[i])draft.notes[i]=r.notes[i];}if(!draft.brief)draft.brief=r.brief;if(!draft.decision)draft.decision=r.decision;}save();}
function available(){if(!remote)return 0;for(let i=0;i<6;i++)if(!remote.stageAnswers[i]||words(remote.notes[i])<15)return i;return 6;}
function move(stage,phase=0){if(busy)return;draft.stage=Math.max(0,Math.min(stage,available()));draft.phase=phase;save();status('');render();$('#main').focus();window.scrollTo({top:0,behavior:'instant'});}
function download(text,name,type='text/plain'){const u=URL.createObjectURL(new Blob([text],{type})),a=document.createElement('a');a.href=u;a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(u),2000);}
function backup(){if(!LLC3.hasSession()){status('Start or resume your check before saving a backup.',true);return;}download(JSON.stringify({version:3,token:LLC3.token(),draft},null,2),'SPM370_LLC3_Private_Backup.json','application/json');}
async function send(action,body,next){if(busy)return;busy=true;document.querySelectorAll('#main button,#progress button').forEach(b=>b.disabled=true);status('Saving…');try{const r=await LLC3.call(action,{revision:remote.revision,...body});adopt(r);if(next){draft.stage=next.stage;draft.phase=next.phase;save();}status('Saved to your instructor’s record.');render();$('#main').focus();}catch(e){status(e.message,true);render();}finally{busy=false;document.querySelectorAll('[data-nav]').forEach(b=>b.disabled=!!remote.submittedAt||Number(b.dataset.nav)>available());}}
function rubric(){return '<ul><li><strong>Multiple choice: 12 points.</strong> Two questions per vignette, 1 point each. Your recorded choices are final; feedback appears after you submit both.</li><li><strong>Six case notes: 6 points.</strong> Each earns 0.5 for an accurate module concept and 0.5 for applying it to the facts. Plain language is enough. Length alone does not earn credit.</li><li><strong>Final recommendation: 2 points.</strong> Two supported priorities (1), a feasible tradeoff (0.5), and a clear recommendation with a focused counsel question (0.5).</li></ul><p>Writing is reviewed for relevant concepts, reasonable application, and meaningful effort. Grammar polish and legal drafting are not the focus. Your total remains pending until the writing is reviewed.</p>';}
function render(){
 if(!remote){welcome();return;}
 const done=remote.stageAnswers.filter(Boolean).length;
 $('#progress').innerHTML=`<nav class="progress" aria-label="Vignettes"><div class="progress-meta"><span>${done} of 6 decision sets recorded</span><span>MC ${remote.mcScore}/${done*2} recorded · Writing /8</span></div><div class="steps">${remote.assessment.stages.map((s,i)=>`<button data-nav="${i}" ${i>available()?'disabled':''} ${draft.stage===i?'aria-current="step"':''} class="${draft.stage===i?'active ':''}${words(remote.notes[i])>=15?'complete':''}">${i+1}. ${esc(s.short)}</button>`).join('')}<button data-nav="6" ${available()<6?'disabled':''} class="${draft.stage===6?'active':''}">Final brief</button></div></nav>`;
 $('#aside').innerHTML=`<h2>Maya’s priorities</h2><ul><li>Predictable pay</li><li>Control of personal content</li><li>Specific consent for voice uses</li><li>A workable sponsor arrangement</li><li>An affordable dispute process</li></ul><button id="showDraft" class="secondary">Review the draft and deal facts</button><div class="notebook"><h2>Your case notes</h2>${remote.assessment.stages.map((s,i)=>`<div class="note-item"><strong>${i+1}. ${esc(s.short)}</strong><p>${draft.notes[i]?esc(draft.notes[i]):'Your note will appear here.'}</p></div>`).join('')}</div>`;
 $('#showDraft').onclick=()=>$('#draftDialog').showModal();document.querySelectorAll('[data-nav]').forEach(b=>b.onclick=()=>move(Number(b.dataset.nav)));
 if(remote.submittedAt){receipt();return;}if(draft.stage>available())draft.stage=available();if(draft.stage===6)finalBrief();else vignette();
}
function welcome(){
 $('#progress').innerHTML='';$('#aside').innerHTML='<h2>Maya’s brief</h2><p>Protect predictable income, personal content, consent, and a workable route to resolve disputes.</p><button id="showDraft" class="secondary">Review the draft and deal facts</button>';
 $('#main').innerHTML=`<section class="paper"><p class="eyebrow">SPM 370 · Legal Literacy Check 3 · 20 points</p><h1>Maya needs advice before she signs.</h1><p class="lead">You are the business manager for Maya, a 20-year-old gaming streamer. Northline Esports offers a six-month creator deal. Help her evaluate the promises, rights, and practical consequences.</p><div class="budget"><div><strong>$5,000</strong><span>Proposed monthly pay</span></div><div><strong>20 hours</strong><span>Proposed monthly streaming</span></div><div><strong>6 months</strong><span>Proposed contract term</span></div></div><p>Maya already has a personal channel and a headset sponsor. Northline wants content, promotional rights, and new uses of her voice. All people, organizations, and deal terms are fictional.</p><h2>One lesson, one scored submission</h2><ol class="plan"><li>Read each of six short vignettes and use the course explanations.</li><li>Answer two scored multiple-choice questions. Record both choices, then read the feedback.</li><li>Write a 30–50 word case note applying a course concept to Maya’s facts.</li><li>Write a 120–160 word final recommendation and submit Legal Literacy Check 3 here.</li></ol><div class="notice"><strong>About 45–55 minutes.</strong> Work individually with your slides, chapter, and notes. No generative AI or outside collaboration. There is no countdown or speed bonus. Follow your instructor’s deadline.</div><details><summary>How the 20 points are awarded</summary>${rubric()}</details><p><strong>This lesson is Legal Literacy Check 3.</strong> There is no additional quiz after it. Both your multiple-choice score and writing points count toward the same total.</p><label for="name">Your full name</label><input id="name" type="text" maxlength="120" autocomplete="name" value="${esc(draft.name)}"><label for="email">Your La Salle email</label><input id="email" type="email" maxlength="120" autocomplete="email" value="${esc(draft.email)}" placeholder="you@lasalle.edu"><label class="checkline"><input type="checkbox" id="honor"><span>I am using my own name and email and will complete this work individually.</span></label><p class="small muted">Your name, email, answers, and grades are visible to your instructor. They are not posted publicly. Identity is self-reported; no GitHub account is needed.</p><div class="actions"><button id="start">Start Legal Literacy Check 3</button></div></section>`;
 $('#showDraft').onclick=()=>$('#draftDialog').showModal();$('#name').oninput=e=>{draft.name=e.target.value;save();};$('#email').oninput=e=>{draft.email=e.target.value;save();};
 $('#start').onclick=async()=>{if(busy)return;if(draft.name.trim().length<2||!/^[^\s@]+@lasalle\.edu$/i.test(draft.email)||!$('#honor').checked){status('Enter your full name and La Salle email, then confirm individual work.',true);return;}busy=true;$('#start').disabled=true;try{adopt(await LLC3.start(draft.name.trim(),draft.email.trim().toLowerCase()));draft.stage=available();draft.phase=0;save();status('Your attempt is connected. Save your private resume code through Course reference.');render();}catch(e){status(e.message,true);$('#start').disabled=false;}finally{busy=false;}};
}
function vignette(){
 const i=draft.stage,s=remote.assessment.stages[i],locked=!!remote.stageAnswers[i];
 let body=`<div class="case-label"><span>VIGNETTE ${i+1} OF 6</span><span>2 MC points + 1 writing point</span></div><h1>${esc(s.title)}</h1>${s.scenarioNotice?`<div class="notice">${esc(s.scenarioNotice)}</div>`:''}<div class="stagesub"><span ${draft.phase===0?'class="current"':''}>1 Read</span><span ${draft.phase===1?'class="current"':''}>2 Decide</span><span ${draft.phase===2?'class="current"':''}>3 Brief Maya</span></div>`;
 const facts=`<div class="evidence"><h3>The facts</h3><p>${esc(s.evidence)}</p></div>`;
 if(draft.phase===0)body+=`<blockquote class="message">${esc(s.message)}</blockquote>${facts}<h2>The legal tools</h2><div class="teaching">${s.teach.map(p=>`<p>${esc(p)}</p>`).join('')}</div><p class="small muted">Course connection: ${esc(s.slides)}</p><div class="actions"><button id="decide">${locked?'Review recorded decisions':'Make the two decisions'}</button></div>`;
 else if(draft.phase===1){body+=facts+`<p class="notice"><strong>${locked?'These choices have been recorded.':'Each question is worth 1 point.'}</strong> ${locked?'Use the feedback when writing your case note.':'Check both answers carefully. Once recorded, your choices cannot be changed. You will receive feedback immediately afterward.'}</p>`+s.questions.map((q,j)=>`<fieldset class="graded-question"><legend>${i*2+j+1}. ${esc(q.prompt)}</legend><div class="options">${q.options.map((o,k)=>`<label class="option"><input type="radio" name="q${j}" value="${k}" ${draft.selections[i][j]===k?'checked':''} ${locked?'disabled':''}><span>${esc(o)}</span></label>`).join('')}</div></fieldset>`).join('')+`<div class="actions"><button id="lock">${locked?'Continue to case note':'Record both answers — 2 points'}</button><button id="read" class="secondary">Review the explanation</button></div>`;}
 else{if(!locked){draft.phase=1;vignette();return;}body+=`<p class="stamp">Multiple-choice points recorded: ${remote.feedback[i].reduce((n,q)=>n+q.earned,0)} / 2</p><details open><summary>Review the answers and explanations</summary>${remote.feedback[i].map((f,j)=>`<div class="feedback ${f.earned?'good':''}"><p><strong>Question ${i*2+j+1}: ${f.earned}/1</strong></p><p>Your choice: ${esc(s.questions[j].options[f.selected])}</p>${!f.earned?`<p>Best answer: ${esc(s.questions[j].options[f.correct])}</p>`:''}<p>${esc(f.why)}</p></div>`).join('')}</details><h2>Brief Maya · 1 point</h2><p>${esc(s.note)}</p><label for="note">Case note ${i+1}</label><textarea id="note" maxlength="6000">${esc(draft.notes[i])}</textarea><p id="wordCount" class="small muted">${words(draft.notes[i])} words · Aim for 30–50; minimum 15 to save and continue.</p><p class="small">Earn 0.5 for an accurate relevant concept and 0.5 for applying it to a scenario fact. A reasonable, specific response in your own words is enough.</p><div class="actions"><button id="saveNote">${i===5?'Save note and write the final brief':'Save note and continue'}</button><button id="read" class="secondary">Review this vignette</button></div>`;}
 $('#main').innerHTML=`<section class="paper">${body}</section>`;
 if($('#decide'))$('#decide').onclick=()=>move(i,1);if($('#read'))$('#read').onclick=()=>move(i,0);
 document.querySelectorAll('input[type=radio]').forEach(x=>x.onchange=()=>{draft.selections[i][Number(x.name.slice(1))]=Number(x.value);save();});
 if($('#lock'))$('#lock').onclick=()=>{if(locked){move(i,2);return;}if(draft.selections[i].some(v=>v===null)){status('Choose one answer for each question before recording both.',true);return;}send('lockStage',{stage:i,answers:draft.selections[i]},{stage:i,phase:2});};
 if($('#note'))$('#note').oninput=e=>{draft.notes[i]=e.target.value;save();$('#wordCount').textContent=words(e.target.value)+' words · Aim for 30–50; minimum 15 to save and continue.';};
 if($('#saveNote'))$('#saveNote').onclick=()=>send('saveNote',{stage:i,note:draft.notes[i]},{stage:i+1,phase:0});
}
function finalBrief(){
 $('#main').innerHTML=`<section class="paper"><p class="eyebrow">Final recommendation · 2 points</p><h1>What should Maya do?</h1><div class="notice"><strong>Return to the original unsigned draft.</strong> The signed, guaranteed-pay agreement in Vignettes 5 and 6 was a separate hypothetical. In the original draft, Northline can still end future pay early.</div><p>In <strong>120–160 words</strong>, give Maya your recommendation, identify your two most important priorities with reasons, explain one feasible business tradeoff, and ask one focused question for counsel. Include a dispute-process concern if it is one of your priorities.</p><label for="decision">Your recommendation</label><select id="decision"><option value="">Choose a recommendation</option>${choices.map(c=>`<option ${draft.decision===c?'selected':''}>${esc(c)}</option>`).join('')}</select><label for="brief">Your final brief to Maya</label><textarea id="brief" maxlength="12000">${esc(draft.brief)}</textarea><p id="wordCount" class="small muted">${words(draft.brief)} words · Minimum 100 to submit.</p><label class="checkline"><input type="checkbox" id="attest"><span>I completed this work individually and wrote these responses myself, using only permitted course materials.</span></label><details><summary>Review your six case notes</summary>${remote.assessment.stages.map((s,i)=>`<h3>${i+1}. ${esc(s.short)}</h3><p class="student-response">${esc(remote.notes[i])}</p>`).join('')}</details><details><summary>Scoring rubric</summary>${rubric()}</details><div class="actions"><button id="submit">Submit Legal Literacy Check 3</button><button id="saveBrief" class="secondary">Save final draft</button></div><p class="small">Wait for the submission receipt. Your multiple-choice subtotal is ${remote.mcScore}/12; writing contributes another 8 points after review.</p></section>`;
 $('#brief').oninput=e=>{draft.brief=e.target.value;save();$('#wordCount').textContent=words(e.target.value)+' words · Minimum 100 to submit.';};$('#decision').onchange=e=>{draft.decision=e.target.value;save();};
 $('#saveBrief').onclick=()=>send('saveBrief',{brief:draft.brief,decision:draft.decision});$('#submit').onclick=()=>{if(!$('#attest').checked){status('Confirm the individual-work statement before submitting.',true);return;}send('submit',{brief:draft.brief,decision:draft.decision,attest:true});};
}
function receipt(){
 $('#main').innerHTML=`<section class="paper completion"><p class="eyebrow">Legal Literacy Check 3</p><h1>Your check is submitted.</h1><p><strong>${esc(remote.name)}</strong><br>${esc(remote.email)}</p><div class="receipt"><strong>Server-confirmed receipt</strong><p class="receipt-code">${esc(remote.receipt)}</p><p>${esc(new Date(remote.submittedAt).toLocaleString())}</p></div><h2>${remote.reviewed?`Final score: ${remote.finalScore} / 20`:`Multiple choice: ${remote.mcScore} / 12`}</h2><p>${remote.reviewed?`Multiple choice ${remote.mcScore}/12 + writing ${remote.writingScore}/8.`:'Your six case notes and final recommendation are awaiting review for the remaining 8 points. This is a subtotal, not your final grade.'}</p><p>All parts of Legal Literacy Check 3 are submitted. There is no second quiz or Canvas upload.</p><div class="actions"><button id="refreshScore">Refresh score</button><button id="download" class="secondary">Download receipt and work</button></div><details><summary>Your submitted writing</summary>${remote.assessment.stages.map((s,i)=>`<h3>${i+1}. ${esc(s.short)}</h3><p class="student-response">${esc(remote.notes[i])}</p>`).join('')}<h3>${esc(remote.decision)}</h3><p class="student-response">${esc(remote.brief)}</p></details></section>`;
 $('#refreshScore').onclick=reconnect;$('#download').onclick=()=>download(`SPM 370 · Legal Literacy Check 3\nName: ${remote.name}\nEmail: ${remote.email}\nReceipt: ${remote.receipt}\nSubmitted: ${remote.submittedAt}\nMC: ${remote.mcScore}/12\nWriting: ${remote.reviewed?remote.writingScore+'/8':'Awaiting review'}\nFinal: ${remote.reviewed?remote.finalScore+'/20':'Pending writing review'}\n\n`+remote.assessment.stages.map((s,i)=>`VIGNETTE ${i+1}: ${s.title}\n${remote.notes[i]}\n`).join('\n')+`\n${remote.decision}\n${remote.brief}\n`,'SPM370_LLC3_Receipt_and_Work.txt');
 document.querySelectorAll('[data-nav]').forEach(b=>b.disabled=true);
}
async function reconnect(){if(busy)return;busy=true;status('Loading your saved record…');try{adopt(await LLC3.resume());draft.stage=available();draft.phase=0;save();status('Saved record loaded.');render();}catch(e){status(e.message,true);if(!remote)welcome();}finally{busy=false;}}
$('#resourcesButton').onclick=()=>$('#resources').showModal();document.querySelectorAll('[data-close]').forEach(b=>b.onclick=()=>$('#'+b.dataset.close).close());
$('#reconnect').onclick=reconnect;$('#backup').onclick=backup;$('#saveCode').onclick=()=>{if(!LLC3.hasSession()){status('Start your check first.',true);return;}download('SPM 370 LLC3 private resume code\n'+LLC3.token()+'\nKeep private. Enter through Course reference on the lesson page.','SPM370_LLC3_Private_Resume_Code.txt');};
$('#recover').onclick=async()=>{try{LLC3.adopt($('#code').value);draft=fresh();save();$('#resources').close();await reconnect();}catch(e){$('#recoveryError').textContent=e.message;}};
$('#restore').onchange=async e=>{try{const f=e.target.files[0];if(!f)return;if(f.size>150000)throw Error('This backup is too large.');const b=JSON.parse(await f.text());if(b.version!==3||!b.draft||!Array.isArray(b.draft.notes)||b.draft.notes.length!==6||!Array.isArray(b.draft.selections)||b.draft.selections.length!==6)throw Error('Choose a Legal Literacy Check 3 backup.');LLC3.adopt(b.token);draft={...fresh(),...b.draft};save();$('#resources').close();await reconnect();}catch(e){$('#recoveryError').textContent=e.message;}};
window.addEventListener('pagehide',save);render();if(LLC3.hasSession())reconnect();
})();
