import test from 'node:test';
import assert from 'node:assert/strict';
import {readFile} from 'node:fs/promises';
import {createHandler} from './handler.mjs';
import {createSupabaseStore} from './supabase-store.mjs';
import {FIXTURES, InputError, transition, sha256, guestProjection, canonical} from './model.mjs';
const origin = 'https://jflevine.github.io';
const base = 'https://havsvkhddvdbzbsmhqbr.supabase.co/functions/v1/spm343-tap-lab2';
// Ephemeral test authorization only; never deployed, never a user credential.
const key = crypto.randomUUID();
const keyHash = await sha256(key);
function memoryStore() {
  const records = new Map(), operations = new Map(), publications = new Map(); let demo = null; let calls = 0;
  return {records, operations, publications, get calls() {return calls;},
    async get(id) {calls++; return structuredClone(records.get(id) || null);},
    async list() {calls++; return structuredClone([...records.values()]);},
    async replay(id, requestId, hash) {calls++; const op = operations.get(`${id}:${requestId}`); if (!op) return null; if (hash !== op.hash) throw new InputError('REQUEST_CONFLICT', 'Conflict', 409); return structuredClone(op.response);},
    async apply(value) {
      calls++; const opKey = `${value.attemptId}:${value.requestId}`, old = operations.get(opKey);
      if (old) {if (old.hash !== value.requestHash) throw new InputError('REQUEST_CONFLICT', 'Conflict', 409); return structuredClone(old.response);}
      const current = records.get(value.attemptId);
      if ((current?.version || 0) !== value.expectedVersion) throw new InputError('VERSION_CONFLICT', 'Conflict', 409);
      records.set(value.attemptId, structuredClone(value.next)); publications.set(value.attemptId, structuredClone(value.publication)); operations.set(opKey, {hash: value.requestHash, response: structuredClone(value.response)});
      return structuredClone(value.response);
    },
    async progress(value) {calls++; if (demo?.format !== value.format || demo?.stage !== value.stage) demo = {...value, updatedAt: new Date().toISOString()}; return structuredClone(demo);},
    async guest() {calls++; const items = [...records.values(), ...(demo ? [{format: demo.format, status: demo.stage}] : [])]; return {aggregate: {started: items.length, initialPlans: items.filter(x => ['plan_locked','submitted'].includes(x.status)).length, completedRevisions: items.filter(x => x.status === 'submitted').length, formats: {guided: items.filter(x => x.format === 'guided').length, tournament: items.filter(x => x.format === 'tournament').length}}, publications: structuredClone([...publications.values()]), demo: structuredClone(demo)};}
  };
}
function rig(options = {}) {const store = memoryStore(); return {store, handle: createHandler({store, instructorKeyHash: keyHash, ...options})};}
async function call(handle, body, {auth = true, method = 'POST', headers = {}, query = ''} = {}) {
  const req = new Request(base + query, {method, headers: {origin, ...(method === 'POST' ? {'content-type': 'application/json'} : {}), ...(auth ? {'x-instructor-key': key} : {}), ...headers}, ...(method === 'POST' ? {body: JSON.stringify(body)} : {})});
  const res = await handle(req); return {status: res.status, headers: res.headers, body: res.status === 204 ? null : await res.json()};
}
const operation = (action, record, extra = {}) => ({action, attemptId: record.attemptId, requestId: crypto.randomUUID(), expectedVersion: record.version, ...extra});

test('status is fail-closed and cannot be enabled by query flags', async () => {const {handle,store} = rig(); const r = await call(handle,null,{method:'GET',auth:false,query:'?live=true'}); assert.equal(r.body.liveEnabled,false); assert.equal(r.body.grading,'instructor-only'); assert.equal(store.calls,0); assert.equal(r.headers.get('cache-control'),'no-store');});
for (const action of ['start','resume','save','lockPlan','submit']) test(`public ${action} is rejected even with instructor key and enabling flags`, async () => {const {handle,store} = rig(); const r=await call(handle,{action,mode:'live',liveEnabled:true,email:'student@lasalle.edu',responses:['raw']}); assert.equal(r.status,403); assert.equal(r.body.error.code,'LIVE_DISABLED'); assert.equal(store.calls,0);});
test('missing/incorrect instructor key denies every private action before data access', async()=>{for(const action of ['instructorList','instructorTest','instructorReview','instructorPublish']) for(const supplied of ['', 'incorrect']) {const {handle,store}=rig();const r=await call(handle,{action,fixture:'guided'},{auth:false,headers:{'x-instructor-key':supplied}});assert.equal(r.status,401);assert.equal(store.calls,0);}});
test('synthetic fixture exercises durable save, initial lock, revision, final receipt',async()=>{const {handle,store}=rig();const r=await call(handle,{action:'instructorTest',fixture:'guided'});assert.equal(r.status,200);const s=r.body.submission;assert.equal(s.version,5);assert.equal(s.synthetic,true);assert.equal(s.status,'submitted');assert.deepEqual(s.initialPlan.responses,s.responses.slice(0,3));assert.ok(s.receipt.receiptId.startsWith('TAP2-PILOT-'));assert.equal(s.receipt.credit,false);assert.equal(s.review,null);assert.equal(s.guest.published,false);assert.equal(store.records.size,1);assert.equal(store.operations.size,5);assert.equal(store.records.values().next().value.email,'tap-guided@example.invalid');});
test('repeated and concurrent fixture tests do not multiply rows or receipts',async()=>{const {handle,store}=rig();const requests=await Promise.all(Array.from({length:10},()=>call(handle,{action:'instructorTest',fixture:'guided'})));assert.ok(requests.every(r=>r.status===200));assert.equal(new Set(requests.map(r=>r.body.submission.receipt.receiptId)).size,1);assert.equal(store.records.size,1);assert.equal(store.operations.size,5);});
test('instructor test rejects raw identity, free text, and unknown fixture',async()=>{for(const extra of [{email:'s@lasalle.edu'},{responses:['secret']},{firstName:'Real'},{fixture:'unknown'}]){const {handle,store}=rig();const r=await call(handle,{action:'instructorTest',fixture:'guided',...extra});assert.equal(r.status,400);assert.equal(store.records.size,0);}});
test('grade is instructor-only and bounded 2/3/3/2; final receipt unchanged',async()=>{const {handle}=rig();const s=(await call(handle,{action:'instructorTest',fixture:'guided'})).body.submission;const input=operation('instructorReview',s,{scores:[2,2,3,1]});const reviewed=await call(handle,input);assert.equal(reviewed.status,200);assert.deepEqual(reviewed.body.submission.review.scores,[2,2,3,1]);assert.equal(reviewed.body.submission.review.total,8);assert.deepEqual(reviewed.body.submission.receipt,s.receipt);const retried=await call(handle,input);assert.deepEqual(retried.body,reviewed.body);const changed=await call(handle,{...input,scores:[2,3,3,2]});assert.equal(changed.status,409);});
test('invalid grade points, floats, raw notes, client total, and changed receipt are rejected',async()=>{const {handle}=rig();const s=(await call(handle,{action:'instructorTest',fixture:'guided'})).body.submission;for(const extra of [{scores:[3,3,3,2]},{scores:[2,4,3,2]},{scores:[2,3,4,2]},{scores:[2,3,3,3]},{scores:[2,3,3,1.5]},{scores:[2,3,3]},{scores:[2,3,3,2],notes:'private'},{scores:[2,3,3,2],total:100},{scores:[2,3,3,2],receipt:'replacement'}]){const r=await call(handle,operation('instructorReview',s,extra));assert.equal(r.status,400);}});
test('optimistic concurrency permits one update and rejects stale overwrite',async()=>{const {handle}=rig();const s=(await call(handle,{action:'instructorTest',fixture:'guided'})).body.submission;const results=await Promise.all([call(handle,operation('instructorReview',s,{scores:[1,2,2,1]})),call(handle,operation('instructorReview',s,{scores:[2,3,3,2]}))]);assert.deepEqual(results.map(r=>r.status).sort(),[200,409]);});
test('guest initially empty and never contains private keys; release/hide uses fixed redaction',async()=>{const {handle}=rig();let g=await call(handle,null,{method:'GET',auth:false,query:'?view=guest'});assert.equal(g.body.aggregate.started,0);assert.deepEqual(g.body.proposals,[]);let s=(await call(handle,{action:'instructorTest',fixture:'guided'})).body.submission;g=await call(handle,null,{method:'GET',auth:false,query:'?view=guest'});assert.equal(g.body.aggregate.completedRevisions,1);assert.deepEqual(g.body.proposals,[]);s=(await call(handle,operation('instructorPublish',s,{published:true}))).body.submission;g=await call(handle,null,{method:'GET',auth:false,query:'?view=guest'});assert.equal(g.body.proposals.length,1);assert.equal(g.body.proposals[0].summary,FIXTURES.guided.summary);for(const forbidden of ['email','firstName','lastName','responses','initialPlan','scores','review','receipt','attemptId'])assert.ok(!JSON.stringify(g.body).includes(`"${forbidden}"`));assert.ok(!JSON.stringify(g.body).includes('example.invalid'));await call(handle,operation('instructorPublish',s,{published:false}));assert.deepEqual((await call(handle,null,{method:'GET',query:'?view=guest'})).body.proposals,[]);});
test('guest projection does not trust arbitrary stored publication text or fields',()=>{const g=guestProjection({started:1,initialPlans:1,completedRevisions:1,formats:{guided:1,tournament:0}},[{format:'guided',label:'Real name',summary:'SECRET raw response',published:true,email:'secret'}]);assert.equal(g.proposals[0].summary,FIXTURES.guided.summary);assert.ok(!JSON.stringify(g).includes('SECRET'));assert.ok(!JSON.stringify(g).includes('Real name'));});
test('public realtime loop stores only enum state in one shared demo, with idempotent retry',async()=>{const {handle,store}=rig();const body={action:'pilotProgress',format:'guided',stage:'draft'};const first=await call(handle,body,{auth:false});assert.equal(first.status,200);assert.deepEqual((await call(handle,body,{auth:false})).body,first.body);let guest=(await call(handle,null,{method:'GET',auth:false,query:'?view=guest'})).body;assert.equal(guest.aggregate.started,1);assert.equal(guest.aggregate.initialPlans,0);assert.equal(guest.demo.summary,FIXTURES.guided.summary);await call(handle,{...body,format:'tournament',stage:'plan_locked'},{auth:false});guest=(await call(handle,null,{method:'GET',auth:false,query:'?view=guest'})).body;assert.equal(guest.aggregate.started,1);assert.equal(guest.aggregate.initialPlans,1);assert.equal(guest.aggregate.formats.tournament,1);await call(handle,{...body,stage:'submitted'},{auth:false});guest=(await call(handle,null,{method:'GET',auth:false,query:'?view=guest'})).body;assert.equal(guest.aggregate.completedRevisions,1);assert.equal(store.records.size,0);assert.equal(store.operations.size,0);});
test('public progress rejects identity/text/IDs and invalid enums before any storage access',async()=>{for(const extra of [{email:'a@b.c'},{responses:['secret']},{name:'Name'},{summary:'raw'},{attemptId:crypto.randomUUID()},{stage:'live'},{format:'any'},{mode:'pilot'}]){const {handle,store}=rig();const r=await call(handle,{action:'pilotProgress',format:'guided',stage:'draft',...extra},{auth:false});assert.equal(r.status,400);assert.equal(store.calls,0);}});
test('a failed durable save never returns a success receipt',async()=>{const {store}=rig();store.apply=async()=>{throw Error('sensitive database internal');};const handle=createHandler({store,instructorKeyHash:keyHash});const r=await call(handle,{action:'instructorTest',fixture:'guided'});assert.equal(r.status,503);assert.ok(!JSON.stringify(r.body).includes('sensitive'));assert.ok(!JSON.stringify(r.body).includes('receipt'));});
test('lost acknowledgment followed by exact retry returns one committed receipt',async()=>{const {store}=rig();const apply=store.apply;let lost=false;store.apply=async value=>{const r=await apply(value);if(value.next.status==='submitted'&&!lost){lost=true;throw Error('network lost');}return r;};const handle=createHandler({store,instructorKeyHash:keyHash});assert.equal((await call(handle,{action:'instructorTest',fixture:'guided'})).status,503);const r=await call(handle,{action:'instructorTest',fixture:'guided'});assert.equal(r.status,200);assert.equal(store.records.size,1);assert.equal(store.operations.size,5);});
test('state machine retains original plan and rejects premature finalization and post-submit editing',()=>{const opts={now:'2026-10-07T13:00:00.000Z',receiptId:'fixed'};let s=transition(null,{action:'start',fixture:'guided'},opts);assert.throws(()=>transition(s,{action:'lockPlan'},opts));assert.throws(()=>transition(s,{action:'submit'},opts));s=transition(s,{action:'save',format:'guided',responses:[...FIXTURES.guided.responses.slice(0,3),'']},opts);s=transition(s,{action:'lockPlan'},opts);const original=structuredClone(s.initialPlan);assert.throws(()=>transition(s,{action:'save',format:'tournament',responses:FIXTURES.guided.responses},opts));const changed=[...FIXTURES.guided.responses];changed[0]='rewritten';assert.throws(()=>transition(s,{action:'save',format:'guided',responses:changed},opts));assert.throws(()=>transition(s,{action:'submit'},opts));s=transition(s,{action:'save',format:'guided',responses:FIXTURES.guided.responses},opts);s=transition(s,{action:'submit'},opts);assert.deepEqual(s.initialPlan,original);assert.throws(()=>transition(s,{action:'save',format:'guided',responses:FIXTURES.guided.responses},opts));});
test('origin, body-size, media-type, path and method protections',async()=>{const {handle,store}=rig();assert.equal((await call(handle,{action:'instructorList'},{headers:{origin:'https://evil.test'}})).status,403);assert.equal((await call(handle,{action:'instructorList'},{headers:{'content-type':'text/plain'}})).status,415);assert.equal((await call(handle,{action:'instructorList'},{headers:{'content-encoding':'gzip'}})).status,415);assert.equal((await call(handle,{action:'instructorList',junk:'x'.repeat(17000)})).status,413);assert.equal((await handle(new Request(base+'/instructor'))).status,404);assert.equal((await handle(new Request(base,{method:'DELETE'}))).status,405);assert.equal(store.calls,0);});
test('storage adapter never uses browser keys and whitelists guest RPC',async()=>{const requests=[];const store=createSupabaseStore({url:'https://havsvkhddvdbzbsmhqbr.supabase.co',serviceRoleKey:'synthetic-server-secret',fetchImpl:async(url,opts)=>{requests.push({url,opts});return new Response(JSON.stringify(url.includes('guest')?{aggregate:{},publications:[]}:[]),{status:200});}});await store.guest();assert.equal(requests.length,1);assert.ok(requests[0].url.endsWith('/rpc/spm343_tap_lab2_guest'));assert.equal(requests[0].opts.headers.apikey,'synthetic-server-secret');assert.equal(requests[0].opts.method,'POST');assert.throws(()=>createSupabaseStore({url:'https://other.example',serviceRoleKey:'x'}));});
test('SQL grants deny browser roles and all functions use security invoker with empty search path',async()=>{const sql=await readFile(new URL('./schema.sql',import.meta.url),'utf8');assert.equal((sql.match(/enable row level security/g)||[]).length,4);assert.equal((sql.match(/force row level security/g)||[]).length,4);assert.equal((sql.match(/security invoker set search_path = ''/g)||[]).length,3);assert.ok(!/security definer/i.test(sql));assert.ok(!/grant .* to (anon|authenticated|public)\s*;/i.test(sql));assert.match(sql,/pg_advisory_xact_lock/);assert.match(sql,/primary key \(attempt_id, request_id\)/);assert.match(sql,/from public, anon, authenticated, service_role/);});
test('public deployment source contains no instructor digest or user key',async()=>{const source=await readFile(new URL('./deployment-config.mjs',import.meta.url),'utf8');assert.ok(!/[a-f0-9]{64}/.test(source));assert.ok(!source.includes(key));assert.match(source,/instructorKeyHash: null/);});
