'use strict';
(()=>{
const ENDPOINT='https://havsvkhddvdbzbsmhqbr.supabase.co/functions/v1/spm370-offscript/instructor';
const $=id=>document.getElementById(id);let key='',rows=[],loading=false,generation=0;
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const finalScore=r=>Number.isInteger(r.grade_override)?r.grade_override:r.score;
function notice(text){$('notice').textContent=text;$('notice').hidden=!text;}
async function api(body){const controller=new AbortController(),timer=setTimeout(()=>controller.abort(),18000);try{const response=await fetch(ENDPOINT,{method:body?'POST':'GET',cache:'no-store',headers:{'x-instructor-key':key,...(body?{'Content-Type':'application/json'}:{})},...(body?{body:JSON.stringify(body)}:{}),signal:controller.signal});const data=await response.json();if(!response.ok||!data.ok)throw Error(data.error||'The request could not be confirmed.');return data;}catch(e){throw Error(e.name==='AbortError'?'The connection timed out. Refresh before assuming a grade was saved.':e.message);}finally{clearTimeout(timer);}}
function filtered(){const q=$('search').value.trim().toLowerCase(),filter=$('review-filter').value;return rows.filter(r=>`${r.first_name} ${r.last_name} ${r.email}`.toLowerCase().includes(q)&&(filter==='all'||(filter==='reviewed'?r.review_status==='REVIEWED':r.review_status!=='REVIEWED')));}
function render(){const list=filtered();$('counts').textContent=`${rows.length} submissions · ${rows.filter(r=>r.review_status!=='REVIEWED').length} need review`;
 $('rows').innerHTML=list.length?list.map(r=>`<details class="panel submission"><summary><span><strong>${esc(r.last_name)}, ${esc(r.first_name)}</strong><span class="student-email">${esc(r.email)}</span></span><span class="score">${finalScore(r)} / 10<span class="review-state">${r.review_status==='REVIEWED'?'Reviewed':'Needs review'}</span></span></summary><div class="answers"><p class="small muted">Automatic score: ${r.score}/10 · completion ${r.completion_score}/6 · concept checks ${r.concept_score}/4${r.partner_name?` · Partner: ${esc(r.partner_name)}`:''}</p><h3>Earlier decision and permission issue</h3><p>${esc(r.reflections?.[0])}</p><h3>Stakeholders and next agreement</h3><p>${esc(r.reflections?.[1])}</p><details><summary>Story choices and check responses</summary><p class="small">${esc(r.choices?.join(' / '))}</p><p class="small">Concept checks: ${esc(r.checks?.join(' / '))}</p></details><form class="grade-form" data-id="${esc(r.id)}"><div class="field"><label for="grade-${esc(r.id)}">Grade / 10</label><input id="grade-${esc(r.id)}" name="grade" type="number" min="0" max="10" step="1" value="${finalScore(r)}" required></div><div class="field"><label for="notes-${esc(r.id)}">Instructor notes (optional)</label><textarea id="notes-${esc(r.id)}" name="notes" maxlength="2000">${esc(r.grader_notes)}</textarea></div><button class="btn secondary" type="submit">Save grade &amp; mark reviewed</button></form><p class="small muted receipt-line">Submitted: ${esc(r.submitted_at)}<br>Receipt: ${esc(r.receipt)}</p></div></details>`).join(''):'<p class="panel">No submissions match this view.</p>';
}
async function load(){if(loading)return;loading=true;const ticket=generation;try{const data=await api();if(ticket!==generation)return;rows=Array.isArray(data.submissions)?data.submissions:[];render();$('updated').textContent='Last refreshed '+new Date().toLocaleString()+'.';notice('');}finally{loading=false;}}
$('login-form').addEventListener('submit',async e=>{e.preventDefault();key=$('key').value.trim();if(!key)return;$('open').disabled=true;try{await load();$('key').value='';$('login').hidden=true;$('dashboard').hidden=false;}catch(error){notice(error.message);}finally{$('open').disabled=false;}});
$('refresh').addEventListener('click',()=>load().catch(error=>notice('Refresh failed; the displayed records may be stale. '+error.message)));
$('logout').addEventListener('click',()=>{generation++;key='';rows=[];$('rows').innerHTML='';$('dashboard').hidden=true;$('login').hidden=false;$('key').value='';notice('');});
$('search').addEventListener('input',render);$('review-filter').addEventListener('change',render);
$('rows').addEventListener('submit',async e=>{const form=e.target;if(!form.matches('.grade-form'))return;e.preventDefault();const grade=Number(form.elements.grade.value),notes=form.elements.notes.value;if(!Number.isInteger(grade)||grade<0||grade>10){notice('Enter a whole-number grade from 0 to 10.');return;}const button=form.querySelector('button');button.disabled=true;try{await api({action:'grade',id:form.dataset.id,grade,notes});await load();notice('Grade saved and marked reviewed.');}catch(error){notice(error.message);button.disabled=false;}});
function cell(value){let s=String(value??'');if(/^[\s]*[=+@-]/.test(s))s="'"+s;return '"'+s.replace(/"/g,'""')+'"';}
$('export').addEventListener('click',()=>{const list=filtered();if(!list.length){notice('No matching submissions to export.');return;}const lines=[['Last name','First name','Email','Grade','Points possible','Automatic score','Completion points','Concept points','Review status','Submitted UTC','Receipt','Partner','Reflection1','Reflection2','Instructor notes'],...list.map(r=>[r.last_name,r.first_name,r.email,finalScore(r),10,r.score,r.completion_score,r.concept_score,r.review_status,r.submitted_at,r.receipt,r.partner_name,r.reflections?.[0],r.reflections?.[1],r.grader_notes])];const blob=new Blob(['\ufeff'+lines.map(row=>row.map(cell).join(',')).join('\r\n')],{type:'text/csv;charset=utf-8'}),url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download='SPM370_OffScript_Lab2_'+new Date().toISOString().slice(0,10)+'.csv';a.click();setTimeout(()=>URL.revokeObjectURL(url),3000);});
})();
