(function(){
const D=window.RPG_DATA, ENDPOINT="https://havsvkhddvdbzbsmhqbr.supabase.co/functions/v1/spm343-rpg-save";
const CREDS_KEY="spm343_rpg_creds_v1", LOCAL_KEY="spm343_rpg_state_v1";
const WORLD={w:1580,h:980}, VIEW={w:1000,h:650};
const $=id=>document.getElementById(id), clamp=(n,a,b)=>Math.max(a,Math.min(b,n));
let state=null, creds=null, keys={}, last=performance.now(), nearest=null, dirty=false, selectedArchetype=null, selectedAvatar=D.colors[0], menuOpen=false;
const canvas=$("world"), ctx=canvas.getContext("2d");

function baseState(name,arch,avatar){
  const skills={Strategy:1,Finance:1,Marketing:1,Operations:1,Community:1,Governance:1};
  Object.entries(D.archetypes[arch].bonuses).forEach(([k,v])=>skills[k]+=v);
  return {playerName:name,archetype:arch,avatar,level:1,xp:0,currentZone:"grassroots",x:255,y:570,inventory:[],skills,
    relationships:{Community:50,Schools:42,Campus:42,Creators:42,Sponsors:40,Publisher:36,Pro:40,Players:50,EventPartners:42},
    quests:{grassroots:"available",scholastic:"locked",creator:"locked",college:"locked",sponsor:"locked",publisher:"locked",pro:"locked",event:"locked",finale:"locked"},
    flags:{completed:[],unlocked:["grassroots"],finalComplete:false},journal:[{title:"Career Begins",text:"You opened a tiny esports operation with one goal: build something the ecosystem actually values."}],news:["A new operator has entered Ecosystem City."],updatedAt:null};
}
function normalize(s){
  s.flags=s.flags||{};s.flags.completed=Array.isArray(s.flags.completed)?s.flags.completed:[];s.flags.unlocked=Array.isArray(s.flags.unlocked)?s.flags.unlocked:["grassroots"];
  s.quests=s.quests||{};Object.keys(D.quests).forEach(q=>{if(!s.quests[q])s.quests[q]="locked"});
  s.inventory=Array.isArray(s.inventory)?s.inventory:[];s.journal=Array.isArray(s.journal)?s.journal:[];s.news=Array.isArray(s.news)?s.news:[];
  s.skills=Object.assign({Strategy:1,Finance:1,Marketing:1,Operations:1,Community:1,Governance:1},s.skills||{});
  s.relationships=Object.assign({Community:50,Schools:42,Campus:42,Creators:42,Sponsors:40,Publisher:36,Pro:40,Players:50,EventPartners:42},s.relationships||{});
  s.x=Number(s.x)||255;s.y=Number(s.y)||570;s.xp=Number(s.xp)||0;s.level=Number(s.level)||1;updateUnlocks(s);return s;
}
function toast(msg){const t=$("toast");t.textContent=msg;t.classList.add("show");clearTimeout(t._timer);t._timer=setTimeout(()=>t.classList.remove("show"),2600)}
function localSave(){if(!state)return;localStorage.setItem(LOCAL_KEY,JSON.stringify(state));if(creds)localStorage.setItem(CREDS_KEY,JSON.stringify(creds));dirty=false}
async function api(body){const r=await fetch(ENDPOINT,{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify(body)});const d=await r.json().catch(()=>({}));if(!r.ok)throw new Error(d.error||"Save service unavailable");return d}
async function createCloud(){try{const d=await api({action:"create",playerName:state.playerName,archetype:state.archetype,avatar:state.avatar,state});creds={saveId:d.saveId,saveToken:d.saveToken};localSave();$("cloudStatus").textContent="connected";return true}catch(e){$("cloudStatus").textContent="local only";localSave();toast("Cloud save unavailable; local save is active.");return false}}
async function saveCloud(showToast=false){if(!state){return}localSave();if(!creds){if(showToast)toast("Saved on this device.");return}try{await api({action:"save",saveId:creds.saveId,saveToken:creds.saveToken,state});$("cloudStatus").textContent="saved";if(showToast)toast("Career saved.")}catch(e){$("cloudStatus").textContent="offline · local save safe";if(showToast)toast("Cloud unavailable; local save kept.")}}
async function loadCloud(c){const d=await api({action:"load",saveId:c.saveId,saveToken:c.saveToken});state=normalize(d.state);creds=c;localSave();return state}
function recoveryKey(){return creds?creds.saveId+"."+creds.saveToken:"Local save only — cloud recovery key unavailable."}
function parseRecovery(v){const p=v.trim().split(".");return p.length===2?{saveId:p[0],saveToken:p[1]}:null}

function renderCreator(){
  const ac=$("avatarChoices");ac.innerHTML="";D.colors.forEach((c,i)=>{const b=document.createElement("button");b.className="avatar-choice"+(c===selectedAvatar?" active":"");b.style.background=c;b.textContent=String(i+1);b.onclick=()=>{selectedAvatar=c;renderCreator();validateStart()};ac.appendChild(b)});
  const ar=$("archetypes");ar.innerHTML="";Object.entries(D.archetypes).forEach(([id,a])=>{const b=document.createElement("div");b.className="archetype"+(id===selectedArchetype?" active":"");b.innerHTML=`<strong>${a.name}</strong><span>${a.desc}</span>`;b.onclick=()=>{selectedArchetype=id;renderCreator();validateStart()};ar.appendChild(b)});validateStart();
}
function validateStart(){$("newGameBtn").disabled=!($("playerName").value.trim()&&selectedArchetype)}
$("playerName").addEventListener("input",validateStart);
$("newGameBtn").onclick=async()=>{const name=$("playerName").value.trim();if(!name||!selectedArchetype)return;state=baseState(name,selectedArchetype,selectedAvatar);$("startStatus").textContent="Creating your career…";await createCloud();enterGame();$("startStatus").textContent=""};
$("recoverBtn").onclick=async()=>{const c=parseRecovery($("recoveryInput").value);if(!c){$("startStatus").textContent="That recovery key is not in the expected format.";return}try{$("startStatus").textContent="Recovering career…";await loadCloud(c);enterGame();$("startStatus").textContent=""}catch(e){$("startStatus").textContent="Recovery failed. Check the key and try again."}};
$("resumeBtn").onclick=async()=>{const c=JSON.parse(localStorage.getItem(CREDS_KEY)||"null"), ls=JSON.parse(localStorage.getItem(LOCAL_KEY)||"null");try{if(c)await loadCloud(c);else if(ls)state=normalize(ls);if(state)enterGame()}catch(e){if(ls){state=normalize(ls);creds=c;enterGame();toast("Loaded local save; cloud sync will retry later.")}}};
function detectResume(){const ls=localStorage.getItem(LOCAL_KEY);if(ls)$("resumeBtn").classList.remove("hidden")}

function enterGame(){state=normalize(state);$("titleScreen").classList.add("hidden");$("gameScreen").classList.remove("hidden");updateHud();last=performance.now();requestAnimationFrame(loop);dirty=true;saveCloud()}
function returnTitle(){$("gameScreen").classList.add("hidden");$("titleScreen").classList.remove("hidden");$("pauseMenu").classList.add("hidden");menuOpen=false;detectResume()}

function updateUnlocks(s=state){if(!s)return;const c=s.flags.completed||[], unlock=new Set(s.flags.unlocked||["grassroots"]);const setAvail=q=>{if(s.quests[q]==="locked")s.quests[q]="available";unlock.add(q==="finale"?"boardroom":q)};
  if(c.includes("grassroots")){setAvail("scholastic");setAvail("creator")}
  if(c.includes("scholastic"))setAvail("college");if(c.includes("creator"))setAvail("sponsor");
  if(c.includes("college")&&c.includes("sponsor"))setAvail("publisher");if(c.includes("publisher")){setAvail("pro");setAvail("event")}
  if(c.includes("pro")&&c.includes("event"))setAvail("finale");s.flags.unlocked=[...unlock];
}
function isUnlocked(zone){return (state.flags.unlocked||[]).includes(zone)}
function activeQuest(){return Object.keys(D.quests).find(q=>state.quests[q]==="available"||state.quests[q]==="in_progress")}
function updateHud(){if(!state)return;$("playerLabel").textContent=state.playerName;$("archetypeLabel").textContent=D.archetypes[state.archetype]?.name||state.archetype;$("portrait").style.background=state.avatar;$("portrait").textContent=state.playerName.slice(0,2).toUpperCase();$("levelLabel").textContent=state.level;$("xpLabel").textContent=state.xp;$("xpFill").style.width=((state.xp%250)/250*100)+"%";const aq=activeQuest();$("activeQuestLabel").textContent=aq?D.quests[aq].title:"Explore the city";
  const qm=$("questMini");qm.innerHTML="";Object.keys(D.quests).filter(q=>state.quests[q]==="available"||state.quests[q]==="in_progress").slice(0,3).forEach(q=>{const x=document.createElement("div");x.className="quest-mini";x.innerHTML=`<strong>${D.quests[q].title}</strong><span>${D.quests[q].sector} · Find ${D.npcs[D.zones[q==="finale"?"boardroom":q].npc].name}</span>`;qm.appendChild(x)});if(!qm.children.length)qm.innerHTML='<div class="small">No open quests. Explore or review your journal.</div>';
  const sk=$("skills");sk.innerHTML="";Object.entries(state.skills).forEach(([k,v])=>{const r=document.createElement("div");r.className="skill-row";r.innerHTML=`<span>${k}</span><div class="skill-dots">${Array.from({length:7},(_,i)=>`<i class="dot ${i<Math.min(v,7)?"on":""}"></i>`).join("")}</div>`;sk.appendChild(r)});
  const rr=$("relationships");rr.innerHTML="";Object.entries(state.relationships).forEach(([k,v])=>{const r=document.createElement("div");r.className="rel-row";r.innerHTML=`<span>${k}</span><div class="reltrack"><div class="relfill" style="width:${clamp(v,0,100)}%"></div></div>`;rr.appendChild(r)});
  const inv=$("inventory");inv.innerHTML=state.inventory.length?state.inventory.map(id=>`<span class="item-chip" title="${D.items[id]?.desc||""}">${D.items[id]?.name||id}</span>`).join(""):'<span class="small">Your backpack is empty.</span>';
  const nf=$("newsFeed");nf.innerHTML=(state.news||[]).slice(-5).reverse().map(n=>`<div class="news-item">${n}</div>`).join("");
}
function addNews(t){state.news=state.news||[];state.news.push(t);if(state.news.length>30)state.news.shift();dirty=true}
function addJournal(title,text){state.journal.push({title,text,time:new Date().toISOString()});dirty=true}
function gainXP(n){state.xp+=n;const nl=1+Math.floor(state.xp/250);if(nl>state.level){state.level=nl;toast(`LEVEL UP — You reached Level ${nl}.`);addNews(`${state.playerName} reached management level ${nl}.`)}dirty=true}
function addItem(id){if(id&&!state.inventory.includes(id)){state.inventory.push(id);toast(`Item acquired: ${D.items[id].name}`);dirty=true}}
function effect(e){if(!e)return;if(e.skills)Object.entries(e.skills).forEach(([k,v])=>state.skills[k]=clamp((state.skills[k]||0)+v,0,10));if(e.relationships)Object.entries(e.relationships).forEach(([k,v])=>state.relationships[k]=clamp((state.relationships[k]||50)+v,0,100));dirty=true}

function cam(){return{x:clamp(state.x-VIEW.w/2,0,WORLD.w-VIEW.w),y:clamp(state.y-VIEW.h/2,0,WORLD.h-VIEW.h)}}
function districtAt(x,y){for(const [id,z] of Object.entries(D.zones)){if(x>=z.x&&x<=z.x+z.w&&y>=z.y&&y<=z.y+z.h)return id}return null}
function drawWorld(){const c=cam();ctx.clearRect(0,0,VIEW.w,VIEW.h);ctx.fillStyle="#0b1d2b";ctx.fillRect(0,0,VIEW.w,VIEW.h);
  ctx.save();ctx.translate(-c.x,-c.y);
  ctx.fillStyle="#10283a";ctx.fillRect(0,0,WORLD.w,WORLD.h);
  ctx.strokeStyle="#18364b";ctx.lineWidth=1;for(let x=0;x<WORLD.w;x+=80){ctx.beginPath();ctx.moveTo(x,0);ctx.lineTo(x,WORLD.h);ctx.stroke()}for(let y=0;y<WORLD.h;y+=80){ctx.beginPath();ctx.moveTo(0,y);ctx.lineTo(WORLD.w,y);ctx.stroke()}
  ctx.strokeStyle="#27465a";ctx.lineWidth=34;[[0,520,WORLD.w,520],[800,0,800,WORLD.h],[0,470,WORLD.w,470]].forEach(a=>{ctx.beginPath();ctx.moveTo(a[0],a[1]);ctx.lineTo(a[2],a[3]);ctx.stroke()});ctx.strokeStyle="#d3a03b";ctx.lineWidth=2;ctx.setLineDash([10,16]);ctx.beginPath();ctx.moveTo(0,520);ctx.lineTo(WORLD.w,520);ctx.stroke();ctx.setLineDash([]);
  Object.entries(D.zones).forEach(([id,z])=>drawZone(id,z));
  Object.values(D.npcs).forEach(n=>{const zone=n.zone;if(isUnlocked(zone))drawNpc(n)});
  drawPlayer();ctx.restore();
  const z=districtAt(state.x,state.y);$("zoneName").textContent=z?D.zones[z].name:"Ecosystem City";
}
function drawZone(id,z){const unlocked=isUnlocked(id);ctx.save();ctx.fillStyle=unlocked?z.color:"#263345";ctx.globalAlpha=unlocked?1:.58;ctx.fillRect(z.x,z.y,z.w,z.h);ctx.fillStyle="#0a1324";ctx.fillRect(z.x+14,z.y+17,z.w-28,z.h-42);ctx.globalAlpha=1;ctx.fillStyle=unlocked?"#eaf4ff":"#7e899b";ctx.font="700 18px 'Times New Roman'";ctx.textAlign="center";ctx.fillText(z.name,z.x+z.w/2,z.y+z.h-14);ctx.font="14px 'Times New Roman'";ctx.fillStyle=unlocked?"#9edce5":"#9099a8";ctx.fillText(unlocked?"OPEN":"LOCKED",z.x+z.w/2,z.y+43);if(!unlocked){ctx.font="700 34px serif";ctx.fillStyle="#8290a5";ctx.fillText("◆",z.x+z.w/2,z.y+z.h/2+12)}else{ctx.strokeStyle="rgba(255,255,255,.13)";ctx.strokeRect(z.x+28,z.y+60,z.w-56,z.h-112)}ctx.restore()}
function drawNpc(n){const q=D.zones[n.zone]?.quest||"finale",status=state.quests[q];ctx.save();ctx.fillStyle=n.color;ctx.beginPath();ctx.arc(n.x,n.y,17,0,Math.PI*2);ctx.fill();ctx.fillStyle="#fff";ctx.font="700 11px 'Times New Roman'";ctx.textAlign="center";ctx.fillText(n.initials,n.x,n.y+4);ctx.font="700 13px 'Times New Roman'";ctx.fillText(n.name.split(" ")[0],n.x,n.y+37);if(status==="available"||status==="in_progress"){ctx.fillStyle="#f5cf68";ctx.font="700 26px 'Times New Roman'";ctx.fillText("!",n.x,n.y-27)}else if(status==="completed"){ctx.fillStyle="#86d9a2";ctx.font="700 18px 'Times New Roman'";ctx.fillText("✓",n.x,n.y-25)}ctx.restore()}
function drawPlayer(){ctx.save();ctx.shadowColor="rgba(0,0,0,.45)";ctx.shadowBlur=10;ctx.fillStyle=state.avatar;ctx.beginPath();ctx.arc(state.x,state.y,18,0,Math.PI*2);ctx.fill();ctx.shadowBlur=0;ctx.strokeStyle="#fff";ctx.lineWidth=3;ctx.stroke();ctx.fillStyle="#07111f";ctx.font="700 11px 'Times New Roman'";ctx.textAlign="center";ctx.fillText(state.playerName.slice(0,2).toUpperCase(),state.x,state.y+4);ctx.restore()}
function findNearest(){let best=null,bd=999;Object.values(D.npcs).forEach(n=>{if(!isUnlocked(n.zone))return;const d=Math.hypot(n.x-state.x,n.y-state.y);if(d<bd){bd=d;best=n}});nearest=bd<78?best:null;$("interactPrompt").classList.toggle("hidden",!nearest);if(nearest)$("interactPrompt").innerHTML=`Press <kbd>E</kbd> to talk to ${nearest.name}`}
function loop(now){if($("gameScreen").classList.contains("hidden"))return;const dt=Math.min(34,now-last);last=now;if($("modalBackdrop").classList.contains("hidden")&&!menuOpen){let dx=0,dy=0;if(keys.ArrowLeft||keys.a)dx--;if(keys.ArrowRight||keys.d)dx++;if(keys.ArrowUp||keys.w)dy--;if(keys.ArrowDown||keys.s)dy++;if(dx||dy){const m=Math.hypot(dx,dy);state.x=clamp(state.x+dx/m*0.22*dt,18,WORLD.w-18);state.y=clamp(state.y+dy/m*0.22*dt,18,WORLD.h-18);dirty=true}}drawWorld();findNearest();requestAnimationFrame(loop)}
window.addEventListener("keydown",e=>{keys[e.key]=true;if((e.key==="e"||e.key==="E")&&!e.repeat)interact();if(e.key==="Escape")closeModal()});window.addEventListener("keyup",e=>keys[e.key]=false);
document.querySelectorAll(".dpad button").forEach(b=>{const k=b.dataset.key;b.onpointerdown=()=>keys[k]=true;b.onpointerup=b.onpointerleave=()=>keys[k]=false});$("talkMobile").onclick=interact;
function interact(){if(!nearest||!$("modalBackdrop").classList.contains("hidden"))return;const qid=D.zones[nearest.zone]?.quest||"finale";const status=state.quests[qid];if(status==="completed")showNPCChat(nearest,qid);else if(status==="available"||status==="in_progress")questIntro(qid);else toast("That district's quest is not available yet.")}

function openModal(eyebrow,title,html){$("modalEyebrow").textContent=eyebrow;$("modalTitle").textContent=title;$("modalBody").innerHTML=html;$("modalBackdrop").classList.remove("hidden")}
function closeModal(){$("modalBackdrop").classList.add("hidden")}
function npcFor(qid){return D.npcs[D.zones[qid==="finale"?"boardroom":qid].npc]}
function branchNote(qid){if(qid==="sponsor"&&state.flags.creator_network)return "Nova's creator network is already giving you better audience insight; Marisol notices.";if(qid==="publisher"&&state.flags.campus_hybrid)return "Your campus governance work taught you to map authority before signing anything. Ana likes the preparation.";if(qid==="pro"&&state.flags.pub_license)return "The license terms you negotiated give the team more predictable operating space.";if(qid==="event"&&state.flags.school_dev)return "Your scholastic work made player support and accessibility harder to treat as afterthoughts.";if(qid==="finale"&&state.flags.pro_runway)return "Your runway discipline gives you more options than organizations that spent as if growth were guaranteed.";return ""}
function questIntro(qid){const q=D.quests[qid],n=npcFor(qid);state.quests[qid]="in_progress";const paragraphs=q.intro.map(x=>`<p>${x}</p>`).join("");const branch=branchNote(qid);openModal(`${q.sector} Quest`,q.title,`<div class="dialogue"><div class="npc-avatar" style="background:${n.color}">${n.initials}</div><div class="speech"><strong>${n.name}</strong><div class="small">${n.role}</div>${paragraphs}${branch?`<div class="lesson"><strong>Your earlier choices matter:</strong> ${branch}</div>`:""}</div></div><div class="actions"><button class="btn btn-primary" id="acceptQuest">Accept Quest</button><button class="btn btn-secondary" id="laterQuest">Not yet</button></div>`);$("acceptQuest").onclick=()=>showDecision(qid);$("laterQuest").onclick=()=>{state.quests[qid]="available";closeModal()}}
function showDecision(qid){const q=D.quests[qid],n=npcFor(qid);openModal("Management Decision",q.title,`<div class="dialogue"><div class="npc-avatar" style="background:${n.color}">${n.initials}</div><div class="speech"><strong>${q.decision.prompt}</strong><div class="small">Choose a direction. There may be tradeoffs, and the story will remember.</div></div></div><div class="choice-grid">${q.decision.choices.map((c,i)=>`<button class="choice" data-choice="${i}"><strong>${String.fromCharCode(65+i)}. ${c.title}</strong><span>${c.text}</span></button>`).join("")}</div>`);document.querySelectorAll("[data-choice]").forEach(b=>b.onclick=()=>chooseDecision(qid,Number(b.dataset.choice)))}
function chooseDecision(qid,i){const q=D.quests[qid],c=q.decision.choices[i];effect(c.effects);state.flags[c.flag]=true;state.flags[`${qid}_choice`]=i;addNews(`${q.title}: ${c.title} became your operating direction.`);addJournal(`${q.title} — Decision`,`${c.title}. ${c.text}`);dirty=true;launchMini(qid,q.mini)}

function launchMini(qid,type){if(type==="budget")miniBudget(qid);else if(type==="titleSelect")miniCards(qid,"Title Selection","The district serves students ages 13–18, has mixed hardware, and wants low barriers to entry.",[
  {t:"Turbo League",p:"E10+ · cross-platform · low hardware burden",good:true},{t:"Shadow Siege",p:"M-rated · high-spec PC · steep entry cost"},{t:"Galaxy Tactics",p:"T-rated · PC-only · moderate entry cost"}]);
else if(type==="audience")miniCards(qid,"Programming Strategy","Your audience is young, mobile, creator-driven, and watches highlights between live events.",[
  {t:"One six-hour broadcast",p:"High polish, little between-event content."},{t:"Creator network",p:"Co-streams, short clips, player stories, and live tentpoles.",good:true},{t:"Immediate paywall",p:"Subscription access before audience habit is established."}]);
else if(type==="orgMap")miniSelect(qid,"Campus Governance Map","Select the four functions you should explicitly map before launch.",[
  "Competition & coaching authority","Student experience & conduct","Academic/career connections","Facilities, technology & budget","Ignore reporting lines until problems emerge"],4,[0,1,2,3]);
else if(type==="sponsorMatch")miniCards(qid,"Activation Match","A broadband brand wants youth/campus relevance, product trial, and authentic community value.",[
  {t:"Logo wall",p:"Maximum logo repetition with no participant utility."},{t:"Connectivity Skills Lab",p:"Creator-led workshops, speed stations, and tournament storytelling.",good:true},{t:"Celebrity photo op",p:"One influencer appearance disconnected from the event journey."}]);
else if(type==="license")miniSelect(qid,"License Checklist","Select the issues you would want clarified before relying on the partnership.",[
  "Competition permission","Broadcast/co-stream rights","Monetization & sponsor categories","Use of game marks/assets","Data/technical access","Change and termination rights"],6,[0,1,2,3,4,5]);
else if(type==="runway")miniSelect(qid,"Runway Challenge","Funding is tighter. Choose THREE moves that best preserve repeatable value and runway.",[
  "Protect creator/content that repeatedly grows audience","Renegotiate underused facility commitments","Diversify sponsorship, merch, events and creator revenue","Increase roster salaries before new revenue appears","Lease a larger headquarters","Pay a new franchise fee to signal ambition"],3,[0,1,2]);
else if(type==="ops")miniSelect(qid,"90-Minute Triage","Choose FOUR priorities before doors and broadcast go live.",[
  "Network redundancy and technical failover","Player check-in, rules and competitive readiness","Broadcast backup and communications chain","Participant safety and incident escalation","Upgrade VIP gift bags","Rebuild stage lighting cues from scratch"],4,[0,1,2,3]);
else if(type==="turnaround")miniSelect(qid,"Esports Winter Turnaround","Choose FOUR moves for the next twelve months.",[
  "Protect community demand and grassroots pathways","Use flexible creator/distribution partnerships","Reduce weak fixed costs and preserve runway","Clarify publisher/partner rights and dependencies","Spend aggressively to restore the old valuation story","Exit scholastic and collegiate activity","Depend on one sponsor for most revenue","Build the biggest facility in the market"],4,[0,1,2,3]);
}
function miniBudget(qid){openModal("Mini-Game","Build the First Tournament",`<p>Allocate exactly <strong>100 credits</strong>. The goal is not maximum spectacle; build something reliable enough to earn a second event.</p><div class="budget-grid">${["Technology","People","Prize Pool","Promotion"].map((k,i)=>`<div class="budget-row"><span>${k}</span><input type="range" min="0" max="60" step="5" value="25" data-budget="${i}"><strong id="bv${i}">25</strong></div>`).join("")}</div><div id="budgetTotal" class="budget-total">Total: 100</div><button class="btn btn-primary" id="budgetDone">Lock Budget</button>`);const ranges=[...document.querySelectorAll("[data-budget]")];function calc(){let t=0;ranges.forEach((r,i)=>{t+=Number(r.value);$("bv"+i).textContent=r.value});$("budgetTotal").textContent="Total: "+t;$("budgetTotal").classList.toggle("bad",t!==100);$("budgetDone").disabled=t!==100}ranges.forEach(r=>r.oninput=calc);calc();$("budgetDone").onclick=()=>{const v=ranges.map(r=>Number(r.value)),strong=v[0]>=25&&v[1]>=20&&v[2]<=35&&v[3]>=10;miniResult(qid,strong,strong?"Your budget protects the technical and human foundation while leaving room for prizes and discovery.":"The event can run, but your allocation creates a vulnerability. The community will remember whether the basics worked.")}}
function miniCards(qid,title,prompt,cards){openModal("Mini-Game",title,`<p>${prompt}</p><div class="mini-card-grid">${cards.map((c,i)=>`<button class="mini-card" data-mini="${i}"><h4>${c.t}</h4><p>${c.p}</p></button>`).join("")}</div>`);document.querySelectorAll("[data-mini]").forEach(b=>b.onclick=()=>{const i=Number(b.dataset.mini);miniResult(qid,!!cards[i].good,cards[i].good?"Strong fit. Your choice aligns the opportunity with the audience and operating context.":"That path can work, but it leaves a clearer fit problem than the alternative.")})}
function miniSelect(qid,title,prompt,items,required,good){openModal("Mini-Game",title,`<p>${prompt}</p><p class="small">Select exactly ${required}.</p><div class="checkbox-grid">${items.map((t,i)=>`<label class="check-card"><input type="checkbox" data-check="${i}"> ${t}</label>`).join("")}</div><div class="actions"><button class="btn btn-primary" id="selectDone" disabled>Lock Selection</button><span id="selectCount" class="small">0 / ${required}</span></div>`);const boxes=[...document.querySelectorAll("[data-check]")];function count(){const n=boxes.filter(b=>b.checked).length;$("selectCount").textContent=`${n} / ${required}`;$("selectDone").disabled=n!==required;boxes.forEach(b=>{if(!b.checked)b.disabled=n>=required})}boxes.forEach(b=>b.onchange=count);count();$("selectDone").onclick=()=>{const chosen=boxes.map((b,i)=>b.checked?i:null).filter(x=>x!==null),strong=chosen.length===good.length&&good.every(x=>chosen.includes(x));miniResult(qid,strong,strong?"You protected the core dependencies without spending scarce attention on secondary signals.":"Your plan moves forward, but at least one stronger priority was left exposed.")}}
function miniResult(qid,strong,text){if(strong){gainXP(40);state.skills[D.quests[qid].skill]=clamp((state.skills[D.quests[qid].skill]||1)+1,0,10)}else gainXP(15);openModal(strong?"Mini-Game Cleared":"Mini-Game Complete",strong?"Strong Execution":"Tradeoff Logged",`<p>${text}</p><div class="reward"><strong>${strong?"Bonus earned":"Experience earned"}</strong><br>${strong?"+40 XP and +1 skill":"+15 XP"}</div><div class="actions"><button class="btn btn-primary" id="finishQuestBtn">Complete Quest</button></div>`);$("finishQuestBtn").onclick=()=>completeQuest(qid)}
function completeQuest(qid){const q=D.quests[qid];gainXP(q.xp);state.skills[q.skill]=clamp((state.skills[q.skill]||1)+1,0,10);addItem(q.item);state.quests[qid]="completed";if(!state.flags.completed.includes(qid))state.flags.completed.push(qid);addJournal(q.title,q.lesson);addNews(`${q.sector} sector cleared. ${q.item?D.items[q.item].name+" added to inventory.":""}`);if(qid==="finale")state.flags.finalComplete=true;updateUnlocks();updateHud();saveCloud();if(qid==="finale")showEnding();else{const unlocked=Object.keys(D.quests).filter(x=>state.quests[x]==="available").map(x=>D.quests[x].sector).join(" · ");openModal("Quest Complete",q.title,`<div class="reward"><strong>+${q.xp} XP · ${D.items[q.item].name}</strong></div><div class="lesson"><strong>Management Insight</strong><br>${q.lesson}</div>${unlocked?`<p><strong>Open opportunities:</strong> ${unlocked}</p>`:""}<div class="actions"><button class="btn btn-primary" id="backWorld">Return to World</button><button class="btn btn-secondary" id="openJournalNow">Open Journal</button></div>`);$("backWorld").onclick=closeModal;$("openJournalNow").onclick=showJournal}}
function showNPCChat(n,qid){const q=D.quests[qid];openModal(n.role,n.name,`<div class="dialogue"><div class="npc-avatar" style="background:${n.color}">${n.initials}</div><div class="speech">You already cleared <strong>${q.title}</strong>. ${q.lesson}</div></div><div class="actions"><button class="btn btn-primary" id="closeChat">Back to World</button></div>`);$("closeChat").onclick=closeModal}
function showEnding(){const avg=Math.round(Object.values(state.relationships).reduce((a,b)=>a+b,0)/Object.keys(state.relationships).length),sum=Object.values(state.skills).reduce((a,b)=>a+b,0);let title="Adaptive Operator",desc="You built a resilient organization by learning across sectors and adjusting as the ecosystem changed.";if(state.flags.final_ecosystem&&avg>=58&&sum>=22){title="Architect of the Ecosystem";desc="You did more than build a team or event. You connected participation, audience, rights, partners, operations, and sustainable economics into one adaptive system."}else if(state.flags.final_hype){title="High-Variance Visionary";desc="You can create attention quickly, but the next chapter depends on whether the economics and relationships catch up to the ambition."}else if(state.flags.final_retreat){title="Defensive Specialist";desc="You protected a narrow core, but left growth pathways and ecosystem relationships on the table."}openModal("Campaign Complete",title,`<div class="ending"><h3>${desc}</h3><p>You can keep exploring Ecosystem City, revisit your journal, and inspect the organization you built.</p><div class="ending-stats"><div class="end-stat"><strong>Lv. ${state.level}</strong><span>Manager Level</span></div><div class="end-stat"><strong>${state.xp}</strong><span>Total XP</span></div><div class="end-stat"><strong>${avg}</strong><span>Avg. Relationship</span></div></div><div class="lesson"><strong>The course-world takeaway:</strong><br>Esports is not one market or one stakeholder. It is an evolving ecosystem. Managers create durable value by understanding the segment, community, distribution system, rights structure, resource model, and dependencies they are actually operating within.</div><div class="actions"><button class="btn btn-primary" id="continueWorld">Continue Exploring</button><button class="btn btn-secondary" id="endingJournal">Review Learning Journal</button></div></div>`);$("continueWorld").onclick=closeModal;$("endingJournal").onclick=showJournal;saveCloud()}

function showQuestLog(){const items=Object.entries(D.quests).map(([id,q])=>{const s=state.quests[id];return `<div class="quest-mini"><strong>${q.title}</strong><span>${q.sector} · ${s.replace("_"," ").toUpperCase()}</span></div>`}).join("");openModal("Career","Quest Log",items+`<div class="actions"><button class="btn btn-primary" id="closeQuestLog">Back</button></div>`);$("closeQuestLog").onclick=closeModal}
function showJournal(){const items=(state.journal||[]).slice().reverse().map(j=>`<div class="quest-mini"><strong>${j.title}</strong><span>${j.text}</span></div>`).join("");openModal("Learning","Management Journal",items||"<p>No entries yet.</p>");const b=document.createElement("button");b.className="btn btn-primary";b.textContent="Back to World";b.onclick=closeModal;$("modalBody").appendChild(b)}
$("questBtn").onclick=showQuestLog;$("journalBtn").onclick=showJournal;
$("menuBtn").onclick=()=>{menuOpen=!menuOpen;$("pauseMenu").classList.toggle("hidden",!menuOpen);$("recoveryBox").classList.add("hidden")};
$("saveNowBtn").onclick=()=>saveCloud(true);$("copyRecoveryBtn").onclick=async()=>{const k=recoveryKey();$("recoveryBox").textContent=k;$("recoveryBox").classList.remove("hidden");try{await navigator.clipboard.writeText(k);toast("Recovery key copied.")}catch(e){toast("Recovery key shown below.")}};
$("returnTitleBtn").onclick=()=>{saveCloud();returnTitle()};$("resetBtn").onclick=()=>{if(confirm("Start over on this device? Your existing cloud save will remain recoverable if you copied its key.")){localStorage.removeItem(LOCAL_KEY);localStorage.removeItem(CREDS_KEY);state=null;creds=null;returnTitle();location.reload()}};
setInterval(()=>{if(state&&dirty)saveCloud()},30000);
window.addEventListener("beforeunload",localSave);

renderCreator();detectResume();
})();