'use strict';
(() => {
const ENDPOINT='https://havsvkhddvdbzbsmhqbr.supabase.co/functions/v1/spm343-tap-lab2';
const $=id=>document.getElementById(id);let key='',busy=false,records=[],pending=null;
function message(text){$('instructor-status').textContent=text;}
function el(tag,text,klass){const node=document.createElement(tag);if(text!==undefined)node.textContent=text;if(klass)node.className=klass;return node;}
function setBusy(value){busy=value;document.querySelectorAll('button').forEach(b=>b.disabled=value);}
async function api(body){const controller=new AbortController(),timeout=setTimeout(()=>controller.abort(),18000);try{const r=await fetch(ENDPOINT,{method:'POST',cache:'no-store',headers:{'Content-Type':'application/json','x-instructor-key':key},body:JSON.stringify(body),signal:controller.signal});const d=await r.json();if(!r.ok||!d.ok){const e=new Error(d.error?.message||'The private request could not be confirmed.');e.code=d.error?.code;throw e;}return d;}finally{clearTimeout(timeout);}}
async function list(){const d=await api({action:'instructorList'});if(d.mode!=='pilot'||d.liveEnabled!==false||!Array.isArray(d.submissions))throw Error('Unexpected service mode.');records=d.submissions;render();}
async function run(body,success){if(busy)return;setBusy(true);pending=body;message('Checking the private service…');try{const d=await api(body);pending=null;if(d.submission){const i=records.findIndex(r=>r.attemptId===d.submission.attemptId);if(i<0)records.push(d.submission);else records[i]=d.submission;render();}message(success);}catch(e){if(e.code==='VERSION_CONFLICT'){pending=null;try{await list();}catch{}message('A newer record was found. Review the refreshed version before saving again.');}else if(e.code==='UNAUTHORIZED'){pending=null;lock();message('That instructor key was not accepted. The private records remain locked.');}else{message(`${e.message} No success is assumed. Use the same action to retry; its request ID is retained.`);}}finally{setBusy(false);}}
function render(){
 $('records').replaceChildren();$('empty-records').hidden=records.length>0;
 for(const r of records){
  const article=el('article',undefined,'review-record');article.append(el('p','PRIVATE · SYNTHETIC TEST ONLY','private-label'),el('h2',`${r.firstName} ${r.lastName}`),el('p',r.email),el('p',`Status: ${r.status} · Synthetic receipt: ${r.receipt||'Not submitted'}`));
  const details=el('details'),summary=el('summary','Review initial plan and reflection');details.append(summary);
  (r.responses||[]).forEach((answer,i)=>{details.append(el('h3',`${i+1}. ${['Event','Venue','Operations','Interview reflection'][i]}`),el('p',answer,'answer-text'));});article.append(details);
  article.append(el('h3','Instructor-only grade · 10 points'));
  const rubric=el('div',undefined,'rubric-grid'),inputs=[];
  [2,3,3,2].forEach((max,i)=>{const label=el('label',undefined,'field');const id=`score-${r.attemptId}-${i}`;label.htmlFor=id;label.append(el('span',`${['Event','Venue','Operations','Interview'][i]} / ${max}`,'field-label'));const input=el('input');input.id=id;input.type='number';input.min='0';input.max=String(max);input.step='1';input.value=r.review?.scores?.[i]??'';label.append(input);rubric.append(label);inputs.push(input);});article.append(rubric,el('p',r.review?`Saved instructor grade: ${r.review.total} / 10`:'No grade assigned.','muted'));
  const actions=el('div',undefined,'review-actions'),save=el('button','Save synthetic grade','button');save.type='button';save.onclick=()=>{const scores=inputs.map(v=>v.value===''?NaN:Number(v.value));if(scores.some((v,i)=>!Number.isInteger(v)||v<0||v>[2,3,3,2][i])){message('Enter a whole-number score within each criterion’s range.');return;}const body=pending?.action==='instructorReview'&&pending.attemptId===r.attemptId?pending:{action:'instructorReview',attemptId:r.attemptId,requestId:crypto.randomUUID(),expectedVersion:r.version,scores};run(body,'Synthetic grade saved privately. It is never shown in the guest view.');};actions.append(save);article.append(actions);
  article.append(el('h3','Screened guest summary'),el('p',r.guest?.summary||'No synthetic summary available.','guest-preview'));
  const reviewLabel=el('label',undefined,'field'),check=el('input');check.type='checkbox';check.id=`screen-${r.attemptId}`;reviewLabel.htmlFor=check.id;reviewLabel.append(check,document.createTextNode(' I reviewed this synthetic summary for identifying or private details.'));article.append(reviewLabel);
  const publish=el('button',r.guest?.published?'Hide from guest view':'Release this synthetic summary','button button-secondary');publish.type='button';publish.onclick=()=>{if(!r.guest?.published&&!check.checked){message('Review the summary and check the screening confirmation before releasing it.');check.focus();return;}const body=pending?.action==='instructorPublish'&&pending.attemptId===r.attemptId?pending:{action:'instructorPublish',attemptId:r.attemptId,requestId:crypto.randomUUID(),expectedVersion:r.version,published:!r.guest?.published};run(body,r.guest?.published?'The synthetic summary is hidden from the next guest refresh.':'The screened synthetic summary is released for the next guest refresh.');};article.append(publish);$('records').append(article);
 }
}
function lock(){key='';records=[];pending=null;$('instructor-key').value='';$('private-workspace').hidden=true;$('login-panel').hidden=false;$('records').replaceChildren();}
$('login-form').addEventListener('submit',async e=>{e.preventDefault();if(busy)return;key=$('instructor-key').value.trim();$('instructor-key').value='';setBusy(true);try{await list();$('private-workspace').hidden=false;$('login-panel').hidden=true;message('Private synthetic records are open. Real class submissions are still closed.');}catch(e){lock();message(e.message||'Private access could not be confirmed.');}finally{setBusy(false);}});
for(const fixture of ['guided','tournament'])$(`test-${fixture}`).onclick=()=>run({action:'instructorTest',fixture},'Synthetic private storage and receipt confirmed. No real student data was collected.');
$('reload').onclick=async()=>{if(busy)return;setBusy(true);try{await list();message('Private records refreshed.');}catch(e){if(e.code==='UNAUTHORIZED'){lock();message('Private access was rejected. This view is now locked.');}else message(e.message);}finally{setBusy(false);}};
$('logout').onclick=()=>{lock();message('Private view locked.');};window.addEventListener('pagehide',lock);
})();
