'use strict';
(()=>{const ENDPOINT='https://havsvkhddvdbzbsmhqbr.supabase.co/functions/v1/spm343-tap-lab2-v2',$=id=>document.getElementById(id),names={cup:'Rivalry Mini-Cup',open:'Play & Connect',showcase:'Campus Showcase'},maxima=[2,3,3,2];let key='',mode='live',records=[],busy=false,pending=null;
function el(tag,text,cls){const n=document.createElement(tag);if(text!==undefined)n.textContent=text;if(cls)n.className=cls;return n;}
function message(t){$('instructor-status').textContent=t;}
function setBusy(v){busy=v;document.querySelectorAll('button').forEach(b=>b.disabled=v);$('record-mode').disabled=v;}
async function api(body){const r=await fetch(ENDPOINT,{method:'POST',cache:'no-store',headers:{'Content-Type':'application/json','x-instructor-key':key},body:JSON.stringify(body),signal:AbortSignal.timeout(18000)});let d;try{d=await r.json();}catch{throw Error('The private request returned no readable confirmation.');}if(!r.ok||!d.ok){const e=new Error(d.error?.message||'The private request was not confirmed.');e.code=d.error?.code;throw e;}return d;}
function lock(){key='';records=[];pending=null;mode='live';$('instructor-key').value='';$('record-mode').value='live';$('records').replaceChildren();$('private-workspace').hidden=true;$('login-panel').hidden=false;}
async function list(){const d=await api({action:'instructorList',mode});if(d.mode!==mode||!Array.isArray(d.submissions))throw Error('Unexpected record set.');records=d.submissions;render();}
function fail(e){if(e.code==='UNAUTHORIZED'){lock();message('Private access was rejected. This view is now locked.');}else message(`${e.message} No success is assumed.`);}
async function mutate(body,success){if(busy)return;setBusy(true);pending=body;message('Saving your explicit review…');try{await api(body);pending=null;await list();message(success);}catch(e){if(e.code==='VERSION_CONFLICT'){pending=null;try{await list();}catch{}message('A newer version was found. Review the refreshed record before saving again.');}else{fail(e);if(key&&pending)message(`${e.message} No success is assumed. The same action will retry its original request safely.`);}}finally{setBusy(false);}}
function render(){
 $('records').replaceChildren();$('test-notice').hidden=mode!=='test';const counts=new Map();for(const r of records)counts.set(r.email,(counts.get(r.email)||0)+1);const filtered=records.filter(r=>!$('show-ungraded').checked||(r.status==='submitted'&&r.review===null));$('empty-records').hidden=filtered.length>0;const submitted=records.filter(r=>r.status==='submitted'),graded=submitted.filter(r=>r.review!==null);$('record-summary').textContent=`${records.length} attempts · ${submitted.length} submitted · ${graded.length} graded · ${submitted.length-graded.length} awaiting review`;
 for(const r of filtered){const a=r.answers||{},card=el('article',undefined,'review-record');card.dataset.attemptId=r.attemptId;const head=el('div',undefined,'record-heading');head.append(el('h2',`${r.lastName}, ${r.firstName}`),el('span',r.review?`${r.review.total} / 10`:r.status==='submitted'?'Submitted · ungraded':'In progress','record-status'));card.append(head,el('p',r.email,'record-meta'),el('p',`${mode==='test'?'SYNTHETIC TEST · ':''}${r.receipt||'No final receipt'} · ${r.submittedAt?new Date(r.submittedAt).toLocaleString():'Not yet submitted'}`,'record-meta'));
 if(counts.get(r.email)>1)card.append(el('p','Multiple attempts use this email. Verify the appropriate record with the student before recording a course grade.','duplicate-warning'));
 const details=el('details'),summary=el('summary',`${names[a.initialChoice]||'Initial choice pending'} → ${names[a.finalChoice]||'Final choice pending'} · Review writing`);details.append(summary,el('h3','Initial position'),el('p',r.initialPlan?.initialPosition||a.initialPosition||'No saved position yet.','answer-text'),el('h3','Final plan and adaptation'),el('p',`Event: ${names[a.finalChoice]||'—'} · Adjustment: ${a.adjustment||'—'} · Priority: ${a.priority||'—'}`,'record-meta'),el('p',a.finalReason||'No final reasoning yet.','answer-text'),el('h3',`Runner-up: ${names[a.runnerUp]||'—'}`),el('p',a.tradeoff||'No tradeoff response yet.','answer-text'));card.append(details);
 if(r.status==='submitted'){
 const grid=el('div',undefined,'rubric-grid'),inputs=[];maxima.forEach((m,i)=>{const label=el('label'),id=`score-${r.attemptId}-${i}`;label.htmlFor=id;label.append(el('span',`${['Initial position','Event/venue fit','Tradeoff/risk','Adaptation'][i]} / ${m}`));const input=el('input');input.id=id;input.type='number';input.min='0';input.max=String(m);input.step='1';input.value=r.review?.scores?.[i]??'';label.append(input);grid.append(label);inputs.push(input);});card.append(grid);const noteLabel=el('label','Private grading notes (instructor only)');noteLabel.htmlFor=`notes-${r.attemptId}`;const notes=el('textarea');notes.id=noteLabel.htmlFor;notes.className='review-notes';notes.maxLength=4000;notes.value=r.review?.notes||'';card.append(noteLabel,notes);const actions=el('div',undefined,'review-actions'),save=el('button','Save score','button');save.type='button';save.onclick=()=>{const scores=inputs.map(i=>i.value===''?NaN:Number(i.value));if(scores.some((n,i)=>!Number.isInteger(n)||n<0||n>maxima[i])){message('Enter a whole-number score within each criterion’s 2/3/3/2 range. Blank is not zero.');return;}const body=pending?.action==='instructorReview'&&pending.attemptId===r.attemptId?pending:{action:'instructorReview',mode,attemptId:r.attemptId,requestId:crypto.randomUUID(),expectedVersion:r.version,scores,notes:notes.value};mutate(body,'Instructor score and notes saved privately. Students see only submission and review status; the guest sees neither.');};actions.append(save);card.append(actions);
 card.append(el('h3','Guest-safe structured summary'),el('p',r.guest?.summary||'Summary unavailable.','guest-preview'));if(!r.guest?.consent){card.append(el('p','The student has not opted in. This attempt cannot be released individually.','record-meta'));}else{const label=el('label',undefined,'screen-label'),check=el('input');check.type='checkbox';check.id=`screen-${r.attemptId}`;label.htmlFor=check.id;label.append(check,document.createTextNode('I reviewed these selected options and want this anonymous summary available for discussion.'));card.append(label);const release=el('button',r.guest.published?'Hide anonymous summary':'Release anonymous summary','button button-secondary');release.type='button';release.onclick=()=>{if(!r.guest.published&&!check.checked){message('Review the exact summary and confirm it before releasing.');check.focus();return;}const body=pending?.action==='instructorPublish'&&pending.attemptId===r.attemptId?pending:{action:'instructorPublish',mode,attemptId:r.attemptId,requestId:crypto.randomUUID(),expectedVersion:r.version,template:'decision',published:!r.guest.published};mutate(body,r.guest.published?'The summary is hidden from the next guest refresh.':'The structured summary is released. No private writing or grade is shared.');};card.append(release);}}
 $('records').append(card);}
}
function cell(value){let s=String(value??'');if(/^[\s]*[=+\-@]/.test(s))s="'"+s;return '"'+s.replace(/"/g,'""')+'"';}
function exportCSV(){if(!key||busy)return;const fields=['Record set','First name','Last name','Email','Identity verification','Status','Receipt','Submitted at','Initial event','Initial position','Final event','Adjustment','Priority','Final reasoning','Runner-up','Tradeoff','Initial score /2','Fit score /3','Tradeoff score /3','Adaptation score /2','Total /10','Private feedback'];const rows=records.map(r=>{const a=r.answers||{};return [mode,r.firstName,r.lastName,r.email,'Self-reported',r.status,r.receipt,r.submittedAt,names[a.initialChoice],r.initialPlan?.initialPosition||a.initialPosition,names[a.finalChoice],a.adjustment,a.priority,a.finalReason,names[a.runnerUp],a.tradeoff,...maxima.map((_,i)=>r.review?.scores?.[i]??''),r.review?.total??'',r.review?.notes||''];});const csv='\uFEFF'+[fields,...rows].map(row=>row.map(cell).join(',')).join('\r\n');const url=URL.createObjectURL(new Blob([csv],{type:'text/csv;charset=utf-8'})),a=document.createElement('a');a.href=url;a.download=`TAP-Decision-Lab-2-${mode}-private.csv`;a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);message('Private CSV downloaded. Keep this file secure; it includes identities and written work.');}
$('login-form').onsubmit=async e=>{e.preventDefault();if(busy)return;key=$('instructor-key').value.trim();$('instructor-key').value='';setBusy(true);try{await list();$('login-panel').hidden=true;$('private-workspace').hidden=false;message('Class records are open. Scores are assigned only when you explicitly save them.');}catch(e){lock();message(e.message);}finally{setBusy(false);}};
$('reload').onclick=async()=>{if(busy)return;setBusy(true);try{await list();message('Private records refreshed.');}catch(e){fail(e);}finally{setBusy(false);}};
$('record-mode').onchange=async()=>{mode=$('record-mode').value;records=[];pending=null;render();setBusy(true);try{await list();message(mode==='test'?'Showing isolated synthetic tests only.':'Showing class records only.');}catch(e){fail(e);}finally{setBusy(false);}};
$('show-ungraded').onchange=render;$('export-csv').onclick=exportCSV;$('logout').onclick=()=>{lock();message('Private view locked.');};window.addEventListener('pagehide',lock);
})();
